// Code generated by oct check --generate. DO NOT EDIT.
package main

import (
	"fmt"
	"os"

	goPackage "github.com/yuechen-li-dev/oct/experimental/octgo/specimen"
	"github.com/yuechen-li-dev/oct/pkg/octxiliary"
)

func main() {
	os.Exit(octxiliary.Main(os.Stdin, os.Stdout, dispatch))
}

func dispatch(req octxiliary.Request) octxiliary.Response {
	if req.Family != "OctGo:github.com/yuechen-li-dev/oct/experimental/octgo/specimen" {
		return octxiliary.ErrString(req.ID, fmt.Sprintf("unknown family %q", req.Family))
	}
	switch req.Function {
	case "Residual":
		arg0, err := octxiliary.ArgInt(req, 0)
		if err != nil {
			return octxiliary.Err(req.ID, err)
		}
		arg1, err := octxiliary.ArgInt(req, 1)
		if err != nil {
			return octxiliary.Err(req.ID, err)
		}
		arg2, err := octxiliary.ArgInt(req, 2)
		if err != nil {
			return octxiliary.Err(req.ID, err)
		}
		result := goPackage.Residual(arg0, arg1, arg2)
		return octxiliary.OkInt(req.ID, result)
	case "StrictlyAbove":
		arg0, err := octxiliary.ArgInt(req, 0)
		if err != nil {
			return octxiliary.Err(req.ID, err)
		}
		arg1, err := octxiliary.ArgInt(req, 1)
		if err != nil {
			return octxiliary.Err(req.ID, err)
		}
		result := goPackage.StrictlyAbove(arg0, arg1)
		return octxiliary.OkBool(req.ID, result)
	default:
		return octxiliary.ErrString(req.ID, fmt.Sprintf("unknown function %q", req.Function))
	}
}
