// Code generated by Veril-Oct. DO NOT EDIT.
// Oct Int hardware policy: signed 64-bit two's-complement; SI dimensions are compile-time only.
// Packed aggregates use declaration order, first field/tag in the least-significant bits.

module UtilityController(
    input  logic Clock,
    input  logic Reset,
    input  logic [129:0] Turn_scores,
    output logic Done,
    output logic Suspended,
    output logic Fault,
    output logic [0:0] StateView,
    output logic [2:0] InstructionView,
    output logic signed [63:0] Result,
    output logic YieldValid,
    output logic signed [63:0] YieldValue,
    output logic signed [63:0] Board_Selected,
    output logic UtilitySite0HasCurrent,
    output logic signed [63:0] UtilitySite0Current,
    output logic signed [63:0] UtilitySite0Score,
    output logic signed [63:0] UtilitySite0CommitAge
);

typedef enum logic [0:0] {
    State_Decide = 1'd0
} StateT;

StateT State;
StateT NextState;
logic [2:0] Instruction;
logic [2:0] NextInstruction;
logic NextDone;
logic NextSuspended;
logic NextFault;
logic signed [63:0] NextResult;
logic NextYieldValid;
logic signed [63:0] NextYieldValue;
logic signed [63:0] NextBoard_Selected;
logic NextUtilitySite0HasCurrent;
logic signed [63:0] NextUtilitySite0Current;
logic signed [63:0] NextUtilitySite0Score;
logic signed [63:0] NextUtilitySite0CommitAge;
logic UtilityComb0Valid;
logic UtilityComb0CurrentStillValid;
logic signed [63:0] UtilityComb0BestValue;
logic signed [63:0] UtilityComb0BestScore;
logic signed [63:0] UtilityComb0Hysteresis;
logic signed [63:0] UtilityComb0MinCommit;
logic signed [63:0] Local_selected;

assign StateView = State;
assign InstructionView = Instruction;

always_comb begin : oct_flow_next
    integer __oct_dispatch;
    logic __oct_running;
    logic __oct_redispatch;
    NextState = State;
    NextInstruction = Instruction;
    NextDone = Done;
    NextSuspended = 1'b0;
    NextFault = Fault;
    NextResult = Result;
    NextYieldValid = 1'b0;
    NextYieldValue = YieldValue;
    NextBoard_Selected = Board_Selected;
    NextUtilitySite0HasCurrent = UtilitySite0HasCurrent;
    NextUtilitySite0Current = UtilitySite0Current;
    NextUtilitySite0Score = UtilitySite0Score;
    NextUtilitySite0CommitAge = UtilitySite0CommitAge;
    UtilityComb0Valid = 1'b0;
    UtilityComb0CurrentStillValid = 1'b0;
    UtilityComb0BestValue = '0;
    UtilityComb0BestScore = '0;
    UtilityComb0Hysteresis = '0;
    UtilityComb0MinCommit = '0;
    Local_selected = '0;
    __oct_running = !Done && !Fault;
    __oct_redispatch = 1'b0;
    for (__oct_dispatch = 0; __oct_dispatch < 5; __oct_dispatch = __oct_dispatch + 1) begin : oct_flow_dispatch
        if (__oct_running) begin
            __oct_redispatch = 1'b0;
            case (NextState)
                State_Decide: begin
                    case (NextInstruction)
                    3'd0: begin
                        UtilityComb0Hysteresis = 64'sd2;
                        UtilityComb0MinCommit = 64'sd3;
                        if (Turn_scores[0]) begin
                            if (!UtilityComb0Valid || Turn_scores[65:2] > UtilityComb0BestScore) begin
                                UtilityComb0Valid = 1'b1;
                                UtilityComb0BestValue = 64'sd1;
                                UtilityComb0BestScore = Turn_scores[65:2];
                            end
                            if (NextUtilitySite0HasCurrent && 64'sd1 == NextUtilitySite0Current) UtilityComb0CurrentStillValid = 1'b1;
                        end
                        if (Turn_scores[1]) begin
                            if (!UtilityComb0Valid || Turn_scores[129:66] > UtilityComb0BestScore) begin
                                UtilityComb0Valid = 1'b1;
                                UtilityComb0BestValue = 64'sd2;
                                UtilityComb0BestScore = Turn_scores[129:66];
                            end
                            if (NextUtilitySite0HasCurrent && 64'sd2 == NextUtilitySite0Current) UtilityComb0CurrentStillValid = 1'b1;
                        end
                        if (!UtilityComb0Valid) begin
                            UtilityComb0Valid = 1'b1;
                            UtilityComb0BestValue = 64'sd0;
                            UtilityComb0BestScore = 64'sd0;
                        end
                        if (NextUtilitySite0HasCurrent && UtilityComb0CurrentStillValid && ((NextUtilitySite0CommitAge < UtilityComb0MinCommit) || (UtilityComb0BestScore <= NextUtilitySite0Score + UtilityComb0Hysteresis))) begin
                            UtilityComb0BestValue = NextUtilitySite0Current;
                            UtilityComb0BestScore = NextUtilitySite0Score;
                        end
                        if (!NextUtilitySite0HasCurrent || NextUtilitySite0Current != UtilityComb0BestValue) begin
                            NextUtilitySite0HasCurrent = 1'b1;
                            NextUtilitySite0Current = UtilityComb0BestValue;
                            NextUtilitySite0Score = UtilityComb0BestScore;
                            NextUtilitySite0CommitAge = 64'sd1;
                        end else begin
                            NextUtilitySite0Score = UtilityComb0BestScore;
                            NextUtilitySite0CommitAge = NextUtilitySite0CommitAge + 64'sd1;
                        end
                        Local_selected = UtilityComb0BestValue;
                        if (__oct_running && !__oct_redispatch) NextInstruction = NextInstruction + 1'b1;
                    end
                    3'd1: begin
                        NextBoard_Selected = Local_selected;
                        if (__oct_running && !__oct_redispatch) NextInstruction = NextInstruction + 1'b1;
                    end
                    3'd2: begin
                        NextYieldValue = Local_selected;
                        NextYieldValid = 1'b1;
                        NextInstruction = NextInstruction + 1'b1;
                        __oct_running = 1'b0;
                        if (__oct_running && !__oct_redispatch) NextInstruction = NextInstruction + 1'b1;
                    end
                    3'd3: begin
                        NextState = State_Decide;
                        NextInstruction = '0;
                        __oct_redispatch = 1'b1;
                        if (__oct_running && !__oct_redispatch) NextInstruction = NextInstruction + 1'b1;
                    end
                    default: begin NextFault = 1'b1; __oct_running = 1'b0; end
                    endcase
                end
                default: begin NextFault = 1'b1; __oct_running = 1'b0; end
            endcase
        end
    end
    if (__oct_running) begin
        NextFault = 1'b1;
        __oct_running = 1'b0;
    end
end

always_ff @(posedge Clock) begin
    if (Reset) begin
        State <= State_Decide;
        Instruction <= '0;
        Done <= 1'b0;
        Suspended <= 1'b0;
        Fault <= 1'b0;
        Result <= '0;
        YieldValid <= 1'b0;
        YieldValue <= '0;
        Board_Selected <= '0;
        UtilitySite0HasCurrent <= 1'b0;
        UtilitySite0Current <= '0;
        UtilitySite0Score <= '0;
        UtilitySite0CommitAge <= '0;
    end else begin
        State <= NextState;
        Instruction <= NextInstruction;
        Done <= NextDone;
        Suspended <= NextSuspended;
        Fault <= NextFault;
        Result <= NextResult;
        YieldValid <= NextYieldValid;
        YieldValue <= NextYieldValue;
        Board_Selected <= NextBoard_Selected;
        UtilitySite0HasCurrent <= NextUtilitySite0HasCurrent;
        UtilitySite0Current <= NextUtilitySite0Current;
        UtilitySite0Score <= NextUtilitySite0Score;
        UtilitySite0CommitAge <= NextUtilitySite0CommitAge;
    end
end

endmodule
