// Code generated by Veril-Oct. DO NOT EDIT.
// Oct Int hardware policy: signed 64-bit two's-complement; SI dimensions are compile-time only.
// Packed aggregates use declaration order, first field/tag in the least-significant bits.

module Add(
    input  logic signed [63:0] A,
    input  logic signed [63:0] B,
    output logic signed [63:0] Result
);

logic signed [63:0] __oct_internal_tmp_0;

always_comb begin
    logic __oct_active_entry;
    Result = '0;
    __oct_internal_tmp_0 = '0;
    __oct_active_entry = 1'b0;
    __oct_active_entry = 1'b1;
    if (__oct_active_entry) begin : oct_block_entry
        __oct_internal_tmp_0 = (A + B);
        Result = __oct_internal_tmp_0;
    end
end

endmodule

module Greater(
    input  logic signed [63:0] A,
    input  logic signed [63:0] B,
    output logic Result
);

logic __oct_internal_tmp_0;

always_comb begin
    logic __oct_active_entry;
    Result = '0;
    __oct_internal_tmp_0 = '0;
    __oct_active_entry = 1'b0;
    __oct_active_entry = 1'b1;
    if (__oct_active_entry) begin : oct_block_entry
        __oct_internal_tmp_0 = (A > B);
        Result = __oct_internal_tmp_0;
    end
end

endmodule

module Literal(
    output logic signed [63:0] Result
);

always_comb begin
    logic __oct_active_entry;
    Result = '0;
    __oct_active_entry = 1'b0;
    __oct_active_entry = 1'b1;
    if (__oct_active_entry) begin : oct_block_entry
        Result = 64'sd42;
    end
end

endmodule

module Multiply(
    input  logic signed [63:0] A,
    input  logic signed [63:0] B,
    output logic signed [63:0] Result
);

logic signed [63:0] __oct_internal_tmp_0;

always_comb begin
    logic __oct_active_entry;
    Result = '0;
    __oct_internal_tmp_0 = '0;
    __oct_active_entry = 1'b0;
    __oct_active_entry = 1'b1;
    if (__oct_active_entry) begin : oct_block_entry
        __oct_internal_tmp_0 = (A * B);
        Result = __oct_internal_tmp_0;
    end
end

endmodule

module Negate(
    input  logic Value,
    output logic Result
);

logic __oct_internal_tmp_0;

always_comb begin
    logic __oct_active_entry;
    Result = '0;
    __oct_internal_tmp_0 = '0;
    __oct_active_entry = 1'b0;
    __oct_active_entry = 1'b1;
    if (__oct_active_entry) begin : oct_block_entry
        __oct_internal_tmp_0 = (!Value);
        Result = __oct_internal_tmp_0;
    end
end

endmodule

module Subtract(
    input  logic signed [63:0] A,
    input  logic signed [63:0] B,
    output logic signed [63:0] Result
);

logic signed [63:0] __oct_internal_tmp_0;

always_comb begin
    logic __oct_active_entry;
    Result = '0;
    __oct_internal_tmp_0 = '0;
    __oct_active_entry = 1'b0;
    __oct_active_entry = 1'b1;
    if (__oct_active_entry) begin : oct_block_entry
        __oct_internal_tmp_0 = (A - B);
        Result = __oct_internal_tmp_0;
    end
end

endmodule

module Temporary(
    input  logic signed [63:0] A,
    input  logic signed [63:0] B,
    output logic signed [63:0] Result
);

logic signed [63:0] __oct_internal_tmp_0;
logic signed [63:0] __oct_internal_tmp_1;
logic signed [63:0] Sum;

always_comb begin
    logic __oct_active_entry;
    Result = '0;
    __oct_internal_tmp_0 = '0;
    __oct_internal_tmp_1 = '0;
    Sum = '0;
    __oct_active_entry = 1'b0;
    __oct_active_entry = 1'b1;
    if (__oct_active_entry) begin : oct_block_entry
        __oct_internal_tmp_0 = (A + B);
        Sum = __oct_internal_tmp_0;
        __oct_internal_tmp_1 = (Sum * 64'sd2);
        Result = __oct_internal_tmp_1;
    end
end

endmodule
