// Generated by canonical GoOct SDSL-V via VD-MIR. Do not edit by hand.
// namespace Prometheus.Experimental.ZImage

struct PackActivationParams
{
    uint LogicalElements;
    uint PackedWords;
};

[[vk::binding(0, 0)]] StructuredBuffer<float> Input;
[[vk::binding(1, 0)]] RWStructuredBuffer<uint> Output;

[[vk::push_constant]] ConstantBuffer<PackActivationParams> params;

[numthreads(256, 1, 1)]
void Dvt2M6aPackActivationF32ToF16_CS(uint3 DispatchThreadID : SV_DispatchThreadID)
{
    uint word = DispatchThreadID.x;
    if ((word >= params.PackedWords))
    {
        return;
    }
    uint lowIndex = (word * 2u);
    uint highIndex = (lowIndex + 1u);
    float low = 0.0;
    float high = 0.0;
    if ((lowIndex < params.LogicalElements))
    {
        low = Input[lowIndex];
    }
    if ((highIndex < params.LogicalElements))
    {
        high = Input[highIndex];
    }
    float2 __sdslv_operand_0 = float2(low, high);
    Output[word] = (f32tof16(__sdslv_operand_0).x | (f32tof16(__sdslv_operand_0).y << 16u));
    return;
}

