package builtin

var names = map[string]struct{}{
	"Len":                {},
	"Append":             {},
	"Complex":            {},
	"ComplexPolar":       {},
	"I":                  {},
	"Real":               {},
	"Imag":               {},
	"Conj":               {},
	"Abs":                {},
	"Arg":                {},
	"Sqrt":               {},
	"Sin":                {},
	"Cos":                {},
	"Tan":                {},
	"Asin":               {},
	"Acos":               {},
	"Atan":               {},
	"Atan2":              {},
	"Exp":                {},
	"Ln":                 {},
	"Log10":              {},
	"Sinh":               {},
	"Cosh":               {},
	"Tanh":               {},
	"Pi":                 {},
	"E":                  {},
	"Print":              {},
	"WriteOctagon":       {},
	"LoadOctagon":        {},
	"XlsxCreateWorkbook": {},
	"XlsxAddSheet":       {},
	"XlsxSetCellString":  {},
	"XlsxSetCellFloat":   {},
	"XlsxSaveWorkbook":   {},
	"PlotLine":           {},
	"PlotScatter":        {},
	"Step":               {},
	"Active":             {},
	"Result":             {},
	"Complete":           {},
	"StateHistory":       {},
	"ResumeTarget":       {},
}

func IsName(name string) bool {
	_, ok := names[name]
	return ok
}
