// Generated by GoOct SDSL-V M4 via VD-MIR. Do not edit by hand.
// namespace Prometheus.Experimental

namespace __sdslv_cooperative {
enum Scope { ScopeWorkgroup = 2, ScopeSubgroup = 3 };
enum Layout { RowMajor = 0, ColumnMajor = 1 };

using MatrixAType = vk::SpirvOpaqueType<
    4456, float16_t, vk::integral_constant<uint, ScopeSubgroup>,
    vk::integral_constant<uint, 16>, vk::integral_constant<uint, 16>,
    vk::integral_constant<uint, 0> >;
using MatrixBType = vk::SpirvOpaqueType<
    4456, float16_t, vk::integral_constant<uint, ScopeSubgroup>,
    vk::integral_constant<uint, 16>, vk::integral_constant<uint, 16>,
    vk::integral_constant<uint, 1> >;
using MatrixCType = vk::SpirvOpaqueType<
    4456, float, vk::integral_constant<uint, ScopeSubgroup>,
    vk::integral_constant<uint, 16>, vk::integral_constant<uint, 16>,
    vk::integral_constant<uint, 2> >;

struct MatrixA {
  [[vk::ext_extension("SPV_KHR_cooperative_matrix")]]
  [[vk::ext_capability(6022)]]
  [[vk::ext_capability(5345)]]
  MatrixAType value;
};
struct MatrixB { MatrixBType value; };
struct MatrixC { MatrixCType value; };

template <typename PointeeType>
using WorkgroupPointer = const vk::SpirvOpaqueType<
    32, vk::Literal<vk::integral_constant<uint, ScopeWorkgroup> >, PointeeType>;

template <typename T>
[[vk::ext_instruction(83)]] WorkgroupPointer<T>
GetGroupSharedAddress([[vk::ext_reference]] T value);

template <typename ResultType, typename ComponentType>
[[vk::ext_instruction(80)]] ResultType Splat(ComponentType value);

template <typename ResultType, typename PointerType>
[[vk::ext_instruction(4457)]] ResultType Load(
    WorkgroupPointer<PointerType> pointer, Layout layout, uint stride,
    [[vk::ext_literal]] uint memoryOperands, Scope scope);

template <typename ResultType, typename MatrixTypeA, typename MatrixTypeB,
          typename MatrixTypeC>
[[vk::ext_instruction(4459)]] ResultType MultiplyAdd(
    MatrixTypeA a, MatrixTypeB b, MatrixTypeC c,
    [[vk::ext_literal]] uint operands);

template <typename ObjectType, typename PointerType>
[[vk::ext_instruction(4458)]] void Store(
    [[vk::ext_reference]] PointerType pointer, ObjectType object, Layout layout,
    uint stride, [[vk::ext_literal]] uint memoryOperands);
}

groupshared float16_t __sdslv_cooperative_tile_a[256];
groupshared float16_t __sdslv_cooperative_tile_b[256];

struct CooperativeSgemmParams
{
    uint m;
    uint n;
    uint k;
};

struct ComputeThread
{
    uint3 DispatchId;
    uint3 GroupId;
    uint3 GroupThreadId;
    uint GroupIndex;
};

[[vk::binding(0, 0)]] StructuredBuffer<uint> A;
[[vk::binding(1, 0)]] StructuredBuffer<uint> B;
[[vk::binding(2, 0)]] RWStructuredBuffer<float> C;

[[vk::push_constant]] ConstantBuffer<CooperativeSgemmParams> params;

[numthreads(32, 1, 1)]
void CooperativeSgemmF16F32M16N16K16_CS(uint3 DispatchThreadID : SV_DispatchThreadID, uint3 GroupThreadID : SV_GroupThreadID, uint3 GroupID : SV_GroupID, uint GroupIndex : SV_GroupIndex)
{
    ComputeThread thread;
    thread.DispatchId = DispatchThreadID;
    thread.GroupId = GroupID;
    thread.GroupThreadId = GroupThreadID;
    thread.GroupIndex = GroupIndex;
    
    {
        uint __sdslv_row = (thread.GroupId).x * 16u;
        uint __sdslv_column = (thread.GroupId).y * 16u;
        __sdslv_cooperative::MatrixC __sdslv_accumulator;
        __sdslv_accumulator.value = __sdslv_cooperative::Splat<__sdslv_cooperative::MatrixCType>(0.0f);
        [loop]
        for (uint __sdslv_inner = 0u; __sdslv_inner < params.k; __sdslv_inner += 16u)
        {
            [unroll]
            for (uint __sdslv_element = thread.GroupIndex; __sdslv_element < 256u; __sdslv_element += 32u)
            {
                uint __sdslv_tile_row = __sdslv_element / 16u;
                uint __sdslv_tile_column = __sdslv_element % 16u;
                uint __sdslv_a_element = (__sdslv_row + __sdslv_tile_row) * params.k + __sdslv_inner + __sdslv_tile_column;
                uint __sdslv_b_element = (__sdslv_inner + __sdslv_tile_row) * params.n + __sdslv_column + __sdslv_tile_column;
                uint __sdslv_a_packed = A[__sdslv_a_element / 2u];
                uint __sdslv_b_packed = B[__sdslv_b_element / 2u];
                __sdslv_cooperative_tile_a[__sdslv_element] = (float16_t)f16tof32((__sdslv_a_element % 2u) == 0u ? (__sdslv_a_packed & 65535u) : (__sdslv_a_packed >> 16u));
                __sdslv_cooperative_tile_b[__sdslv_element] = (float16_t)f16tof32((__sdslv_b_element % 2u) == 0u ? (__sdslv_b_packed & 65535u) : (__sdslv_b_packed >> 16u));
            }
            GroupMemoryBarrierWithGroupSync();
            __sdslv_cooperative::MatrixA __sdslv_tile_a;
            __sdslv_tile_a.value = __sdslv_cooperative::Load<__sdslv_cooperative::MatrixAType>(__sdslv_cooperative::GetGroupSharedAddress(__sdslv_cooperative_tile_a[0]), __sdslv_cooperative::RowMajor, 16u, 48, __sdslv_cooperative::ScopeWorkgroup);
            __sdslv_cooperative::MatrixB __sdslv_tile_b;
            __sdslv_tile_b.value = __sdslv_cooperative::Load<__sdslv_cooperative::MatrixBType>(__sdslv_cooperative::GetGroupSharedAddress(__sdslv_cooperative_tile_b[0]), __sdslv_cooperative::RowMajor, 16u, 48, __sdslv_cooperative::ScopeWorkgroup);
            __sdslv_accumulator.value = __sdslv_cooperative::MultiplyAdd<__sdslv_cooperative::MatrixCType>(__sdslv_tile_a.value, __sdslv_tile_b.value, __sdslv_accumulator.value, 0);
            GroupMemoryBarrierWithGroupSync();
        }
        __sdslv_cooperative::Store(C[__sdslv_row * params.n + __sdslv_column], __sdslv_accumulator.value, __sdslv_cooperative::RowMajor, params.n, 0);
    }
    return;
}

