// Package compileddata emits validated Oct values as backend-native Go static
// data. It is deliberately an emitter, not a wire format or runtime decoder.
package compileddata

import (
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"go/format"
	"sort"
	"strconv"
	"strings"
	"time"
	"unicode"

	"github.com/yuechen-li-dev/oct/internal/layoutcontract"
)

type Kind string

const (
	Int        Kind = "Int"
	Float      Kind = "Float"
	Bool       Kind = "Bool"
	String     Kind = "String"
	Array      Kind = "Array"
	Record     Kind = "Record"
	Enum       Kind = "Enum"
	Refinement Kind = "Refinement"
)

type Type struct {
	Kind     Kind
	Name     string
	Elem     *Type
	Base     *Type
	Fields   []Field
	Variants []string
	Table    bool
}

type Field struct {
	Name string
	Type Type
}

type Value struct {
	Kind    Kind
	Int     int64
	Float   float64
	Bool    bool
	Text    string
	Array   []Value
	Fields  map[string]Value
	Variant string
}

type Dataset struct {
	Symbol       string
	Type         Type
	Value        Value
	ProofSubject layoutcontract.DataSubjectRef
	StaticFacts  []layoutcontract.StaticFact
}

type Result struct {
	Source          []byte
	LogicalHash     string
	SchemaHash      string
	RowCount        int
	Timings         Timings
	Contract        layoutcontract.Contract
	Materialization string
}

type Timings struct {
	Validation         time.Duration
	ContractEnrichment time.Duration
	Emission           time.Duration
	Formatting         time.Duration
}

func EmitGo(dataset Dataset) (Result, error) {
	return emitGo(dataset, 2)
}

// emitGoGeneric is the test/benchmark control for the pre-contract emitter.
// It is intentionally unexported: this is not a user-facing compiler option.
func emitGoGeneric(dataset Dataset) (Result, error) {
	return emitGo(dataset, 0)
}

// emitGoLayout is the M1 materialized-projection benchmark control.
func emitGoLayout(dataset Dataset) (Result, error) {
	return emitGo(dataset, 1)
}

func emitGo(dataset Dataset, materializationLevel int) (Result, error) {
	validationStarted := time.Now()
	if !validIdentifier(dataset.Symbol) {
		return Result{}, fmt.Errorf("compiled data symbol %q is not a valid Go identifier", dataset.Symbol)
	}
	if err := validate(dataset.Type, dataset.Value, dataset.Type.Name); err != nil {
		return Result{}, err
	}
	logical := canonicalValue(dataset.Type, dataset.Value)
	schema := canonicalType(dataset.Type)
	logicalHash := hash(logical)
	schemaHash := hash(schema)
	validationElapsed := time.Since(validationStarted)
	contractStarted := time.Now()
	contract := deriveLayoutContract(dataset)
	contractElapsed := time.Since(contractStarted)

	emissionStarted := time.Now()
	var b strings.Builder
	b.WriteString("// Code generated by Oct compiled-data publication. DO NOT EDIT.\n")
	b.WriteString("package main\n\n")
	emitDeclarations(&b, dataset.Type, map[string]bool{})
	fmt.Fprintf(&b, "const %sLogicalHash = %q\n", dataset.Symbol, logicalHash)
	fmt.Fprintf(&b, "const %sSchemaHash = %q\n", dataset.Symbol, schemaHash)
	rows := 0
	if dataset.Type.Kind == Record && dataset.Type.Table {
		rows = tableExtent(dataset.Value)
		fmt.Fprintf(&b, "const %sRowCount = %d\n\n", dataset.Symbol, rows)
		emitTable(&b, dataset.Symbol, dataset.Type, dataset.Value)
		if materializationLevel >= 1 {
			emitColumnProjections(&b, dataset.Symbol, dataset.Type, dataset.Value, contract)
		}
		if materializationLevel >= 2 {
			emitSearchIndexes(&b, dataset.Symbol, dataset.Type, contract)
		}
	} else {
		if materializationLevel >= 1 && dataset.Type.Kind == Array && contract.Invariants.ExactExtent != nil {
			fmt.Fprintf(&b, "const %sExtent = %d\n", dataset.Symbol, contract.Invariants.ExactExtent.Value)
		}
		b.WriteString("\nvar ")
		b.WriteString(dataset.Symbol)
		b.WriteString(" = ")
		emitValue(&b, dataset.Type, dataset.Value)
		b.WriteString("\n")
	}
	emissionElapsed := time.Since(emissionStarted)
	formatStarted := time.Now()
	formatted, err := format.Source([]byte(b.String()))
	if err != nil {
		return Result{}, fmt.Errorf("format compiled Go data: %w", err)
	}
	materialization := "generic-static-value"
	if dataset.Type.Kind == Record && dataset.Type.Table {
		materialization = "row-array"
		if materializationLevel >= 1 && len(contract.Metadata.ColumnProjections) > 0 {
			materialization = "row-array+static-column-projections"
		}
		if materializationLevel >= 2 && len(contract.Metadata.SearchIndexes) > 0 {
			materialization += "+proved-binary-search"
		}
	} else if dataset.Type.Kind == Array && contract.Invariants.ExactExtent != nil {
		materialization = "fixed-array"
	}
	return Result{Source: formatted, LogicalHash: logicalHash, SchemaHash: schemaHash, RowCount: rows, Timings: Timings{Validation: validationElapsed, ContractEnrichment: contractElapsed, Emission: emissionElapsed, Formatting: time.Since(formatStarted)}, Contract: contract, Materialization: materialization}, nil
}

func deriveLayoutContract(dataset Dataset) layoutcontract.Contract {
	phase := layoutcontract.Provenance{Phase: layoutcontract.PublicationMaterial, Source: "Artifact.WriteCompiledData"}
	subjectKind := layoutcontract.CompiledDataRoot
	identity := dataset.Symbol
	contract := layoutcontract.Contract{Subject: layoutcontract.DataSubjectRef{Kind: subjectKind, Identity: identity}}
	contract.Invariants.Immutable = &layoutcontract.Immutable{Provenance: phase}
	if dataset.Type.Name != "" {
		contract.Invariants.NominalIdentity = &layoutcontract.NominalIdentity{Provenance: phase}
	}
	if dataset.Type.Kind == Record && dataset.Type.Table {
		contract.Invariants.ExactExtent = &layoutcontract.ExactExtent{Value: tableExtent(dataset.Value), Provenance: phase}
		contract.Invariants.LogicalOrder = &layoutcontract.LogicalOrder{Provenance: phase}
		for ordinal, field := range dataset.Type.Fields {
			if staticallyProjectable(field.Type) {
				contract.Metadata.ColumnProjections = append(contract.Metadata.ColumnProjections, layoutcontract.ColumnProjectionEligibility{Field: layoutcontract.FieldRef{Subject: contract.Subject, Ordinal: ordinal, Name: field.Name}, Provenance: phase})
			}
		}
	} else if dataset.Type.Kind == Array {
		contract.Subject.Kind = layoutcontract.StaticArray
		contract.Invariants.ExactExtent = &layoutcontract.ExactExtent{Value: len(dataset.Value.Array), Provenance: phase}
		contract.Invariants.LogicalOrder = &layoutcontract.LogicalOrder{Provenance: phase}
	}
	promoted := rebaseStaticFacts(dataset, contract.Subject)
	layoutcontract.Enrich(&contract, promoted)
	for _, unique := range contract.Invariants.UniqueFields {
		if !hasFieldInvariant(contract.Invariants.SortedFields, unique.Field) || !fieldSupportsBinarySearch(dataset.Type, unique.Field) {
			continue
		}
		contract.Metadata.SearchIndexes = append(contract.Metadata.SearchIndexes, layoutcontract.SearchIndexEligibility{
			Field: unique.Field, DerivedFrom: contract.Subject,
			ProofBasis: []layoutcontract.StaticFactKind{layoutcontract.Unique, layoutcontract.SortedAscending},
		})
	}
	return contract
}

func rebaseStaticFacts(dataset Dataset, target layoutcontract.DataSubjectRef) []layoutcontract.StaticFact {
	if dataset.ProofSubject.Identity == "" {
		return nil
	}
	result := make([]layoutcontract.StaticFact, 0, len(dataset.StaticFacts))
	for _, fact := range dataset.StaticFacts {
		if fact.Subject != dataset.ProofSubject || fact.Provenance.Phase != layoutcontract.ArtifactEvaluation || fact.Provenance.Source != layoutcontract.StaticAssertProof || len(fact.Fields) != 1 {
			continue
		}
		field := fact.Fields[0]
		if field.Subject != dataset.ProofSubject || field.Ordinal < 0 || field.Ordinal >= len(dataset.Type.Fields) || dataset.Type.Fields[field.Ordinal].Name != field.Name {
			continue
		}
		fact.Subject = target
		fact.Fields = []layoutcontract.FieldRef{{Subject: target, Ordinal: field.Ordinal, Name: field.Name}}
		result = append(result, fact)
	}
	return result
}

func hasFieldInvariant(invariants []layoutcontract.FieldInvariant, field layoutcontract.FieldRef) bool {
	for _, invariant := range invariants {
		if invariant.Field == field {
			return true
		}
	}
	return false
}

func fieldSupportsBinarySearch(typ Type, field layoutcontract.FieldRef) bool {
	return typ.Kind == Record && typ.Table && field.Ordinal >= 0 && field.Ordinal < len(typ.Fields) && typ.Fields[field.Ordinal].Name == field.Name && typ.Fields[field.Ordinal].Type.Kind == Int
}

func staticallyProjectable(typ Type) bool {
	if typ.Kind == Refinement && typ.Base != nil {
		return staticallyProjectable(*typ.Base)
	}
	switch typ.Kind {
	case Int, Float, Bool, String, Enum:
		return true
	default:
		return false
	}
}

func emitColumnProjections(b *strings.Builder, symbol string, typ Type, value Value, contract layoutcontract.Contract) {
	if contract.Invariants.ExactExtent == nil || contract.Invariants.LogicalOrder == nil || contract.Invariants.Immutable == nil {
		return
	}
	for _, candidate := range contract.Metadata.ColumnProjections {
		for _, field := range typ.Fields {
			if field.Name != candidate.Field.Name {
				continue
			}
			fmt.Fprintf(b, "\nvar %s%sColumn = [...]%s{", symbol, safeName(field.Name), goType(field.Type))
			for index, item := range value.Fields[field.Name].Array {
				if index > 0 {
					b.WriteString(", ")
				}
				emitValue(b, field.Type, item)
			}
			b.WriteString("}\n")
			break
		}
	}
}

func emitSearchIndexes(b *strings.Builder, symbol string, typ Type, contract layoutcontract.Contract) {
	for _, candidate := range contract.Metadata.SearchIndexes {
		field := typ.Fields[candidate.Field.Ordinal]
		if field.Type.Kind != Int {
			continue
		}
		rowType := safeName(typ.Name) + "Row"
		column := symbol + safeName(field.Name) + "Column"
		fmt.Fprintf(b, "\nfunc %sLookupBy%s(key int) (%s, bool) {\n", symbol, safeName(field.Name), rowType)
		fmt.Fprintf(b, "\tlow, high := 0, len(%s)\n", column)
		b.WriteString("\tfor low < high {\n")
		b.WriteString("\t\tmiddle := int(uint(low+high) >> 1)\n")
		fmt.Fprintf(b, "\t\tif %s[middle] < key { low = middle + 1 } else { high = middle }\n", column)
		b.WriteString("\t}\n")
		fmt.Fprintf(b, "\tif low < len(%s) && %s[low] == key { return %s[low], true }\n", column, column, symbol)
		fmt.Fprintf(b, "\treturn %s{}, false\n", rowType)
		b.WriteString("}\n")
	}
}

func emitDeclarations(b *strings.Builder, typ Type, seen map[string]bool) {
	if typ.Kind == Array && typ.Elem != nil {
		emitDeclarations(b, *typ.Elem, seen)
		return
	}
	if typ.Kind == Refinement && typ.Base != nil {
		if seen[typ.Name] {
			return
		}
		seen[typ.Name] = true
		emitDeclarations(b, *typ.Base, seen)
		fmt.Fprintf(b, "type %s = %s\n\n", safeName(typ.Name), goType(*typ.Base))
		return
	}
	if typ.Name == "" || seen[typ.Name] {
		return
	}
	seen[typ.Name] = true
	switch typ.Kind {
	case Enum:
		fmt.Fprintf(b, "type %s int\n\nconst (\n", safeName(typ.Name))
		for index, variant := range typ.Variants {
			fmt.Fprintf(b, "\t%s_%s %s = %d\n", safeName(typ.Name), safeName(variant), safeName(typ.Name), index)
		}
		b.WriteString(")\n\n")
	case Record:
		for _, field := range typ.Fields {
			emitDeclarations(b, field.Type, seen)
		}
		name := safeName(typ.Name)
		if typ.Table {
			name += "Row"
		}
		fmt.Fprintf(b, "type %s struct {\n", name)
		for _, field := range typ.Fields {
			fmt.Fprintf(b, "\t%s %s\n", safeName(field.Name), goType(field.Type))
		}
		b.WriteString("}\n\n")
	}
}

func emitTable(b *strings.Builder, symbol string, typ Type, value Value) {
	rows := tableExtent(value)
	fmt.Fprintf(b, "var %s = [...]%sRow{\n", symbol, safeName(typ.Name))
	for row := 0; row < rows; row++ {
		b.WriteString("\t{")
		for index, field := range typ.Fields {
			if index > 0 {
				b.WriteString(", ")
			}
			fmt.Fprintf(b, "%s: ", safeName(field.Name))
			emitValue(b, field.Type, value.Fields[field.Name].Array[row])
		}
		b.WriteString("},\n")
	}
	b.WriteString("}\n")
}

func emitValue(b *strings.Builder, typ Type, value Value) {
	switch typ.Kind {
	case Int:
		b.WriteString(strconv.FormatInt(value.Int, 10))
	case Float:
		b.WriteString(strconv.FormatFloat(value.Float, 'g', -1, 64))
	case Bool:
		b.WriteString(strconv.FormatBool(value.Bool))
	case String:
		b.WriteString(strconv.Quote(value.Text))
	case Refinement:
		emitValue(b, *typ.Base, value)
	case Enum:
		fmt.Fprintf(b, "%s_%s", safeName(typ.Name), safeName(value.Variant))
	case Array:
		fmt.Fprintf(b, "[...]%s{", goType(*typ.Elem))
		for index, item := range value.Array {
			if index > 0 {
				b.WriteString(", ")
			}
			emitValue(b, *typ.Elem, item)
		}
		b.WriteString("}")
	case Record:
		fmt.Fprintf(b, "%s{", safeName(typ.Name))
		for index, field := range typ.Fields {
			if index > 0 {
				b.WriteString(", ")
			}
			fmt.Fprintf(b, "%s: ", safeName(field.Name))
			emitValue(b, field.Type, value.Fields[field.Name])
		}
		b.WriteString("}")
	}
}

func goType(typ Type) string {
	switch typ.Kind {
	case Int:
		return "int"
	case Float:
		return "float64"
	case Bool:
		return "bool"
	case String:
		return "string"
	case Array:
		return "[]" + goType(*typ.Elem)
	case Record, Enum, Refinement:
		return safeName(typ.Name)
	default:
		return "any"
	}
}

func validate(typ Type, value Value, path string) error {
	if typ.Kind == Refinement {
		return validate(*typ.Base, value, path)
	}
	if typ.Kind != value.Kind {
		return fmt.Errorf("compiled data %s expects %s, got %s", path, typ.Kind, value.Kind)
	}
	switch typ.Kind {
	case Array:
		for index, item := range value.Array {
			if err := validate(*typ.Elem, item, fmt.Sprintf("%s[%d]", path, index)); err != nil {
				return err
			}
		}
	case Enum:
		for _, variant := range typ.Variants {
			if value.Variant == variant {
				return nil
			}
		}
		return fmt.Errorf("compiled data %s has unknown %s variant %q", path, typ.Name, value.Variant)
	case Record:
		for _, field := range typ.Fields {
			fieldValue, ok := value.Fields[field.Name]
			if !ok {
				return fmt.Errorf("compiled data %s missing field %s", path, field.Name)
			}
			fieldType := field.Type
			if typ.Table {
				fieldType = Type{Kind: Array, Elem: &field.Type}
			}
			if err := validate(fieldType, fieldValue, path+"."+field.Name); err != nil {
				return err
			}
		}
		if typ.Table {
			want := -1
			for _, field := range typ.Fields {
				got := len(value.Fields[field.Name].Array)
				if want < 0 {
					want = got
				} else if got != want {
					return fmt.Errorf("compiled data table %s column %s has extent %d; expected %d", typ.Name, field.Name, got, want)
				}
			}
		}
	}
	return nil
}

func tableExtent(value Value) int {
	for _, column := range value.Fields {
		return len(column.Array)
	}
	return 0
}
func hash(text string) string {
	sum := sha256.Sum256([]byte(text))
	return "sha256:" + hex.EncodeToString(sum[:])
}
func canonicalType(typ Type) string {
	var b strings.Builder
	b.WriteString(string(typ.Kind))
	b.WriteString(typ.Name)
	if typ.Table {
		b.WriteString("#table")
	}
	if typ.Elem != nil {
		b.WriteString("[")
		b.WriteString(canonicalType(*typ.Elem))
		b.WriteString("]")
	}
	if typ.Base != nil {
		b.WriteString("=")
		b.WriteString(canonicalType(*typ.Base))
	}
	for _, field := range typ.Fields {
		b.WriteString(";")
		b.WriteString(field.Name)
		b.WriteString(":")
		b.WriteString(canonicalType(field.Type))
	}
	for _, variant := range typ.Variants {
		b.WriteString("|")
		b.WriteString(variant)
	}
	return b.String()
}
func canonicalValue(typ Type, value Value) string {
	if typ.Kind == Refinement {
		return canonicalValue(*typ.Base, value)
	}
	var b strings.Builder
	switch typ.Kind {
	case Int:
		b.WriteString(strconv.FormatInt(value.Int, 10))
	case Float:
		b.WriteString(strconv.FormatFloat(value.Float, 'g', -1, 64))
	case Bool:
		b.WriteString(strconv.FormatBool(value.Bool))
	case String:
		b.WriteString(strconv.Quote(value.Text))
	case Enum:
		b.WriteString(typ.Name + "." + value.Variant)
	case Array:
		for _, item := range value.Array {
			b.WriteString("[")
			b.WriteString(canonicalValue(*typ.Elem, item))
			b.WriteString("]")
		}
	case Record:
		for _, field := range typ.Fields {
			b.WriteString(field.Name + ":")
			fieldType := field.Type
			if typ.Table {
				fieldType = Type{Kind: Array, Elem: &field.Type}
			}
			b.WriteString(canonicalValue(fieldType, value.Fields[field.Name]))
		}
	}
	return b.String()
}
func safeName(name string) string {
	if dot := strings.LastIndex(name, "."); dot >= 0 {
		name = name[dot+1:]
	}
	var b strings.Builder
	for _, r := range name {
		if unicode.IsLetter(r) || unicode.IsDigit(r) || r == '_' {
			b.WriteRune(r)
		} else {
			b.WriteRune('_')
		}
	}
	return b.String()
}
func validIdentifier(name string) bool {
	if name == "" {
		return false
	}
	for index, r := range name {
		if (index == 0 && !unicode.IsLetter(r) && r != '_') || (index > 0 && !unicode.IsLetter(r) && !unicode.IsDigit(r) && r != '_') {
			return false
		}
	}
	return true
}

// StableTypeNames returns nominal names in deterministic order for diagnostics.
func StableTypeNames(types map[string]Type) []string {
	names := make([]string, 0, len(types))
	for name := range types {
		names = append(names, name)
	}
	sort.Strings(names)
	return names
}
