// Generated by GoOct SDSL-V M36a. Do not edit.
[[vk::binding(0, 0)]] StructuredBuffer<float> Input;
[[vk::binding(1, 0)]] RWStructuredBuffer<float> Output;
[numthreads(1, 1, 1)]
void main()
{
    float values[4];
    for (uint i = 0u; i < 4u; ++i)
    {
        uint __sdslv_tensor_index_0 = i;
        uint __sdslv_tensor_offset_1 = __sdslv_tensor_index_0;
        values[__sdslv_tensor_offset_1] = ((Input[i] * 2.0) + 1.0);
    }
    float copied[4];
    for (uint i = 0u; i < 4u; ++i)
    {
        uint __sdslv_tensor_index_2 = i;
        uint __sdslv_tensor_offset_3 = __sdslv_tensor_index_2;
        copied[__sdslv_tensor_offset_3] = values[i];
    }
    Output[0u] = copied[0u];
    Output[1u] = copied[1u];
    Output[2u] = copied[2u];
    Output[3u] = copied[3u];
    return;
}

