// Generated by GoOct SDSL-V M36a. Do not edit.
[[vk::binding(0, 0)]] StructuredBuffer<float> Input;
[[vk::binding(1, 0)]] RWStructuredBuffer<float> Output;
[numthreads(1, 1, 1)]
void main()
{
    float values[4];
    for (uint i = 0u; i < 4u; ++i)
    {
        uint __sdslv_tensor_index_0 = i;
        uint __sdslv_tensor_offset_1 = __sdslv_tensor_index_0;
        values[__sdslv_tensor_offset_1] = ((Input[i] * 2.0) + 1.0);
    }
    float copied[4];
    // tensor free-index loop 53:23 i
    for (uint __sdslv_tensor_free_0 = 0u; __sdslv_tensor_free_0 < 4u; __sdslv_tensor_free_0 += 1u)
    {
        // tensor statement 53:9 set
        uint __sdslv_tensor_index_2 = __sdslv_tensor_free_0;
        uint __sdslv_tensor_offset_3 = __sdslv_tensor_index_2;
        float __sdslv_tensor_rhs_4 = values[__sdslv_tensor_free_0];
        // tensor final destination write 53:9 =
        copied[__sdslv_tensor_offset_3] = __sdslv_tensor_rhs_4;
    }
    Output[0u] = copied[0u];
    Output[1u] = copied[1u];
    Output[2u] = copied[2u];
    Output[3u] = copied[3u];
    return;
}

