// Generated by GoOct SDSL-V M36a. Do not edit.
[[vk::binding(0, 0)]] StructuredBuffer<float> Input;
[[vk::binding(1, 0)]] RWStructuredBuffer<float> Output;
[numthreads(1, 1, 1)]
void main()
{
    float left[4];
    for (uint i = 0u; i < 2u; ++i)
    {
        for (uint k = 0u; k < 2u; ++k)
        {
            uint __sdslv_tensor_index_0 = i;
            uint __sdslv_tensor_index_1 = k;
            uint __sdslv_tensor_offset_2 = ((__sdslv_tensor_index_0 * 2u) + __sdslv_tensor_index_1);
            left[__sdslv_tensor_offset_2] = ((Input[0u] + i) + k);
        }
    }
    float right[4];
    for (uint k = 0u; k < 2u; ++k)
    {
        for (uint j = 0u; j < 2u; ++j)
        {
            uint __sdslv_tensor_index_3 = k;
            uint __sdslv_tensor_index_4 = j;
            uint __sdslv_tensor_offset_5 = ((__sdslv_tensor_index_3 * 2u) + __sdslv_tensor_index_4);
            right[__sdslv_tensor_offset_5] = (((Input[0u] + k) + j) + 1.0);
        }
    }
    float result[4];
    // tensor free-index loop 79:23 i
    for (uint __sdslv_tensor_free_0 = 0u; __sdslv_tensor_free_0 < 2u; __sdslv_tensor_free_0 += 1u)
    {
        // tensor free-index loop 79:26 j
        for (uint __sdslv_tensor_free_1 = 0u; __sdslv_tensor_free_1 < 2u; __sdslv_tensor_free_1 += 1u)
        {
            // tensor statement 79:9 set
            uint __sdslv_tensor_index_6 = __sdslv_tensor_free_0;
            uint __sdslv_tensor_index_7 = __sdslv_tensor_free_1;
            uint __sdslv_tensor_offset_8 = ((__sdslv_tensor_index_6 * 2u) + __sdslv_tensor_index_7);
            // tensor accumulator initialization examples/SDSL-V/M36a/BasicBenchmarks.sdslvbench:79:31 Sum
            float __sdslv_tensor_accumulator_10 = 0.0;
            // tensor reduction loop 79:35 k
            for (uint __sdslv_tensor_reduce_0 = 0u; __sdslv_tensor_reduce_0 < 2u; __sdslv_tensor_reduce_0 += 1u)
            {
                // tensor reduction body 79:31 Sum
                __sdslv_tensor_accumulator_10 = __sdslv_tensor_accumulator_10 + ((left[((__sdslv_tensor_free_0 * 2u) + __sdslv_tensor_reduce_0)] * right[((__sdslv_tensor_reduce_0 * 2u) + __sdslv_tensor_free_1)]));
            }
            float __sdslv_tensor_rhs_9 = __sdslv_tensor_accumulator_10;
            // tensor final destination write 79:9 =
            result[__sdslv_tensor_offset_8] = __sdslv_tensor_rhs_9;
        }
    }
    Output[0u] = result[((0u * 2u) + 0u)];
    Output[1u] = result[((0u * 2u) + 1u)];
    Output[2u] = result[((1u * 2u) + 0u)];
    Output[3u] = result[((1u * 2u) + 1u)];
    return;
}

