// Generated by GoOct SDSL-V M36a. Do not edit.
[[vk::binding(0, 0)]] StructuredBuffer<float> Input;
[[vk::binding(1, 0)]] RWStructuredBuffer<float> Output;
[numthreads(1, 1, 1)]
void main()
{
    float left[4];
    for (uint i = 0u; i < 2u; ++i)
    {
        for (uint k = 0u; k < 2u; ++k)
        {
            uint __sdslv_tensor_index_0 = i;
            uint __sdslv_tensor_index_1 = k;
            uint __sdslv_tensor_offset_2 = ((__sdslv_tensor_index_0 * 2u) + __sdslv_tensor_index_1);
            left[__sdslv_tensor_offset_2] = ((Input[0u] + i) + k);
        }
    }
    float right[4];
    for (uint k = 0u; k < 2u; ++k)
    {
        for (uint j = 0u; j < 2u; ++j)
        {
            uint __sdslv_tensor_index_3 = k;
            uint __sdslv_tensor_index_4 = j;
            uint __sdslv_tensor_offset_5 = ((__sdslv_tensor_index_3 * 2u) + __sdslv_tensor_index_4);
            right[__sdslv_tensor_offset_5] = (((Input[0u] + k) + j) + 1.0);
        }
    }
    float result[4];
    for (uint i = 0u; i < 2u; ++i)
    {
        for (uint j = 0u; j < 2u; ++j)
        {
            uint __sdslv_tensor_index_6 = i;
            uint __sdslv_tensor_index_7 = j;
            uint __sdslv_tensor_offset_8 = ((__sdslv_tensor_index_6 * 2u) + __sdslv_tensor_index_7);
            float __sdslv_reduce_9 = 0.0;
            for (uint k = 0u; k < 2u; k += 1)
            {
                __sdslv_reduce_9 = __sdslv_reduce_9 + ((left[((i * 2u) + k)] * right[((k * 2u) + j)]));
            }
            result[__sdslv_tensor_offset_8] = __sdslv_reduce_9;
        }
    }
    Output[0u] = result[((0u * 2u) + 0u)];
    Output[1u] = result[((0u * 2u) + 1u)];
    Output[2u] = result[((1u * 2u) + 0u)];
    Output[3u] = result[((1u * 2u) + 1u)];
    return;
}

