// Generated by canonical GoOct SDSL-V via VD-MIR. Do not edit by hand.
// namespace Sdslv.Conformance.AttentionSpaceErased

// type ModelEmbedding = float4

// type QwenHidden = float4

// type QueryHead = float4

// type KeyHead = float4

// type ValueHead = float4

// type PositionedQueryHead = float4

// type PositionedKeyHead = float4

// type AlternatePositionedKeyHead = float4

// type AttentionScore = float4

// type AttentionProbability = float4

// type AttentionOutput = float4

// type FrameCoordinate = float2

// type RowCoordinate = float2

// type ColumnCoordinate = float2

// type TextTokenCoordinate = float2

// type ForeignValueHead = float4

// type QueryTensor = float4

// type KeyTensor = float4

// type ValueTensor = float4

struct ZImageM1Contract
{
    uint ModelWidth;
    uint HeadCount;
    uint HeadWidth;
    uint FfnWidth;
    uint RopeFrameWidth;
    uint RopeRowWidth;
    uint RopeColumnWidth;
    uint RopeTheta;
};

struct FusedQKV
{
    float4 Query;
    float4 Key;
    float4 Value;
};

struct ComputeThread
{
    [[vk::location(0)]] nointerpolation uint3 DispatchId : TEXCOORD0;
    [[vk::location(1)]] nointerpolation uint3 GroupId : TEXCOORD1;
    [[vk::location(2)]] nointerpolation uint3 GroupThreadId : TEXCOORD2;
    [[vk::location(3)]] nointerpolation uint GroupIndex : TEXCOORD3;
};

static const int QueryPositionState_Unpositioned = 0;
static const int QueryPositionState_Positioned = 1;
struct QueryPositionState_UnpositionedPayload
{
    float4 Value;
};

struct QueryPositionState_PositionedPayload
{
    float4 Value;
};

struct QueryPositionState
{
    int Tag;
    QueryPositionState_UnpositionedPayload Unpositioned;
    QueryPositionState_PositionedPayload Positioned;
};

QueryPositionState __sdslv_make_QueryPositionState_Unpositioned(float4 Value)
{
    QueryPositionState value;
    value.Tag = QueryPositionState_Unpositioned;
    value.Unpositioned.Value = Value;
    return value;
}

QueryPositionState __sdslv_make_QueryPositionState_Positioned(float4 Value)
{
    QueryPositionState value;
    value.Tag = QueryPositionState_Positioned;
    value.Positioned.Value = Value;
    return value;
}

[[vk::binding(0, 0)]] StructuredBuffer<float> Input;
[[vk::binding(1, 0)]] RWStructuredBuffer<float> Output;

float4 ProjectQuery(float4 value)
{
    return float4(value.x, value.y, value.z, value.w);
}

float4 ProjectKey(float4 value)
{
    return float4(value.x, value.y, value.z, value.w);
}

float4 ProjectValue(float4 value)
{
    return float4(value.x, value.y, value.z, value.w);
}

FusedQKV ProjectFusedQKV(float4 value)
{
    FusedQKV __sdslv_board_0;
    __sdslv_board_0.Query = ProjectQuery(value);
    __sdslv_board_0.Key = ProjectKey(value);
    __sdslv_board_0.Value = ProjectValue(value);
    return __sdslv_board_0;
}

float MaximumFinite(float a, float b)
{
    if ((b > a))
    {
        return b;
    }
    return a;
}

float4 NormalizeQuery(float4 value)
{
    float __sdslv_operand_1 = MaximumFinite(0.000001, ((((value.x * value.x) + (value.y * value.y)) + (value.z * value.z)) + (value.w * value.w)));
    float scale = (1.0 / __sdslv_operand_1);
    return float4((value.x * scale), (value.y * scale), (value.z * scale), (value.w * scale));
}

float4 NormalizeKey(float4 value)
{
    float __sdslv_operand_2 = MaximumFinite(0.000001, ((((value.x * value.x) + (value.y * value.y)) + (value.z * value.z)) + (value.w * value.w)));
    float scale = (1.0 / __sdslv_operand_2);
    return float4((value.x * scale), (value.y * scale), (value.z * scale), (value.w * scale));
}

float4 ApplyQueryRoPE(float4 value, float2 frame, float2 row, float2 column)
{
    float semanticWitness = (((frame.x + row.x) + column.x) * 0.0);
    return float4((value.x + semanticWitness), value.y, value.z, value.w);
}

float4 ApplyKeyRoPE(float4 value, float2 frame, float2 row, float2 column)
{
    float semanticWitness = (((frame.x + row.x) + column.x) * 0.0);
    return float4((value.x + semanticWitness), value.y, value.z, value.w);
}

float4 Score(float4 query, float4 key)
{
    float dot = ((((query.x * key.x) + (query.y * key.y)) + (query.z * key.z)) + (query.w * key.w));
    return float4(dot, (dot - 1.0), (dot - 2.0), (dot - 3.0));
}

float ExpF32(float value)
{
    float __sdslv_inline_hlsl_3;
    {
        // BEGIN INLINE HLSL Examples/SDSL-V/conformance/compute/AttentionSpacePocErased.sdslvvalid:113
         __sdslv_inline_hlsl_3 = exp(value); 
        // END INLINE HLSL
    }
    float result = __sdslv_inline_hlsl_3;
    return result;
}

float4 NormalizeScores(float4 scores)
{
    float __sdslv_operand_4 = MaximumFinite(scores.x, scores.y);
    float __sdslv_operand_5 = MaximumFinite(scores.z, scores.w);
    float maximum = MaximumFinite(__sdslv_operand_4, __sdslv_operand_5);
    float ex = ExpF32((scores.x - maximum));
    float ey = ExpF32((scores.y - maximum));
    float ez = ExpF32((scores.z - maximum));
    float ew = ExpF32((scores.w - maximum));
    float denominator = (((ex + ey) + ez) + ew);
    return float4((ex / denominator), (ey / denominator), (ez / denominator), (ew / denominator));
}

float4 AggregateValues(float4 probability, float4 value)
{
    return float4((probability.x * value.x), (probability.y * value.y), (probability.z * value.z), (probability.w * value.w));
}

float4 OutputProject(float4 value)
{
    return float4(value.x, value.y, value.z, value.w);
}

float4 AddResidual(float4 residual, float4 attention)
{
    return float4((residual.x + attention.x), (residual.y + attention.y), (residual.z + attention.z), (residual.w + attention.w));
}

[numthreads(1, 1, 1)]
void AttentionSpacePoc_CS(uint3 DispatchThreadID : SV_DispatchThreadID, uint3 GroupThreadID : SV_GroupThreadID, uint3 GroupID : SV_GroupID, uint GroupIndex : SV_GroupIndex)
{
    ComputeThread thread;
    thread.DispatchId = DispatchThreadID;
    thread.GroupId = GroupID;
    thread.GroupThreadId = GroupThreadID;
    thread.GroupIndex = GroupIndex;
    
    ZImageM1Contract contract;
    contract.ModelWidth = 3840u;
    contract.HeadCount = 30u;
    contract.HeadWidth = 128u;
    contract.FfnWidth = 10240u;
    contract.RopeFrameWidth = 32u;
    contract.RopeRowWidth = 48u;
    contract.RopeColumnWidth = 48u;
    contract.RopeTheta = 256u;
    float4 embedding = float4(Input[0u], Input[1u], Input[2u], Input[3u]);
    FusedQKV fused = ProjectFusedQKV(embedding);
    float4 query = NormalizeQuery(fused.Query);
    float4 key = NormalizeKey(fused.Key);
    float2 frame = float2(float(contract.RopeFrameWidth), 0.0);
    float2 row = float2(float(contract.RopeRowWidth), 0.0);
    float2 column = float2(float(contract.RopeColumnWidth), 0.0);
    float4 positionedQuery = ApplyQueryRoPE(query, frame, row, column);
    float4 positionedKey = ApplyKeyRoPE(key, frame, row, column);
    float4 attentionScore = Score(positionedQuery, positionedKey);
    float4 probability = NormalizeScores(attentionScore);
    float4 aggregated = AggregateValues(probability, fused.Value);
    float4 projected = OutputProject(aggregated);
    float4 output = AddResidual(embedding, projected);
    Output[0u] = (output.x + (float(((((((thread.GroupIndex + contract.HeadCount) + contract.HeadWidth) + contract.ModelWidth) + contract.FfnWidth) + contract.RopeColumnWidth) + contract.RopeTheta)) * 0.0));
    Output[1u] = output.y;
    Output[2u] = output.z;
    Output[3u] = output.w;
    return;
}

