// Generated by canonical GoOct SDSL-V via VD-MIR. Do not edit by hand.
// namespace Sdslv.AttentionSpace.Equivalence

// type QueryHead = float4 @space(zimage.attention.query_head)

// type KeyHead = float4 @space(zimage.attention.key_head)

// type ValueHead = float4 @space(zimage.attention.value_head)

// type PositionedQueryHead = float4 @space(zimage.attention.positioned_query_head)

// type PositionedKeyHead = float4 @space(zimage.attention.positioned_key_head)

// type Score = float4 @space(zimage.attention.score)

// type Probability = float4 @space(zimage.attention.probability)

// type Output = float4 @space(zimage.attention.output)

struct ComputeThread
{
    [[vk::location(0)]] nointerpolation uint3 DispatchId : TEXCOORD0;
    [[vk::location(1)]] nointerpolation uint3 GroupId : TEXCOORD1;
    [[vk::location(2)]] nointerpolation uint3 GroupThreadId : TEXCOORD2;
    [[vk::location(3)]] nointerpolation uint GroupIndex : TEXCOORD3;
};

[[vk::binding(0, 0)]] StructuredBuffer<float> Input;
[[vk::binding(1, 0)]] RWStructuredBuffer<float> OutputBuffer;

float4 ProjectQuery(float4 value)
{
    return float4(value.x, value.y, value.z, value.w);
}

float4 ProjectKey(float4 value)
{
    return float4(value.x, value.y, value.z, value.w);
}

float4 ProjectValue(float4 value)
{
    return float4(value.x, value.y, value.z, value.w);
}

float4 ApplyQueryRoPE(float4 value)
{
    return float4(value.x, value.y, value.z, value.w);
}

float4 ApplyKeyRoPE(float4 value)
{
    return float4(value.x, value.y, value.z, value.w);
}

float4 Pair(float4 query, float4 key)
{
    return float4((query.x * key.x), (query.y * key.y), (query.z * key.z), (query.w * key.w));
}

float4 NormalizeScores(float4 value)
{
    return float4(value.x, value.y, value.z, value.w);
}

float4 AggregateValues(float4 probability, float4 value)
{
    return float4((probability.x * value.x), (probability.y * value.y), (probability.z * value.z), (probability.w * value.w));
}

[numthreads(1, 1, 1)]
void GroupedSpaceEquivalence_CS(uint3 DispatchThreadID : SV_DispatchThreadID, uint3 GroupThreadID : SV_GroupThreadID, uint3 GroupID : SV_GroupID, uint GroupIndex : SV_GroupIndex)
{
    ComputeThread thread;
    thread.DispatchId = DispatchThreadID;
    thread.GroupId = GroupID;
    thread.GroupThreadId = GroupThreadID;
    thread.GroupIndex = GroupIndex;
    
    float4 input = float4(Input[0u], Input[1u], Input[2u], Input[3u]);
    float4 __sdslv_operand_0 = ProjectQuery(input);
    float4 __sdslv_operand_1 = ApplyQueryRoPE(__sdslv_operand_0);
    float4 __sdslv_operand_2 = ProjectKey(input);
    float4 __sdslv_operand_3 = ApplyKeyRoPE(__sdslv_operand_2);
    float4 scoreValue = Pair(__sdslv_operand_1, __sdslv_operand_3);
    float4 probability = NormalizeScores(scoreValue);
    float4 __sdslv_operand_4 = ProjectValue(input);
    float4 output = AggregateValues(probability, __sdslv_operand_4);
    OutputBuffer[thread.GroupIndex] = output.x;
    return;
}

