// Generated by canonical GoOct SDSL-V via VD-MIR. Do not edit by hand.
// namespace Prometheus.Production.Gemma4E2BM1

struct AttentionScoreParams
{
    uint TokenCount;
    uint QueryHeadCount;
    uint KeyHeadCount;
    uint HeadDim;
    float Scale;
    uint Reserved0;
    uint Reserved1;
    uint Reserved2;
};

[[vk::binding(1, 0)]] StructuredBuffer<float> Key;
[[vk::binding(0, 0)]] StructuredBuffer<float> Query;
[[vk::binding(3, 0)]] RWStructuredBuffer<float> Score;

[[vk::push_constant]] ConstantBuffer<AttentionScoreParams> params;

[numthreads(256, 1, 1)]
void Gemma4E2BM1AttentionScores_CS(uint3 DispatchThreadID : SV_DispatchThreadID)
{
    uint score_index = DispatchThreadID.x;
    uint score_count = ((params.QueryHeadCount * params.TokenCount) * params.TokenCount);
    if ((score_index < score_count))
    {
        uint key_position = (score_index % params.TokenCount);
        uint query_row = (score_index / params.TokenCount);
        uint query_position = (query_row % params.TokenCount);
        uint query_head = (query_row / params.TokenCount);
        uint kv_head = (query_head / (params.QueryHeadCount / params.KeyHeadCount));
        uint query_base = (((query_position * params.QueryHeadCount) + query_head) * params.HeadDim);
        uint key_base = (((key_position * params.KeyHeadCount) + kv_head) * params.HeadDim);
        float accumulator = 0.0;
        for (uint coordinate = 0u; coordinate < params.HeadDim; coordinate += 1)
        {
            accumulator = (accumulator + (Query[(query_base + coordinate)] * Key[(key_base + coordinate)]));
        }
        Score[score_index] = (accumulator * params.Scale);
    }
    return;
}

