// Generated by canonical GoOct SDSL-V via VD-MIR. Do not edit by hand.
// namespace Prometheus.Production.Gemma4E2BM1

struct Bf16RoundtripParams
{
    uint ElementCount;
    uint Reserved0;
    uint Reserved1;
    uint Reserved2;
    uint Reserved3;
    uint Reserved4;
    uint Reserved5;
    uint Reserved6;
};

[[vk::binding(0, 0)]] StructuredBuffer<float> Input;
[[vk::binding(3, 0)]] RWStructuredBuffer<float> Output;
[[vk::binding(1, 0)]] RWStructuredBuffer<float> Reserved0;
[[vk::binding(2, 0)]] RWStructuredBuffer<float> Reserved1;

float RoundtripBF16(float value)
{
    float __sdslv_inline_hlsl_0;
    {
        // BEGIN INLINE HLSL internal/prometheus/shaders/sdslv/production/gemma4e2b/bf16_roundtrip.sdslv:26
        
                uint bits = asuint(value);
                uint exponent = bits & 0x7f800000u;
                uint mantissa = bits & 0x007fffffu;
                if (exponent == 0x7f800000u) {
                    if (mantissa == 0u) __sdslv_inline_hlsl_0 = value;
                    uint bf16 = (bits >> 16u) | 0x0040u;
                    return asfloat(bf16 << 16u);
                }
                uint lsb = (bits >> 16u) & 1u;
                uint bf16 = (bits + 0x00007fffu + lsb) >> 16u;
                return asfloat(bf16 << 16u);
            
        // END INLINE HLSL
    }
    float rounded = __sdslv_inline_hlsl_0;
    return rounded;
}

[[vk::push_constant]] ConstantBuffer<Bf16RoundtripParams> params;

[numthreads(256, 1, 1)]
void Gemma4E2BM1Bf16Roundtrip_CS(uint3 DispatchThreadID : SV_DispatchThreadID)
{
    uint element = DispatchThreadID.x;
    if ((element < params.ElementCount))
    {
        Output[element] = RoundtripBF16(Input[element]);
    }
    return;
}

