// Generated by canonical GoOct SDSL-V via VD-MIR. Do not edit by hand.
// namespace Prometheus.Production.Gemma4E2BM1

struct RopeParams
{
    uint TokenCount;
    uint HeadCount;
    uint HeadDim;
    uint Reserved0;
    uint Reserved1;
    uint Reserved2;
    uint Reserved3;
    uint Reserved4;
};

[[vk::binding(0, 0)]] StructuredBuffer<float> Input;
[[vk::binding(3, 0)]] RWStructuredBuffer<float> Output;
[[vk::binding(1, 0)]] RWStructuredBuffer<float> Reserved0;
[[vk::binding(2, 0)]] RWStructuredBuffer<float> Reserved1;

float RoundtripBF16(float value)
{
    float __sdslv_inline_hlsl_0;
    {
        // BEGIN INLINE HLSL internal\prometheus\shaders\sdslv\production\gemma4e2b\rope_half_split.sdslv:25
        
                uint bits = asuint(value); uint exponent = bits & 0x7f800000u;
                uint mantissa = bits & 0x007fffffu;
                if (exponent == 0x7f800000u) {
                    if (mantissa == 0u) __sdslv_inline_hlsl_0 = value;
                    return asfloat((((bits >> 16u) | 0x0040u) << 16u));
                }
                return asfloat(((bits + 0x00007fffu + ((bits >> 16u) & 1u)) >> 16u) << 16u);
            
        // END INLINE HLSL
    }
    return __sdslv_inline_hlsl_0;
}

[[vk::push_constant]] ConstantBuffer<RopeParams> params;

[numthreads(256, 1, 1)]
void Gemma4E2BM1RopeHalfSplit_CS(uint3 DispatchThreadID : SV_DispatchThreadID)
{
    uint element = DispatchThreadID.x;
    uint total = ((params.TokenCount * params.HeadCount) * params.HeadDim);
    if ((element < total))
    {
        uint component = (element % params.HeadDim);
        uint half = (params.HeadDim / 2u);
        uint frequency_index = (component % half);
        uint token = (element / (params.HeadCount * params.HeadDim));
        uint pair_element = (element - half);
        if ((component < half))
        {
            pair_element = (element + half);
        }
        float source = Input[element];
        float pair_source = Input[pair_element];
        float __sdslv_inline_hlsl_1;
        {
            // BEGIN INLINE HLSL internal\prometheus\shaders\sdslv\production\gemma4e2b\rope_half_split.sdslv:50
            
                            float angle = (float)token * pow(10000.0, -((float)(frequency_index * 2u) / 256.0));
                            float cosine = asfloat((asuint(cos(angle)) + 0x7fffu + ((asuint(cos(angle)) >> 16u) & 1u)) & 0xffff0000u);
                            float sine = asfloat((asuint(sin(angle)) + 0x7fffu + ((asuint(sin(angle)) >> 16u) & 1u)) & 0xffff0000u);
                            __sdslv_inline_hlsl_1 = component < half ? source * cosine - pair_source * sine : source * cosine + pair_source * sine;
                        
            // END INLINE HLSL
        }
        float transformed = __sdslv_inline_hlsl_1;
        Output[element] = RoundtripBF16(transformed);
    }
    return;
}

