// Generated by canonical GoOct SDSL-V via VD-MIR. Do not edit by hand.
// namespace Prometheus.Production.Gemma4E2BM1

struct RopeParams
{
    uint TokenCount;
    uint HeadCount;
    uint HeadDim;
    uint Reserved0;
    uint Reserved1;
    uint Reserved2;
    uint Reserved3;
    uint Reserved4;
};

[[vk::binding(1, 0)]] StructuredBuffer<float> Cosine;
[[vk::binding(0, 0)]] StructuredBuffer<float> Input;
[[vk::binding(3, 0)]] RWStructuredBuffer<float> Output;
[[vk::binding(2, 0)]] StructuredBuffer<float> Sine;

float RoundtripBF16(float value)
{
    float __sdslv_inline_hlsl_0;
    {
        // BEGIN INLINE HLSL internal/prometheus/shaders/sdslv/production/gemma4e2b/rope_half_split.sdslv:27
        
                uint bits = asuint(value); uint exponent = bits & 0x7f800000u;
                uint mantissa = bits & 0x007fffffu;
                if (exponent == 0x7f800000u) {
                    if (mantissa == 0u) __sdslv_inline_hlsl_0 = value;
                    return asfloat((((bits >> 16u) | 0x0040u) << 16u));
                }
                return asfloat(((bits + 0x00007fffu + ((bits >> 16u) & 1u)) >> 16u) << 16u);
            
        // END INLINE HLSL
    }
    return __sdslv_inline_hlsl_0;
}

[[vk::push_constant]] ConstantBuffer<RopeParams> params;

[numthreads(256, 1, 1)]
void Gemma4E2BM1RopeHalfSplit_CS(uint3 DispatchThreadID : SV_DispatchThreadID)
{
    uint element = DispatchThreadID.x;
    uint total = ((params.TokenCount * params.HeadCount) * params.HeadDim);
    if ((element < total))
    {
        uint component = (element % params.HeadDim);
        uint half = (params.HeadDim / 2u);
        uint frequency_index = (component % half);
        uint token = (element / (params.HeadCount * params.HeadDim));
        uint pair_element = (element - half);
        if ((component < half))
        {
            pair_element = (element + half);
        }
        float source = Input[element];
        float pair_source = Input[pair_element];
        uint table_element = ((token * params.HeadDim) + frequency_index);
        float cosine = Cosine[table_element];
        float sine = Sine[table_element];
        float first_product = RoundtripBF16((source * cosine));
        float second_product = RoundtripBF16((pair_source * sine));
        float transformed = RoundtripBF16((first_product - second_product));
        if ((component >= half))
        {
            transformed = RoundtripBF16((first_product + second_product));
        }
        Output[element] = transformed;
    }
    return;
}

