package toolchain

import (
	"encoding/binary"
	"fmt"
	"path/filepath"
	"strings"
)

type HeaderOptions struct {
	Symbol       string
	SourcePath   string
	Compute      *ComputeHeaderMetadata
	CommandLine  string
	HeaderPath   string
	IncludeGuard string
}

type ComputeHeaderMetadata struct {
	EntryPoint   string
	NumThreadsX  uint32
	NumThreadsY  uint32
	NumThreadsZ  uint32
	Metadata     []MetadataField
	ConfigValues []MetadataField
}

type MetadataField struct {
	Name  string
	Value uint32
}

func HeaderFromSPIRVBytes(bytes []byte, opts HeaderOptions) (string, error) {
	if len(bytes)%4 != 0 {
		return "", fmt.Errorf("SPIR-V byte length %d is not a multiple of 4", len(bytes))
	}
	words := make([]uint32, 0, len(bytes)/4)
	for i := 0; i < len(bytes); i += 4 {
		words = append(words, binary.LittleEndian.Uint32(bytes[i:i+4]))
	}
	return HeaderFromWords(words, opts)
}

func HeaderFromWords(words []uint32, opts HeaderOptions) (string, error) {
	if strings.TrimSpace(opts.Symbol) == "" {
		return "", fmt.Errorf("header symbol must be non-empty")
	}
	guard := opts.IncludeGuard
	if strings.TrimSpace(guard) == "" {
		guard = headerIncludeGuard(opts)
	}
	var b strings.Builder
	fmt.Fprintf(&b, "#ifndef %s\n", guard)
	fmt.Fprintf(&b, "#define %s\n\n", guard)
	b.WriteString("#include <stdint.h>\n\n")
	if opts.SourcePath != "" {
		fmt.Fprintf(&b, "// Source: %s\n", filepath.ToSlash(opts.SourcePath))
	}
	if opts.Compute != nil && opts.Compute.EntryPoint != "" {
		fmt.Fprintf(&b, "// Entry point: %s\n", opts.Compute.EntryPoint)
	}
	if opts.CommandLine != "" {
		fmt.Fprintf(&b, "// Generated by: %s\n", opts.CommandLine)
	}
	b.WriteString("// Deterministic SPIR-V words emitted for Prometheus-native inclusion.\n\n")
	fmt.Fprintf(&b, "static const uint32_t %s[] = {\n", opts.Symbol)
	for i, word := range words {
		if i%4 == 0 {
			b.WriteString("    ")
		}
		fmt.Fprintf(&b, "0x%08xu", word)
		if i+1 < len(words) {
			b.WriteString(", ")
		}
		if i%4 == 3 || i+1 == len(words) {
			b.WriteString("\n")
		}
	}
	b.WriteString("};\n\n")
	fmt.Fprintf(&b, "static const uint32_t %s_word_count = %du;\n", opts.Symbol, len(words))
	fmt.Fprintf(&b, "static const uint32_t %s_byte_length = %du;\n", opts.Symbol, len(words)*4)
	if opts.Compute != nil {
		fmt.Fprintf(&b, "static const uint32_t %s_numthreads_x = %du;\n", opts.Symbol, opts.Compute.NumThreadsX)
		fmt.Fprintf(&b, "static const uint32_t %s_numthreads_y = %du;\n", opts.Symbol, opts.Compute.NumThreadsY)
		fmt.Fprintf(&b, "static const uint32_t %s_numthreads_z = %du;\n", opts.Symbol, opts.Compute.NumThreadsZ)
		for _, field := range opts.Compute.Metadata {
			fmt.Fprintf(&b, "static const uint32_t %s_%s = %du;\n", opts.Symbol, metadataIdentifier(field.Name), field.Value)
		}
		for _, field := range opts.Compute.ConfigValues {
			fmt.Fprintf(&b, "static const uint32_t %s_config_%s = %du;\n", opts.Symbol, metadataIdentifier(field.Name), field.Value)
		}
	}
	b.WriteString("\n")
	fmt.Fprintf(&b, "#endif  // %s\n", guard)
	return b.String(), nil
}

func headerIncludeGuard(opts HeaderOptions) string {
	base := opts.Symbol
	if base == "" && opts.HeaderPath != "" {
		base = filepath.Base(opts.HeaderPath)
	}
	if base == "" {
		base = "sdslv_generated_spirv"
	}
	return sanitizeIdentifier("OCT_INTERNAL_SDSLV_" + base + "_H")
}

func sanitizeIdentifier(text string) string {
	var b strings.Builder
	for _, r := range text {
		if r >= 'a' && r <= 'z' {
			b.WriteRune(r - ('a' - 'A'))
			continue
		}
		if (r >= 'A' && r <= 'Z') || (r >= '0' && r <= '9') {
			b.WriteRune(r)
			continue
		}
		b.WriteByte('_')
	}
	return b.String()
}

func metadataIdentifier(text string) string {
	var b strings.Builder
	lastUnderscore := false
	for _, r := range text {
		switch {
		case r >= 'A' && r <= 'Z':
			b.WriteRune(r + ('a' - 'A'))
			lastUnderscore = false
		case r >= 'a' && r <= 'z':
			b.WriteRune(r)
			lastUnderscore = false
		case r >= '0' && r <= '9':
			b.WriteRune(r)
			lastUnderscore = false
		default:
			if !lastUnderscore {
				b.WriteByte('_')
				lastUnderscore = true
			}
		}
	}
	return strings.Trim(b.String(), "_")
}
