package toolchain

import (
	"encoding/binary"
	"fmt"
	"path/filepath"
	"strings"
)

type HeaderOptions struct {
	Symbol       string
	SourcePath   string
	EntryPoint   string
	CommandLine  string
	HeaderPath   string
	IncludeGuard string
}

func HeaderFromSPIRVBytes(bytes []byte, opts HeaderOptions) (string, error) {
	if len(bytes)%4 != 0 {
		return "", fmt.Errorf("SPIR-V byte length %d is not a multiple of 4", len(bytes))
	}
	words := make([]uint32, 0, len(bytes)/4)
	for i := 0; i < len(bytes); i += 4 {
		words = append(words, binary.LittleEndian.Uint32(bytes[i:i+4]))
	}
	return HeaderFromWords(words, opts)
}

func HeaderFromWords(words []uint32, opts HeaderOptions) (string, error) {
	if strings.TrimSpace(opts.Symbol) == "" {
		return "", fmt.Errorf("header symbol must be non-empty")
	}
	guard := opts.IncludeGuard
	if strings.TrimSpace(guard) == "" {
		guard = headerIncludeGuard(opts)
	}
	var b strings.Builder
	fmt.Fprintf(&b, "#ifndef %s\n", guard)
	fmt.Fprintf(&b, "#define %s\n\n", guard)
	b.WriteString("#include <stdint.h>\n\n")
	if opts.SourcePath != "" {
		fmt.Fprintf(&b, "// Source: %s\n", filepath.ToSlash(opts.SourcePath))
	}
	if opts.EntryPoint != "" {
		fmt.Fprintf(&b, "// Entry point: %s\n", opts.EntryPoint)
	}
	if opts.CommandLine != "" {
		fmt.Fprintf(&b, "// Generated by: %s\n", opts.CommandLine)
	}
	b.WriteString("// Deterministic SPIR-V words emitted for Prometheus-native inclusion.\n\n")
	fmt.Fprintf(&b, "static const uint32_t %s[] = {\n", opts.Symbol)
	for i, word := range words {
		if i%4 == 0 {
			b.WriteString("    ")
		}
		fmt.Fprintf(&b, "0x%08xu", word)
		if i+1 < len(words) {
			b.WriteString(", ")
		}
		if i%4 == 3 || i+1 == len(words) {
			b.WriteString("\n")
		}
	}
	b.WriteString("};\n\n")
	fmt.Fprintf(&b, "static const uint32_t %s_word_count = %du;\n", opts.Symbol, len(words))
	fmt.Fprintf(&b, "static const uint32_t %s_byte_length = %du;\n\n", opts.Symbol, len(words)*4)
	fmt.Fprintf(&b, "#endif  // %s\n", guard)
	return b.String(), nil
}

func headerIncludeGuard(opts HeaderOptions) string {
	base := opts.Symbol
	if base == "" && opts.HeaderPath != "" {
		base = filepath.Base(opts.HeaderPath)
	}
	if base == "" {
		base = "sdslv_generated_spirv"
	}
	return sanitizeIdentifier("OCT_INTERNAL_SDSLV_" + base + "_H")
}

func sanitizeIdentifier(text string) string {
	var b strings.Builder
	for _, r := range text {
		if r >= 'a' && r <= 'z' {
			b.WriteRune(r - ('a' - 'A'))
			continue
		}
		if (r >= 'A' && r <= 'Z') || (r >= '0' && r <= '9') {
			b.WriteRune(r)
			continue
		}
		b.WriteByte('_')
	}
	return b.String()
}
