#ifndef OCT_INTERNAL_SDSLV_K_PROM_INLINE_HLSL_BITCAST_PROOF_SPIRV_H
#define OCT_INTERNAL_SDSLV_K_PROM_INLINE_HLSL_BITCAST_PROOF_SPIRV_H

#include <stdint.h>

// Source: internal/prometheus/shaders/sdslv/production/sgemm/inline_hlsl_bitcast_proof.sdslv
// Entry point: InlineHlslBitCastProof_CS
// Generated by: oct sdslv generate-header internal/prometheus/shaders/sdslv/production/sgemm/inline_hlsl_bitcast_proof.sdslv -o internal/prometheus/native/reactor_vulkan_inline_hlsl_bitcast_proof_spirv.h --symbol k_prom_inline_hlsl_bitcast_proof_spirv
// Deterministic SPIR-V words emitted for Prometheus-native inclusion.

static const uint32_t k_prom_inline_hlsl_bitcast_proof_spirv[] = {
    0x07230203u, 0x00010000u, 0x000e0000u, 0x00000008u,
    0x00000000u, 0x00020011u, 0x00000001u, 0x0003000eu,
    0x00000000u, 0x00000001u, 0x000a000fu, 0x00000005u,
    0x00000001u, 0x696c6e49u, 0x6c48656eu, 0x69426c73u,
    0x73614374u, 0x6f725074u, 0x435f666fu, 0x00000053u,
    0x00060010u, 0x00000001u, 0x00000011u, 0x00000001u,
    0x00000001u, 0x00000001u, 0x00030003u, 0x00000005u,
    0x00000258u, 0x00090005u, 0x00000001u, 0x696c6e49u,
    0x6c48656eu, 0x69426c73u, 0x73614374u, 0x6f725074u,
    0x435f666fu, 0x00000053u, 0x00020013u, 0x00000002u,
    0x00030021u, 0x00000003u, 0x00000002u, 0x00040015u,
    0x00000004u, 0x00000020u, 0x00000000u, 0x0004002bu,
    0x00000004u, 0x00000005u, 0x00000002u, 0x0004002bu,
    0x00000004u, 0x00000006u, 0x00000108u, 0x00050036u,
    0x00000002u, 0x00000001u, 0x00000000u, 0x00000003u,
    0x000200f8u, 0x00000007u, 0x000400e0u, 0x00000005u,
    0x00000005u, 0x00000006u, 0x000100fdu, 0x00010038u
};

static const uint32_t k_prom_inline_hlsl_bitcast_proof_spirv_word_count = 68u;
static const uint32_t k_prom_inline_hlsl_bitcast_proof_spirv_byte_length = 272u;
static const uint32_t k_prom_inline_hlsl_bitcast_proof_spirv_numthreads_x = 1u;
static const uint32_t k_prom_inline_hlsl_bitcast_proof_spirv_numthreads_y = 1u;
static const uint32_t k_prom_inline_hlsl_bitcast_proof_spirv_numthreads_z = 1u;

#endif  // OCT_INTERNAL_SDSLV_K_PROM_INLINE_HLSL_BITCAST_PROOF_SPIRV_H
