#ifndef OCT_INTERNAL_PROMETHEUS_NATIVE_REACTOR_DOMINATUS_BLACKBOARD_H
#define OCT_INTERNAL_PROMETHEUS_NATIVE_REACTOR_DOMINATUS_BLACKBOARD_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dominatus subsystem blackboard core:
 * this stores staged/visible control facts consumed across the Dominatus
 * subsystem (Judgment Engine, slot HFSM/stack state machine, lease-control,
 * and future measurement-filter/predictor seams). */
enum {
  PROM_DOM_MAX_SLOTS = 8u,
  PROM_DOM_MAX_EVENTS = 32u,
  PROM_DOM_MAX_TRACE = 64u,
  PROM_DOM_KEY_WORDS = 4u,
  PROM_DOM_STORAGE_CAPACITY = 256u * PROM_DOM_MAX_SLOTS,
};

typedef enum prom_dom_domain {
  PROM_DOM_DOMAIN_INVALID = 0,
  PROM_DOM_DOMAIN_SGEMM = 1,
  PROM_DOM_DOMAIN_SLOT = 2,
  PROM_DOM_DOMAIN_QUEUE = 3,
  PROM_DOM_DOMAIN_MEMORY = 4,
  PROM_DOM_DOMAIN_DIAGNOSTICS = 5,
  PROM_DOM_DOMAIN_FFT = 6,
  PROM_DOM_DOMAIN_ASYNC = 7,
} prom_dom_domain;

typedef enum prom_dom_key {
  PROM_DOM_KEY_INVALID = 0,

  PROM_DOM_KEY_SGEMM_SHAPE = 0x0101,
  PROM_DOM_KEY_SGEMM_LAYOUT = 0x0102,
  PROM_DOM_KEY_SGEMM_PRECISION = 0x0103,
  PROM_DOM_KEY_SGEMM_PATH_MODE = 0x0104,
  PROM_DOM_KEY_SGEMM_COMPUTE_MODE = 0x0105,
  PROM_DOM_KEY_SGEMM_BUFFERING_MODE = 0x0106,
  PROM_DOM_KEY_SGEMM_FALLBACK_REASON = 0x0107,
  PROM_DOM_KEY_SGEMM_M35_FIXED_FEASIBLE = 0x0108,
  PROM_DOM_KEY_SGEMM_M35_PULL_LAG_FEASIBLE = 0x0109,
  PROM_DOM_KEY_SGEMM_M35_SERIAL_FEASIBLE = 0x010A,
  PROM_DOM_KEY_SGEMM_M35_FIXED_SCORE = 0x010B,
  PROM_DOM_KEY_SGEMM_M35_PULL_LAG_SCORE = 0x010C,
  PROM_DOM_KEY_SGEMM_M35_SERIAL_SCORE = 0x010D,
  PROM_DOM_KEY_SGEMM_M35_REASON_CODE = 0x010E,
  PROM_DOM_KEY_SGEMM_M35_FINAL_REASON_CODE = 0x010F,
  PROM_DOM_KEY_SGEMM_M35_FIXED_REJECTION_REASON = 0x0110,
  PROM_DOM_KEY_SGEMM_M35_PULL_LAG_REJECTION_REASON = 0x0111,
  PROM_DOM_KEY_SGEMM_M35_SERIAL_REJECTION_REASON = 0x0112,
  PROM_DOM_KEY_SGEMM_M35_TRANSFER_VARIANCE_CLASS = 0x0113,
  PROM_DOM_KEY_SGEMM_M35_COMPUTE_PREDICTABILITY_CLASS = 0x0114,
  PROM_DOM_KEY_SGEMM_M35_STARVATION_RISK_HIGH = 0x0115,
  PROM_DOM_KEY_SGEMM_M35_PULL_LAG_WIP_WASTE_EXCEEDED = 0x0116,
  PROM_DOM_KEY_SGEMM_M35_FALLBACK_AVAILABLE = 0x0117,
  PROM_DOM_KEY_SGEMM_M35_FIXED_REJECTED = 0x0118,
  PROM_DOM_KEY_SGEMM_M35_PULL_LAG_REJECTED = 0x0119,
  PROM_DOM_KEY_SGEMM_M35_SERIAL_REJECTED = 0x011A,
  PROM_DOM_KEY_SGEMM_M35_SUCCESS = 0x011B,
  PROM_DOM_KEY_SGEMM_M35_NO_FEASIBLE_DETAIL = 0x011C,
  PROM_DOM_KEY_SGEMM_PACKED4_AVAILABLE = 0x011D,
  PROM_DOM_KEY_SGEMM_PACKED4_SMALL_SHAPE = 0x011E,
  PROM_DOM_KEY_SGEMM_PACKED4_PADDING_WASTE_PERMILLE = 0x011F,
  PROM_DOM_KEY_SGEMM_PACKED4_MODE_BUDGET_PERMILLE = 0x0120,
  PROM_DOM_KEY_SGEMM_PACKED4_ROW_MAJOR_VALID = 0x0121,
  PROM_DOM_KEY_SGEMM_PACKED4_TAIL_VALID = 0x0122,
  PROM_DOM_KEY_SGEMM_FP16_STRICT_FP32 = 0x0123,
  PROM_DOM_KEY_SGEMM_FP16_TOLERANCE_KNOWN = 0x0124,
  PROM_DOM_KEY_SGEMM_FP16_TOLERANCE_PASS = 0x0125,
  PROM_DOM_KEY_SGEMM_FP16_HAS_SPECIAL_VALUES = 0x0126,
  PROM_DOM_KEY_SGEMM_FP16_CAPABILITY_STORAGE = 0x0127,
  PROM_DOM_KEY_SGEMM_FP16_FALLBACK_AVAILABLE = 0x0128,
  PROM_DOM_KEY_SGEMM_FP16_UTILITY_SCORE = 0x0129,
  PROM_DOM_KEY_SGEMM_PACKED4_SELECTED = 0x012A,
  PROM_DOM_KEY_SGEMM_PACKED4_REJECT_REASON = 0x012B,
  PROM_DOM_KEY_SGEMM_FP16_SELECTED = 0x012C,
  PROM_DOM_KEY_SGEMM_FP16_REJECT_REASON = 0x012D,
  PROM_DOM_KEY_SGEMM_FACT_SHAPE_M = 0x012E,
  PROM_DOM_KEY_SGEMM_FACT_SHAPE_N = 0x012F,
  PROM_DOM_KEY_SGEMM_FACT_SHAPE_K = 0x0130,
  PROM_DOM_KEY_SGEMM_FACT_WORK_UNITS = 0x0131,
  PROM_DOM_KEY_SGEMM_FACT_CAN_STAGE = 0x0132,
  PROM_DOM_KEY_SGEMM_FACT_CAN_DIRECT = 0x0133,
  PROM_DOM_KEY_SGEMM_FACT_ALLOW_FALLBACK = 0x0134,
  PROM_DOM_KEY_SGEMM_FACT_READBACK_REQUIRED = 0x0135,
  PROM_DOM_KEY_SGEMM_FACT_FORCE_DIRECT = 0x0136,
  PROM_DOM_KEY_SGEMM_FACT_FORCE_STAGED = 0x0137,
  PROM_DOM_KEY_SGEMM_FACT_FORCE_TILED = 0x0138,
  PROM_DOM_KEY_SGEMM_FACT_TILED_SHAPE = 0x0139,
  PROM_DOM_KEY_SGEMM_FACT_SOFTWARE_VULKAN = 0x013A,
  PROM_DOM_KEY_SGEMM_FACT_POLICY_MODE = 0x013B,
  PROM_DOM_KEY_SGEMM_JUDGMENT_SUCCESS = 0x013C,
  PROM_DOM_KEY_SGEMM_JUDGMENT_ERROR_DETAIL = 0x013D,
  PROM_DOM_KEY_SGEMM_JUDGMENT_REQUESTED_PATH = 0x013E,
  PROM_DOM_KEY_SGEMM_JUDGMENT_SELECTED_PATH = 0x013F,
  PROM_DOM_KEY_SGEMM_JUDGMENT_COMPUTE_MODE = 0x0140,
  PROM_DOM_KEY_SGEMM_JUDGMENT_FINAL_DETAIL = 0x0141,
  PROM_DOM_KEY_SGEMM_JUDGMENT_USED_FALLBACK_TO_DIRECT = 0x0142,
  PROM_DOM_KEY_SGEMM_JUDGMENT_WINNING_CANDIDATE_INDEX = 0x0143,
  PROM_DOM_KEY_SGEMM_JUDGMENT_WINNING_SCORE = 0x0144,
  PROM_DOM_KEY_SGEMM_LEASE_WORKER_ID = 0x0145,
  PROM_DOM_KEY_SGEMM_LEASE_SLOT_ID = 0x0146,
  PROM_DOM_KEY_SGEMM_LEASE_ENTRY_ID = 0x0147,
  PROM_DOM_KEY_SGEMM_LEASE_SHAPE_CLASS = 0x0148,
  PROM_DOM_KEY_SGEMM_LEASE_DEVICE_BAND = 0x0149,
  PROM_DOM_KEY_SGEMM_LEASE_SELECTED_RECIPE_VARIANT = 0x014A,
  PROM_DOM_KEY_SGEMM_LEASE_REQUESTED_RESOURCE_CLASS = 0x014B,
  PROM_DOM_KEY_SGEMM_LEASE_REGISTER_PRESSURE_CLASS = 0x014C,
  PROM_DOM_KEY_SGEMM_LEASE_SHARED_MEMORY_PRESSURE_CLASS = 0x014D,
  PROM_DOM_KEY_SGEMM_LEASE_MEMORY_BANDWIDTH_PRESSURE_CLASS = 0x014E,
  PROM_DOM_KEY_SGEMM_LEASE_COMPUTE_PRESSURE_CLASS = 0x014F,
  PROM_DOM_KEY_SGEMM_LEASE_PIPELINE_LATENCY_PRESSURE_CLASS = 0x0150,
  PROM_DOM_KEY_SGEMM_LEASE_CURRENT_OUTSTANDING_DEPTH = 0x0151,
  PROM_DOM_KEY_SGEMM_LEASE_MAX_OUTSTANDING_DEPTH = 0x0152,
  PROM_DOM_KEY_SGEMM_LEASE_LOOKAHEAD_REQUESTED = 0x0153,
  PROM_DOM_KEY_SGEMM_LEASE_LOOKAHEAD_LIMIT = 0x0154,
  PROM_DOM_KEY_SGEMM_LEASE_TRANSFER_OVERLAP_AVAILABLE = 0x0155,
  PROM_DOM_KEY_SGEMM_LEASE_TRUE_MULTI_QUEUE_SELECTED = 0x0156,
  PROM_DOM_KEY_SGEMM_LEASE_UNSAFE_TO_REUSE = 0x0157,
  PROM_DOM_KEY_SGEMM_LEASE_YIELD_REQUESTED = 0x0158,
  PROM_DOM_KEY_SGEMM_LEASE_DECISION_SUCCESS = 0x0159,
  PROM_DOM_KEY_SGEMM_LEASE_DECISION_STATE = 0x015A,
  PROM_DOM_KEY_SGEMM_LEASE_DECISION_GRANT = 0x015B,
  PROM_DOM_KEY_SGEMM_LEASE_DECISION_REASON = 0x015C,
  PROM_DOM_KEY_SGEMM_LEASE_DECISION_ALLOWED_OUTSTANDING_DEPTH = 0x015D,
  PROM_DOM_KEY_SGEMM_LEASE_DECISION_LOOKAHEAD_ALLOWED = 0x015E,
  PROM_DOM_KEY_SGEMM_LEASE_DECISION_BACKPRESSURE_APPLIED = 0x015F,
  PROM_DOM_KEY_SGEMM_LEASE_DECISION_YIELD_REQUIRED = 0x0160,
  PROM_DOM_KEY_SGEMM_LEASE_DIAG_GRANTED_COUNT = 0x0161,
  PROM_DOM_KEY_SGEMM_LEASE_DIAG_DENIED_COUNT = 0x0162,
  PROM_DOM_KEY_SGEMM_LEASE_DIAG_BACKPRESSURE_COUNT = 0x0163,
  PROM_DOM_KEY_SGEMM_LEASE_DIAG_YIELD_COUNT = 0x0164,
  PROM_DOM_KEY_SGEMM_LEASE_DIAG_FAILED_COUNT = 0x0165,
  PROM_DOM_KEY_SGEMM_LEASE_DIAG_LOOKAHEAD_BLOCKED_REASON = 0x0166,
  PROM_DOM_KEY_DIAGNOSTICS_PACKED4_SELECTED_LAYOUT_FORMAT = 0x0504,
  PROM_DOM_KEY_DIAGNOSTICS_PACKED4_TAIL_COUNT_LAST = 0x0505,
  PROM_DOM_KEY_DIAGNOSTICS_PACKED4_TAIL_COUNT_TOTAL = 0x0506,
  PROM_DOM_KEY_DIAGNOSTICS_PACKED4_PADDED_LANE_COUNT_LAST = 0x0507,
  PROM_DOM_KEY_DIAGNOSTICS_PACKED4_PADDED_LANE_COUNT_TOTAL = 0x0508,
  PROM_DOM_KEY_DIAGNOSTICS_PACKED4_PADDING_WASTE_PERMILLE_LAST = 0x0509,
  PROM_DOM_KEY_DIAGNOSTICS_PACKED4_MODE_BUDGET_DENIALS = 0x050A,
  PROM_DOM_KEY_DIAGNOSTICS_PACKED4_ROW_MAJOR_CHECK_FAILURES = 0x050B,
  PROM_DOM_KEY_DIAGNOSTICS_PACKED4_SELECTION_COUNT = 0x050C,
  PROM_DOM_KEY_DIAGNOSTICS_PACKED4_FALLBACK_REASON_PADDING_WASTE = 0x050D,
  PROM_DOM_KEY_DIAGNOSTICS_PACKED4_FALLBACK_REASON_SMALL_SHAPE = 0x050E,
  PROM_DOM_KEY_DIAGNOSTICS_PACKED4_FALLBACK_REASON_CAPABILITY_MISSING = 0x050F,
  PROM_DOM_KEY_DIAGNOSTICS_PACKED4_FALLBACK_REASON_FALLBACK_REQUIRED = 0x0510,
  PROM_DOM_KEY_DIAGNOSTICS_PACKED4_FALLBACK_REASON_MODE_BUDGET_DENIED = 0x0511,
  PROM_DOM_KEY_DIAGNOSTICS_FP16_MAX_ABSOLUTE_ERROR_BITS = 0x0512,
  PROM_DOM_KEY_DIAGNOSTICS_FP16_MAX_RELATIVE_ERROR_BITS = 0x0513,
  PROM_DOM_KEY_DIAGNOSTICS_FP16_AGGREGATE_ERROR_BITS = 0x0514,
  PROM_DOM_KEY_DIAGNOSTICS_FP16_WORST_CASE_ELEMENT_INDEX = 0x0515,
  PROM_DOM_KEY_DIAGNOSTICS_FP16_K_ERROR_GROWTH_BITS = 0x0516,
  PROM_DOM_KEY_DIAGNOSTICS_FP16_CANCELLATION_RISK_BITS = 0x0517,
  PROM_DOM_KEY_DIAGNOSTICS_FP16_TOLERANCE_KNOWN = 0x0518,
  PROM_DOM_KEY_DIAGNOSTICS_FP16_TOLERANCE_PASS = 0x0519,
  PROM_DOM_KEY_DIAGNOSTICS_FP16_FALLBACK_REASON_DETAIL = 0x051A,
  PROM_DOM_KEY_DIAGNOSTICS_FP16_SELECTED_CANDIDATE = 0x051B,

  PROM_DOM_KEY_SLOT_STATE = 0x0201,
  PROM_DOM_KEY_SLOT_GENERATION = 0x0202,
  PROM_DOM_KEY_SLOT_VALID = 0x0203,
  PROM_DOM_KEY_SLOT_CURRENT_ID = 0x0204,
  PROM_DOM_KEY_SLOT_NEXT_ID = 0x0205,
  PROM_DOM_KEY_SLOT_FAILURE_REASON = 0x0206,
  PROM_DOM_KEY_SLOT_SWAP_COUNT = 0x0207,
  PROM_DOM_KEY_SLOT_MAX_WIP_DEPTH = 0x0208,
  PROM_DOM_KEY_SLOT_OVERWRITE_REJECTION_COUNT = 0x0209,
  PROM_DOM_KEY_SLOT_STALE_BUFFER_REJECTION_COUNT = 0x020A,
  PROM_DOM_KEY_SLOT_SHAPE_INVALIDATION_COUNT = 0x020B,
  PROM_DOM_KEY_SLOT_LAYOUT_INVALIDATION_COUNT = 0x020C,
  PROM_DOM_KEY_SLOT_CAPACITY_INVALIDATION_COUNT = 0x020D,
  PROM_DOM_KEY_SLOT_INFLIGHT_REJECTION_COUNT = 0x020E,
  PROM_DOM_KEY_SLOT_CLEANUP_SUCCESS_COUNT = 0x020F,
  PROM_DOM_KEY_SLOT_FAILURE_SLOT_ID = 0x0210,
  PROM_DOM_KEY_SLOT_FAILURE_REASON_GLOBAL = 0x0211,

  PROM_DOM_KEY_QUEUE_COMPUTE_FAMILY = 0x0301,
  PROM_DOM_KEY_QUEUE_TRANSFER_FAMILY = 0x0302,
  PROM_DOM_KEY_QUEUE_DEDICATED_AVAILABLE = 0x0303,
  PROM_DOM_KEY_QUEUE_TRANSFER_POLICY = 0x0304,
  PROM_DOM_KEY_QUEUE_HANDOFF_COUNT = 0x0305,
  PROM_DOM_KEY_QUEUE_FAMILIES_DIFFER = 0x0306,
  PROM_DOM_KEY_QUEUE_TRANSFER_SUPPORTED = 0x0307,
  PROM_DOM_KEY_QUEUE_TRANSFER_DISABLED_BY_CONFIG = 0x0308,
  PROM_DOM_KEY_QUEUE_TRANSFER_WORKLOAD_LARGE_ENOUGH = 0x0309,
  PROM_DOM_KEY_QUEUE_TRANSFER_SYNC_OWNERSHIP_SUPPORTED = 0x030A,
  PROM_DOM_KEY_QUEUE_TRANSFER_FALLBACK_AVAILABLE = 0x030B,
  PROM_DOM_KEY_QUEUE_TRANSFER_UPLOAD_ONLY_ELIGIBLE = 0x030C,
  PROM_DOM_KEY_QUEUE_TRANSFER_UPLOAD_READBACK_SUPPORTED = 0x030D,
  PROM_DOM_KEY_QUEUE_TRANSFER_POLICY_SELECTED = 0x030E,
  PROM_DOM_KEY_QUEUE_TRANSFER_FALLBACK_REASON = 0x030F,
  PROM_DOM_KEY_QUEUE_TRANSFER_QUEUE_USED = 0x0310,
  PROM_DOM_KEY_QUEUE_TRANSFER_COMPUTE_WAIT_COUNT = 0x0311,
  PROM_DOM_KEY_QUEUE_TRANSFER_FAILURE_SLOT_ID = 0x0312,
  PROM_DOM_KEY_QUEUE_TRANSFER_FAILURE_REASON = 0x0313,
  PROM_DOM_KEY_QUEUE_TRANSFER_FAILURE_COUNT = 0x0314,
  PROM_DOM_KEY_QUEUE_ASYNC_TRANSFER_COMPLETE = 0x0315,
  PROM_DOM_KEY_QUEUE_ASYNC_TRANSFER_COMPLETION_GENERATION = 0x0316,

  PROM_DOM_KEY_MEMORY_REQUIRED_CAPACITY = 0x0401,
  PROM_DOM_KEY_MEMORY_BUDGET = 0x0402,
  PROM_DOM_KEY_MEMORY_HEADROOM = 0x0403,
  PROM_DOM_KEY_MEMORY_INVALIDATION_FLAGS = 0x0404,
  PROM_DOM_KEY_MEMORY_M35_FIXED_HEADROOM = 0x0405,
  PROM_DOM_KEY_MEMORY_M35_PULL_LAG_HEADROOM = 0x0406,
  PROM_DOM_KEY_MEMORY_M35_SERIAL_HEADROOM = 0x0407,
  PROM_DOM_KEY_MEMORY_M35_REQUIRED_FIXED = 0x0408,
  PROM_DOM_KEY_MEMORY_M35_REQUIRED_PULL_LAG = 0x0409,
  PROM_DOM_KEY_MEMORY_M35_REQUIRED_SERIAL = 0x040A,

  PROM_DOM_KEY_DIAGNOSTICS_REASON_CODE = 0x0501,
  PROM_DOM_KEY_DIAGNOSTICS_COUNTER = 0x0502,
  PROM_DOM_KEY_DIAGNOSTICS_LAST_TRANSITION = 0x0503,

  PROM_DOM_KEY_FFT_RESERVED = 0x0601,

  PROM_DOM_KEY_ASYNC_TASK_ID = 0x0701,
  PROM_DOM_KEY_ASYNC_LIFECYCLE_STATE = 0x0702,
  PROM_DOM_KEY_ASYNC_STAGE = 0x0703,
  PROM_DOM_KEY_ASYNC_DETAIL = 0x0704,
  PROM_DOM_KEY_ASYNC_READY = 0x0705,
  PROM_DOM_KEY_ASYNC_FAILED = 0x0706,
  PROM_DOM_KEY_ASYNC_CONSUMED = 0x0707,
  PROM_DOM_KEY_ASYNC_OUTSTANDING_TASKS = 0x0708,
  PROM_DOM_KEY_ASYNC_FAILURE_STAGE = 0x0709,
  PROM_DOM_KEY_ASYNC_FAILURE_DETAIL = 0x070A,
  PROM_DOM_KEY_ASYNC_SUBMIT_DETAIL = 0x070B,
  PROM_DOM_KEY_ASYNC_QUERY_DETAIL = 0x070C,
  PROM_DOM_KEY_ASYNC_SLOT_ID = 0x070D,
  PROM_DOM_KEY_ASYNC_SLOT_GENERATION = 0x070E,
  PROM_DOM_KEY_ASYNC_OWNS_SLOT = 0x070F,
  PROM_DOM_KEY_ASYNC_TRANSFER_COMPLETE = 0x0710,
  PROM_DOM_KEY_ASYNC_COMPUTE_COMPLETE = 0x0711,
  PROM_DOM_KEY_ASYNC_READBACK_COMPLETE = 0x0712,
} prom_dom_key;

typedef enum prom_dom_value_type {
  PROM_DOM_VALUE_UNSET = 0,
  PROM_DOM_VALUE_U32 = 1,
  PROM_DOM_VALUE_U64 = 2,
  PROM_DOM_VALUE_I32 = 3,
  PROM_DOM_VALUE_I64 = 4,
  PROM_DOM_VALUE_BOOL = 5,
} prom_dom_value_type;

typedef enum prom_dom_source {
  PROM_DOM_SOURCE_UNKNOWN = 0,
  PROM_DOM_SOURCE_REACTOR = 1,
  PROM_DOM_SOURCE_JUDGMENT = 2,
  PROM_DOM_SOURCE_SLOT_HFSM = 3,
  PROM_DOM_SOURCE_POLICY = 4,
  PROM_DOM_SOURCE_QUEUE = 5,
  PROM_DOM_SOURCE_MEMORY = 6,
  PROM_DOM_SOURCE_DIAGNOSTICS = 7,
} prom_dom_source;

typedef enum prom_dom_event_kind {
  PROM_DOM_EVENT_NONE = 0,
  PROM_DOM_EVENT_SLOT_PREPARED = 1,
  PROM_DOM_EVENT_SLOT_READY = 2,
  PROM_DOM_EVENT_SLOT_SUBMITTED = 3,
  PROM_DOM_EVENT_SLOT_COMPLETE = 4,
  PROM_DOM_EVENT_SLOT_FAILED = 5,
  PROM_DOM_EVENT_TRANSFER_COMPLETE = 6,
  PROM_DOM_EVENT_QUEUE_HANDOFF = 7,
  PROM_DOM_EVENT_POLICY_SELECTED_MODE = 8,
  PROM_DOM_EVENT_FALLBACK_EMITTED = 9,
  PROM_DOM_EVENT_SLOT_PROMOTED_CURRENT = 10,
  PROM_DOM_EVENT_SLOT_CONSUMED = 11,
  PROM_DOM_EVENT_SLOT_CLEANUP = 12,
  PROM_DOM_EVENT_SLOT_INVALIDATED = 13,
  PROM_DOM_EVENT_TRANSFER_FAILED = 14,
  PROM_DOM_EVENT_TRANSFER_WAIT = 15,
  PROM_DOM_EVENT_ASYNC_SUBMITTED = 16,
  PROM_DOM_EVENT_ASYNC_NOT_READY = 17,
  PROM_DOM_EVENT_ASYNC_READY = 18,
  PROM_DOM_EVENT_ASYNC_FAILED = 19,
  PROM_DOM_EVENT_ASYNC_CONSUMED = 20,
  PROM_DOM_EVENT_ASYNC_ABANDONED = 21,
  PROM_DOM_EVENT_ASYNC_INVALID_TASK = 22,
  PROM_DOM_EVENT_ASYNC_ALREADY_CONSUMED = 23,
  PROM_DOM_EVENT_ASYNC_UNCONSUMED_REJECTED = 24,
  PROM_DOM_EVENT_LEASE_REQUESTED = 25,
  PROM_DOM_EVENT_LEASE_GRANTED = 26,
  PROM_DOM_EVENT_LEASE_DENIED = 27,
  PROM_DOM_EVENT_LEASE_YIELDED = 28,
} prom_dom_event_kind;

typedef struct prom_dom_value {
  prom_dom_value_type type;
  union {
    uint32_t u32;
    uint64_t u64;
    int32_t i32;
    int64_t i64;
    uint32_t boolean;
  } data;
} prom_dom_value;

typedef struct prom_dom_event {
  uint64_t generation;
  uint64_t sequence;
  prom_dom_event_kind kind;
  prom_dom_source source;
  prom_dom_domain domain;
  prom_dom_key key;
  uint32_t slot_id;
  int32_t reason_code;
} prom_dom_event;

typedef struct prom_dom_trace_entry {
  uint64_t generation;
  uint64_t sequence;
  prom_dom_source source;
  prom_dom_domain domain;
  prom_dom_key key;
  prom_dom_event_kind event_kind;
  uint32_t slot_id;
  int32_t reason_code;
  prom_dom_value old_value;
  prom_dom_value new_value;
} prom_dom_trace_entry;

typedef struct prom_dom_blackboard {
  prom_dom_value visible_values[PROM_DOM_STORAGE_CAPACITY];
  prom_dom_value staged_values[PROM_DOM_STORAGE_CAPACITY];
  uint64_t visible_generation;
  uint64_t staged_generation;
  uint64_t sequence_counter;
  uint64_t dirty_keys_staged[PROM_DOM_KEY_WORDS];
  uint64_t dirty_keys_last_commit[PROM_DOM_KEY_WORDS];
  uint32_t dirty_domains_staged;
  uint32_t dirty_domains_last_commit;
  uint32_t dirty_slots_staged;
  uint32_t dirty_slots_last_commit;
  uint64_t slot_readiness_boundary_generation;
  uint32_t slot_readiness_dirty_slot_mask;
  uint32_t slot_readiness_ready_slot_mask;
  uint32_t slot_readiness_failed_slot_mask;
  uint32_t slot_readiness_invalidated_slot_mask;
  uint32_t slot_readiness_attention_slot_mask;
  uint32_t slot_readiness_overflow_spill_count;
  uint64_t slot_readiness_duplicate_ready_event_count;
  uint64_t slot_readiness_empty_boundary_commit_count;
  prom_dom_event staged_events[PROM_DOM_MAX_EVENTS];
  uint32_t staged_event_count;
  prom_dom_event committed_events[PROM_DOM_MAX_EVENTS];
  uint32_t committed_event_start;
  uint32_t committed_event_count;
  prom_dom_trace_entry trace_ring[PROM_DOM_MAX_TRACE];
  uint32_t trace_start;
  uint32_t trace_count;
} prom_dom_blackboard;

void prom_dom_blackboard_init(prom_dom_blackboard* board);
void prom_dom_blackboard_reset(prom_dom_blackboard* board);

uint32_t prom_dom_set_u32(prom_dom_blackboard* board,
                          prom_dom_source source,
                          prom_dom_key key,
                          uint32_t slot_id,
                          uint32_t value,
                          int32_t reason_code);
uint32_t prom_dom_set_u64(prom_dom_blackboard* board,
                          prom_dom_source source,
                          prom_dom_key key,
                          uint32_t slot_id,
                          uint64_t value,
                          int32_t reason_code);
uint32_t prom_dom_set_i32(prom_dom_blackboard* board,
                          prom_dom_source source,
                          prom_dom_key key,
                          uint32_t slot_id,
                          int32_t value,
                          int32_t reason_code);
uint32_t prom_dom_set_i64(prom_dom_blackboard* board,
                          prom_dom_source source,
                          prom_dom_key key,
                          uint32_t slot_id,
                          int64_t value,
                          int32_t reason_code);
uint32_t prom_dom_set_bool(prom_dom_blackboard* board,
                           prom_dom_source source,
                           prom_dom_key key,
                           uint32_t slot_id,
                           uint32_t value,
                           int32_t reason_code);

uint32_t prom_dom_get_u32(const prom_dom_blackboard* board, prom_dom_key key, uint32_t slot_id, uint32_t* out_value);
uint32_t prom_dom_get_u64(const prom_dom_blackboard* board, prom_dom_key key, uint32_t slot_id, uint64_t* out_value);
uint32_t prom_dom_get_i32(const prom_dom_blackboard* board, prom_dom_key key, uint32_t slot_id, int32_t* out_value);
uint32_t prom_dom_get_i64(const prom_dom_blackboard* board, prom_dom_key key, uint32_t slot_id, int64_t* out_value);
uint32_t prom_dom_get_bool(const prom_dom_blackboard* board, prom_dom_key key, uint32_t slot_id, uint32_t* out_value);

uint32_t prom_dom_stage_event(prom_dom_blackboard* board, const prom_dom_event* event);
void prom_dom_commit(prom_dom_blackboard* board);

uint64_t prom_dom_dirty_keys_staged_word(const prom_dom_blackboard* board, uint32_t word_index);
uint64_t prom_dom_dirty_keys_last_commit_word(const prom_dom_blackboard* board, uint32_t word_index);
uint32_t prom_dom_dirty_key_staged(const prom_dom_blackboard* board, prom_dom_key key);
uint32_t prom_dom_dirty_key_last_commit(const prom_dom_blackboard* board, prom_dom_key key);
uint32_t prom_dom_dirty_domains_staged(const prom_dom_blackboard* board);
uint32_t prom_dom_dirty_domains_last_commit(const prom_dom_blackboard* board);
uint32_t prom_dom_dirty_slots_staged(const prom_dom_blackboard* board);
uint32_t prom_dom_dirty_slots_last_commit(const prom_dom_blackboard* board);

uint32_t prom_dom_staged_event_count(const prom_dom_blackboard* board);
uint32_t prom_dom_committed_event_count(const prom_dom_blackboard* board);
uint32_t prom_dom_committed_event_at(const prom_dom_blackboard* board, uint32_t index, prom_dom_event* out_event);

uint32_t prom_dom_trace_count(const prom_dom_blackboard* board);
uint32_t prom_dom_trace_at(const prom_dom_blackboard* board, uint32_t index, prom_dom_trace_entry* out_entry);

#ifdef __cplusplus
}
#endif

#endif
