// Generated by canonical GoOct SDSL-V via VD-MIR. Do not edit by hand.
// namespace Prometheus.Production.ZImage

struct AttentionStreamingParams
{
    uint TokenCount;
    uint HeadCount;
    uint HeadWidth;
    uint FusedWidth;
};

[[vk::binding(1, 0)]] RWStructuredBuffer<float> Attention;
[[vk::binding(2, 0)]] RWStructuredBuffer<float> Audit;
[[vk::binding(0, 0)]] StructuredBuffer<float> Qkv;
groupshared float Scores[1024];
groupshared float Probabilities[1024];

float ExponentialF32(float value)
{
    float __sdslv_inline_hlsl_0;
    {
        // BEGIN INLINE HLSL internal/prometheus/shaders/sdslv/production/zimage/nr0_attention_streaming.sdslv:12
         __sdslv_inline_hlsl_0 = exp(value); 
        // END INLINE HLSL
    }
    float result = __sdslv_inline_hlsl_0;
    return result;
}

void Nr0AttentionStreaming_WriteAuditSample(uint base, uint offset, uint key, float maximum)
{
    Audit[(base + offset)] = (Scores[key] / 0.08838834764831843);
    Audit[((base + offset) + 1u)] = Scores[key];
    Audit[((base + offset) + 2u)] = (Scores[key] - maximum);
    Audit[((base + offset) + 3u)] = Probabilities[key];
    Audit[((base + offset) + 4u)] = 0.0;
    return;
}

void Nr0AttentionStreaming_WriteAuditProbability(uint base, uint offset, uint key)
{
    Audit[((base + offset) + 4u)] = Probabilities[key];
    return;
}

[[vk::push_constant]] ConstantBuffer<AttentionStreamingParams> params;

[numthreads(256, 1, 1)]
void Nr0AttentionStreaming_CS(uint3 GroupThreadID : SV_GroupThreadID, uint3 GroupID : SV_GroupID)
{
    uint packedRow = GroupID.x;
    uint token = (packedRow / params.HeadCount);
    uint head = (packedRow - (token * params.HeadCount));
    uint lane = GroupThreadID.x;
    if ((token >= params.TokenCount))
    {
        return;
    }
    for (uint part = 0u; part < 4u; part += 1)
    {
        uint key = (lane + (part * 256u));
        float dot = 0.0;
        for (uint channel = 0u; channel < params.HeadWidth; channel += 1)
        {
            uint qIndex = (((token * params.FusedWidth) + (head * params.HeadWidth)) + channel);
            uint kIndex = ((((key * params.FusedWidth) + 3840u) + (head * params.HeadWidth)) + channel);
            dot = (dot + (Qkv[qIndex] * Qkv[kIndex]));
        }
        Scores[key] = (dot * 0.08838834764831843);
    }
    GroupMemoryBarrierWithGroupSync();
    if ((lane == 0u))
    {
        float maximum = Scores[0u];
        for (uint key = 1u; key < params.TokenCount; key += 1)
        {
            if ((Scores[key] > maximum))
            {
                maximum = Scores[key];
            }
        }
        float probabilitySum = 0.0;
        for (uint key = 0u; key < params.TokenCount; key += 1)
        {
            float exponential = ExponentialF32((Scores[key] - maximum));
            Probabilities[key] = exponential;
            probabilitySum = (probabilitySum + exponential);
        }
        bool selected = (((token == 0u) && (head == 0u)) || ((token == 1023u) && (head == 29u)));
        uint auditBase = 0u;
        if ((token == 1023u))
        {
            auditBase = 32u;
        }
        if (selected)
        {
            Nr0AttentionStreaming_WriteAuditSample(auditBase, 0u, 0u, maximum);
            Nr0AttentionStreaming_WriteAuditSample(auditBase, 5u, 1u, maximum);
            Nr0AttentionStreaming_WriteAuditSample(auditBase, 10u, 512u, maximum);
            Nr0AttentionStreaming_WriteAuditSample(auditBase, 15u, 1023u, maximum);
            Audit[(auditBase + 20u)] = maximum;
            Audit[(auditBase + 21u)] = probabilitySum;
        }
        uint denominatorValid = 0u;
        if ((((probabilitySum == probabilitySum) && (probabilitySum > 0.0)) && ((probabilitySum - probabilitySum) == 0.0)))
        {
            denominatorValid = 1u;
        }
        if (selected)
        {
            if ((denominatorValid != 0u))
            {
                Audit[(auditBase + 30u)] = 1.0;
            }
            else
            {
                Audit[(auditBase + 30u)] = 0.0;
            }
        }
        float rowSum = 0.0;
        for (uint key = 0u; key < params.TokenCount; key += 1)
        {
            if ((denominatorValid != 0u))
            {
                Probabilities[key] = (Probabilities[key] / probabilitySum);
            }
            else
            {
                Probabilities[key] = 0.0;
            }
            rowSum = (rowSum + Probabilities[key]);
        }
        if (selected)
        {
            Nr0AttentionStreaming_WriteAuditProbability(auditBase, 0u, 0u);
            Nr0AttentionStreaming_WriteAuditProbability(auditBase, 5u, 1u);
            Nr0AttentionStreaming_WriteAuditProbability(auditBase, 10u, 512u);
            Nr0AttentionStreaming_WriteAuditProbability(auditBase, 15u, 1023u);
            Audit[(auditBase + 22u)] = rowSum;
        }
    }
    GroupMemoryBarrierWithGroupSync();
    if ((lane < params.HeadWidth))
    {
        float total = 0.0;
        for (uint key = 0u; key < params.TokenCount; key += 1)
        {
            uint valueIndex = ((((key * params.FusedWidth) + 7680u) + (head * params.HeadWidth)) + lane);
            total = (total + (Probabilities[key] * Qkv[valueIndex]));
        }
        Attention[(((token * 3840u) + (head * params.HeadWidth)) + lane)] = total;
        if (((lane == 0u) && (((token == 0u) && (head == 0u)) || ((token == 1023u) && (head == 29u)))))
        {
            uint auditBase = 0u;
            if ((token == 1023u))
            {
                auditBase = 32u;
            }
            float value0 = Qkv[(7680u + (head * params.HeadWidth))];
            Audit[(auditBase + 23u)] = (Probabilities[0u] * value0);
            Audit[(auditBase + 24u)] = total;
        }
    }
    return;
}

