/*
 * reactor_cuda_tc_kernels.h
 *
 * Prometheus CUDA Tensor Core PTX kernels embedded as C string literals.
 * Loaded at runtime via cuModuleLoadDataEx (PTX JIT compilation by the CUDA driver).
 *
 * Two kernels:
 *   k_prom_bf16_tc_ptx   -- BF16 training kernel  (mma.sync.m16n8k16.bf16)
 *   k_prom_fp8_tc_ptx    -- FP8 inference kernel  (mma.sync.m16n8k32.e4m3)
 *
 * Usage in reactor_cuda_fast_path.c:
 *
 *   CUmodule mod;
 *   CUfunction fn;
 *
 *   // Load PTX (JIT compiled by driver on first call, cached afterward)
 *   CUresult r = cuModuleLoadDataEx(&mod, k_prom_bf16_tc_ptx, 0, NULL, NULL);
 *   if (r != CUDA_SUCCESS) { ... handle error ... }
 *
 *   r = cuModuleGetFunction(&fn, mod, "prom_sgemm_bf16_tc");
 *   if (r != CUDA_SUCCESS) { ... }
 *
 *   // Set up launch parameters
 *   void* args[] = { &d_A, &d_B, &d_C, &M, &N, &K };
 *   unsigned int grid_x  = (N + 63) / 64;
 *   unsigned int grid_y  = (M + 63) / 64;
 *   unsigned int block_x = 128;
 *   unsigned int smem    = 4096;   // 4KB shared memory per CTA
 *
 *   r = cuLaunchKernel(fn,
 *       grid_x, grid_y, 1,         // grid dims
 *       block_x, 1, 1,             // block dims
 *       smem,                       // dynamic shared memory bytes
 *       stream,                     // CUDA stream
 *       args, NULL);
 *
 * Prometheus C layer responsibilities (NOT in these kernels):
 *   - Buffer staging (device-resident via cudaExternalMemoryGetMappedBuffer)
 *   - Arena lifecycle and fence synchronization
 *   - Judgment engine variant selection (bf16 vs fp8 based on precision class)
 *   - FP8 input/output scaling (scale factors applied before/after kernel)
 *   - Grid dimension bounds checking (pad M and N to multiples of 64 if needed)
 *
 * Function names for cuModuleGetFunction:
 *   BF16: "prom_sgemm_bf16_tc"
 *   FP8:  "prom_sgemm_fp8e4m3_tc"
 *
 * Requires: SM90 (Hopper H100/H200). Will fail to load on earlier architectures.
 * The CUDA driver validates the .target sm_90 directive at cuModuleLoadDataEx time.
 */

#ifndef PROMETHEUS_REACTOR_CUDA_TC_KERNELS_H
#define PROMETHEUS_REACTOR_CUDA_TC_KERNELS_H

/* ============================================================================
 * Kernel function name constants
 * ============================================================================ */
#define PROM_TC_KERNEL_BF16  "prom_sgemm_bf16_tc"
#define PROM_TC_KERNEL_FP8   "prom_sgemm_fp8e4m3_tc"

/* ============================================================================
 * Shared memory size for cuLaunchKernel smem parameter
 * Both kernels use 4096 bytes (64x16 BF16 + 16x64 BF16 for BF16,
 * or 64x32 FP8 + 32x64 FP8 for FP8 -- both happen to be 4096 bytes)
 * ============================================================================ */
#define PROM_TC_SMEM_BYTES   4096u

/* ============================================================================
 * Grid and block dimension helpers
 * grid_x = (N + 63) / 64
 * grid_y = (M + 63) / 64
 * block   = 128 threads
 * ============================================================================ */
#define PROM_TC_BLOCK_THREADS    128u
#define PROM_TC_TILE_SIZE        64u
#define PROM_TC_GRID_X(N)        (((N) + 63u) / 64u)
#define PROM_TC_GRID_Y(M)        (((M) + 63u) / 64u)

/* ============================================================================
 * PTX source strings (include the .ptx files generated by Prometheus tooling)
 * These are loaded via cuModuleLoadDataEx for driver-side JIT compilation.
 *
 * The PTX driver JIT cache persists across process restarts (stored in
 * ~/.nv/ComputeCache on Linux). First-load compilation takes ~100-200ms;
 * subsequent loads are instant from cache.
 * ============================================================================ */

/*
 * BF16 training kernel PTX.
 * Computed: C[M,N] = A_bf16[M,K] * B_bf16[K,N], output C is FP32.
 * Best for: transformer training, forward pass, attention projection GEMMs.
 * K step: 16 BF16 elements per K-tile.
 */
static const char k_prom_bf16_tc_ptx[] =
#include "reactor_cuda_bf16_tc.ptx.inc"   /* generated string-ified PTX */
;

/*
 * FP8 E4M3 inference kernel PTX.
 * Computed: C[M,N] = A_fp8[M,K] * B_fp8[K,N], output C is FP32.
 * Best for: inference, decode phase, post-quantization serving.
 * K step: 32 FP8 elements per K-tile (double BF16 due to smaller element size).
 * NOTE: caller must apply absmax scale factors to C_fp32 after this kernel.
 *   C_real = (scale_A * scale_B) * C_fp32
 */
static const char k_prom_fp8e4m3_tc_ptx[] =
#include "reactor_cuda_fp8_tc.ptx.inc"
;

/*
 * Alternative: if .inc file generation is not set up yet, embed inline:
 *
 * static const char k_prom_bf16_tc_ptx[] =
 *     ".version 8.0\n"
 *     ".target sm_90\n"
 *     ".address_size 64\n"
 *     // ... (full PTX as a multiline C string) ...
 *     ;
 *
 * For Codex: when wiring this into reactor_cuda_fast_path.c, use the
 * inline string approach until the .inc generation step is set up.
 * The .ptx files in this directory are the canonical source; the .inc
 * files are generated by the build step: sed 's/"/\\"/g; s/^/"/; s/$/ \\n"/'
 */

#endif /* PROMETHEUS_REACTOR_CUDA_TC_KERNELS_H */
