// Generated by canonical GoOct SDSL-V via VD-MIR. Do not edit by hand.
// namespace Prometheus.Production.ZImage

// type FfnNormalizedEmbedding = float4 @space(zimage.noise_refiner.ffn_normalized_embedding)

// type FfnHiddenW1 = float4 @space(zimage.noise_refiner.ffn_hidden_w1)

// type FfnHiddenW3 = float4 @space(zimage.noise_refiner.ffn_hidden_w3)

struct FfnProjectionParams
{
    uint TokenCount;
    uint ModelWidth;
    uint HiddenWidth;
    uint Reserved;
};

[[vk::binding(0, 0)]] StructuredBuffer<float> FfnInput;
[[vk::binding(6, 0)]] RWStructuredBuffer<float> W1;
[[vk::binding(1, 0)]] StructuredBuffer<uint> W1F16;
[[vk::binding(2, 0)]] StructuredBuffer<uint> W3F16;
[[vk::binding(3, 0)]] RWStructuredBuffer<float> W3PartA;
[[vk::binding(4, 0)]] RWStructuredBuffer<float> W3PartB;
[[vk::binding(5, 0)]] RWStructuredBuffer<float> W3PartC;
groupshared float InputTile[16 * 16];
groupshared float W1Tile[16 * 16];
groupshared float W3Tile[16 * 16];

float4 ProjectW1(float4 value)
{
    return float4(value.x, value.y, value.z, value.w);
}

float4 ProjectW3(float4 value)
{
    return float4(value.x, value.y, value.z, value.w);
}

[[vk::push_constant]] ConstantBuffer<FfnProjectionParams> params;

[numthreads(8, 8, 1)]
void Nr0FfnW1W3_CS(uint3 GroupThreadID : SV_GroupThreadID, uint3 GroupID : SV_GroupID)
{
    uint localToken = GroupThreadID.x;
    uint localOutput = GroupThreadID.y;
    uint localLinear = ((localToken * 8u) + localOutput);
    uint groupToken = (GroupID.x * 16u);
    uint groupOutput = (GroupID.y * 16u);
    uint token = (groupToken + (localToken * 2u));
    uint output = (groupOutput + (localOutput * 2u));
    float w1[4];
    w1[0] = 0.0;
    w1[1] = 0.0;
    w1[2] = 0.0;
    w1[3] = 0.0;
    float w3[4];
    w3[0] = 0.0;
    w3[1] = 0.0;
    w3[2] = 0.0;
    w3[3] = 0.0;
    uint tileCount = 240u;
    [loop]
    for (uint tile = 0u; tile < tileCount; tile += 1)
    {
        uint tileBase = (tile * 16u);
        uint tileIndex__ct0 = ((localLinear * 4u) + 0u);
        uint tileRow__ct0 = (tileIndex__ct0 / 16u);
        uint tileColumn__ct0 = (tileIndex__ct0 % 16u);
        uint element__ct0 = ((((tileBase + tileRow__ct0) * 10240u) + groupOutput) + tileColumn__ct0);
        float2 w1Lanes__ct0 = f16tof32(uint2((W1F16[(element__ct0 / 2u)] & 65535u), (W1F16[(element__ct0 / 2u)] >> 16u)));
        float2 w3Lanes__ct0 = f16tof32(uint2((W3F16[(element__ct0 / 2u)] & 65535u), (W3F16[(element__ct0 / 2u)] >> 16u)));
        float w1Weight__ct0 = w1Lanes__ct0.x;
        float w3Weight__ct0 = w3Lanes__ct0.x;
        if (((element__ct0 % 2u) != 0u))
        {
            w1Weight__ct0 = w1Lanes__ct0.y;
            w3Weight__ct0 = w3Lanes__ct0.y;
        }
        InputTile[((tileRow__ct0) * (16)) + (tileColumn__ct0)] = FfnInput[((((groupToken + tileRow__ct0) * 3840u) + tileBase) + tileColumn__ct0)];
        W1Tile[((tileRow__ct0) * (16)) + (tileColumn__ct0)] = w1Weight__ct0;
        W3Tile[((tileRow__ct0) * (16)) + (tileColumn__ct0)] = w3Weight__ct0;
        uint tileIndex__ct1 = ((localLinear * 4u) + 1u);
        uint tileRow__ct1 = (tileIndex__ct1 / 16u);
        uint tileColumn__ct1 = (tileIndex__ct1 % 16u);
        uint element__ct1 = ((((tileBase + tileRow__ct1) * 10240u) + groupOutput) + tileColumn__ct1);
        float2 w1Lanes__ct1 = f16tof32(uint2((W1F16[(element__ct1 / 2u)] & 65535u), (W1F16[(element__ct1 / 2u)] >> 16u)));
        float2 w3Lanes__ct1 = f16tof32(uint2((W3F16[(element__ct1 / 2u)] & 65535u), (W3F16[(element__ct1 / 2u)] >> 16u)));
        float w1Weight__ct1 = w1Lanes__ct1.x;
        float w3Weight__ct1 = w3Lanes__ct1.x;
        if (((element__ct1 % 2u) != 0u))
        {
            w1Weight__ct1 = w1Lanes__ct1.y;
            w3Weight__ct1 = w3Lanes__ct1.y;
        }
        InputTile[((tileRow__ct1) * (16)) + (tileColumn__ct1)] = FfnInput[((((groupToken + tileRow__ct1) * 3840u) + tileBase) + tileColumn__ct1)];
        W1Tile[((tileRow__ct1) * (16)) + (tileColumn__ct1)] = w1Weight__ct1;
        W3Tile[((tileRow__ct1) * (16)) + (tileColumn__ct1)] = w3Weight__ct1;
        uint tileIndex__ct2 = ((localLinear * 4u) + 2u);
        uint tileRow__ct2 = (tileIndex__ct2 / 16u);
        uint tileColumn__ct2 = (tileIndex__ct2 % 16u);
        uint element__ct2 = ((((tileBase + tileRow__ct2) * 10240u) + groupOutput) + tileColumn__ct2);
        float2 w1Lanes__ct2 = f16tof32(uint2((W1F16[(element__ct2 / 2u)] & 65535u), (W1F16[(element__ct2 / 2u)] >> 16u)));
        float2 w3Lanes__ct2 = f16tof32(uint2((W3F16[(element__ct2 / 2u)] & 65535u), (W3F16[(element__ct2 / 2u)] >> 16u)));
        float w1Weight__ct2 = w1Lanes__ct2.x;
        float w3Weight__ct2 = w3Lanes__ct2.x;
        if (((element__ct2 % 2u) != 0u))
        {
            w1Weight__ct2 = w1Lanes__ct2.y;
            w3Weight__ct2 = w3Lanes__ct2.y;
        }
        InputTile[((tileRow__ct2) * (16)) + (tileColumn__ct2)] = FfnInput[((((groupToken + tileRow__ct2) * 3840u) + tileBase) + tileColumn__ct2)];
        W1Tile[((tileRow__ct2) * (16)) + (tileColumn__ct2)] = w1Weight__ct2;
        W3Tile[((tileRow__ct2) * (16)) + (tileColumn__ct2)] = w3Weight__ct2;
        uint tileIndex__ct3 = ((localLinear * 4u) + 3u);
        uint tileRow__ct3 = (tileIndex__ct3 / 16u);
        uint tileColumn__ct3 = (tileIndex__ct3 % 16u);
        uint element__ct3 = ((((tileBase + tileRow__ct3) * 10240u) + groupOutput) + tileColumn__ct3);
        float2 w1Lanes__ct3 = f16tof32(uint2((W1F16[(element__ct3 / 2u)] & 65535u), (W1F16[(element__ct3 / 2u)] >> 16u)));
        float2 w3Lanes__ct3 = f16tof32(uint2((W3F16[(element__ct3 / 2u)] & 65535u), (W3F16[(element__ct3 / 2u)] >> 16u)));
        float w1Weight__ct3 = w1Lanes__ct3.x;
        float w3Weight__ct3 = w3Lanes__ct3.x;
        if (((element__ct3 % 2u) != 0u))
        {
            w1Weight__ct3 = w1Lanes__ct3.y;
            w3Weight__ct3 = w3Lanes__ct3.y;
        }
        InputTile[((tileRow__ct3) * (16)) + (tileColumn__ct3)] = FfnInput[((((groupToken + tileRow__ct3) * 3840u) + tileBase) + tileColumn__ct3)];
        W1Tile[((tileRow__ct3) * (16)) + (tileColumn__ct3)] = w1Weight__ct3;
        W3Tile[((tileRow__ct3) * (16)) + (tileColumn__ct3)] = w3Weight__ct3;
        GroupMemoryBarrierWithGroupSync();
        [unroll]
        for (uint channel = 0u; channel < 16u; channel += 1)
        {
            w1[((0u) * (2)) + (0u)] = (w1[((0u) * (2)) + (0u)] + (InputTile[((((localToken * 2u) + 0u)) * (16)) + (channel)] * W1Tile[((channel) * (16)) + (((localOutput * 2u) + 0u))]));
            w3[((0u) * (2)) + (0u)] = (w3[((0u) * (2)) + (0u)] + (InputTile[((((localToken * 2u) + 0u)) * (16)) + (channel)] * W3Tile[((channel) * (16)) + (((localOutput * 2u) + 0u))]));
            w1[((0u) * (2)) + (1u)] = (w1[((0u) * (2)) + (1u)] + (InputTile[((((localToken * 2u) + 0u)) * (16)) + (channel)] * W1Tile[((channel) * (16)) + (((localOutput * 2u) + 1u))]));
            w3[((0u) * (2)) + (1u)] = (w3[((0u) * (2)) + (1u)] + (InputTile[((((localToken * 2u) + 0u)) * (16)) + (channel)] * W3Tile[((channel) * (16)) + (((localOutput * 2u) + 1u))]));
            w1[((1u) * (2)) + (0u)] = (w1[((1u) * (2)) + (0u)] + (InputTile[((((localToken * 2u) + 1u)) * (16)) + (channel)] * W1Tile[((channel) * (16)) + (((localOutput * 2u) + 0u))]));
            w3[((1u) * (2)) + (0u)] = (w3[((1u) * (2)) + (0u)] + (InputTile[((((localToken * 2u) + 1u)) * (16)) + (channel)] * W3Tile[((channel) * (16)) + (((localOutput * 2u) + 0u))]));
            w1[((1u) * (2)) + (1u)] = (w1[((1u) * (2)) + (1u)] + (InputTile[((((localToken * 2u) + 1u)) * (16)) + (channel)] * W1Tile[((channel) * (16)) + (((localOutput * 2u) + 1u))]));
            w3[((1u) * (2)) + (1u)] = (w3[((1u) * (2)) + (1u)] + (InputTile[((((localToken * 2u) + 1u)) * (16)) + (channel)] * W3Tile[((channel) * (16)) + (((localOutput * 2u) + 1u))]));
        }
        GroupMemoryBarrierWithGroupSync();
    }
    uint index__ct0__ct0 = ((((token + 0u) * 10240u) + output) + 0u);
    W1[index__ct0__ct0] = w1[((0u) * (2)) + (0u)];
    if ((index__ct0__ct0 < 3932160u))
    {
        W3PartA[index__ct0__ct0] = w3[((0u) * (2)) + (0u)];
    }
    if (((index__ct0__ct0 >= 3932160u) && (index__ct0__ct0 < 7864320u)))
    {
        W3PartB[(index__ct0__ct0 - 3932160u)] = w3[((0u) * (2)) + (0u)];
    }
    if ((index__ct0__ct0 >= 7864320u))
    {
        W3PartC[(index__ct0__ct0 - 7864320u)] = w3[((0u) * (2)) + (0u)];
    }
    uint index__ct1__ct0 = ((((token + 0u) * 10240u) + output) + 1u);
    W1[index__ct1__ct0] = w1[((0u) * (2)) + (1u)];
    if ((index__ct1__ct0 < 3932160u))
    {
        W3PartA[index__ct1__ct0] = w3[((0u) * (2)) + (1u)];
    }
    if (((index__ct1__ct0 >= 3932160u) && (index__ct1__ct0 < 7864320u)))
    {
        W3PartB[(index__ct1__ct0 - 3932160u)] = w3[((0u) * (2)) + (1u)];
    }
    if ((index__ct1__ct0 >= 7864320u))
    {
        W3PartC[(index__ct1__ct0 - 7864320u)] = w3[((0u) * (2)) + (1u)];
    }
    uint index__ct0__ct1 = ((((token + 1u) * 10240u) + output) + 0u);
    W1[index__ct0__ct1] = w1[((1u) * (2)) + (0u)];
    if ((index__ct0__ct1 < 3932160u))
    {
        W3PartA[index__ct0__ct1] = w3[((1u) * (2)) + (0u)];
    }
    if (((index__ct0__ct1 >= 3932160u) && (index__ct0__ct1 < 7864320u)))
    {
        W3PartB[(index__ct0__ct1 - 3932160u)] = w3[((1u) * (2)) + (0u)];
    }
    if ((index__ct0__ct1 >= 7864320u))
    {
        W3PartC[(index__ct0__ct1 - 7864320u)] = w3[((1u) * (2)) + (0u)];
    }
    uint index__ct1__ct1 = ((((token + 1u) * 10240u) + output) + 1u);
    W1[index__ct1__ct1] = w1[((1u) * (2)) + (1u)];
    if ((index__ct1__ct1 < 3932160u))
    {
        W3PartA[index__ct1__ct1] = w3[((1u) * (2)) + (1u)];
    }
    if (((index__ct1__ct1 >= 3932160u) && (index__ct1__ct1 < 7864320u)))
    {
        W3PartB[(index__ct1__ct1 - 3932160u)] = w3[((1u) * (2)) + (1u)];
    }
    if ((index__ct1__ct1 >= 7864320u))
    {
        W3PartC[(index__ct1__ct1 - 7864320u)] = w3[((1u) * (2)) + (1u)];
    }
    return;
}

