/* Generated by concept-vulkan-m1. DO NOT EDIT. */
#ifndef PROM_CONCEPT_VULKAN_KERNEL54_GENERATED_H
#define PROM_CONCEPT_VULKAN_KERNEL54_GENERATED_H

/* Private conformance-only plan witness; no public Prometheus ABI. */
int prom_concept_vulkan_kernel54_plan_verify(void);

#endif
