// Generated by canonical GoOct SDSL-V via VD-MIR. Do not edit by hand.
// namespace Prometheus.Production.ZImage

// type FfnNormalizedEmbedding = float4 @space(zimage.noise_refiner.ffn_normalized_embedding)

// type FfnHiddenW1 = float4 @space(zimage.noise_refiner.ffn_hidden_w1)

// type FfnHiddenW3 = float4 @space(zimage.noise_refiner.ffn_hidden_w3)

struct FfnProjectionParams
{
    uint TokenCount;
    uint ModelWidth;
    uint HiddenWidth;
    uint Reserved;
};

[[vk::binding(0, 0)]] StructuredBuffer<float> FfnInput;
[[vk::binding(6, 0)]] RWStructuredBuffer<float> W1;
[[vk::binding(1, 0)]] StructuredBuffer<uint> W1F16;
[[vk::binding(2, 0)]] StructuredBuffer<uint> W3F16;
[[vk::binding(3, 0)]] RWStructuredBuffer<float> W3PartA;
[[vk::binding(4, 0)]] RWStructuredBuffer<float> W3PartB;
[[vk::binding(5, 0)]] RWStructuredBuffer<float> W3PartC;

float4 ProjectW1(float4 value)
{
    return float4(value.x, value.y, value.z, value.w);
}

float4 ProjectW3(float4 value)
{
    return float4(value.x, value.y, value.z, value.w);
}

[[vk::push_constant]] ConstantBuffer<FfnProjectionParams> params;

[numthreads(8, 8, 1)]
void Nr0FfnW1W3_CS(uint3 DispatchThreadID : SV_DispatchThreadID)
{
    uint token = DispatchThreadID.x;
    uint output = DispatchThreadID.y;
    if (((token >= params.TokenCount) || (output >= params.HiddenWidth)))
    {
        return;
    }
    float w1 = 0.0;
    float w3 = 0.0;
    for (uint channel = 0u; channel < params.ModelWidth; channel += 1)
    {
        uint element = ((channel * params.HiddenWidth) + output);
        float2 w1Lanes = f16tof32(uint2((W1F16[(element / 2u)] & 65535u), (W1F16[(element / 2u)] >> 16u)));
        float2 w3Lanes = f16tof32(uint2((W3F16[(element / 2u)] & 65535u), (W3F16[(element / 2u)] >> 16u)));
        float w1Weight = w1Lanes.x;
        float w3Weight = w3Lanes.x;
        if (((element % 2u) != 0u))
        {
            w1Weight = w1Lanes.y;
            w3Weight = w3Lanes.y;
        }
        float input = FfnInput[((token * params.ModelWidth) + channel)];
        w1 = (w1 + (input * w1Weight));
        w3 = (w3 + (input * w3Weight));
    }
    uint index = ((token * params.HiddenWidth) + output);
    W1[index] = w1;
    if ((index < 3932160u))
    {
        W3PartA[index] = w3;
    }
    if (((index >= 3932160u) && (index < 7864320u)))
    {
        W3PartB[(index - 3932160u)] = w3;
    }
    if ((index >= 7864320u))
    {
        W3PartC[(index - 7864320u)] = w3;
    }
    return;
}

