/* Generated by concept-vulkan-m1. DO NOT EDIT. */
#ifndef PROM_CONCEPT_VULKAN_KERNEL54_GENERATED_H
#define PROM_CONCEPT_VULKAN_KERNEL54_GENERATED_H
#include "reactor_vulkan.h"
#include "reactor_shader_package.h"

/* Private conformance-only ABI; never included by public Prometheus headers. */
int prom_concept_vulkan_kernel54_execute(const prom_vk_runtime_services* services, prom_shader_package* package, VkAccelerationStructureKHR admitted_tlas, uint32_t* out_evidence);
#ifdef PROM_CONCEPT_VULKAN_CONFORMANCE
int prom_concept_vulkan_kernel54_handwritten_adapter(void* handle, uint64_t scene_id, PrometheusRayQueryProbeResult* out_result);
int prom_concept_vulkan_kernel54_generated_adapter(void* handle, uint64_t scene_id, PrometheusRayQueryProbeResult* out_result);
#endif

#endif
