// Generated by canonical GoOct SDSL-V via VD-MIR. Do not edit by hand.
// namespace Prometheus.Production.ZImage

// type FfnHiddenW1 = float4 @space(zimage.noise_refiner.ffn_hidden_w1)

// type FfnHiddenW3 = float4 @space(zimage.noise_refiner.ffn_hidden_w3)

// type FfnGatedHidden = float4 @space(zimage.noise_refiner.ffn_gated_hidden)

struct FfnGateParams
{
    uint ElementCount;
    uint Reserved0;
    uint Reserved1;
    uint Reserved2;
};

[[vk::binding(0, 0)]] RWStructuredBuffer<float> W1;
[[vk::binding(1, 0)]] StructuredBuffer<float> W3PartA;
[[vk::binding(2, 0)]] StructuredBuffer<float> W3PartB;
[[vk::binding(3, 0)]] StructuredBuffer<float> W3PartC;

float4 GateFfn(float4 value)
{
    return float4(value.x, value.y, value.z, value.w);
}

float ExponentialF32(float value)
{
    float __sdslv_inline_hlsl_0;
    {
        // BEGIN INLINE HLSL internal/prometheus/shaders/sdslv/production/zimage/nr0_ffn_gate.sdslv:20
         __sdslv_inline_hlsl_0 = exp(value); 
        // END INLINE HLSL
    }
    float result = __sdslv_inline_hlsl_0;
    return result;
}

[[vk::push_constant]] ConstantBuffer<FfnGateParams> params;

[numthreads(256, 1, 1)]
void Nr0FfnGate_CS(uint3 DispatchThreadID : SV_DispatchThreadID)
{
    uint index = DispatchThreadID.x;
    if ((index >= params.ElementCount))
    {
        return;
    }
    float w1 = W1[index];
    float __sdslv_operand_1 = ExponentialF32(-w1);
    float silu = (w1 / (1.0 + __sdslv_operand_1));
    float w3 = 0.0;
    if ((index < 3932160u))
    {
        w3 = W3PartA[index];
    }
    if (((index >= 3932160u) && (index < 7864320u)))
    {
        w3 = W3PartB[(index - 3932160u)];
    }
    if ((index >= 7864320u))
    {
        w3 = W3PartC[(index - 7864320u)];
    }
    W1[index] = (silu * w3);
    return;
}

