/* Fixed M29 test host.  It is intentionally a process executable, not a
 * Prometheus reactor API: one SPIR-V module, one fixed result buffer, one case. */
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <vulkan/vulkan.h>
#ifdef _WIN32
#include <windows.h>
#else
#include <unistd.h>
#endif

typedef struct result_record { uint32_t abi_version,failed,assertion_id,source_line,source_column,invocation_x,invocation_y,invocation_z,value_kind,component_count,expected[4],actual[4],tolerance[4]; } result_record;
typedef struct push_data { uint32_t case_id,row_id,width,height; } push_data;
static void pause_ms(void){
#ifdef _WIN32
  Sleep(10);
#else
  usleep(10000);
#endif
}
static void json(const char* status,const char* detail,const char* id,const result_record* r){
  printf("{\"status\":\"%s\",\"detail\":\"%s\",\"stable_case_id\":\"%s\"",status,detail,id?id:"");
  if(r) printf(",\"invocation\":[%u,%u,%u],\"assertion_id\":%u,\"source\":[%u,%u],\"expected_bits\":[%u,%u,%u,%u],\"actual_bits\":[%u,%u,%u,%u],\"tolerance_bits\":[%u,%u,%u,%u]",r->invocation_x,r->invocation_y,r->invocation_z,r->assertion_id,r->source_line,r->source_column,r->expected[0],r->expected[1],r->expected[2],r->expected[3],r->actual[0],r->actual[1],r->actual[2],r->actual[3],r->tolerance[0],r->tolerance[1],r->tolerance[2],r->tolerance[3]);
  puts("}");
}
static uint32_t memory_type(VkPhysicalDevice p,uint32_t bits,VkMemoryPropertyFlags flags){ VkPhysicalDeviceMemoryProperties m;uint32_t i;vkGetPhysicalDeviceMemoryProperties(p,&m);for(i=0;i<m.memoryTypeCount;i++)if((bits&(1u<<i))&&(m.memoryTypes[i].propertyFlags&flags)==flags)return i;return UINT32_MAX; }
int main(int argc,char** argv){
  const char *manifest=NULL,*spv=NULL,*id=""; uint32_t case_id=0,row_id=0,gx=1,gy=1,gz=1,wgx=1,wgy=1,wgz=1,inv=0,width=0,height=0; FILE* f; long n; uint32_t* words=NULL; VkResult vr; VkInstance instance=0;VkPhysicalDevice physical=0;VkDevice device=0;VkQueue queue=0;uint32_t family=UINT32_MAX,count=0,i;VkCommandPool pool=0;VkDescriptorSetLayout set_layout=0;VkPipelineLayout layout=0;VkShaderModule shader=0;VkPipeline pipeline=0;VkDescriptorPool descriptor_pool=0;VkDescriptorSet set=0;VkBuffer buffer=0;VkDeviceMemory memory=0;void* mapped=0;VkCommandBuffer command=0;VkFence fence=0;result_record* records=NULL;result_record* failure=NULL;
  for(i=1;i<(uint32_t)argc;i++){ if(strcmp(argv[i],"--manifest")==0&&i+1<(uint32_t)argc)manifest=argv[++i]; else if(strcmp(argv[i],"--spv")==0&&i+1<(uint32_t)argc)spv=argv[++i]; else if(strcmp(argv[i],"--case")==0&&i+1<(uint32_t)argc)id=argv[++i]; else if(strcmp(argv[i],"--case-index")==0&&i+1<(uint32_t)argc)case_id=(uint32_t)strtoul(argv[++i],0,10); else if(strcmp(argv[i],"--row-index")==0&&i+1<(uint32_t)argc)row_id=(uint32_t)strtoul(argv[++i],0,10); else if(strcmp(argv[i],"--groups")==0&&i+3<(uint32_t)argc){gx=(uint32_t)strtoul(argv[++i],0,10);gy=(uint32_t)strtoul(argv[++i],0,10);gz=(uint32_t)strtoul(argv[++i],0,10);} else if(strcmp(argv[i],"--workgroup")==0&&i+3<(uint32_t)argc){wgx=(uint32_t)strtoul(argv[++i],0,10);wgy=(uint32_t)strtoul(argv[++i],0,10);wgz=(uint32_t)strtoul(argv[++i],0,10);} }
  if(!manifest||!spv||(f=fopen(manifest,"rb"))==NULL){json("HOST_FAILURE","missing manifest or SPIR-V",id,NULL);return 2;}fclose(f);if(wgx&&wgy&&wgz&&gx<=UINT32_MAX/wgx&&gy<=UINT32_MAX/wgy&&gz<=UINT32_MAX/wgz){width=gx*wgx;height=gy*wgy;inv=width*height*(gz*wgz);}if(!inv||inv>UINT32_MAX/sizeof(result_record)){json("HOST_FAILURE","invalid invocation count",id,NULL);return 2;}
  f=fopen(spv,"rb");if(!f){json("COMPILE_FAILED","cannot read SPIR-V",id,NULL);return 2;}fseek(f,0,SEEK_END);n=ftell(f);rewind(f);if(n<=0||n%4){fclose(f);json("COMPILE_FAILED","invalid SPIR-V bytes",id,NULL);return 2;}words=(uint32_t*)malloc((size_t)n);if(!words||fread(words,1,(size_t)n,f)!=(size_t)n){fclose(f);free(words);json("COMPILE_FAILED","read SPIR-V",id,NULL);return 2;}fclose(f);
  {VkInstanceCreateInfo ci={VK_STRUCTURE_TYPE_INSTANCE_CREATE_INFO};vr=vkCreateInstance(&ci,0,&instance);if(vr){json("HOST_FAILURE","vkCreateInstance",id,NULL);goto done;}}
  vr=vkEnumeratePhysicalDevices(instance,&count,0);if(vr||!count){json("HOST_FAILURE","no Vulkan physical device",id,NULL);goto done;} {VkPhysicalDevice* ds=(VkPhysicalDevice*)malloc(sizeof(VkPhysicalDevice)*count);vkEnumeratePhysicalDevices(instance,&count,ds);for(i=0;i<count&&!physical;i++){uint32_t qn=0,j;VkQueueFamilyProperties* qs;vkGetPhysicalDeviceQueueFamilyProperties(ds[i],&qn,0);qs=(VkQueueFamilyProperties*)malloc(sizeof(*qs)*qn);vkGetPhysicalDeviceQueueFamilyProperties(ds[i],&qn,qs);for(j=0;j<qn;j++)if(qs[j].queueFlags&VK_QUEUE_COMPUTE_BIT){physical=ds[i];family=j;break;}free(qs);}free(ds);}if(!physical){json("HOST_FAILURE","no compute queue",id,NULL);goto done;}
  {float priority=1;VkDeviceQueueCreateInfo qi={VK_STRUCTURE_TYPE_DEVICE_QUEUE_CREATE_INFO,0,0,family,1,&priority};VkDeviceCreateInfo di={VK_STRUCTURE_TYPE_DEVICE_CREATE_INFO,0,0,1,&qi};vr=vkCreateDevice(physical,&di,0,&device);if(vr){json("HOST_FAILURE","vkCreateDevice",id,NULL);goto done;}}vkGetDeviceQueue(device,family,0,&queue);
  {VkCommandPoolCreateInfo x={VK_STRUCTURE_TYPE_COMMAND_POOL_CREATE_INFO,0,VK_COMMAND_POOL_CREATE_RESET_COMMAND_BUFFER_BIT,family};vr=vkCreateCommandPool(device,&x,0,&pool);if(vr){json("HOST_FAILURE","vkCreateCommandPool",id,NULL);goto done;}}
  {VkDescriptorSetLayoutBinding b={0,VK_DESCRIPTOR_TYPE_STORAGE_BUFFER,1,VK_SHADER_STAGE_COMPUTE_BIT,0};VkDescriptorSetLayoutCreateInfo x={VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_CREATE_INFO,0,0,1,&b};vr=vkCreateDescriptorSetLayout(device,&x,0,&set_layout);if(vr){json("PIPELINE_CREATION_FAILED","descriptor layout",id,NULL);goto done;}}
  {VkPushConstantRange r={VK_SHADER_STAGE_COMPUTE_BIT,0,sizeof(push_data)};VkPipelineLayoutCreateInfo x={VK_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO,0,0,1,&set_layout,1,&r};vr=vkCreatePipelineLayout(device,&x,0,&layout);if(vr){json("PIPELINE_CREATION_FAILED","pipeline layout",id,NULL);goto done;}}
  {VkShaderModuleCreateInfo x={VK_STRUCTURE_TYPE_SHADER_MODULE_CREATE_INFO,0,0,(size_t)n,words};vr=vkCreateShaderModule(device,&x,0,&shader);if(vr){json("PIPELINE_CREATION_FAILED","shader module",id,NULL);goto done;}VkPipelineShaderStageCreateInfo s={VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO,0,0,VK_SHADER_STAGE_COMPUTE_BIT,shader,"main",0};VkComputePipelineCreateInfo p={VK_STRUCTURE_TYPE_COMPUTE_PIPELINE_CREATE_INFO,0,0,s,layout,0,-1};vr=vkCreateComputePipelines(device,0,1,&p,0,&pipeline);if(vr){json("PIPELINE_CREATION_FAILED","compute pipeline",id,NULL);goto done;}}
  {VkBufferCreateInfo x={VK_STRUCTURE_TYPE_BUFFER_CREATE_INFO,0,0,(VkDeviceSize)inv*sizeof(result_record),VK_BUFFER_USAGE_STORAGE_BUFFER_BIT,VK_SHARING_MODE_EXCLUSIVE,0,0};VkMemoryRequirements mr;VkMemoryAllocateInfo ai={VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO};vr=vkCreateBuffer(device,&x,0,&buffer);if(vr){json("HOST_FAILURE","result buffer",id,NULL);goto done;}vkGetBufferMemoryRequirements(device,buffer,&mr);ai.allocationSize=mr.size;ai.memoryTypeIndex=memory_type(physical,mr.memoryTypeBits,VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT|VK_MEMORY_PROPERTY_HOST_COHERENT_BIT);if(ai.memoryTypeIndex==UINT32_MAX||(vr=vkAllocateMemory(device,&ai,0,&memory))){json("HOST_FAILURE","result memory",id,NULL);goto done;}vkBindBufferMemory(device,buffer,memory,0);if(vkMapMemory(device,memory,0,VK_WHOLE_SIZE,0,&mapped)){json("HOST_FAILURE","map result buffer",id,NULL);goto done;}memset(mapped,0,(size_t)inv*sizeof(result_record));}
  {VkDescriptorPoolSize ps={VK_DESCRIPTOR_TYPE_STORAGE_BUFFER,1};VkDescriptorPoolCreateInfo p={VK_STRUCTURE_TYPE_DESCRIPTOR_POOL_CREATE_INFO,0,0,1,1,&ps};VkDescriptorSetAllocateInfo a={VK_STRUCTURE_TYPE_DESCRIPTOR_SET_ALLOCATE_INFO,0,0,1,&set_layout};VkDescriptorBufferInfo bi={buffer,0,(VkDeviceSize)inv*sizeof(result_record)};VkWriteDescriptorSet w={VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET,0,0,0,0,1,VK_DESCRIPTOR_TYPE_STORAGE_BUFFER,0,&bi,0};vr=vkCreateDescriptorPool(device,&p,0,&descriptor_pool);if(vr){json("HOST_FAILURE","descriptor pool",id,NULL);goto done;}a.descriptorPool=descriptor_pool;vkAllocateDescriptorSets(device,&a,&set);w.dstSet=set;vkUpdateDescriptorSets(device,1,&w,0,0);}
  {VkCommandBufferAllocateInfo a={VK_STRUCTURE_TYPE_COMMAND_BUFFER_ALLOCATE_INFO,0,pool,VK_COMMAND_BUFFER_LEVEL_PRIMARY,1};VkCommandBufferBeginInfo b={VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO};VkSubmitInfo s={VK_STRUCTURE_TYPE_SUBMIT_INFO};VkFenceCreateInfo fi={VK_STRUCTURE_TYPE_FENCE_CREATE_INFO};push_data pd={case_id,row_id,width,height};vkAllocateCommandBuffers(device,&a,&command);vkBeginCommandBuffer(command,&b);vkCmdBindPipeline(command,VK_PIPELINE_BIND_POINT_COMPUTE,pipeline);vkCmdBindDescriptorSets(command,VK_PIPELINE_BIND_POINT_COMPUTE,layout,0,1,&set,0,0);vkCmdPushConstants(command,layout,VK_SHADER_STAGE_COMPUTE_BIT,0,sizeof(pd),&pd);vkCmdDispatch(command,gx,gy,gz);vkEndCommandBuffer(command);vkCreateFence(device,&fi,0,&fence);s.commandBufferCount=1;s.pCommandBuffers=&command;vr=vkQueueSubmit(queue,1,&s,fence);if(vr){json(vr==VK_ERROR_DEVICE_LOST?"DEVICE_LOST":"SUBMIT_FAILED","queue submit",id,NULL);goto done;}for(i=0;i<500;i++){vr=vkWaitForFences(device,1,&fence,VK_TRUE,10000000ull);if(vr==VK_SUCCESS)break;if(vr==VK_ERROR_DEVICE_LOST){json("DEVICE_LOST","fence",id,NULL);goto done;}}if(vr!=VK_SUCCESS){json("TIMEOUT","deadline exceeded",id,NULL);goto done;}}
  records=(result_record*)mapped;for(i=0;i<inv;i++){if(records[i].abi_version!=1u){json("INVALID_RESULT_BUFFER","ABI version",id,NULL);goto done;}if(!failure&&records[i].failed)failure=&records[i];}if(failure)json("ASSERTION_FAILED","assertion",id,failure);else json("PASS","",id,NULL);
done: if(device)vkDeviceWaitIdle(device);if(fence)vkDestroyFence(device,fence,0);if(pool&&command)vkFreeCommandBuffers(device,pool,1,&command);if(descriptor_pool)vkDestroyDescriptorPool(device,descriptor_pool,0);if(mapped)vkUnmapMemory(device,memory);if(buffer)vkDestroyBuffer(device,buffer,0);if(memory)vkFreeMemory(device,memory,0);if(pipeline)vkDestroyPipeline(device,pipeline,0);if(shader)vkDestroyShaderModule(device,shader,0);if(layout)vkDestroyPipelineLayout(device,layout,0);if(set_layout)vkDestroyDescriptorSetLayout(device,set_layout,0);if(pool)vkDestroyCommandPool(device,pool,0);if(device)vkDestroyDevice(device,0);if(instance)vkDestroyInstance(instance,0);free(words);return 0;
}
