// Code generated by Oct's compiled backend. DO NOT EDIT.
package controller

import (
	"fmt"
	"reflect"
)

type __octRange struct {
	Start    int
	HasStart bool
	End      int
	HasEnd   bool
	Step     int
	HasStep  bool
}

func __octClone[T any](value T) T {
	cloned := __octCloneValue(reflect.ValueOf(value))
	if !cloned.IsValid() {
		return value
	}
	return cloned.Interface().(T)
}

func __octCloneValue(value reflect.Value) reflect.Value {
	if !value.IsValid() {
		return value
	}
	switch value.Kind() {
	case reflect.Slice:
		if value.IsNil() {
			return reflect.Zero(value.Type())
		}
		out := reflect.MakeSlice(value.Type(), value.Len(), value.Len())
		for i := 0; i < value.Len(); i++ {
			out.Index(i).Set(__octCloneValue(value.Index(i)))
		}
		return out
	case reflect.Array:
		out := reflect.New(value.Type()).Elem()
		for i := 0; i < value.Len(); i++ {
			out.Index(i).Set(__octCloneValue(value.Index(i)))
		}
		return out
	case reflect.Struct:
		out := reflect.New(value.Type()).Elem()
		for i := 0; i < value.NumField(); i++ {
			if out.Field(i).CanSet() {
				out.Field(i).Set(__octCloneValue(value.Field(i)))
			}
		}
		return out
	default:
		return value
	}
}

func __octAssignRow[T any](matrix [][]T, row int, rhs []T) {
	if row < 0 || row >= len(matrix) {
		panic(fmt.Sprintf("runtime error: row index %d out of bounds for array with %d rows", row, len(matrix)))
	}
	if len(rhs) != len(matrix[row]) {
		panic(fmt.Sprintf("runtime error: row length mismatch: expected %d, got %d", len(matrix[row]), len(rhs)))
	}
	matrix[row] = __octClone(rhs)
}

type octResult_Int struct {
	Value int
	Err   string
	IsErr bool
}

type Controller_AdmissionControllerBoardSnapshot struct {
	Decision int
}

type __octFlowInstance_Int interface {
	__octStep()
	__octActive() string
	__octComplete() bool
	__octResult() (int, bool)
	__octStateHistory() []string
	__octResumeTarget() string
	__octBoardSnapshot() (any, bool)
}

type __octResultFlow_Int struct {
	Value int
	Err   string
	IsErr bool
}

type __octFlow_Controller_AdmissionController struct {
	started         bool
	completed       bool
	currentState    int
	instruction     int
	result          int
	hasResult       bool
	history         []string
	hasResumeTarget bool
	resumeTarget    int
	requested       int
	capacity        int
	board           struct {
		Decision int
	}
}

func fn_Controller_AdmissionController(requested int, capacity int) __octFlowInstance_Int {
	__flow := &__octFlow_Controller_AdmissionController{}
	__flow.requested = requested
	__flow.capacity = capacity
	return __flow
}

func (f *__octFlow_Controller_AdmissionController) __octActive() string {
	if !f.started || f.completed {
		return ""
	}
	switch f.currentState {
	case 0:
		return "Idle"
	case 1:
		return "Evaluate"
	case 2:
		return "Accept"
	case 3:
		return "Reject"
	default:
		return ""
	}
}

func (f *__octFlow_Controller_AdmissionController) __octComplete() bool { return f.completed }

func (f *__octFlow_Controller_AdmissionController) __octResult() (int, bool) {
	return f.result, f.hasResult
}

func (f *__octFlow_Controller_AdmissionController) __octStateHistory() []string {
	out := make([]string, len(f.history))
	copy(out, f.history)
	return out
}

func (f *__octFlow_Controller_AdmissionController) __octStateName(id int) string {
	switch id {
	case 0:
		return "Idle"
	case 1:
		return "Evaluate"
	case 2:
		return "Accept"
	case 3:
		return "Reject"
	default:
		return ""
	}
}

func (f *__octFlow_Controller_AdmissionController) __octResumeTarget() string {
	if !f.hasResumeTarget {
		return ""
	}
	return f.__octStateName(f.resumeTarget)
}

func (f *__octFlow_Controller_AdmissionController) __octBoardSnapshot() (any, bool) {
	return Controller_AdmissionControllerBoardSnapshot{
		Decision: f.board.Decision,
	}, true
}

func (f *__octFlow_Controller_AdmissionController) __octStep() {
	if f.completed {
		return
	}
	if !f.started {
		f.started = true
		f.currentState = 0
		f.instruction = 0
		f.history = append(f.history, "Idle")
	}
	for {
		switch f.currentState {
		case 0:
			switch f.instruction {
			case 0:
				f.currentState = 1
				f.instruction = 0
				f.history = append(f.history, "Evaluate")
				continue
			default:
				panic("runtime invariant violation: flow state Idle exited without suspend or return")
			}
		case 1:
			switch f.instruction {
			case 0:
				if f.requested <= f.capacity {
					f.currentState = 2
					f.instruction = 0
					f.history = append(f.history, "Accept")
					continue
				}
				f.currentState = 3
				f.instruction = 0
				f.history = append(f.history, "Reject")
				continue
			default:
				panic("runtime invariant violation: flow state Evaluate exited without suspend or return")
			}
		case 2:
			switch f.instruction {
			case 0:
				f.board.Decision = 1
				f.instruction++
				continue
			case 1:
				f.result = f.board.Decision
				f.hasResult = true
				f.completed = true
				f.currentState = -1
				return
			default:
				panic("runtime invariant violation: flow state Accept exited without suspend or return")
			}
		case 3:
			switch f.instruction {
			case 0:
				f.board.Decision = 0
				f.instruction++
				continue
			case 1:
				f.result = f.board.Decision
				f.hasResult = true
				f.completed = true
				f.currentState = -1
				return
			default:
				panic("runtime invariant violation: flow state Reject exited without suspend or return")
			}
		default:
			panic("runtime invariant violation: unknown flow state")
		}
	}
}

func __octIntArrayToFloat(values []int) []float64 {
	out := make([]float64, len(values))
	for i, value := range values {
		out[i] = float64(value)
	}
	return out
}
func fn_Controller_Main() int {
	var __oct_internal_tmp_0 __octFlowInstance_Int
	_ = __oct_internal_tmp_0
	var __oct_internal_tmp_1 int
	_ = __oct_internal_tmp_1
	var __oct_user_0 __octFlowInstance_Int
	_ = __oct_user_0
	__oct_internal_pc := 0
	for {
		switch __oct_internal_pc {
		case 0:
			__oct_internal_tmp_0 = fn_Controller_AdmissionController(1, 1)
			__oct_user_0 = __oct_internal_tmp_0
			__oct_user_0.__octStep()
			__oct_internal_tmp_1 = 0
			_ = __oct_internal_tmp_1
			return 0
		}
	}
}

var __octAssertionCount int
