// Generated by canonical GoOct SDSL-V via VD-MIR. Do not edit by hand.
// namespace Prometheus.Experimental.Transformer

struct ResidualAddParams
{
    uint Tokens;
    uint ModelWidth;
    uint XRowStride;
    uint YRowStride;
    uint ZRowStride;
    uint LogicalElementCount;
    uint Reserved0;
    uint Reserved1;
};

[[vk::binding(0, 0)]] StructuredBuffer<float> X;
[[vk::binding(1, 0)]] StructuredBuffer<float> Y;
[[vk::binding(2, 0)]] RWStructuredBuffer<float> Z;

[[vk::push_constant]] ConstantBuffer<ResidualAddParams> params;

[numthreads(256, 1, 1)]
void ResidualAdd_CS(uint3 DispatchThreadID : SV_DispatchThreadID)
{
    uint logicalIndex = DispatchThreadID.x;
    if ((logicalIndex >= params.LogicalElementCount))
    {
        return;
    }
    uint token = (logicalIndex / params.ModelWidth);
    uint column = (logicalIndex - (token * params.ModelWidth));
    uint xIndex = ((token * params.XRowStride) + column);
    uint yIndex = ((token * params.YRowStride) + column);
    uint zIndex = ((token * params.ZRowStride) + column);
    Z[zIndex] = (X[xIndex] + Y[yIndex]);
    return;
}

