// Generated by canonical GoOct SDSL-V via VD-MIR. Do not edit by hand.
// namespace Prometheus.Experimental.Transformer

struct RmsNormApplyParams
{
    uint Tokens;
    uint ModelWidth;
    uint ZRowStride;
    uint NRowStride;
    uint LogicalElementCount;
    uint Reserved0;
    uint Reserved1;
    uint Reserved2;
};

[[vk::binding(2, 0)]] StructuredBuffer<float> InvRms;
[[vk::binding(3, 0)]] RWStructuredBuffer<float> N;
[[vk::binding(1, 0)]] StructuredBuffer<float> Weight;
[[vk::binding(0, 0)]] StructuredBuffer<float> Z;

[[vk::push_constant]] ConstantBuffer<RmsNormApplyParams> params;

[numthreads(256, 1, 1)]
void RmsNormApply_CS(uint3 DispatchThreadID : SV_DispatchThreadID)
{
    uint logicalIndex = DispatchThreadID.x;
    if ((logicalIndex >= params.LogicalElementCount))
    {
        return;
    }
    uint token = (logicalIndex / params.ModelWidth);
    uint column = (logicalIndex - (token * params.ModelWidth));
    uint zIndex = ((token * params.ZRowStride) + column);
    uint nIndex = ((token * params.NRowStride) + column);
    N[nIndex] = ((Z[zIndex] * InvRms[token]) * Weight[column]);
    return;
}

