// Generated by canonical GoOct SDSL-V via VD-MIR. Do not edit by hand.
// namespace Prometheus.Experimental.Transformer

struct RmsNormReductionParams
{
    uint RowCount;
    uint ElementsPerRow;
    uint PartialsPerRow;
    uint InputRowStride;
    uint ChunkElements;
    uint TotalElements;
    uint StageRole;
    float Epsilon;
};

struct ComputeThread
{
    [[vk::location(0)]] nointerpolation uint3 DispatchId : TEXCOORD0;
    [[vk::location(1)]] nointerpolation uint3 GroupId : TEXCOORD1;
    [[vk::location(2)]] nointerpolation uint3 GroupThreadId : TEXCOORD2;
    [[vk::location(3)]] nointerpolation uint GroupIndex : TEXCOORD3;
};

static const int ReductionLane_Idle = 0;
static const int ReductionLane_Active = 1;
struct ReductionLane_ActivePayload
{
    float Partner;
};

struct ReductionLane
{
    int Tag;
    ReductionLane_ActivePayload Active;
};

ReductionLane __sdslv_make_ReductionLane_Idle()
{
    ReductionLane value;
    value.Tag = ReductionLane_Idle;
    return value;
}

ReductionLane __sdslv_make_ReductionLane_Active(float Partner)
{
    ReductionLane value;
    value.Tag = ReductionLane_Active;
    value.Active.Partner = Partner;
    return value;
}

[[vk::binding(1, 0)]] RWStructuredBuffer<float> Auxiliary0;
[[vk::binding(2, 0)]] RWStructuredBuffer<float> Auxiliary1;
[[vk::binding(0, 0)]] StructuredBuffer<float> Input;
[[vk::binding(3, 0)]] RWStructuredBuffer<float> Output;
groupshared float Shared[256];

float ReciprocalSqrtF32(float value)
{
    float __sdslv_inline_hlsl_0;
    {
        // BEGIN INLINE HLSL internal/prometheus/shaders/sdslv/experimental/transformer/rmsnorm_reduce.sdslv:37
         __sdslv_inline_hlsl_0 = rsqrt(value); 
        // END INLINE HLSL
    }
    float result = __sdslv_inline_hlsl_0;
    return result;
}

ReductionLane RmsNormReduce_SelectLane(uint index, uint stride)
{
    if ((index < stride))
    {
        return __sdslv_make_ReductionLane_Active(Shared[(index + stride)]);
    }
    return __sdslv_make_ReductionLane_Idle();
}

[[vk::push_constant]] ConstantBuffer<RmsNormReductionParams> params;

[numthreads(256, 1, 1)]
void RmsNormReduce_CS(uint3 DispatchThreadID : SV_DispatchThreadID, uint3 GroupThreadID : SV_GroupThreadID, uint3 GroupID : SV_GroupID, uint GroupIndex : SV_GroupIndex)
{
    ComputeThread thread;
    thread.DispatchId = DispatchThreadID;
    thread.GroupId = GroupID;
    thread.GroupThreadId = GroupThreadID;
    thread.GroupIndex = GroupIndex;
    
    uint group = thread.GroupId.x;
    uint row = (group / params.PartialsPerRow);
    uint partial = (group - (row * params.PartialsPerRow));
    uint begin = (partial * params.ChunkElements);
    uint end = (begin + params.ChunkElements);
    if ((end > params.ElementsPerRow))
    {
        end = params.ElementsPerRow;
    }
    float value = 0.0;
    for (uint element = (begin + thread.GroupIndex); element < end; element += 256u)
    {
        float inputValue = Input[((row * params.InputRowStride) + element)];
        if ((params.StageRole == 2u))
        {
            value = (value + inputValue);
        }
        else
        {
            value = (value + (inputValue * inputValue));
        }
    }
    Shared[thread.GroupIndex] = value;
    GroupMemoryBarrierWithGroupSync();
    uint stride = 128u;
    for (uint round = 0u; round < 8u; round += 1u)
    {
        ReductionLane lane = RmsNormReduce_SelectLane(thread.GroupIndex, stride);
        float reduced;
        ReductionLane __sdslv_match_subject_1 = lane;
        if (__sdslv_match_subject_1.Tag == ReductionLane_Idle)
        {
            reduced = Shared[thread.GroupIndex];
        }
        else if (__sdslv_match_subject_1.Tag == ReductionLane_Active)
        {
            ReductionLane_ActivePayload payload = __sdslv_match_subject_1.Active;
            reduced = (Shared[thread.GroupIndex] + payload.Partner);
        }
        if ((thread.GroupIndex < stride))
        {
            Shared[thread.GroupIndex] = reduced;
        }
        GroupMemoryBarrierWithGroupSync();
        stride = (stride / 2u);
    }
    if ((thread.GroupIndex < 1u))
    {
        if ((params.StageRole == 1u))
        {
            Output[group] = Shared[0u];
        }
        else
        {
            Output[row] = ReciprocalSqrtF32(((Shared[0u] / params.TotalElements) + params.Epsilon));
        }
    }
    return;
}

