// Generated by canonical GoOct SDSL-V via VD-MIR. Do not edit by hand.
// namespace Prometheus.Experimental.Transformer

struct SiluGatePackParams
{
    uint LogicalRows;
    uint LogicalColumns;
    uint InputRowStride;
    uint OutputRows;
    uint OutputColumns;
    uint Mode;
    uint PackedWordCount;
    uint Reserved;
};

[[vk::binding(0, 0)]] StructuredBuffer<float> Gate;
[[vk::binding(2, 0)]] StructuredBuffer<float> Hidden;
[[vk::binding(3, 0)]] RWStructuredBuffer<uint> PackedHidden;
[[vk::binding(1, 0)]] StructuredBuffer<float> Up;

float Silu(float value)
{
    if ((value >= 0.0))
    {
        float __sdslv_inline_hlsl_0;
        {
            // BEGIN INLINE HLSL internal/prometheus/shaders/sdslv/experimental/transformer/silu_gate_pack.sdslv:26
             __sdslv_inline_hlsl_0 = exp(-value); 
            // END INLINE HLSL
        }
        float exponential = __sdslv_inline_hlsl_0;
        return (value / (1.0 + exponential));
    }
    float __sdslv_inline_hlsl_1;
    {
        // BEGIN INLINE HLSL internal/prometheus/shaders/sdslv/experimental/transformer/silu_gate_pack.sdslv:29
         __sdslv_inline_hlsl_1 = exp(value); 
        // END INLINE HLSL
    }
    float exponential = __sdslv_inline_hlsl_1;
    return ((value * exponential) / (1.0 + exponential));
}

float HiddenValue(float gate, float up, float hidden, uint mode)
{
    if ((mode == 1u))
    {
        float __sdslv_operand_2 = Silu(gate);
        return (__sdslv_operand_2 * up);
    }
    return hidden;
}

[[vk::push_constant]] ConstantBuffer<SiluGatePackParams> params;

[numthreads(256, 1, 1)]
void SiluGatePack_CS(uint3 DispatchThreadID : SV_DispatchThreadID)
{
    uint word = DispatchThreadID.x;
    if ((word >= params.PackedWordCount))
    {
        return;
    }
    uint lowIndex = (word * 2u);
    uint highIndex = (lowIndex + 1u);
    uint lowRow = (lowIndex / params.OutputColumns);
    uint lowColumn = (lowIndex - (lowRow * params.OutputColumns));
    float low = 0.0;
    if (((lowRow < params.LogicalRows) && (lowColumn < params.LogicalColumns)))
    {
        uint source = ((lowRow * params.InputRowStride) + lowColumn);
        low = HiddenValue(Gate[source], Up[source], Hidden[source], params.Mode);
    }
    float high = 0.0;
    if ((highIndex < (params.OutputRows * params.OutputColumns)))
    {
        uint highRow = (highIndex / params.OutputColumns);
        uint highColumn = (highIndex - (highRow * params.OutputColumns));
        if (((highRow < params.LogicalRows) && (highColumn < params.LogicalColumns)))
        {
            uint source = ((highRow * params.InputRowStride) + highColumn);
            high = HiddenValue(Gate[source], Up[source], Hidden[source], params.Mode);
        }
    }
    float2 __sdslv_operand_3 = float2(low, high);
    PackedHidden[word] = (f32tof16(__sdslv_operand_3).x | (f32tof16(__sdslv_operand_3).y << 16u));
    return;
}

