// Generated by canonical GoOct SDSL-V via VD-MIR. Do not edit by hand.
// namespace Prometheus.Experimental.Transformer

struct SiluGateParams
{
    uint LogicalRows;
    uint LogicalColumns;
    uint InputRowStride;
    uint OutputRows;
    uint OutputColumns;
    uint Mode;
    uint ElementCount;
    uint Reserved;
};

[[vk::binding(2, 0)]] RWStructuredBuffer<float> ActivatedGate;
[[vk::binding(0, 0)]] StructuredBuffer<float> Gate;
[[vk::binding(3, 0)]] RWStructuredBuffer<float> Hidden;
[[vk::binding(1, 0)]] StructuredBuffer<float> Up;

float Silu(float value)
{
    if ((value >= 0.0))
    {
        float __sdslv_inline_hlsl_0;
        {
            // BEGIN INLINE HLSL internal/prometheus/shaders/sdslv/experimental/transformer/silu_gate.sdslv:26
             __sdslv_inline_hlsl_0 = exp(-value); 
            // END INLINE HLSL
        }
        float exponential = __sdslv_inline_hlsl_0;
        return (value / (1.0 + exponential));
    }
    float __sdslv_inline_hlsl_1;
    {
        // BEGIN INLINE HLSL internal/prometheus/shaders/sdslv/experimental/transformer/silu_gate.sdslv:29
         __sdslv_inline_hlsl_1 = exp(value); 
        // END INLINE HLSL
    }
    float exponential = __sdslv_inline_hlsl_1;
    return ((value * exponential) / (1.0 + exponential));
}

[[vk::push_constant]] ConstantBuffer<SiluGateParams> params;

[numthreads(256, 1, 1)]
void SiluGate_CS(uint3 DispatchThreadID : SV_DispatchThreadID)
{
    uint index = DispatchThreadID.x;
    if ((index >= params.ElementCount))
    {
        return;
    }
    uint row = (index / params.OutputColumns);
    uint column = (index - (row * params.OutputColumns));
    bool active = ((row < params.LogicalRows) && (column < params.LogicalColumns));
    float gateValue = 0.0;
    float upValue = 0.0;
    if (active)
    {
        uint source = ((row * params.InputRowStride) + column);
        gateValue = Gate[source];
        upValue = Up[source];
    }
    if ((params.Mode == 1u))
    {
        ActivatedGate[index] = Silu(gateValue);
        return;
    }
    if ((params.Mode == 2u))
    {
        Hidden[index] = (ActivatedGate[index] * upValue);
        return;
    }
    float __sdslv_operand_2 = Silu(gateValue);
    Hidden[index] = (__sdslv_operand_2 * upValue);
    return;
}

