// Command prometheus_native_manifest renders and verifies the checked-in
// platform build fragments from the canonical native manifest.  It deliberately
// uses only the Go standard library so Windows and Linux builders can validate
// source parity before compiling.
package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

type manifest struct {
	Production []string `json:"production_sources"`
	Tests      []string `json:"native_test_sources"`
	Slow       []string `json:"slow_only_test_sources"`
	Mains      struct {
		Normal     string `json:"normal"`
		Slow       string `json:"slow"`
		Benchmarks string `json:"benchmarks"`
	} `json:"test_mains"`
}

func load(root string) (manifest, error) {
	var m manifest
	b, err := os.ReadFile(filepath.Join(root, "internal", "prometheus", "native", "native_manifest.json"))
	if err != nil { return m, err }
	err = json.Unmarshal(b, &m)
	return m, err
}

func checkUnique(kind string, paths []string) error {
	seen := map[string]bool{}
	for _, p := range paths {
		if seen[p] { return fmt.Errorf("duplicate %s entry: %s", kind, p) }
		seen[p] = true
		if !strings.HasSuffix(p, ".c") && !strings.HasSuffix(p, ".cpp") { return fmt.Errorf("invalid %s extension: %s", kind, p) }
	}
	return nil
}

func validate(root string, m manifest) error {
	if err := checkUnique("production", m.Production); err != nil { return err }
	if err := checkUnique("test", m.Tests); err != nil { return err }
	if err := checkUnique("slow test", m.Slow); err != nil { return err }
	all := append(append(append([]string{}, m.Production...), m.Tests...), m.Slow...)
	for _, main := range []string{m.Mains.Normal, m.Mains.Slow, m.Mains.Benchmarks} {
		if main != "" { all = append(all, main) }
	}
	for _, p := range all {
		if _, err := os.Stat(filepath.Join(root, "internal", "prometheus", "native", filepath.FromSlash(p))); err != nil { return fmt.Errorf("manifest entry missing: %s", p) }
	}
	for _, slow := range m.Slow {
		for _, normal := range m.Tests { if slow == normal { return fmt.Errorf("slow test is also normal: %s", slow) } }
	}
	return nil
}

func qWin(p string) string { return `"%NATIVE_DIR%\` + strings.ReplaceAll(p, "/", `\`) + `"` }
func qSh(p string) string { return `"$NATIVE_DIR/` + p + `"` }

func windows(m manifest) []byte {
	var b strings.Builder
	b.WriteString("@rem Generated by tools/prometheus_native_manifest; do not edit.\r\n")
	write := func(name string, paths []string) {
		fmt.Fprintf(&b, "set \"%s=", name)
		for i, p := range paths { if i > 0 { b.WriteByte(' ') }; b.WriteString(qWin(p)) }
		b.WriteString("\"\r\n")
	}
	write("PROMETHEUS_COMMON_C_SRCS", m.Production)
	objs := make([]string, 0, len(m.Production))
	for _, p := range m.Production { objs = append(objs, `"%OBJ_DIR%\`+strings.TrimSuffix(filepath.Base(p), ".c")+`.obj"`) }
	fmt.Fprintf(&b, "set \"PROMETHEUS_COMMON_OBJS=%s\"\r\n", strings.Join(objs, " "))
	write("PROMETHEUS_MARIONETTE_CPP_SRCS", m.Tests)
	write("PROMETHEUS_MARIONETTE_SLOW_ONLY_SRCS", m.Slow)
	fmt.Fprintf(&b, "set \"PROMETHEUS_MARIONETTE_MAIN=%s\"\r\n", qWin(m.Mains.Normal))
	if m.Mains.Slow == "" { b.WriteString("set \"PROMETHEUS_MARIONETTE_SLOW_MAIN=\"\r\n") } else { fmt.Fprintf(&b, "set \"PROMETHEUS_MARIONETTE_SLOW_MAIN=%s\"\r\n", qWin(m.Mains.Slow)) }
	fmt.Fprintf(&b, "set \"PROMETHEUS_MARIONETTE_BENCH_MAIN=%s\"\r\n", qWin(m.Mains.Benchmarks))
	return []byte(b.String())
}

func shell(m manifest) []byte {
	var b strings.Builder
	b.WriteString("# Generated by tools/prometheus_native_manifest; do not edit.\n")
	write := func(name string, paths []string) {
		fmt.Fprintf(&b, "%s=(\n", name)
		for _, p := range paths { fmt.Fprintf(&b, "  %s\n", qSh(p)) }
		b.WriteString(")\n")
	}
	write("PROMETHEUS_COMMON_C", m.Production)
	write("PROMETHEUS_MARIONETTE_CPP", m.Tests)
	write("PROMETHEUS_MARIONETTE_SLOW_ONLY", m.Slow)
	fmt.Fprintf(&b, "PROMETHEUS_MARIONETTE_MAIN=%s\n", qSh(m.Mains.Normal))
	if m.Mains.Slow == "" { b.WriteString("PROMETHEUS_MARIONETTE_SLOW_MAIN=\n") } else { fmt.Fprintf(&b, "PROMETHEUS_MARIONETTE_SLOW_MAIN=%s\n", qSh(m.Mains.Slow)) }
	fmt.Fprintf(&b, "PROMETHEUS_MARIONETTE_BENCH_MAIN=%s\n", qSh(m.Mains.Benchmarks))
	return []byte(b.String())
}

func main() {
	write := flag.Bool("write", false, "write generated fragments")
	check := flag.Bool("check", false, "verify generated fragments")
	flag.Parse()
	root, err := os.Getwd(); if err != nil { panic(err) }
	m, err := load(root); if err != nil { panic(err) }
	if err := validate(root, m); err != nil { panic(err) }
	files := []struct{ path string; data []byte }{
		{filepath.Join(root, "internal", "prometheus", "native", "native_sources_windows.cmd"), windows(m)},
		{filepath.Join(root, "internal", "prometheus", "native", "native_sources_linux.sh"), shell(m)},
	}
	if !*write && !*check { *check = true }
	for _, f := range files {
		got, readErr := os.ReadFile(f.path)
		if *check && (readErr != nil || !bytes.Equal(got, f.data)) {
			fmt.Fprintf(os.Stderr, "native manifest drift: %s (run: go run ./tools/prometheus_native_manifest -write)\n", f.path)
			os.Exit(1)
		}
		if *write { if err := os.WriteFile(f.path, f.data, 0644); err != nil { panic(err) } }
	}
}
