// Code generated by Veril-Oct. DO NOT EDIT.
// Oct Int hardware policy: signed 64-bit two's-complement; SI dimensions are compile-time only.
// Packed aggregates use declaration order, first field/tag in the least-significant bits.

module UtilityChooser(
    input  logic Clock,
    input  logic Reset,
    input  logic [129:0] Turn_scores,
    output logic Done,
    output logic Suspended,
    output logic Fault,
    output logic [0:0] StateView,
    output logic [2:0] InstructionView,
    output logic signed [63:0] Result,
    output logic YieldValid,
    output logic signed [63:0] YieldValue,
    output logic signed [63:0] Board_Selected
);

typedef enum logic [0:0] {
    State_Decide = 1'd0
} StateT;

StateT State;
StateT NextState;
logic [2:0] Instruction;
logic [2:0] NextInstruction;
logic NextDone;
logic NextSuspended;
logic NextFault;
logic signed [63:0] NextResult;
logic NextYieldValid;
logic signed [63:0] NextYieldValue;
logic signed [63:0] NextBoard_Selected;
logic UtilityComb0Valid;
logic UtilityComb0CurrentStillValid;
logic signed [31:0] UtilityComb0BestArm;
logic signed [63:0] UtilityComb0BestValue;
logic signed [63:0] UtilityComb0BestScore;
logic signed [63:0] UtilityComb0Hysteresis;
logic signed [63:0] UtilityComb0MinCommit;
logic signed [63:0] Local_selected;

assign StateView = State;
assign InstructionView = Instruction;

always_comb begin : oct_flow_next
    integer __oct_dispatch;
    logic __oct_running;
    logic __oct_redispatch;
    NextState = State;
    NextInstruction = Instruction;
    NextDone = Done;
    NextSuspended = 1'b0;
    NextFault = Fault;
    NextResult = Result;
    NextYieldValid = 1'b0;
    NextYieldValue = YieldValue;
    NextBoard_Selected = Board_Selected;
    UtilityComb0Valid = 1'b0;
    UtilityComb0CurrentStillValid = 1'b0;
    UtilityComb0BestArm = -32'sd1;
    UtilityComb0BestValue = '0;
    UtilityComb0BestScore = '0;
    UtilityComb0Hysteresis = '0;
    UtilityComb0MinCommit = '0;
    Local_selected = '0;
    __oct_running = !Done && !Fault;
    __oct_redispatch = 1'b0;
    for (__oct_dispatch = 0; __oct_dispatch < 5; __oct_dispatch = __oct_dispatch + 1) begin : oct_flow_dispatch
        if (__oct_running) begin
            __oct_redispatch = 1'b0;
            case (NextState)
                State_Decide: begin
                    case (NextInstruction)
                    3'd0: begin
                        UtilityComb0Hysteresis = 64'sd0;
                        UtilityComb0MinCommit = 64'sd0;
                        if (Turn_scores[0]) begin
                            if (!UtilityComb0Valid || Turn_scores[65:2] > UtilityComb0BestScore) begin
                                UtilityComb0Valid = 1'b1;
                                UtilityComb0BestArm = 32'sd0;
                                UtilityComb0BestScore = Turn_scores[65:2];
                            end
                        end
                        if (Turn_scores[1]) begin
                            if (!UtilityComb0Valid || Turn_scores[129:66] > UtilityComb0BestScore) begin
                                UtilityComb0Valid = 1'b1;
                                UtilityComb0BestArm = 32'sd1;
                                UtilityComb0BestScore = Turn_scores[129:66];
                            end
                        end
                        if (!UtilityComb0Valid) begin
                            UtilityComb0Valid = 1'b1;
                            UtilityComb0BestArm = -32'sd1;
                            UtilityComb0BestScore = 64'sd0;
                        end
                        case (UtilityComb0BestArm)
                            32'sd0: UtilityComb0BestValue = 64'sd1;
                            32'sd1: UtilityComb0BestValue = 64'sd2;
                            default: UtilityComb0BestValue = 64'sd0;
                        endcase
                        Local_selected = UtilityComb0BestValue;
                        if (__oct_running && !__oct_redispatch) NextInstruction = NextInstruction + 1'b1;
                    end
                    3'd1: begin
                        NextBoard_Selected = Local_selected;
                        if (__oct_running && !__oct_redispatch) NextInstruction = NextInstruction + 1'b1;
                    end
                    3'd2: begin
                        NextYieldValue = Local_selected;
                        NextYieldValid = 1'b1;
                        NextInstruction = NextInstruction + 1'b1;
                        __oct_running = 1'b0;
                        if (__oct_running && !__oct_redispatch) NextInstruction = NextInstruction + 1'b1;
                    end
                    3'd3: begin
                        NextState = State_Decide;
                        NextInstruction = '0;
                        __oct_redispatch = 1'b1;
                        if (__oct_running && !__oct_redispatch) NextInstruction = NextInstruction + 1'b1;
                    end
                    default: begin NextFault = 1'b1; __oct_running = 1'b0; end
                    endcase
                end
                default: begin NextFault = 1'b1; __oct_running = 1'b0; end
            endcase
        end
    end
    if (__oct_running) begin
        NextFault = 1'b1;
        __oct_running = 1'b0;
    end
end

always_ff @(posedge Clock) begin
    if (Reset) begin
        State <= State_Decide;
        Instruction <= '0;
        Done <= 1'b0;
        Suspended <= 1'b0;
        Fault <= 1'b0;
        Result <= '0;
        YieldValid <= 1'b0;
        YieldValue <= '0;
        Board_Selected <= '0;
    end else begin
        State <= NextState;
        Instruction <= NextInstruction;
        Done <= NextDone;
        Suspended <= NextSuspended;
        Fault <= NextFault;
        Result <= NextResult;
        YieldValid <= NextYieldValid;
        YieldValue <= NextYieldValue;
        Board_Selected <= NextBoard_Selected;
    end
end

endmodule
