/* Generated by tools/compiled_model_lock from lock-tagon.octagon. Do not edit. */
#ifndef OCT_ZIMAGE_TURBO_RESOLVED_AUDIT_SCHEDULE_H
#define OCT_ZIMAGE_TURBO_RESOLVED_AUDIT_SCHEDULE_H

#define PROM_ZIMAGE_TURBO_AUDIT_LOCK_ID 0x71ef202b4e34b562ull
#define PROM_ZIMAGE_TURBO_AUDIT_ARENA_BYTES 47186176u
#define PROM_ZIMAGE_TURBO_AUDIT_REQUIRED_BYTES 189696u
#define PROM_ZIMAGE_TURBO_AUDIT_SLACK_BYTES 46996480u
#define PROM_ZIMAGE_TURBO_AUDIT_TRANSIENT_ATTENTION_OFFSET 189440u
#define PROM_ZIMAGE_TURBO_AUDIT_TRANSIENT_ATTENTION_BYTES 256u
#define PROM_ZIMAGE_TURBO_AUDIT_STAGE_COUNT 29u
typedef struct prom_zimage_turbo_audit_schedule_entry { uint64_t authority_identity; uint32_t stage_id; uint32_t capture_policy; uint32_t source_resource; uint32_t layout_kind; uint32_t source_base_element; uint32_t element_count; uint32_t projection_key_offset; uint32_t projection_key_count; uint32_t audit_destination_offset; uint32_t legal_capture_point; uint32_t last_legal_lifetime_point; } prom_zimage_turbo_audit_schedule_entry;
enum { PROM_ZIMAGE_AUDIT_CAPTURE_FULL=1u, PROM_ZIMAGE_AUDIT_CAPTURE_PROJECTION=2u, PROM_ZIMAGE_AUDIT_CAPTURE_SUMMARY=3u, PROM_ZIMAGE_AUDIT_CAPTURE_PROJECTION_AND_SUMMARY=4u };
enum { PROM_ZIMAGE_AUDIT_LAYOUT_VECTOR=1u, PROM_ZIMAGE_AUDIT_LAYOUT_TOKEN_CHANNEL=2u, PROM_ZIMAGE_AUDIT_LAYOUT_FUSED_QKV=3u, PROM_ZIMAGE_AUDIT_LAYOUT_TOKEN_HEAD_CHANNEL=4u, PROM_ZIMAGE_AUDIT_LAYOUT_FFN_HIDDEN=5u };
enum { PROM_ZIMAGE_AUDIT_SOURCE_ADALN=1u, PROM_ZIMAGE_AUDIT_SOURCE_ATTENTION_SCALE=2u, PROM_ZIMAGE_AUDIT_SOURCE_ATTENTION_GATE=3u, PROM_ZIMAGE_AUDIT_SOURCE_MLP_SCALE=4u, PROM_ZIMAGE_AUDIT_SOURCE_MLP_GATE=5u, PROM_ZIMAGE_AUDIT_SOURCE_NORM=6u, PROM_ZIMAGE_AUDIT_SOURCE_MODULATED=7u, PROM_ZIMAGE_AUDIT_SOURCE_QKV=8u, PROM_ZIMAGE_AUDIT_SOURCE_ATTENTION=9u, PROM_ZIMAGE_AUDIT_SOURCE_ATTENTION_PROJECTION=10u, PROM_ZIMAGE_AUDIT_SOURCE_ATTENTION_RESIDUAL=11u, PROM_ZIMAGE_AUDIT_SOURCE_INPUT=12u, PROM_ZIMAGE_AUDIT_SOURCE_W3_DECLARED_VIEWS=13u };
static const uint32_t k_prom_zimage_turbo_audit_projection_keys[] = {
  0u,15359u,7680u,3839u,11519u,0u,3839u,1920u,
  0u,3839u,1920u,0u,3839u,1920u,0u,3839u,
  1920u,0u,3839u,1920u,0u,3839u,1920u,0u,
  3839u,1920u,0u,3839u,1920u,0u,3932159u,1966080u,
  3839u,3928320u,0u,3932159u,1966080u,3839u,3928320u,0u,
  11796479u,5898240u,3932159u,3932160u,7864319u,7864320u,0u,3932159u,
  1966080u,127u,128u,3928320u,0u,3932159u,1966080u,127u,
  128u,3928320u,0u,3932159u,1966080u,127u,128u,3928320u,
  0u,3932159u,1966080u,127u,128u,3928320u,0u,3932159u,
  1966080u,127u,128u,3928320u,0u,3932159u,1966080u,63u,
  64u,127u,128u,3928320u,0u,3932159u,1966080u,63u,
  64u,127u,128u,3928320u,0u,3932159u,1966080u,127u,
  128u,3928320u,0u,3932159u,1966080u,3839u,3928320u,0u,
  3932159u,1966080u,3839u,3928320u,0u,3932159u,1966080u,3839u,
  3928320u,0u,3932159u,1966080u,3839u,3928320u,0u,10485759u,
  5242880u,10239u,10475520u,0u,10485759u,5242880u,10239u,10475520u,
  0u,10485759u,5242880u,10239u,10475520u,0u,3932159u,1966080u,
  3839u,3928320u,0u,3932159u,1966080u,3839u,3928320u,
};
static const prom_zimage_turbo_audit_schedule_entry k_prom_zimage_turbo_audit_schedule[] = {
  {PROM_ZIMAGE_TURBO_AUDIT_LOCK_ID,1u,1u,1u,1u,0u,15360u,0u,5u,0u,1u,2u}, /* timestep_linear: after_adaln -> before_attention_norm */
  {PROM_ZIMAGE_TURBO_AUDIT_LOCK_ID,2u,1u,1u,1u,0u,3840u,5u,3u,61440u,1u,2u}, /* attention_scale_raw: after_adaln -> before_attention_norm */
  {PROM_ZIMAGE_TURBO_AUDIT_LOCK_ID,3u,1u,2u,1u,0u,3840u,8u,3u,76800u,1u,2u}, /* attention_scale_adjusted: after_adaln -> before_attention_norm */
  {PROM_ZIMAGE_TURBO_AUDIT_LOCK_ID,4u,1u,1u,1u,3840u,3840u,11u,3u,92160u,1u,8u}, /* attention_gate_raw: after_adaln -> before_attention_residual */
  {PROM_ZIMAGE_TURBO_AUDIT_LOCK_ID,5u,1u,3u,1u,0u,3840u,14u,3u,107520u,1u,8u}, /* attention_gate_tanh: after_adaln -> before_attention_residual */
  {PROM_ZIMAGE_TURBO_AUDIT_LOCK_ID,6u,1u,1u,1u,7680u,3840u,17u,3u,122880u,1u,9u}, /* mlp_scale_raw: after_adaln -> before_ffn_norm */
  {PROM_ZIMAGE_TURBO_AUDIT_LOCK_ID,7u,1u,4u,1u,0u,3840u,20u,3u,138240u,1u,9u}, /* mlp_scale_adjusted: after_adaln -> before_ffn_norm */
  {PROM_ZIMAGE_TURBO_AUDIT_LOCK_ID,8u,1u,1u,1u,11520u,3840u,23u,3u,153600u,1u,13u}, /* mlp_gate_raw: after_adaln -> before_final_residual */
  {PROM_ZIMAGE_TURBO_AUDIT_LOCK_ID,9u,1u,5u,1u,0u,3840u,26u,3u,168960u,1u,13u}, /* mlp_gate_tanh: after_adaln -> before_final_residual */
  {PROM_ZIMAGE_TURBO_AUDIT_LOCK_ID,10u,4u,6u,2u,0u,3932160u,29u,5u,184320u,2u,3u}, /* attention_norm: after_attention_norm -> before_qkv */
  {PROM_ZIMAGE_TURBO_AUDIT_LOCK_ID,11u,4u,7u,2u,0u,3932160u,34u,5u,184576u,2u,3u}, /* attention_modulated: after_attention_norm -> before_qkv */
  {PROM_ZIMAGE_TURBO_AUDIT_LOCK_ID,12u,4u,8u,3u,0u,11796480u,39u,7u,184832u,3u,4u}, /* qkv: after_qkv -> before_q_rope */
  {PROM_ZIMAGE_TURBO_AUDIT_LOCK_ID,13u,4u,8u,4u,0u,3932160u,46u,6u,185088u,3u,4u}, /* q: after_qkv -> before_q_rope */
  {PROM_ZIMAGE_TURBO_AUDIT_LOCK_ID,14u,4u,8u,4u,3932160u,3932160u,52u,6u,185344u,3u,5u}, /* k: after_qkv -> before_k_rope */
  {PROM_ZIMAGE_TURBO_AUDIT_LOCK_ID,15u,4u,8u,4u,7864320u,3932160u,58u,6u,185600u,3u,6u}, /* v: after_qkv -> before_attention */
  {PROM_ZIMAGE_TURBO_AUDIT_LOCK_ID,16u,4u,6u,4u,0u,3932160u,64u,6u,185856u,4u,4u}, /* q_norm: after_q_norm -> before_q_rope */
  {PROM_ZIMAGE_TURBO_AUDIT_LOCK_ID,17u,4u,6u,4u,0u,3932160u,70u,6u,186112u,5u,5u}, /* k_norm: after_k_norm -> before_k_rope */
  {PROM_ZIMAGE_TURBO_AUDIT_LOCK_ID,18u,4u,8u,4u,0u,3932160u,76u,8u,186368u,4u,6u}, /* q_rope: after_q_rope -> before_attention */
  {PROM_ZIMAGE_TURBO_AUDIT_LOCK_ID,19u,4u,8u,4u,3932160u,3932160u,84u,8u,186624u,5u,6u}, /* k_rope: after_k_rope -> before_attention */
  {PROM_ZIMAGE_TURBO_AUDIT_LOCK_ID,20u,4u,9u,4u,0u,3932160u,92u,6u,186880u,6u,7u}, /* attention_aggregation: after_attention -> before_projection */
  {PROM_ZIMAGE_TURBO_AUDIT_LOCK_ID,21u,4u,10u,2u,0u,3932160u,98u,5u,187136u,7u,8u}, /* attention_projection: after_projection -> before_attention_residual */
  {PROM_ZIMAGE_TURBO_AUDIT_LOCK_ID,22u,4u,11u,2u,0u,3932160u,103u,5u,187392u,8u,9u}, /* attention_residual: after_attention_residual -> before_ffn_norm */
  {PROM_ZIMAGE_TURBO_AUDIT_LOCK_ID,23u,4u,6u,2u,0u,3932160u,108u,5u,187648u,9u,10u}, /* ffn_norm: after_ffn_norm -> before_w1_w3 */
  {PROM_ZIMAGE_TURBO_AUDIT_LOCK_ID,24u,4u,7u,2u,0u,3932160u,113u,5u,187904u,9u,10u}, /* ffn_modulated: after_ffn_norm -> before_w1_w3 */
  {PROM_ZIMAGE_TURBO_AUDIT_LOCK_ID,25u,4u,8u,5u,0u,10485760u,118u,5u,188160u,10u,11u}, /* w1: after_w1_w3 -> before_gate */
  {PROM_ZIMAGE_TURBO_AUDIT_LOCK_ID,26u,4u,13u,5u,0u,10485760u,123u,5u,188416u,10u,11u}, /* w3: after_w1_w3 -> before_gate */
  {PROM_ZIMAGE_TURBO_AUDIT_LOCK_ID,27u,4u,8u,5u,0u,10485760u,128u,5u,188672u,11u,12u}, /* ffn_gated_hidden: after_gate -> before_w2 */
  {PROM_ZIMAGE_TURBO_AUDIT_LOCK_ID,28u,4u,12u,2u,0u,3932160u,133u,5u,188928u,12u,13u}, /* w2: after_w2 -> before_final_residual */
  {PROM_ZIMAGE_TURBO_AUDIT_LOCK_ID,29u,4u,9u,2u,0u,3932160u,138u,5u,189184u,13u,14u}, /* final_output: after_final_residual -> resident_output_replaced */
};
#define PROM_ZIMAGE_TURBO_CONTEXT_AUDIT_ARENA_BYTES 1048576u
#define PROM_ZIMAGE_TURBO_CONTEXT_AUDIT_REQUIRED_BYTES 4352u
#define PROM_ZIMAGE_TURBO_CONTEXT_AUDIT_TRANSIENT_ATTENTION_OFFSET 4096u
#define PROM_ZIMAGE_TURBO_CONTEXT_AUDIT_TRANSIENT_ATTENTION_BYTES 256u
#define PROM_ZIMAGE_TURBO_CONTEXT_AUDIT_STAGE_COUNT 16u
static const uint32_t k_prom_zimage_turbo_context_audit_projection_keys[] = {
  0u,122879u,61440u,3839u,0u,122879u,61440u,3839u,
  0u,368639u,184320u,122879u,122880u,245760u,0u,122879u,
  61440u,127u,128u,0u,122879u,61440u,127u,128u,
  0u,122879u,61440u,63u,64u,127u,128u,0u,
  122879u,61440u,63u,64u,127u,128u,0u,122879u,
  61440u,127u,128u,0u,122879u,61440u,3839u,0u,
  122879u,61440u,3839u,0u,122879u,61440u,3839u,0u,
  327679u,163840u,10239u,0u,327679u,163840u,10239u,0u,
  327679u,163840u,10239u,0u,122879u,61440u,3839u,0u,
  122879u,61440u,3839u,
};
static const prom_zimage_turbo_audit_schedule_entry k_prom_zimage_turbo_context_audit_schedule[] = {
  {PROM_ZIMAGE_TURBO_AUDIT_LOCK_ID,1u,4u,12u,2u,0u,122880u,0u,4u,0u,1u,2u}, /* context_embedding_input */
  {PROM_ZIMAGE_TURBO_AUDIT_LOCK_ID,2u,4u,6u,2u,0u,122880u,4u,4u,256u,2u,3u}, /* attention_norm */
  {PROM_ZIMAGE_TURBO_AUDIT_LOCK_ID,3u,4u,8u,3u,0u,368640u,8u,6u,512u,3u,4u}, /* qkv */
  {PROM_ZIMAGE_TURBO_AUDIT_LOCK_ID,4u,4u,6u,4u,0u,122880u,14u,5u,768u,4u,4u}, /* q_norm */
  {PROM_ZIMAGE_TURBO_AUDIT_LOCK_ID,5u,4u,6u,4u,0u,122880u,19u,5u,1024u,5u,5u}, /* k_norm */
  {PROM_ZIMAGE_TURBO_AUDIT_LOCK_ID,6u,4u,8u,4u,0u,122880u,24u,7u,1280u,4u,6u}, /* q_rope */
  {PROM_ZIMAGE_TURBO_AUDIT_LOCK_ID,7u,4u,8u,4u,122880u,122880u,31u,7u,1536u,5u,6u}, /* k_rope */
  {PROM_ZIMAGE_TURBO_AUDIT_LOCK_ID,8u,4u,9u,4u,0u,122880u,38u,5u,1792u,6u,7u}, /* attention_aggregation */
  {PROM_ZIMAGE_TURBO_AUDIT_LOCK_ID,9u,4u,10u,2u,0u,122880u,43u,4u,2048u,7u,8u}, /* attention_projection */
  {PROM_ZIMAGE_TURBO_AUDIT_LOCK_ID,10u,4u,11u,2u,0u,122880u,47u,4u,2304u,8u,9u}, /* attention_residual */
  {PROM_ZIMAGE_TURBO_AUDIT_LOCK_ID,11u,4u,7u,2u,0u,122880u,51u,4u,2560u,9u,10u}, /* ffn_norm */
  {PROM_ZIMAGE_TURBO_AUDIT_LOCK_ID,12u,4u,8u,5u,0u,327680u,55u,4u,2816u,10u,11u}, /* w1 */
  {PROM_ZIMAGE_TURBO_AUDIT_LOCK_ID,13u,4u,13u,5u,0u,327680u,59u,4u,3072u,10u,11u}, /* w3 */
  {PROM_ZIMAGE_TURBO_AUDIT_LOCK_ID,14u,4u,8u,5u,0u,327680u,63u,4u,3328u,11u,12u}, /* ffn_gated_hidden */
  {PROM_ZIMAGE_TURBO_AUDIT_LOCK_ID,15u,4u,10u,2u,0u,122880u,67u,4u,3584u,12u,13u}, /* w2 */
  {PROM_ZIMAGE_TURBO_AUDIT_LOCK_ID,16u,4u,9u,2u,0u,122880u,71u,4u,3840u,13u,14u}, /* final_output */
};

#endif
