// Package octgen hosts the experimental external Oct-to-Go generation seam.
// It deliberately does not participate in the stable Oct CLI or language API.
package octgen

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/token"
	"io"
	"os"
	"path/filepath"
	"strings"

	"github.com/yuechen-li-dev/oct/internal/interpret"
	"github.com/yuechen-li-dev/oct/internal/project"
	"github.com/yuechen-li-dev/oct/internal/typecheck"
)

const generatedHeader = "// Code generated by OctGen. DO NOT EDIT.\n"

// File is the deliberately small generation model supported by M0. The model
// describes one octxiliary time-dispatch declaration; it is not a Go AST binding
// or a general source-template protocol.
type File struct {
	Package    string
	Operations []Operation
}

// Operation selects one established time-wrapper behavior and its declared
// Octxiliary argument kinds. Mode names are intentionally a closed host-owned
// vocabulary so Oct chooses declarations while Go owns syntax and APIs.
type Operation struct {
	Name          string
	Mode          string
	ArgumentKinds []string
}

// Generate executes a type-checked Oct Generate function and renders its
// bounded result. output must stay beside the generator source; the Oct
// program has no file-system mutation capability.
func Generate(generatorPath, outputPath string) ([]byte, error) {
	if err := validateOutputPath(generatorPath, outputPath); err != nil {
		return nil, err
	}
	value, err := execute(generatorPath)
	if err != nil {
		return nil, err
	}
	return renderGenerated(value, generatorPath)
}

// Write generates and atomically replaces outputPath only after rendering and
// formatting succeed.
func Write(generatorPath, outputPath string) error {
	contents, err := Generate(generatorPath, outputPath)
	if err != nil {
		return err
	}
	return atomicWrite(outputPath, contents)
}

// Check regenerates in memory and reports a stale committed output without
// modifying it.
func Check(generatorPath, outputPath string) error {
	contents, err := Generate(generatorPath, outputPath)
	if err != nil {
		return err
	}
	existing, err := os.ReadFile(outputPath)
	if err != nil {
		if os.IsNotExist(err) {
			return fmt.Errorf("generated Go is missing: %s", outputPath)
		}
		return fmt.Errorf("read generated Go %s: %w", outputPath, err)
	}
	if !bytes.Equal(existing, contents) {
		return fmt.Errorf("generated Go is stale: %s; run octgen generate", outputPath)
	}
	return nil
}

func validateOutputPath(generatorPath, outputPath string) error {
	if filepath.Ext(outputPath) != ".go" {
		return fmt.Errorf("OctGen output must be a .go file: %s", outputPath)
	}
	generatorDir, err := filepath.Abs(filepath.Dir(generatorPath))
	if err != nil {
		return fmt.Errorf("resolve generator directory: %w", err)
	}
	outputAbs, err := filepath.Abs(outputPath)
	if err != nil {
		return fmt.Errorf("resolve output path: %w", err)
	}
	rel, err := filepath.Rel(generatorDir, outputAbs)
	if err != nil || rel == ".." || strings.HasPrefix(rel, ".."+string(filepath.Separator)) || filepath.IsAbs(rel) {
		return fmt.Errorf("OctGen output escapes declared destination %s: %s", generatorDir, outputPath)
	}
	return nil
}

// execute is the reusable staging seam: normal project loading, type checking,
// and the existing interpreter return one typed runtime value to a host model
// decoder. It does not add a second evaluator or generator-only Oct semantics.
func execute(generatorPath string) (interpret.Value, error) {
	program, err := project.Load(generatorPath)
	if err != nil {
		return interpret.Value{}, fmt.Errorf("load OctGen generator %s: %w", generatorPath, err)
	}
	if err := typecheck.CheckProgram(program); err != nil {
		return interpret.Value{}, fmt.Errorf("type-check OctGen generator %s: %w", generatorPath, err)
	}
	value, err := interpret.CallFunctionWithArgsAndOptions(program, program.Entry, "Generate", nil, io.Discard, interpret.ExecuteOptions{})
	if err != nil {
		return interpret.Value{}, fmt.Errorf("interpret OctGen generator %s: %w", generatorPath, err)
	}
	return value, nil
}

func renderGenerated(value interpret.Value, provenance string) ([]byte, error) {
	if value.Kind != interpret.ValueRecord {
		return nil, modelError(provenance, "Generate must return a supported structured record")
	}
	switch value.Record.TypeName {
	case "GeneratedTimeDispatch":
		model, err := decodeFile(value, provenance)
		if err != nil {
			return nil, err
		}
		return render(model)
	case "GeneratedAuditStages":
		model, err := decodeAuditStages(value, provenance)
		if err != nil {
			return nil, err
		}
		return renderAuditStages(model)
	default:
		return nil, modelError(provenance, "unsupported Generate record %q", value.Record.TypeName)
	}
}

func decodeFile(value interpret.Value, provenance string) (File, error) {
	if value.Kind != interpret.ValueRecord || value.Record.TypeName != "GeneratedTimeDispatch" {
		return File{}, modelError(provenance, "Generate must return GeneratedTimeDispatch")
	}
	packageName, err := requiredString(value.Record.Fields, "Package", provenance)
	if err != nil {
		return File{}, err
	}
	if packageName != "main" {
		return File{}, modelError(provenance, "Package must be main for the time-dispatch model, got %q", packageName)
	}
	operationsValue, ok := value.Record.Fields["Operations"]
	if !ok || operationsValue.Kind != interpret.ValueArray {
		return File{}, modelError(provenance, "GeneratedTimeDispatch.Operations must be an array")
	}
	model := File{Package: packageName, Operations: make([]Operation, 0, len(operationsValue.Array))}
	seenNames := map[string]struct{}{}
	for index, operationValue := range operationsValue.Array {
		operation, err := decodeOperation(operationValue, provenance, index)
		if err != nil {
			return File{}, err
		}
		if _, exists := seenNames[operation.Name]; exists {
			return File{}, modelError(provenance, "Operations[%d].Name %q is duplicated", index, operation.Name)
		}
		seenNames[operation.Name] = struct{}{}
		model.Operations = append(model.Operations, operation)
	}
	if len(model.Operations) < 3 {
		return File{}, modelError(provenance, "at least three operations are required, got %d", len(model.Operations))
	}
	return model, nil
}

func decodeOperation(value interpret.Value, provenance string, index int) (Operation, error) {
	if value.Kind != interpret.ValueRecord || value.Record.TypeName != "TimeOperation" {
		return Operation{}, modelError(provenance, "Operations[%d] must be TimeOperation", index)
	}
	name, err := requiredString(value.Record.Fields, "Name", provenance)
	if err != nil {
		return Operation{}, err
	}
	if name == "" {
		return Operation{}, modelError(provenance, "Operations[%d].Name must not be empty", index)
	}
	modeValue, ok := value.Record.Fields["Mode"]
	if !ok || modeValue.Kind != interpret.ValueEnum || modeValue.Enum.TypeName != "TimeMode" {
		return Operation{}, modelError(provenance, "Operations[%d].Mode must be a TimeMode enum", index)
	}
	kindsValue, ok := value.Record.Fields["ArgumentKinds"]
	if !ok || kindsValue.Kind != interpret.ValueArray {
		return Operation{}, modelError(provenance, "Operations[%d].ArgumentKinds must be a String[]", index)
	}
	kinds := make([]string, 0, len(kindsValue.Array))
	for kindIndex, kindValue := range kindsValue.Array {
		if kindValue.Kind != interpret.ValueString {
			return Operation{}, modelError(provenance, "Operations[%d].ArgumentKinds[%d] must be String", index, kindIndex)
		}
		if kindValue.Text != "String" && kindValue.Text != "Int" {
			return Operation{}, modelError(provenance, "Operations[%d].ArgumentKinds[%d] has unsupported kind %q", index, kindIndex, kindValue.Text)
		}
		kinds = append(kinds, kindValue.Text)
	}
	operation := Operation{Name: name, Mode: modeValue.Enum.Variant, ArgumentKinds: kinds}
	if err := validateOperation(operation, provenance, index); err != nil {
		return Operation{}, err
	}
	return operation, nil
}

func requiredString(fields map[string]interpret.Value, name, provenance string) (string, error) {
	value, ok := fields[name]
	if !ok || value.Kind != interpret.ValueString {
		return "", modelError(provenance, "%s must be String", name)
	}
	return value.Text, nil
}

func validateOperation(operation Operation, provenance string, index int) error {
	wantArgs := map[string][]string{
		"NowIso8601":       {},
		"NormalizeIso8601": {"String"},
		"UnixSecondsNow":   {},
		"FormatUnixSecond": {"Int"},
	}
	want, ok := wantArgs[operation.Mode]
	if !ok {
		return modelError(provenance, "Operations[%d].Mode %q is not supported by this M0 host", index, operation.Mode)
	}
	if len(want) != len(operation.ArgumentKinds) {
		return modelError(provenance, "Operations[%d] mode %s requires %d argument kinds, got %d", index, operation.Mode, len(want), len(operation.ArgumentKinds))
	}
	for i := range want {
		if want[i] != operation.ArgumentKinds[i] {
			return modelError(provenance, "Operations[%d] mode %s requires argument kind %s at %d, got %s", index, operation.Mode, want[i], i, operation.ArgumentKinds[i])
		}
	}
	return nil
}

func modelError(provenance, format string, arguments ...any) error {
	return fmt.Errorf("OctGen model %s: %s", provenance, fmt.Sprintf(format, arguments...))
}

func atomicWrite(path string, contents []byte) error {
	directory := filepath.Dir(path)
	if err := os.MkdirAll(directory, 0o755); err != nil {
		return fmt.Errorf("create OctGen output directory %s: %w", directory, err)
	}
	temporary, err := os.CreateTemp(directory, ".octgen-*.tmp")
	if err != nil {
		return fmt.Errorf("create temporary OctGen output: %w", err)
	}
	temporaryName := temporary.Name()
	defer os.Remove(temporaryName)
	if _, err := temporary.Write(contents); err != nil {
		temporary.Close()
		return fmt.Errorf("write temporary OctGen output: %w", err)
	}
	if err := temporary.Chmod(0o644); err != nil {
		temporary.Close()
		return fmt.Errorf("set temporary OctGen output permissions: %w", err)
	}
	if err := temporary.Close(); err != nil {
		return fmt.Errorf("close temporary OctGen output: %w", err)
	}
	if err := os.Rename(temporaryName, path); err != nil {
		return fmt.Errorf("replace generated Go %s: %w", path, err)
	}
	return nil
}

func render(model File) ([]byte, error) {
	decl, err := dispatchDeclaration(model)
	if err != nil {
		return nil, err
	}
	file := &ast.File{
		Name: ast.NewIdent(model.Package),
		Decls: []ast.Decl{&ast.GenDecl{Tok: token.IMPORT, Specs: []ast.Spec{
			&ast.ImportSpec{Path: stringLiteral("fmt")},
			&ast.ImportSpec{Path: stringLiteral("time")},
			&ast.ImportSpec{Path: stringLiteral("github.com/yuechen-li-dev/oct/internal/octxiliary")},
		}}, decl},
	}
	var formatted bytes.Buffer
	if err := format.Node(&formatted, token.NewFileSet(), file); err != nil {
		return nil, fmt.Errorf("format structured Go model: %w", err)
	}
	return append([]byte(generatedHeader), formatted.Bytes()...), nil
}

func dispatchDeclaration(model File) (*ast.FuncDecl, error) {
	cases := make([]ast.Stmt, 0, len(model.Operations)+1)
	for _, operation := range model.Operations {
		clause, err := operationCase(operation)
		if err != nil {
			return nil, err
		}
		cases = append(cases, clause)
	}
	cases = append(cases, &ast.CaseClause{Body: []ast.Stmt{returnErrorf("unknown function %q", selector(ident("req"), "Function"))}})
	return &ast.FuncDecl{
		Name: ast.NewIdent("dispatch"),
		Type: &ast.FuncType{Params: &ast.FieldList{List: []*ast.Field{{
			Names: []*ast.Ident{ast.NewIdent("req")}, Type: selector(ident("octxiliary"), "Request"),
		}}}, Results: &ast.FieldList{List: []*ast.Field{
			{Type: selector(ident("octxiliary"), "Value")},
			{Type: ident("error")},
		}}},
		Body: &ast.BlockStmt{List: []ast.Stmt{
			&ast.IfStmt{Cond: binary(selector(ident("req"), "Family"), token.NEQ, stringLiteral("Time")), Body: &ast.BlockStmt{List: []ast.Stmt{
				returnErrorf("unknown family %q", selector(ident("req"), "Family")),
			}}},
			&ast.IfStmt{Cond: unary(token.NOT, selector(ident("req"), "HasArgs")), Body: &ast.BlockStmt{List: []ast.Stmt{
				returnErrorf("generic args missing"),
			}}},
			&ast.SwitchStmt{Tag: selector(ident("req"), "Function"), Body: &ast.BlockStmt{List: cases}},
		}},
	}, nil
}

func operationCase(operation Operation) (*ast.CaseClause, error) {
	body := []ast.Stmt{expectStatement(operation.ArgumentKinds)}
	switch operation.Mode {
	case "NowIso8601":
		nowUTC := call(selector(call(selector(ident("time"), "Now")), "UTC"))
		body = append(body, returnValue(call(selector(nowUTC, "Format"), selector(ident("time"), "RFC3339"))))
	case "NormalizeIso8601":
		body = append(body,
			&ast.AssignStmt{Lhs: []ast.Expr{ident("parsed"), ident("err")}, Tok: token.DEFINE, Rhs: []ast.Expr{call(ident("parseIso8601"), argumentField(0, "String"))}},
			&ast.IfStmt{Cond: binary(ident("err"), token.NEQ, ident("nil")), Body: &ast.BlockStmt{List: []ast.Stmt{returnEmptyAnd(ident("err"))}}},
			returnValue(call(selector(ident("parsed"), "Format"), selector(ident("time"), "RFC3339"))),
		)
	case "UnixSecondsNow":
		nowUTC := call(selector(call(selector(ident("time"), "Now")), "UTC"))
		body = append(body, returnIntValue(call(ident("int"), call(selector(nowUTC, "Unix")))))
	case "FormatUnixSecond":
		unixTime := call(selector(ident("time"), "Unix"), call(ident("int64"), argumentField(0, "Int")), integerLiteral(0))
		utc := call(selector(unixTime, "UTC"))
		body = append(body, returnValue(call(selector(utc, "Format"), selector(ident("time"), "RFC3339"))))
	default:
		return nil, fmt.Errorf("render unsupported time operation mode %q", operation.Mode)
	}
	return &ast.CaseClause{List: []ast.Expr{stringLiteral(operation.Name)}, Body: body}, nil
}

func expectStatement(kinds []string) ast.Stmt {
	arguments := []ast.Expr{selector(ident("req"), "Args")}
	for _, kind := range kinds {
		arguments = append(arguments, selector(ident("octxiliary"), "Value"+kind))
	}
	return &ast.IfStmt{
		Init: &ast.AssignStmt{Lhs: []ast.Expr{ident("err")}, Tok: token.DEFINE, Rhs: []ast.Expr{call(ident("expect"), arguments...)}},
		Cond: binary(ident("err"), token.NEQ, ident("nil")),
		Body: &ast.BlockStmt{List: []ast.Stmt{returnEmptyAnd(ident("err"))}},
	}
}

func returnErrorf(format string, arguments ...ast.Expr) ast.Stmt {
	return returnEmptyAnd(call(selector(ident("fmt"), "Errorf"), append([]ast.Expr{stringLiteral(format)}, arguments...)...))
}

func returnEmptyAnd(err ast.Expr) ast.Stmt {
	return &ast.ReturnStmt{Results: []ast.Expr{composite(selector(ident("octxiliary"), "Value")), err}}
}

func returnValue(value ast.Expr) ast.Stmt {
	return &ast.ReturnStmt{Results: []ast.Expr{call(ident("stringValue"), value), ident("nil")}}
}

func returnIntValue(value ast.Expr) ast.Stmt {
	return &ast.ReturnStmt{Results: []ast.Expr{call(ident("intValue"), value), ident("nil")}}
}

func argumentField(index int, field string) ast.Expr {
	return selector(&ast.IndexExpr{X: selector(ident("req"), "Args"), Index: integerLiteral(index)}, field)
}

func ident(name string) *ast.Ident { return ast.NewIdent(name) }

func selector(x ast.Expr, name string) *ast.SelectorExpr {
	return &ast.SelectorExpr{X: x, Sel: ident(name)}
}

func call(function ast.Expr, arguments ...ast.Expr) *ast.CallExpr {
	return &ast.CallExpr{Fun: function, Args: arguments}
}

func binary(left ast.Expr, operator token.Token, right ast.Expr) *ast.BinaryExpr {
	return &ast.BinaryExpr{X: left, Op: operator, Y: right}
}

func unary(operator token.Token, expression ast.Expr) *ast.UnaryExpr {
	return &ast.UnaryExpr{Op: operator, X: expression}
}

func composite(typeExpression ast.Expr) *ast.CompositeLit {
	return &ast.CompositeLit{Type: typeExpression}
}

func stringLiteral(value string) *ast.BasicLit {
	return &ast.BasicLit{Kind: token.STRING, Value: fmt.Sprintf("%q", value)}
}

func integerLiteral(value int) *ast.BasicLit {
	return &ast.BasicLit{Kind: token.INT, Value: fmt.Sprintf("%d", value)}
}
