package octgen

import (
	"bytes"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

func timeGenerator(t *testing.T) string {
	t.Helper()
	return copyGenerator(t, filepath.Join("..", "..", "cmd", "octxiliary-time", "time_dispatch.oct"))
}

func auditGenerator(t *testing.T) string {
	t.Helper()
	return copyGenerator(t, filepath.Join("..", "..", "tools", "compiled_model_lock", "audit_stages.oct"))
}

func copyGenerator(t *testing.T, source string) string {
	t.Helper()
	contents, err := os.ReadFile(source)
	if err != nil {
		t.Fatalf("read time generator: %v", err)
	}
	path := filepath.Join(t.TempDir(), "time_dispatch.oct")
	if err := os.WriteFile(path, contents, 0o644); err != nil {
		t.Fatalf("copy time generator: %v", err)
	}
	return path
}

func TestGenerateUsesTypeCheckedInterpreterAndIsDeterministic(t *testing.T) {
	generator := timeGenerator(t)
	output := filepath.Join(filepath.Dir(generator), "..", "escape.generated.go")
	first, err := Generate(generator, output)
	if err == nil {
		t.Fatal("Generate unexpectedly accepted output outside generator directory")
	}
	if !strings.Contains(err.Error(), "escapes declared destination") {
		t.Fatalf("output-boundary error = %v", err)
	}
	if _, statErr := os.Stat(output); !os.IsNotExist(statErr) {
		t.Fatalf("traversal attempt created %s: %v", output, statErr)
	}

	output = filepath.Join(filepath.Dir(generator), "time_dispatch.generated.go")
	first, err = Generate(generator, output)
	if err != nil {
		t.Fatalf("Generate: %v", err)
	}
	second, err := Generate(generator, output)
	if err != nil {
		t.Fatalf("Generate second time: %v", err)
	}
	if !bytes.Equal(first, second) {
		t.Fatal("generation was not byte-for-byte deterministic")
	}
	text := string(first)
	for _, want := range []string{
		"// Code generated by OctGen. DO NOT EDIT.",
		"func dispatch(req octxiliary.Request) (octxiliary.Value, error)",
		"case \"TimeNowIso8601\":",
		"case \"TimeFormatUnixSecond\":",
	} {
		if !strings.Contains(text, want) {
			t.Fatalf("generated Go missing %q:\n%s", want, text)
		}
	}
}

func TestWriteAndCheckDetectStaleOutput(t *testing.T) {
	generator := timeGenerator(t)
	output := filepath.Join(filepath.Dir(generator), "time_dispatch.generated.go")
	if err := Write(generator, output); err != nil {
		t.Fatalf("Write: %v", err)
	}
	if err := Check(generator, output); err != nil {
		t.Fatalf("fresh Check: %v", err)
	}
	if err := os.WriteFile(output, []byte("package main\n"), 0o644); err != nil {
		t.Fatalf("modify output: %v", err)
	}
	if err := Check(generator, output); err == nil || !strings.Contains(err.Error(), "stale") {
		t.Fatalf("stale Check error = %v", err)
	}
}

func TestInvalidOctAndInvalidModelHaveUsefulDiagnostics(t *testing.T) {
	for _, tc := range []struct {
		name      string
		generator string
		want      string
		wantPath  string
	}{
		{"invalid source", filepath.Join("testdata", "invalid_source", "generator.oct"), "type-check OctGen generator", "invalid_source"},
		{"invalid model", filepath.Join("testdata", "invalid_model", "generator.oct"), "Operations[1] mode NormalizeIso8601", "invalid_model"},
		{"invalid compile-time requirement", filepath.Join("testdata", "invalid_requirement", "generator.oct"), "compile-time requirement failed in Generate: time dispatch must declare at least three operations", "invalid_requirement"},
	} {
		t.Run(tc.name, func(t *testing.T) {
			output := filepath.Join(filepath.Dir(tc.generator), "generated.go")
			err := Write(tc.generator, output)
			if err == nil || !strings.Contains(err.Error(), tc.want) || !strings.Contains(err.Error(), tc.wantPath) {
				t.Fatalf("Write error = %v, want %q with provenance %q", err, tc.want, tc.wantPath)
			}
		})
	}
}

func TestOrdinaryGoTestDoesNotRunOctGen(t *testing.T) {
	root := filepath.Join("..", "..")
	generated := filepath.Join(root, "cmd", "octxiliary-time", "time_dispatch.generated.go")
	before, err := os.Stat(generated)
	if err != nil {
		t.Fatalf("stat committed generated source: %v", err)
	}
	command := exec.Command("go", "test", "./cmd/octxiliary-time")
	command.Dir = root
	if output, err := command.CombinedOutput(); err != nil {
		t.Fatalf("ordinary go test: %v\n%s", err, output)
	}
	after, err := os.Stat(generated)
	if err != nil {
		t.Fatalf("restat committed generated source: %v", err)
	}
	if !after.ModTime().Equal(before.ModTime()) || after.Size() != before.Size() {
		t.Fatal("ordinary go test modified generated source; it must not invoke OctGen")
	}
}

func TestAuditStageGenerationComputesDeterministicTablesAndChecksStaleness(t *testing.T) {
	generator := auditGenerator(t)
	output := filepath.Join(filepath.Dir(generator), "audit_stages.generated.go")
	first, err := Generate(generator, output)
	if err != nil {
		t.Fatalf("Generate audit stages: %v", err)
	}
	second, err := Generate(generator, output)
	if err != nil {
		t.Fatalf("Generate audit stages again: %v", err)
	}
	if !bytes.Equal(first, second) {
		t.Fatal("audit-stage generation was not byte-for-byte deterministic")
	}
	for _, want := range []string{"generatedNoiseAuditStages", "generatedContextAuditStages", "ID: 29", "ID: 16", "Count: 11796480"} {
		if !strings.Contains(string(first), want) {
			t.Fatalf("generated audit stages missing %q", want)
		}
	}
	if err := Write(generator, output); err != nil {
		t.Fatalf("Write audit stages: %v", err)
	}
	if err := Check(generator, output); err != nil {
		t.Fatalf("fresh audit-stage Check: %v", err)
	}
	if err := os.WriteFile(output, []byte("package main\n"), 0o644); err != nil {
		t.Fatalf("modify audit-stage output: %v", err)
	}
	if err := Check(generator, output); err == nil || !strings.Contains(err.Error(), "stale") {
		t.Fatalf("stale audit-stage Check error = %v", err)
	}
}

func TestInvalidAuditModelIncludesProvenance(t *testing.T) {
	generator := filepath.Join("testdata", "invalid_audit_model", "generator.oct")
	err := Write(generator, filepath.Join("testdata", "invalid_audit_model", "generated.go"))
	if err == nil || !strings.Contains(err.Error(), "Noise[1].ID must be derived sequentially") || !strings.Contains(err.Error(), "invalid_audit_model") {
		t.Fatalf("invalid audit model error = %v", err)
	}
}
