package main

import (
	"bytes"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestGenerateCheckDeterminismAndStaleDetection(t *testing.T) {
	specimen := filepath.Join("specimen", "controller", "controller.oct")
	input := filepath.Join(t.TempDir(), "controller.oct")
	contents, err := os.ReadFile(specimen)
	if err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(input, contents, 0o644); err != nil {
		t.Fatal(err)
	}
	output := filepath.Join(filepath.Dir(input), "controller.generated.go")
	arguments := []string{"-input", input, "-output", output, "-package", "controller"}
	if err := run(append([]string{"generate"}, arguments...)); err != nil {
		t.Fatal(err)
	}
	first, err := os.ReadFile(output)
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.HasPrefix(first, []byte("// Code generated by Oct's compiled backend. DO NOT EDIT.\npackage controller\n")) {
		t.Fatalf("generated header/package missing:\n%s", first)
	}
	if strings.Contains(string(first), "func main()") {
		t.Fatal("embeddable output contains a standalone main function")
	}
	if err := run(append([]string{"generate"}, arguments...)); err != nil {
		t.Fatal(err)
	}
	second, err := os.ReadFile(output)
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(first, second) {
		t.Fatal("repeated generation was not byte-identical")
	}
	if err := run(append([]string{"check"}, arguments...)); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(output, append(second, []byte("// stale\n")...), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := run(append([]string{"check"}, arguments...)); err == nil || !strings.Contains(err.Error(), "generated Go is stale") {
		t.Fatalf("check after mutation = %v, want stale diagnostic", err)
	}
}
