// Code generated by Veril-Oct. DO NOT EDIT.
// Oct Int hardware policy: signed 64-bit two's-complement; SI dimensions are compile-time only.
// Packed aggregates use declaration order, first field/tag in the least-significant bits.

module Counter(
    input  logic Clock,
    input  logic Reset,
    input  logic signed [63:0] limit,
    input  logic Turn_enable,
    output logic Done,
    output logic Suspended,
    output logic Fault,
    output logic [0:0] StateView,
    output logic [1:0] InstructionView,
    output logic signed [63:0] Result,
    output logic YieldValid,
    output logic signed [63:0] YieldValue,
    output logic signed [63:0] Board_Count,
    output logic Board_Armed
);

typedef enum logic [0:0] {
    State_Count = 1'd0,
    State_Emit = 1'd1
} StateT;

StateT State;
StateT NextState;
logic [1:0] Instruction;
logic [1:0] NextInstruction;
logic NextDone;
logic NextSuspended;
logic NextFault;
logic signed [63:0] NextResult;
logic NextYieldValid;
logic signed [63:0] NextYieldValue;
logic signed [63:0] Param_limit;
logic signed [63:0] NextBoard_Count;
logic NextBoard_Armed;

assign StateView = State;
assign InstructionView = Instruction;

always_comb begin : oct_flow_next
    integer __oct_dispatch;
    logic __oct_running;
    logic __oct_redispatch;
    NextState = State;
    NextInstruction = Instruction;
    NextDone = Done;
    NextSuspended = 1'b0;
    NextFault = Fault;
    NextResult = Result;
    NextYieldValid = 1'b0;
    NextYieldValue = YieldValue;
    NextBoard_Count = Board_Count;
    NextBoard_Armed = Board_Armed;
    __oct_running = !Done && !Fault;
    __oct_redispatch = 1'b0;
    for (__oct_dispatch = 0; __oct_dispatch < 6; __oct_dispatch = __oct_dispatch + 1) begin : oct_flow_dispatch
        if (__oct_running) begin
            __oct_redispatch = 1'b0;
            case (NextState)
                State_Count: begin
                    case (NextInstruction)
                    2'd0: begin
                        NextBoard_Armed = Turn_enable;
                        if (__oct_running && !__oct_redispatch) NextInstruction = NextInstruction + 1'b1;
                    end
                    2'd1: begin
                        if (NextBoard_Armed) begin
                            if (__oct_running && !__oct_redispatch) begin
                                NextBoard_Count = (NextBoard_Count + 64'sd1);
                            end
                        end
                        if (__oct_running && !__oct_redispatch) NextInstruction = NextInstruction + 1'b1;
                    end
                    2'd2: begin
                        if ((NextBoard_Count >= Param_limit)) begin
                            NextResult = NextBoard_Count;
                            NextDone = 1'b1;
                            __oct_running = 1'b0;
                        end else begin
                            NextState = State_Emit;
                            NextInstruction = '0;
                            __oct_redispatch = 1'b1;
                        end
                        if (__oct_running && !__oct_redispatch) NextInstruction = NextInstruction + 1'b1;
                    end
                    default: begin NextFault = 1'b1; __oct_running = 1'b0; end
                    endcase
                end
                State_Emit: begin
                    case (NextInstruction)
                    2'd0: begin
                        NextYieldValue = NextBoard_Count;
                        NextYieldValid = 1'b1;
                        NextInstruction = NextInstruction + 1'b1;
                        __oct_running = 1'b0;
                        if (__oct_running && !__oct_redispatch) NextInstruction = NextInstruction + 1'b1;
                    end
                    2'd1: begin
                        NextState = State_Count;
                        NextInstruction = '0;
                        __oct_redispatch = 1'b1;
                        if (__oct_running && !__oct_redispatch) NextInstruction = NextInstruction + 1'b1;
                    end
                    default: begin NextFault = 1'b1; __oct_running = 1'b0; end
                    endcase
                end
                default: begin NextFault = 1'b1; __oct_running = 1'b0; end
            endcase
        end
    end
    if (__oct_running) begin
        NextFault = 1'b1;
        __oct_running = 1'b0;
    end
end

always_ff @(posedge Clock) begin
    if (Reset) begin
        State <= State_Count;
        Instruction <= '0;
        Done <= 1'b0;
        Suspended <= 1'b0;
        Fault <= 1'b0;
        Result <= '0;
        YieldValid <= 1'b0;
        YieldValue <= '0;
        Param_limit <= limit;
        Board_Count <= '0;
        Board_Armed <= '0;
    end else begin
        State <= NextState;
        Instruction <= NextInstruction;
        Done <= NextDone;
        Suspended <= NextSuspended;
        Fault <= NextFault;
        Result <= NextResult;
        YieldValid <= NextYieldValid;
        YieldValue <= NextYieldValue;
        Board_Count <= NextBoard_Count;
        Board_Armed <= NextBoard_Armed;
    end
end

endmodule

module SumFour(
    input  logic Clock,
    input  logic Reset,
    output logic Done,
    output logic Suspended,
    output logic Fault,
    output logic [0:0] StateView,
    output logic [1:0] InstructionView,
    output logic signed [63:0] Result,
    output logic signed [63:0] Board_Total
);

typedef enum logic [0:0] {
    State_Run = 1'd0
} StateT;

StateT State;
StateT NextState;
logic [1:0] Instruction;
logic [1:0] NextInstruction;
logic NextDone;
logic NextSuspended;
logic NextFault;
logic signed [63:0] NextResult;
logic signed [63:0] NextBoard_Total;
logic signed [63:0] Local_i;

assign StateView = State;
assign InstructionView = Instruction;

always_comb begin : oct_flow_next
    integer __oct_dispatch;
    logic __oct_running;
    logic __oct_redispatch;
    NextState = State;
    NextInstruction = Instruction;
    NextDone = Done;
    NextSuspended = 1'b0;
    NextFault = Fault;
    NextResult = Result;
    NextBoard_Total = Board_Total;
    Local_i = '0;
    __oct_running = !Done && !Fault;
    __oct_redispatch = 1'b0;
    for (__oct_dispatch = 0; __oct_dispatch < 3; __oct_dispatch = __oct_dispatch + 1) begin : oct_flow_dispatch
        if (__oct_running) begin
            __oct_redispatch = 1'b0;
            case (NextState)
                State_Run: begin
                    case (NextInstruction)
                    2'd0: begin
                        for (Local_i = 64'sd0; Local_i < 64'sd4; Local_i = Local_i + 64'sd1) begin
                            if (__oct_running && !__oct_redispatch) begin
                                NextBoard_Total = (NextBoard_Total + Local_i);
                            end
                        end
                        if (__oct_running && !__oct_redispatch) NextInstruction = NextInstruction + 1'b1;
                    end
                    2'd1: begin
                        NextResult = NextBoard_Total;
                        NextDone = 1'b1;
                        __oct_running = 1'b0;
                        if (__oct_running && !__oct_redispatch) NextInstruction = NextInstruction + 1'b1;
                    end
                    default: begin NextFault = 1'b1; __oct_running = 1'b0; end
                    endcase
                end
                default: begin NextFault = 1'b1; __oct_running = 1'b0; end
            endcase
        end
    end
    if (__oct_running) begin
        NextFault = 1'b1;
        __oct_running = 1'b0;
    end
end

always_ff @(posedge Clock) begin
    if (Reset) begin
        State <= State_Run;
        Instruction <= '0;
        Done <= 1'b0;
        Suspended <= 1'b0;
        Fault <= 1'b0;
        Result <= '0;
        Board_Total <= '0;
    end else begin
        State <= NextState;
        Instruction <= NextInstruction;
        Done <= NextDone;
        Suspended <= NextSuspended;
        Fault <= NextFault;
        Result <= NextResult;
        Board_Total <= NextBoard_Total;
    end
end

endmodule

module WaitOnce(
    input  logic Clock,
    input  logic Reset,
    output logic Done,
    output logic Suspended,
    output logic Fault,
    output logic [0:0] StateView,
    output logic [1:0] InstructionView,
    output logic signed [63:0] Result
);

typedef enum logic [0:0] {
    State_Wait = 1'd0
} StateT;

StateT State;
StateT NextState;
logic [1:0] Instruction;
logic [1:0] NextInstruction;
logic NextDone;
logic NextSuspended;
logic NextFault;
logic signed [63:0] NextResult;

assign StateView = State;
assign InstructionView = Instruction;

always_comb begin : oct_flow_next
    integer __oct_dispatch;
    logic __oct_running;
    logic __oct_redispatch;
    NextState = State;
    NextInstruction = Instruction;
    NextDone = Done;
    NextSuspended = 1'b0;
    NextFault = Fault;
    NextResult = Result;
    __oct_running = !Done && !Fault;
    __oct_redispatch = 1'b0;
    for (__oct_dispatch = 0; __oct_dispatch < 3; __oct_dispatch = __oct_dispatch + 1) begin : oct_flow_dispatch
        if (__oct_running) begin
            __oct_redispatch = 1'b0;
            case (NextState)
                State_Wait: begin
                    case (NextInstruction)
                    2'd0: begin
                        NextSuspended = 1'b1;
                        NextInstruction = NextInstruction + 1'b1;
                        __oct_running = 1'b0;
                        if (__oct_running && !__oct_redispatch) NextInstruction = NextInstruction + 1'b1;
                    end
                    2'd1: begin
                        NextResult = 64'sd9;
                        NextDone = 1'b1;
                        __oct_running = 1'b0;
                        if (__oct_running && !__oct_redispatch) NextInstruction = NextInstruction + 1'b1;
                    end
                    default: begin NextFault = 1'b1; __oct_running = 1'b0; end
                    endcase
                end
                default: begin NextFault = 1'b1; __oct_running = 1'b0; end
            endcase
        end
    end
    if (__oct_running) begin
        NextFault = 1'b1;
        __oct_running = 1'b0;
    end
end

always_ff @(posedge Clock) begin
    if (Reset) begin
        State <= State_Wait;
        Instruction <= '0;
        Done <= 1'b0;
        Suspended <= 1'b0;
        Fault <= 1'b0;
        Result <= '0;
    end else begin
        State <= NextState;
        Instruction <= NextInstruction;
        Done <= NextDone;
        Suspended <= NextSuspended;
        Fault <= NextFault;
        Result <= NextResult;
    end
end

endmodule
