// Generated by canonical GoOct SDSL-V via VD-MIR. Do not edit by hand.

struct ComputeThread
{
    [[vk::location(0)]] nointerpolation uint3 DispatchId : TEXCOORD0;
    [[vk::location(1)]] nointerpolation uint3 GroupId : TEXCOORD1;
    [[vk::location(2)]] nointerpolation uint3 GroupThreadId : TEXCOORD2;
    [[vk::location(3)]] nointerpolation uint GroupIndex : TEXCOORD3;
};

[[vk::binding(0, 0)]] StructuredBuffer<float> Input;
[[vk::binding(1, 0)]] RWStructuredBuffer<float> Output;

[numthreads(8, 1, 1)]
void ComputeNoRegression_CS(uint3 DispatchThreadID : SV_DispatchThreadID, uint3 GroupThreadID : SV_GroupThreadID, uint3 GroupID : SV_GroupID, uint GroupIndex : SV_GroupIndex)
{
    ComputeThread thread;
    thread.DispatchId = DispatchThreadID;
    thread.GroupId = GroupID;
    thread.GroupThreadId = GroupThreadID;
    thread.GroupIndex = GroupIndex;
    
    uint index = thread.DispatchId.x;
    Output[index] = Input[index];
    return;
}

