// Generated by canonical GoOct SDSL-V via VD-MIR. Do not edit by hand.
// namespace Sdslv.Conformance.Graphics

// type ObjectPosition3 = float3 @space(object.position)

// type WorldPosition3 = float3 @space(world.position)

// type WorldNormal3 = float3 @space(world.normal)

// type ClipPosition4 = float4 @space(clip.position)

struct Surface
{
    float4 Color;
    float Roughness;
};

struct ForwardTextured_Material
{
    float4 Tint;
    float Roughness;
};

struct VertexInput
{
    [[vk::location(0)]] float3 Position : TEXCOORD0;
    [[vk::location(1)]] float2 UV : TEXCOORD1;
};

struct VertexBuiltins
{
    uint VertexId : SV_VertexID;
    uint InstanceId : SV_InstanceID;
};

struct ForwardVaryings
{
    float4 Position : SV_Position;
    [[vk::location(0)]] float2 UV : TEXCOORD0;
    [[vk::location(1)]] float3 WorldPosition : TEXCOORD1;
};

struct PixelBuiltins
{
    bool FrontFace : SV_IsFrontFace;
};

struct ForwardOutput
{
    float4 Color : SV_Target0;
};

static const int ShadeMode_Textured = 0;
static const int ShadeMode_Tinted = 1;
struct ShadeMode_TintedPayload
{
    float Amount;
};

struct ShadeMode
{
    int Tag;
    ShadeMode_TintedPayload Tinted;
};

ShadeMode __sdslv_make_ShadeMode_Textured()
{
    ShadeMode value;
    value.Tag = ShadeMode_Textured;
    return value;
}

ShadeMode __sdslv_make_ShadeMode_Tinted(float Amount)
{
    ShadeMode value;
    value.Tag = ShadeMode_Tinted;
    value.Tinted.Amount = Amount;
    return value;
}

[[vk::binding(0, 0)]] Texture2D<float4> Albedo;
[[vk::binding(1, 0)]] SamplerState LinearSampler;
[[vk::binding(2, 0)]] ConstantBuffer<ForwardTextured_Material> Material;

float3 EstablishWorld(float3 value)
{
    return float3(value.x, value.y, value.z);
}

float4 EstablishClip(float3 value)
{
    return float4(value.x, value.y, value.z, 1.0);
}

float GraphicsMath(float3 normal, float3 incident)
{
    float3 unitNormal = normalize(normal);
    float3 tangent = cross(unitNormal, incident);
    float3 reflected = reflect(incident, unitNormal);
    float3 blended = lerp(tangent, reflected, 0.5);
    return saturate(dot(blended, unitNormal));
}

ForwardVaryings ForwardTextured_VS(VertexInput input, VertexBuiltins thread)
{
    float3 world = EstablishWorld(input.Position);
    float vertexBias = (float((thread.VertexId + thread.InstanceId)) * 0.000001);
    ForwardVaryings __sdslv_board_0;
    __sdslv_board_0.Position = EstablishClip(input.Position);
    __sdslv_board_0.UV = float2((input.UV.x + vertexBias), input.UV.y);
    __sdslv_board_0.WorldPosition = world;
    return __sdslv_board_0;
}

ForwardOutput ForwardTextured_PS(ForwardVaryings input, PixelBuiltins fragment)
{
    float4 sampled = Albedo.Sample(LinearSampler, input.UV);
    ShadeMode mode = __sdslv_make_ShadeMode_Tinted(0.25);
    float weight;
    ShadeMode __sdslv_match_subject_1 = mode;
    if (__sdslv_match_subject_1.Tag == ShadeMode_Textured)
    {
        weight = 0.0;
    }
    else if (__sdslv_match_subject_1.Tag == ShadeMode_Tinted)
    {
        ShadeMode_TintedPayload payload = __sdslv_match_subject_1.Tinted;
        weight = payload.Amount;
    }
    float3 __sdslv_operand_2 = float3(input.WorldPosition.x, input.WorldPosition.y, input.WorldPosition.z);
    float3 __sdslv_operand_3 = float3(0.0, 0.0, -1.0);
    float geometry = GraphicsMath(__sdslv_operand_2, __sdslv_operand_3);
    float screenFactor = saturate((input.Position.x * 0.0001));
    Surface surface;
    surface.Color = sampled;
    surface.Roughness = Material.Roughness;
    Surface __sdslv_with_4 = surface;
    __sdslv_with_4.Color = lerp(surface.Color, Material.Tint, saturate(((weight + (geometry * 0.01)) + (screenFactor * 0.01))));
    Surface tuned = __sdslv_with_4;
    float4 shaded = tuned.Color;
    {
        if (fragment.FrontFace)
        {
            shaded = saturate(shaded);
        }
    }
    ForwardOutput __sdslv_board_5;
    __sdslv_board_5.Color = shaded;
    return __sdslv_board_5;
}

