// Generated by canonical GoOct SDSL-V via VD-MIR. Do not edit by hand.

// type ClipPosition4 = float4 @space(clip.position)

struct MinimalVertexInput
{
    [[vk::location(0)]] float3 Position : TEXCOORD0;
};

struct MinimalVertexOutput
{
    float4 Position : SV_Position;
};

MinimalVertexOutput MinimalVertexProgram_VS(MinimalVertexInput input)
{
    MinimalVertexOutput __sdslv_board_0;
    __sdslv_board_0.Position = float4(input.Position.x, input.Position.y, input.Position.z, 1.0);
    return __sdslv_board_0;
}

