// Generated by canonical GoOct SDSL-V via VD-MIR. Do not edit by hand.

struct MinimalPixelInput
{
    [[vk::location(0)]] float2 UV : TEXCOORD0;
};

float4 MinimalPixelProgram_PS(MinimalPixelInput input) : SV_Target0
{
    return float4(input.UV.x, input.UV.y, 0.0, 1.0);
}

