// Code generated by Veril-Oct. DO NOT EDIT.
// Oct Int hardware policy: signed 64-bit two's-complement; SI dimensions are compile-time only.
// Packed aggregates use declaration order, first field/tag in the least-significant bits.

module AddEdge(
    input  logic signed [63:0] left,
    input  logic signed [63:0] right,
    output logic signed [63:0] Result
);

logic signed [63:0] __oct_internal_tmp_0;

always_comb begin
    logic __oct_active_entry;
    Result = '0;
    __oct_internal_tmp_0 = '0;
    __oct_active_entry = 1'b0;
    __oct_active_entry = 1'b1;
    if (__oct_active_entry) begin : oct_block_entry
        __oct_internal_tmp_0 = (left + right);
        Result = __oct_internal_tmp_0;
    end
end

endmodule

module Apply(
    input  logic signed [63:0] a,
    input  logic signed [63:0] b,
    input  logic [65:0] operation,
    output logic signed [63:0] Result
);

logic __oct_internal_tmp_0;
logic signed [63:0] __oct_internal_tmp_1;
logic signed [63:0] __oct_internal_tmp_2;
logic __oct_internal_tmp_3;
logic signed [63:0] __oct_internal_tmp_4;
logic __oct_internal_tmp_5;
logic signed [63:0] __oct_internal_tmp_6;
logic signed [63:0] scale;

always_comb begin
    logic __oct_active_entry;
    logic __oct_active_b1;
    logic __oct_active_b2;
    logic __oct_active_b3;
    logic __oct_active_b4;
    logic __oct_active_b5;
    logic __oct_active_b6;
    logic __oct_active_b7;
    Result = '0;
    __oct_internal_tmp_0 = '0;
    __oct_internal_tmp_1 = '0;
    __oct_internal_tmp_2 = '0;
    __oct_internal_tmp_3 = '0;
    __oct_internal_tmp_4 = '0;
    __oct_internal_tmp_5 = '0;
    __oct_internal_tmp_6 = '0;
    scale = '0;
    __oct_active_entry = 1'b0;
    __oct_active_b1 = 1'b0;
    __oct_active_b2 = 1'b0;
    __oct_active_b3 = 1'b0;
    __oct_active_b4 = 1'b0;
    __oct_active_b5 = 1'b0;
    __oct_active_b6 = 1'b0;
    __oct_active_b7 = 1'b0;
    __oct_active_entry = 1'b1;
    if (__oct_active_entry) begin : oct_block_entry
        __oct_internal_tmp_0 = (operation[1:0] == 2'd0);
        if (__oct_internal_tmp_0) __oct_active_b2 = 1'b1;
        else __oct_active_b3 = 1'b1;
    end
    if (__oct_active_b2) begin : oct_block_b2
        __oct_internal_tmp_1 = (a + b);
        __oct_internal_tmp_2 = __oct_internal_tmp_1;
        __oct_active_b1 = 1'b1;
    end
    if (__oct_active_b3) begin : oct_block_b3
        __oct_internal_tmp_3 = (operation[1:0] == 2'd1);
        if (__oct_internal_tmp_3) __oct_active_b4 = 1'b1;
        else __oct_active_b5 = 1'b1;
    end
    if (__oct_active_b4) begin : oct_block_b4
        __oct_internal_tmp_4 = (a - b);
        __oct_internal_tmp_2 = __oct_internal_tmp_4;
        __oct_active_b1 = 1'b1;
    end
    if (__oct_active_b5) begin : oct_block_b5
        __oct_internal_tmp_5 = (operation[1:0] == 2'd2);
        if (__oct_internal_tmp_5) __oct_active_b6 = 1'b1;
        else __oct_active_b7 = 1'b1;
    end
    if (__oct_active_b6) begin : oct_block_b6
        scale = operation[65:2];
        __oct_internal_tmp_6 = (a * scale);
        __oct_internal_tmp_2 = __oct_internal_tmp_6;
        __oct_active_b1 = 1'b1;
    end
    if (__oct_active_b1) begin : oct_block_b1
        Result = __oct_internal_tmp_2;
    end
    if (__oct_active_b7) begin : oct_block_b7
    end
end

endmodule

module Clamp(
    input  logic signed [63:0] value,
    input  logic signed [63:0] limit,
    output logic signed [63:0] Result
);

logic __oct_internal_tmp_0;
logic signed [63:0] __oct_internal_tmp_1;
logic __oct_internal_tmp_2;
logic signed [63:0] __oct_internal_tmp_3;

always_comb begin
    logic __oct_active_entry;
    logic __oct_active_b1;
    logic __oct_active_b2;
    logic __oct_active_b3;
    logic __oct_active_b4;
    logic __oct_active_b5;
    logic __oct_active_b6;
    Result = '0;
    __oct_internal_tmp_0 = '0;
    __oct_internal_tmp_1 = '0;
    __oct_internal_tmp_2 = '0;
    __oct_internal_tmp_3 = '0;
    __oct_active_entry = 1'b0;
    __oct_active_b1 = 1'b0;
    __oct_active_b2 = 1'b0;
    __oct_active_b3 = 1'b0;
    __oct_active_b4 = 1'b0;
    __oct_active_b5 = 1'b0;
    __oct_active_b6 = 1'b0;
    __oct_active_entry = 1'b1;
    if (__oct_active_entry) begin : oct_block_entry
        __oct_internal_tmp_0 = (value > limit);
        if (__oct_internal_tmp_0) __oct_active_b1 = 1'b1;
        else __oct_active_b2 = 1'b1;
    end
    if (__oct_active_b1) begin : oct_block_b1
        Result = limit;
    end
    if (__oct_active_b2) begin : oct_block_b2
        __oct_active_b3 = 1'b1;
    end
    if (__oct_active_b3) begin : oct_block_b3
        __oct_internal_tmp_1 = (-limit);
        __oct_internal_tmp_2 = (value < __oct_internal_tmp_1);
        if (__oct_internal_tmp_2) __oct_active_b4 = 1'b1;
        else __oct_active_b5 = 1'b1;
    end
    if (__oct_active_b4) begin : oct_block_b4
        __oct_internal_tmp_3 = (-limit);
        Result = __oct_internal_tmp_3;
    end
    if (__oct_active_b5) begin : oct_block_b5
        __oct_active_b6 = 1'b1;
    end
    if (__oct_active_b6) begin : oct_block_b6
        Result = value;
    end
end

endmodule

module ConceptDistanceWithinLimit(
    input  logic signed [63:0] value,
    input  logic signed [63:0] limit,
    output logic Result
);

logic __oct_internal_tmp_0;

always_comb begin
    logic __oct_active_entry;
    Result = '0;
    __oct_internal_tmp_0 = '0;
    __oct_active_entry = 1'b0;
    __oct_active_entry = 1'b1;
    if (__oct_active_entry) begin : oct_block_entry
        __oct_internal_tmp_0 = (value <= limit);
        Result = __oct_internal_tmp_0;
    end
end

endmodule

module DistanceWithinLimit(
    input  logic signed [63:0] distance,
    input  logic signed [63:0] limit,
    output logic Result
);

logic __oct_internal_tmp_0;

always_comb begin
    logic __oct_active_entry;
    Result = '0;
    __oct_internal_tmp_0 = '0;
    __oct_active_entry = 1'b0;
    __oct_active_entry = 1'b1;
    if (__oct_active_entry) begin : oct_block_entry
        __oct_internal_tmp_0 = (distance <= limit);
        Result = __oct_internal_tmp_0;
    end
end

endmodule

module LessEdge(
    input  logic signed [63:0] left,
    input  logic signed [63:0] right,
    output logic Result
);

logic __oct_internal_tmp_0;

always_comb begin
    logic __oct_active_entry;
    Result = '0;
    __oct_internal_tmp_0 = '0;
    __oct_active_entry = 1'b0;
    __oct_active_entry = 1'b1;
    if (__oct_active_entry) begin : oct_block_entry
        __oct_internal_tmp_0 = (left < right);
        Result = __oct_internal_tmp_0;
    end
end

endmodule

module Maximum(
    input  logic signed [63:0] left,
    input  logic signed [63:0] right,
    output logic signed [63:0] Result
);

logic __oct_internal_tmp_0;

always_comb begin
    logic __oct_active_entry;
    logic __oct_active_b1;
    logic __oct_active_b2;
    Result = '0;
    __oct_internal_tmp_0 = '0;
    __oct_active_entry = 1'b0;
    __oct_active_b1 = 1'b0;
    __oct_active_b2 = 1'b0;
    __oct_active_entry = 1'b1;
    if (__oct_active_entry) begin : oct_block_entry
        __oct_internal_tmp_0 = (left > right);
        if (__oct_internal_tmp_0) __oct_active_b1 = 1'b1;
        else __oct_active_b2 = 1'b1;
    end
    if (__oct_active_b1) begin : oct_block_b1
        Result = left;
    end
    if (__oct_active_b2) begin : oct_block_b2
        Result = right;
    end
end

endmodule

module MoveAndClamp(
    input  logic [127:0] point,
    input  logic signed [63:0] delta,
    input  logic signed [63:0] limit,
    output logic [127:0] Result
);

function automatic logic signed [63:0] oct_fn_Main__Clamp(input logic signed [63:0] value, input logic signed [63:0] limit);
    logic __oct_internal_tmp_0;
    logic signed [63:0] __oct_internal_tmp_1;
    logic __oct_internal_tmp_2;
    logic signed [63:0] __oct_internal_tmp_3;
    logic __oct_active_entry;
    logic __oct_active_b1;
    logic __oct_active_b2;
    logic __oct_active_b3;
    logic __oct_active_b4;
    logic __oct_active_b5;
    logic __oct_active_b6;
    oct_fn_Main__Clamp = '0;
    __oct_internal_tmp_0 = '0;
    __oct_internal_tmp_1 = '0;
    __oct_internal_tmp_2 = '0;
    __oct_internal_tmp_3 = '0;
    __oct_active_entry = 1'b0;
    __oct_active_b1 = 1'b0;
    __oct_active_b2 = 1'b0;
    __oct_active_b3 = 1'b0;
    __oct_active_b4 = 1'b0;
    __oct_active_b5 = 1'b0;
    __oct_active_b6 = 1'b0;
    __oct_active_entry = 1'b1;
    if (__oct_active_entry) begin : oct_block_entry
        __oct_internal_tmp_0 = (value > limit);
        if (__oct_internal_tmp_0) __oct_active_b1 = 1'b1;
        else __oct_active_b2 = 1'b1;
    end
    if (__oct_active_b1) begin : oct_block_b1
        oct_fn_Main__Clamp = limit;
    end
    if (__oct_active_b2) begin : oct_block_b2
        __oct_active_b3 = 1'b1;
    end
    if (__oct_active_b3) begin : oct_block_b3
        __oct_internal_tmp_1 = (-limit);
        __oct_internal_tmp_2 = (value < __oct_internal_tmp_1);
        if (__oct_internal_tmp_2) __oct_active_b4 = 1'b1;
        else __oct_active_b5 = 1'b1;
    end
    if (__oct_active_b4) begin : oct_block_b4
        __oct_internal_tmp_3 = (-limit);
        oct_fn_Main__Clamp = __oct_internal_tmp_3;
    end
    if (__oct_active_b5) begin : oct_block_b5
        __oct_active_b6 = 1'b1;
    end
    if (__oct_active_b6) begin : oct_block_b6
        oct_fn_Main__Clamp = value;
    end
endfunction

logic signed [63:0] __oct_internal_tmp_0;
logic signed [63:0] __oct_internal_tmp_1;
logic [127:0] __oct_internal_tmp_2;
logic signed [63:0] __oct_internal_tmp_3;
logic signed [63:0] __oct_internal_tmp_4;
logic signed [63:0] __oct_internal_tmp_5;
logic [127:0] __oct_internal_tmp_6;
logic [127:0] moved;

always_comb begin
    logic __oct_active_entry;
    Result = '0;
    __oct_internal_tmp_0 = '0;
    __oct_internal_tmp_1 = '0;
    __oct_internal_tmp_2 = '0;
    __oct_internal_tmp_3 = '0;
    __oct_internal_tmp_4 = '0;
    __oct_internal_tmp_5 = '0;
    __oct_internal_tmp_6 = '0;
    moved = '0;
    __oct_active_entry = 1'b0;
    __oct_active_entry = 1'b1;
    if (__oct_active_entry) begin : oct_block_entry
        __oct_internal_tmp_0 = point[63:0];
        __oct_internal_tmp_1 = (__oct_internal_tmp_0 + delta);
        __oct_internal_tmp_2 = {point[127:64], __oct_internal_tmp_1};
        moved = __oct_internal_tmp_2;
        __oct_internal_tmp_3 = moved[63:0];
        __oct_internal_tmp_4 = oct_fn_Main__Clamp(__oct_internal_tmp_3, limit);
        __oct_internal_tmp_5 = moved[127:64];
        __oct_internal_tmp_6 = {__oct_internal_tmp_5, __oct_internal_tmp_4};
        Result = __oct_internal_tmp_6;
    end
end

endmodule

module MultiplyEdge(
    input  logic signed [63:0] left,
    input  logic signed [63:0] right,
    output logic signed [63:0] Result
);

logic signed [63:0] __oct_internal_tmp_0;

always_comb begin
    logic __oct_active_entry;
    Result = '0;
    __oct_internal_tmp_0 = '0;
    __oct_active_entry = 1'b0;
    __oct_active_entry = 1'b1;
    if (__oct_active_entry) begin : oct_block_entry
        __oct_internal_tmp_0 = (left * right);
        Result = __oct_internal_tmp_0;
    end
end

endmodule

module NegateEdge(
    input  logic signed [63:0] value,
    output logic signed [63:0] Result
);

logic signed [63:0] __oct_internal_tmp_0;

always_comb begin
    logic __oct_active_entry;
    Result = '0;
    __oct_internal_tmp_0 = '0;
    __oct_active_entry = 1'b0;
    __oct_active_entry = 1'b1;
    if (__oct_active_entry) begin : oct_block_entry
        __oct_internal_tmp_0 = (-value);
        Result = __oct_internal_tmp_0;
    end
end

endmodule

module ReservedNames(
    input  logic signed [63:0] oct_wire,
    input  logic signed [63:0] oct_logic,
    output logic signed [63:0] Result
);

logic signed [63:0] __oct_internal_tmp_0;

always_comb begin
    logic __oct_active_entry;
    Result = '0;
    __oct_internal_tmp_0 = '0;
    __oct_active_entry = 1'b0;
    __oct_active_entry = 1'b1;
    if (__oct_active_entry) begin : oct_block_entry
        __oct_internal_tmp_0 = (oct_wire + oct_logic);
        Result = __oct_internal_tmp_0;
    end
end

endmodule

module ShiftSegmentStart(
    input  logic [255:0] segment,
    input  logic signed [63:0] delta,
    output logic [255:0] Result
);

logic [127:0] __oct_internal_tmp_0;
logic [127:0] __oct_internal_tmp_1;
logic signed [63:0] __oct_internal_tmp_2;
logic signed [63:0] __oct_internal_tmp_3;
logic [127:0] __oct_internal_tmp_4;
logic [255:0] __oct_internal_tmp_5;

always_comb begin
    logic __oct_active_entry;
    Result = '0;
    __oct_internal_tmp_0 = '0;
    __oct_internal_tmp_1 = '0;
    __oct_internal_tmp_2 = '0;
    __oct_internal_tmp_3 = '0;
    __oct_internal_tmp_4 = '0;
    __oct_internal_tmp_5 = '0;
    __oct_active_entry = 1'b0;
    __oct_active_entry = 1'b1;
    if (__oct_active_entry) begin : oct_block_entry
        __oct_internal_tmp_0 = segment[127:0];
        __oct_internal_tmp_1 = segment[127:0];
        __oct_internal_tmp_2 = __oct_internal_tmp_1[63:0];
        __oct_internal_tmp_3 = (__oct_internal_tmp_2 + delta);
        __oct_internal_tmp_4 = {__oct_internal_tmp_0[127:64], __oct_internal_tmp_3};
        __oct_internal_tmp_5 = {segment[255:128], __oct_internal_tmp_4};
        Result = __oct_internal_tmp_5;
    end
end

endmodule

module SubtractEdge(
    input  logic signed [63:0] left,
    input  logic signed [63:0] right,
    output logic signed [63:0] Result
);

logic signed [63:0] __oct_internal_tmp_0;

always_comb begin
    logic __oct_active_entry;
    Result = '0;
    __oct_internal_tmp_0 = '0;
    __oct_active_entry = 1'b0;
    __oct_active_entry = 1'b1;
    if (__oct_active_entry) begin : oct_block_entry
        __oct_internal_tmp_0 = (left - right);
        Result = __oct_internal_tmp_0;
    end
end

endmodule

module SumEight(
    output logic signed [63:0] Result
);

logic signed [63:0] __oct_internal_tmp_0;
logic signed [63:0] __oct_internal_tmp_1;
logic signed [63:0] __oct_internal_tmp_2;
logic signed [63:0] __oct_internal_tmp_3;
logic signed [63:0] sum;
logic signed [63:0] i;

always_comb begin
    logic __oct_active_entry;
    logic __oct_active_b1;
    logic __oct_active_b2;
    logic __oct_active_b3;
    logic __oct_active_b4;
    logic __oct_active_b5;
    logic __oct_active_b6;
    Result = '0;
    __oct_internal_tmp_0 = '0;
    __oct_internal_tmp_1 = '0;
    __oct_internal_tmp_2 = '0;
    __oct_internal_tmp_3 = '0;
    sum = '0;
    i = '0;
    __oct_active_entry = 1'b0;
    __oct_active_b1 = 1'b0;
    __oct_active_b2 = 1'b0;
    __oct_active_b3 = 1'b0;
    __oct_active_b4 = 1'b0;
    __oct_active_b5 = 1'b0;
    __oct_active_b6 = 1'b0;
    __oct_active_entry = 1'b1;
    if (__oct_active_entry) begin : oct_block_entry
        sum = 64'sd0;
        __oct_internal_tmp_0 = 64'sd0;
        __oct_internal_tmp_1 = 64'sd8;
        __oct_internal_tmp_2 = 64'sd1;
        __oct_active_b1 = 1'b1;
    end
    if (__oct_active_b1) begin : oct_block_b1
        i = __oct_internal_tmp_0;
        if ((__oct_internal_tmp_0 <= __oct_internal_tmp_1)) __oct_active_b2 = 1'b1;
        else __oct_active_b6 = 1'b1;
    end
    if (__oct_active_b2) begin : oct_block_b2
        for (i = 64'sd0; i < 64'sd8; i = i + 64'sd1) begin : oct_static_loop_b2
            __oct_internal_tmp_3 = (sum + i);
            sum = __oct_internal_tmp_3;
        end
        __oct_active_b5 = 1'b1;
    end
    if (__oct_active_b5) begin : oct_block_b5
        Result = sum;
    end
    if (__oct_active_b6) begin : oct_block_b6
    end
end

endmodule
