// Code generated by Veril-Oct. DO NOT EDIT.
// Oct Int hardware policy: signed 64-bit two's-complement; SI dimensions are compile-time only.
// Packed aggregates use declaration order, first field/tag in the least-significant bits.

module Interruptible(
    input  logic Clock,
    input  logic Reset,
    input  logic Turn_divert,
    output logic Done,
    output logic Suspended,
    output logic Fault,
    output logic [1:0] StateView,
    output logic [1:0] InstructionView,
    output logic signed [63:0] Result,
    output logic YieldValid,
    output logic signed [63:0] YieldValue,
    output logic HasResumeTarget,
    output logic [1:0] ResumeStateView
);

typedef enum logic [1:0] {
    State_Work = 2'd0,
    State_EmitWork = 2'd1,
    State_Detour = 2'd2
} StateT;

StateT State;
StateT NextState;
logic [1:0] Instruction;
logic [1:0] NextInstruction;
logic NextDone;
logic NextSuspended;
logic NextFault;
logic signed [63:0] NextResult;
logic NextYieldValid;
logic signed [63:0] NextYieldValue;
logic NextHasResumeTarget;
StateT ResumeState;
StateT NextResumeState;

assign StateView = State;
assign InstructionView = Instruction;
assign ResumeStateView = ResumeState;

always_comb begin : oct_flow_next
    integer __oct_dispatch;
    logic __oct_running;
    logic __oct_redispatch;
    NextState = State;
    NextInstruction = Instruction;
    NextDone = Done;
    NextSuspended = 1'b0;
    NextFault = Fault;
    NextResult = Result;
    NextYieldValid = 1'b0;
    NextYieldValue = YieldValue;
    NextHasResumeTarget = HasResumeTarget;
    NextResumeState = ResumeState;
    __oct_running = !Done && !Fault;
    __oct_redispatch = 1'b0;
    for (__oct_dispatch = 0; __oct_dispatch < 6; __oct_dispatch = __oct_dispatch + 1) begin : oct_flow_dispatch
        if (__oct_running) begin
            __oct_redispatch = 1'b0;
            case (NextState)
                State_Work: begin
                    case (NextInstruction)
                    2'd0: begin
                        if (Turn_divert) begin
                            if (__oct_running && !__oct_redispatch) begin
                                NextHasResumeTarget = 1'b1;
                                NextResumeState = NextState;
                            end
                            if (__oct_running && !__oct_redispatch) begin
                                NextState = State_Detour;
                                NextInstruction = '0;
                                __oct_redispatch = 1'b1;
                            end
                        end else begin
                            NextState = State_EmitWork;
                            NextInstruction = '0;
                            __oct_redispatch = 1'b1;
                        end
                        if (__oct_running && !__oct_redispatch) NextInstruction = NextInstruction + 1'b1;
                    end
                    default: begin NextFault = 1'b1; __oct_running = 1'b0; end
                    endcase
                end
                State_EmitWork: begin
                    case (NextInstruction)
                    2'd0: begin
                        NextYieldValue = 64'sd1;
                        NextYieldValid = 1'b1;
                        NextInstruction = NextInstruction + 1'b1;
                        __oct_running = 1'b0;
                        if (__oct_running && !__oct_redispatch) NextInstruction = NextInstruction + 1'b1;
                    end
                    2'd1: begin
                        NextState = State_Work;
                        NextInstruction = '0;
                        __oct_redispatch = 1'b1;
                        if (__oct_running && !__oct_redispatch) NextInstruction = NextInstruction + 1'b1;
                    end
                    default: begin NextFault = 1'b1; __oct_running = 1'b0; end
                    endcase
                end
                State_Detour: begin
                    case (NextInstruction)
                    2'd0: begin
                        NextYieldValue = 64'sd2;
                        NextYieldValid = 1'b1;
                        NextInstruction = NextInstruction + 1'b1;
                        __oct_running = 1'b0;
                        if (__oct_running && !__oct_redispatch) NextInstruction = NextInstruction + 1'b1;
                    end
                    2'd1: begin
                        if (!NextHasResumeTarget) begin
                            NextFault = 1'b1;
                            __oct_running = 1'b0;
                         end else begin
                            NextState = NextResumeState;
                            NextInstruction = '0;
                            NextHasResumeTarget = 1'b0;
                            NextResumeState = State_Work;
                            __oct_redispatch = 1'b1;
                        end
                        if (__oct_running && !__oct_redispatch) NextInstruction = NextInstruction + 1'b1;
                    end
                    default: begin NextFault = 1'b1; __oct_running = 1'b0; end
                    endcase
                end
                default: begin NextFault = 1'b1; __oct_running = 1'b0; end
            endcase
        end
    end
    if (__oct_running) begin
        NextFault = 1'b1;
        __oct_running = 1'b0;
    end
end

always_ff @(posedge Clock) begin
    if (Reset) begin
        State <= State_Work;
        Instruction <= '0;
        Done <= 1'b0;
        Suspended <= 1'b0;
        Fault <= 1'b0;
        Result <= '0;
        YieldValid <= 1'b0;
        YieldValue <= '0;
        HasResumeTarget <= 1'b0;
        ResumeState <= State_Work;
    end else begin
        State <= NextState;
        Instruction <= NextInstruction;
        Done <= NextDone;
        Suspended <= NextSuspended;
        Fault <= NextFault;
        Result <= NextResult;
        YieldValid <= NextYieldValid;
        YieldValue <= NextYieldValue;
        HasResumeTarget <= NextHasResumeTarget;
        ResumeState <= NextResumeState;
    end
end

endmodule
