// Generated by canonical GoOct SDSL-V via VD-MIR. Do not edit by hand.

struct GBufferInput
{
    [[vk::location(0)]] float4 Value : TEXCOORD0;
};

struct GBufferOutput
{
    float4 Color : SV_Target0;
    float4 Normal : SV_Target1;
};

GBufferOutput GBufferProgram_PS(GBufferInput input)
{
    GBufferOutput __sdslv_board_0;
    __sdslv_board_0.Color = input.Value;
    __sdslv_board_0.Normal = float4(0.0, 0.0, 1.0, 0.0);
    return __sdslv_board_0;
}

