package octgo

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"sort"
	"strings"

	"github.com/yuechen-li-dev/oct/internal/project"
)

const bridgeHeader = "// Code generated by oct check --generate. DO NOT EDIT.\n"

type TestSession struct {
	WrapperPath string
	Wrappers    []project.WrapperMetadata
	cleanup     func()
}

func (s *TestSession) Close() {
	if s != nil && s.cleanup != nil {
		s.cleanup()
		s.cleanup = nil
	}
}

func PrepareTest(path string) (*TestSession, error) {
	report, err := Check(path, false)
	if err != nil {
		return nil, err
	}
	if report.BridgePath == "" {
		return &TestSession{Wrappers: append([]project.WrapperMetadata(nil), report.wrappers...)}, nil
	}
	tmp, err := os.MkdirTemp("", "octgo-sidecar-*")
	if err != nil {
		return nil, fmt.Errorf("create OCTGO sidecar scope: %w", err)
	}
	cleanup := func() { _ = os.RemoveAll(tmp) }
	binary := filepath.Join(tmp, sidecarCommand(report.Package.Name))
	if runtime.GOOS == "windows" {
		binary += ".exe"
	}
	directory, dirErr := contractDirectory(path)
	if dirErr != nil {
		cleanup()
		return nil, dirErr
	}
	command := bridgeBuildCommand(directory, binary)
	var stderr bytes.Buffer
	command.Stderr = &stderr
	if err := command.Run(); err != nil {
		cleanup()
		return nil, fmt.Errorf("build OCTGO static adapter: %w: %s", err, strings.TrimSpace(stderr.String()))
	}
	return &TestSession{WrapperPath: tmp, Wrappers: append([]project.WrapperMetadata(nil), report.wrappers...), cleanup: cleanup}, nil
}

func bridgeBuildCommand(directory, binary string) *exec.Cmd {
	target := "./octgo_bridge"
	commandDirectory := directory
	bridgeDirectory := filepath.Join(directory, "octgo_bridge")
	if _, err := os.Stat(filepath.Join(bridgeDirectory, "go.mod")); err == nil {
		target = "."
		commandDirectory = bridgeDirectory
	}
	command := exec.Command("go", "build", "-o", binary, target)
	command.Dir = commandDirectory
	return command
}

func renderBridge(model PackageModel, functions []bridgeFunction) ([]byte, error) {
	ordered := append([]bridgeFunction(nil), functions...)
	sort.Slice(ordered, func(i, j int) bool { return ordered[i].Go.Name < ordered[j].Go.Name })
	var body strings.Builder
	body.WriteString("package main\n\n")
	body.WriteString("import (\n\t\"fmt\"\n\t\"os\"\n\n")
	body.WriteString("\tgoPackage \"")
	body.WriteString(model.Package.Path)
	body.WriteString("\"\n\t\"github.com/yuechen-li-dev/oct/pkg/octxiliary\"\n)\n\n")
	body.WriteString(`func main() {
	os.Exit(octxiliary.Main(os.Stdin, os.Stdout, dispatch))
}

`)
	family := "OctGo:" + model.Package.Path
	body.WriteString("func dispatch(req octxiliary.Request) octxiliary.Response {\n")
	body.WriteString(fmt.Sprintf("\tif req.Family != %q { return octxiliary.ErrString(req.ID, fmt.Sprintf(\"unknown family %%q\", req.Family)) }\n", family))
	body.WriteString("\tswitch req.Function {\n")
	for _, function := range ordered {
		body.WriteString(renderFunctionCase(model, function.Go))
	}
	body.WriteString("\tdefault:\n\t\treturn octxiliary.ErrString(req.ID, fmt.Sprintf(\"unknown function %q\", req.Function))\n\t}\n}\n")
	formatted, err := format.Source([]byte(body.String()))
	if err != nil {
		return nil, fmt.Errorf("format OCTGO static adapter: %w", err)
	}
	return append([]byte(bridgeHeader), formatted...), nil
}

func renderFunctionCase(model PackageModel, function FunctionModel) string {
	args := make([]string, 0, len(function.Parameters))
	loads := make([]string, 0, len(function.Parameters))
	for index, parameter := range function.Parameters {
		kind := projectedOctType(parameter, model.Package.Path)
		if parameter.Name != "" {
			kind = parameter.Kind
		}
		name := fmt.Sprintf("arg%d", index)
		loads = append(loads, fmt.Sprintf("\t\t%s, err := octxiliary.Arg%s(req, %d)\n\t\tif err != nil { return octxiliary.Err(req.ID, err) }\n", name, kind, index))
		expression := name
		if parameter.Name != "" {
			expression = fmt.Sprintf("goPackage.%s(%s)", parameter.Name, expression)
		}
		args = append(args, expression)
	}
	var builder strings.Builder
	builder.WriteString(fmt.Sprintf("\tcase %q:\n", function.Name))
	for _, load := range loads {
		builder.WriteString(load)
	}
	call := fmt.Sprintf("goPackage.%s(%s)", function.Name, strings.Join(args, ", "))
	if len(function.Results) == 0 {
		builder.WriteString("\t\t" + call + "\n\t\treturn octxiliary.OkVoid(req.ID)\n")
		return builder.String()
	}
	result := function.Results[0]
	kind := result.Kind
	builder.WriteString("\t\tresult := " + call + "\n")
	builder.WriteString(fmt.Sprintf("\t\treturn octxiliary.Ok%s(req.ID, %s)\n", kind, bridgeResultExpression(result, "result")))
	return builder.String()
}

func bridgeResultExpression(ref TypeRef, expression string) string {
	if ref.Name == "" {
		return expression
	}
	switch ref.Kind {
	case "Int":
		return "int(" + expression + ")"
	case "Float":
		return "float64(" + expression + ")"
	case "Bool":
		return "bool(" + expression + ")"
	case "String":
		return "string(" + expression + ")"
	default:
		return expression
	}
}

func writeBridge(path string, contents []byte) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return fmt.Errorf("create OCTGO bridge directory: %w", err)
	}
	if current, err := os.ReadFile(path); err == nil && bytes.Equal(current, contents) {
		return nil
	}
	tmp, err := os.CreateTemp(filepath.Dir(path), ".octgo-bridge-*")
	if err != nil {
		return fmt.Errorf("stage OCTGO bridge: %w", err)
	}
	tmpPath := tmp.Name()
	defer os.Remove(tmpPath)
	if _, err := tmp.Write(contents); err != nil {
		tmp.Close()
		return fmt.Errorf("write staged OCTGO bridge: %w", err)
	}
	if err := tmp.Close(); err != nil {
		return fmt.Errorf("close staged OCTGO bridge: %w", err)
	}
	if err := os.Rename(tmpPath, path); err != nil {
		return fmt.Errorf("publish OCTGO bridge: %w", err)
	}
	return nil
}
