package hlsl

import (
	"fmt"
	"strings"

	"github.com/yuechen-li-dev/oct/internal/sdslv/vdmir"
)

func Emit(module vdmir.Module) (string, error) {
	var e emitter
	e.line("// Generated by GoOct SDSL-V M4 via VD-MIR. Do not edit by hand.")
	if module.Namespace != "" {
		e.line("// namespace " + module.Namespace)
	}
	e.line("")
	for _, alias := range module.TypeAliases {
		e.line(fmt.Sprintf("// type %s = %s", alias.Name, typeRef(alias.Target, "")))
		e.line("")
	}
	for _, record := range module.Records {
		e.emitStruct(record.Name, record.Fields)
	}
	for _, board := range module.Boards {
		e.emitStruct(board.Name, board.Fields)
	}
	for _, stream := range module.Streams {
		if len(stream.Fields) == 0 {
			continue
		}
		e.emitStruct(stream.Name, stream.Fields)
	}
	for _, enum := range module.Enums {
		e.emitEnum(enum)
	}
	for _, resource := range module.Resources {
		e.emitResource(resource)
	}
	for _, workgroup := range module.Workgroups {
		e.emitWorkgroup(workgroup)
	}
	if len(module.Resources) > 0 || len(module.Workgroups) > 0 {
		e.line("")
	}
	entrySet := map[string]vdmir.ComputeEntryPoint{}
	for _, entry := range module.EntryPoints {
		entrySet[entry.EmittedName] = entry
	}
	for _, fn := range module.Functions {
		e.emitFunction(fn, entrySet[fn.EmittedName])
	}
	return e.builder.String(), nil
}

type emitter struct {
	builder     strings.Builder
	indent      int
	tempCounter int
	viewAliases map[string]vdmir.RowMajorViewExpr
	testMode    bool
}

func (e *emitter) emitStruct(name string, fields []vdmir.Field) {
	e.line("struct " + name)
	e.line("{")
	e.indent++
	for _, field := range fields {
		e.line(fmt.Sprintf("%s;", typeRef(field.Type, field.Name)))
	}
	e.indent--
	e.line("};")
	e.line("")
}

func (e *emitter) emitEnum(enum vdmir.Enum) {
	for i, variant := range enum.Variants {
		e.line(fmt.Sprintf("static const int %s_%s = %d;", enum.Name, variant.Name, i))
	}
	for _, variant := range enum.Variants {
		if !variant.HasPayload {
			continue
		}
		e.emitStruct(enumPayloadTypeName(enum.Name, variant.Name), variant.Payload)
	}
	e.line("struct " + enum.Name)
	e.line("{")
	e.indent++
	e.line("int Tag;")
	for _, variant := range enum.Variants {
		if !variant.HasPayload {
			continue
		}
		e.line(fmt.Sprintf("%s %s;", enumPayloadTypeName(enum.Name, variant.Name), hlslIdentifier(variant.Name)))
	}
	e.indent--
	e.line("};")
	e.line("")
	for _, variant := range enum.Variants {
		e.emitEnumConstructor(enum.Name, variant)
	}
}

func (e *emitter) emitEnumConstructor(enumName string, variant vdmir.EnumVariant) {
	params := make([]string, 0, len(variant.Payload))
	for _, field := range variant.Payload {
		params = append(params, typeRef(field.Type, field.Name))
	}
	e.line(fmt.Sprintf("%s %s(%s)", enumName, enumConstructorName(enumName, variant.Name), strings.Join(params, ", ")))
	e.line("{")
	e.indent++
	e.line(fmt.Sprintf("%s value;", enumName))
	e.line(fmt.Sprintf("value.Tag = %s_%s;", enumName, variant.Name))
	for _, field := range variant.Payload {
		e.line(fmt.Sprintf("value.%s.%s = %s;", hlslIdentifier(variant.Name), hlslIdentifier(field.Name), hlslIdentifier(field.Name)))
	}
	e.line("return value;")
	e.indent--
	e.line("}")
	e.line("")
}

func (e *emitter) emitResource(resource vdmir.Resource) {
	elem := typeRef(resource.ElementType, "")
	prefix := fmt.Sprintf("[[vk::binding(%d, %d)]] ", resource.Binding.Binding, resource.Binding.Set)
	if resource.Access == vdmir.ResourceReadOnly {
		e.line(fmt.Sprintf("%sStructuredBuffer<%s> %s;", prefix, elem, hlslIdentifier(resource.Name)))
		return
	}
	e.line(fmt.Sprintf("%sRWStructuredBuffer<%s> %s;", prefix, elem, hlslIdentifier(resource.Name)))
}

func (e *emitter) emitWorkgroup(workgroup vdmir.WorkgroupMemoryDecl) {
	if workgroup.IsTile {
		e.line(fmt.Sprintf("groupshared %s %s[%d * %d];", typeRef(workgroup.ElementType, ""), hlslIdentifier(workgroup.Name), workgroup.Rows, workgroup.Cols))
		return
	}
	e.line(fmt.Sprintf("groupshared %s;", typeRef(workgroup.Type, workgroup.Name)))
}

func (e *emitter) emitFunction(fn vdmir.Function, entry vdmir.ComputeEntryPoint) {
	e.viewAliases = map[string]vdmir.RowMajorViewExpr{}
	if entry.EmittedName != "" {
		e.emitEntryParamGlobals(entry)
	}
	if entry.EmittedName != "" {
		e.line(fmt.Sprintf("[numthreads(%d, %d, %d)]", entry.NumThreadsX, entry.NumThreadsY, entry.NumThreadsZ))
	}
	params := make([]string, 0, len(fn.Params))
	if entry.EmittedName == "" {
		for _, param := range fn.Params {
			params = append(params, typeRef(param.Type, param.Name))
		}
		if e.testMode {
			params = append(params, "inout SdslvTestFailure failure")
		}
	} else {
		for _, builtin := range entry.Builtins {
			if builtin.Referenced {
				params = append(params, fmt.Sprintf("%s %s : %s", typeRef(builtin.Type, ""), hlslIdentifier(builtin.Name), builtin.Semantic))
			}
		}
	}
	e.line(fmt.Sprintf("%s %s(%s)", typeRef(fn.ReturnType, ""), fn.EmittedName, strings.Join(params, ", ")))
	e.line("{")
	e.indent++
	e.emitEntryThreadLocals(entry)
	for _, stmt := range fn.Body.Statements {
		e.emitStmt(stmt)
	}
	e.indent--
	e.line("}")
	e.line("")
}

func (e *emitter) emitEntryParamGlobals(entry vdmir.ComputeEntryPoint) {
	for _, param := range entry.Params {
		e.line(fmt.Sprintf("[[vk::push_constant]] ConstantBuffer<%s> %s;", typeRef(param.Type, ""), hlslIdentifier(param.Name)))
	}
	if len(entry.Params) > 0 {
		e.line("")
	}
}

func (e *emitter) emitEntryThreadLocals(entry vdmir.ComputeEntryPoint) {
	for _, thread := range entry.ThreadParams {
		e.line(fmt.Sprintf("%s %s;", thread.TypeName, hlslIdentifier(thread.ParamName)))
		for _, field := range thread.Fields {
			value := field.BuiltinName
			if field.BuiltinField != "" {
				value += "." + field.BuiltinField
			}
			e.line(fmt.Sprintf("%s.%s = %s;", hlslIdentifier(thread.ParamName), hlslIdentifier(field.FieldName), hlslExprPath(value)))
		}
	}
	if len(entry.ThreadParams) > 0 {
		e.line("")
	}
}

func (e *emitter) emitBlock(block vdmir.Block) {
	e.line("{")
	e.indent++
	for _, stmt := range block.Statements {
		e.emitStmt(stmt)
	}
	e.indent--
	e.line("}")
}

func (e *emitter) emitStmt(stmt vdmir.Stmt) {
	switch s := stmt.(type) {
	case vdmir.ForeignShaderStmt:
		e.emitForeignSource(s.Provenance.Path, s.SourceLine, s.RawSource)
	case vdmir.LetStmt:
		if s.Value == nil {
			e.line(fmt.Sprintf("%s;", typeRef(s.Type, s.Name)))
			return
		}
		if zero, ok := s.Value.(vdmir.RegTileZeroExpr); ok {
			e.emitRegTileZeroLet(s.Name, zero.Type())
			return
		}
		if rowMajor, ok := s.Value.(vdmir.RowMajorViewExpr); ok {
			e.viewAliases[s.Name] = rowMajor
			return
		}
		if reduction, ok := s.Value.(vdmir.ReductionExpr); ok {
			e.emitReductionLet(s, reduction)
			return
		}
		if utility, ok := s.Value.(vdmir.WhenUtilityExpr); ok {
			e.emitWhenUtilityLet(s, utility)
			return
		}
		if withExpr, ok := s.Value.(vdmir.WithExpr); ok {
			e.emitWithLet(s, withExpr)
			return
		}
		if matchExpr, ok := s.Value.(vdmir.MatchExpr); ok {
			e.emitMatchLet(s, matchExpr)
			return
		}
		if board, ok := s.Value.(vdmir.BoardConstructExpr); ok {
			e.emitBoardConstructLet(s, board)
			return
		}
		if derive, ok := s.Value.(vdmir.DeriveExpr); ok {
			e.emitDeriveLet(s, derive)
			return
		}
		if guardedRead, ok := s.Value.(vdmir.GuardedReadExpr); ok {
			e.emitGuardedReadLet(s, guardedRead)
			return
		}
		if foreign, ok := s.Value.(vdmir.ForeignShaderExpr); ok {
			e.line(fmt.Sprintf("%s;", typeRef(s.Type, s.Name)))
			e.emitForeignExpressionAssignment(hlslIdentifier(s.Name), foreign)
			return
		}
		e.line(fmt.Sprintf("%s = %s;", typeRef(s.Type, s.Name), e.expr(s.Value)))
	case vdmir.AssignStmt:
		if foreign, ok := s.Value.(vdmir.ForeignShaderExpr); ok {
			e.emitForeignExpressionAssignment(e.expr(s.Target), foreign)
			return
		}
		if reduction, ok := s.Value.(vdmir.ReductionExpr); ok {
			e.emitReductionAssign(e.expr(s.Target), reduction)
			return
		}
		if utility, ok := s.Value.(vdmir.WhenUtilityExpr); ok {
			e.emitWhenUtilityAssign(e.expr(s.Target), utility)
			return
		}
		if withExpr, ok := s.Value.(vdmir.WithExpr); ok {
			e.emitWithAssign(e.expr(s.Target), withExpr)
			return
		}
		if matchExpr, ok := s.Value.(vdmir.MatchExpr); ok {
			e.emitMatchAssign(e.expr(s.Target), matchExpr)
			return
		}
		if board, ok := s.Value.(vdmir.BoardConstructExpr); ok {
			e.emitBoardConstructAssign(e.expr(s.Target), board)
			return
		}
		if derive, ok := s.Value.(vdmir.DeriveExpr); ok {
			e.emitDeriveAssign(e.expr(s.Target), derive)
			return
		}
		if guardedRead, ok := s.Value.(vdmir.GuardedReadExpr); ok {
			e.emitGuardedReadAssign(e.expr(s.Target), guardedRead)
			return
		}
		e.line(fmt.Sprintf("%s = %s;", e.expr(s.Target), e.expr(s.Value)))
	case vdmir.GuardedWriteStmt:
		e.line("if (" + e.expr(s.Condition) + ")")
		e.line("{")
		e.indent++
		e.line(fmt.Sprintf("%s = %s;", e.expr(s.Target), e.expr(s.Value)))
		e.indent--
		e.line("}")
	case vdmir.ReturnStmt:
		if s.Value == nil {
			e.line("return;")
			return
		}
		if reduction, ok := s.Value.(vdmir.ReductionExpr); ok {
			e.emitReductionReturn(reduction)
			return
		}
		if withExpr, ok := s.Value.(vdmir.WithExpr); ok {
			e.emitWithReturn(withExpr)
			return
		}
		if matchExpr, ok := s.Value.(vdmir.MatchExpr); ok {
			e.emitMatchReturn(matchExpr)
			return
		}
		if board, ok := s.Value.(vdmir.BoardConstructExpr); ok {
			e.emitBoardConstructReturn(board)
			return
		}
		if derive, ok := s.Value.(vdmir.DeriveExpr); ok {
			e.emitDeriveReturn(derive)
			return
		}
		if guardedRead, ok := s.Value.(vdmir.GuardedReadExpr); ok {
			e.emitGuardedReadReturn(guardedRead)
			return
		}
		if foreign, ok := s.Value.(vdmir.ForeignShaderExpr); ok {
			temp := e.nextTempWithPrefix("inline_hlsl")
			e.line(fmt.Sprintf("%s;", typeRef(foreign.Type(), temp)))
			e.emitForeignExpressionAssignment(temp, foreign)
			e.line("return " + temp + ";")
			return
		}
		e.line("return " + e.expr(s.Value) + ";")
	case vdmir.ExprStmt:
		if foreign, ok := s.Value.(vdmir.ForeignShaderExpr); ok {
			e.emitForeignExprStatement(foreign)
			return
		}
		e.line(e.expr(s.Value) + ";")
	case vdmir.AssertStmt:
		e.emitTestAssert(s)
	case vdmir.BlockStmt:
		e.emitBlock(s.Body)
	case vdmir.IfStmt:
		e.emitIfStmt(s)
	case vdmir.ForRangeStmt:
		switch s.LoopHint {
		case vdmir.LoopHintUnroll:
			e.line("[unroll]")
		case vdmir.LoopHintLoop:
			e.line("[loop]")
		}
		loopType := typeRef(s.Type, "")
		e.line(fmt.Sprintf("for (%s %s = %s; %s < %s; %s += %s)", loopType, s.Name, e.expr(s.Start), s.Name, e.expr(s.End), s.Name, e.expr(s.Step)))
		e.emitBlock(s.Body)
	}
}

func (e *emitter) emitIfStmt(stmt vdmir.IfStmt) {
	e.line("if (" + e.expr(stmt.Condition) + ")")
	e.emitBlock(stmt.ThenBody)
	if stmt.ElseBody == nil {
		return
	}
	if len(stmt.ElseBody.Statements) == 1 {
		if nested, ok := stmt.ElseBody.Statements[0].(vdmir.IfStmt); ok {
			e.line("else " + "if (" + e.expr(nested.Condition) + ")")
			e.emitBlock(nested.ThenBody)
			if nested.ElseBody != nil {
				e.emitElseTail(*nested.ElseBody)
			}
			return
		}
	}
	e.line("else")
	e.emitBlock(*stmt.ElseBody)
}

func (e *emitter) emitElseTail(block vdmir.Block) {
	if len(block.Statements) == 1 {
		if nested, ok := block.Statements[0].(vdmir.IfStmt); ok {
			e.line("else " + "if (" + e.expr(nested.Condition) + ")")
			e.emitBlock(nested.ThenBody)
			if nested.ElseBody != nil {
				e.emitElseTail(*nested.ElseBody)
			}
			return
		}
	}
	e.line("else")
	e.emitBlock(block)
}

func (e *emitter) emitWhenUtilityLet(stmt vdmir.LetStmt, utility vdmir.WhenUtilityExpr) {
	e.line(fmt.Sprintf("%s = %s;", typeRef(stmt.Type, stmt.Name), e.expr(utility.Else)))
	e.emitWhenUtilityAssign(hlslIdentifier(stmt.Name), utility)
}

func (e *emitter) emitReductionLet(stmt vdmir.LetStmt, reduction vdmir.ReductionExpr) {
	e.line(fmt.Sprintf("%s = %s;", typeRef(stmt.Type, stmt.Name), reductionIdentityLiteral(reduction)))
	e.emitReductionLoop(hlslIdentifier(stmt.Name), reduction)
}

func (e *emitter) emitReductionAssign(target string, reduction vdmir.ReductionExpr) {
	tempName := e.nextTempWithPrefix("reduce")
	e.line(fmt.Sprintf("%s = %s;", typeRef(reduction.Type(), tempName), reductionIdentityLiteral(reduction)))
	e.emitReductionLoop(tempName, reduction)
	e.line(fmt.Sprintf("%s = %s;", target, tempName))
}

func (e *emitter) emitReductionReturn(reduction vdmir.ReductionExpr) {
	tempName := e.nextTempWithPrefix("reduce")
	e.line(fmt.Sprintf("%s = %s;", typeRef(reduction.Type(), tempName), reductionIdentityLiteral(reduction)))
	e.emitReductionLoop(tempName, reduction)
	e.line("return " + tempName + ";")
}

func (e *emitter) emitReductionLoop(target string, reduction vdmir.ReductionExpr) {
	switch reduction.LoopHint {
	case vdmir.LoopHintUnroll:
		e.line("[unroll]")
	case vdmir.LoopHintLoop:
		e.line("[loop]")
	}
	loopType := typeRef(reduction.IndexType, "")
	e.line(fmt.Sprintf("for (%s %s = %s; %s < %s; %s += %s)", loopType, reduction.Name, e.expr(reduction.Start), reduction.Name, e.expr(reduction.End), reduction.Name, e.expr(reduction.Step)))
	e.line("{")
	e.indent++
	e.line(fmt.Sprintf("%s = %s %s (%s);", target, target, reductionCombineOperator(reduction.Op), e.expr(reduction.Body)))
	e.indent--
	e.line("}")
}

func (e *emitter) emitWhenUtilityAssign(target string, utility vdmir.WhenUtilityExpr) {
	scoreName := "__sdslv_" + sanitizeName(target) + "_score"
	e.line(fmt.Sprintf("float %s = -3.402823466e+38F;", scoreName))
	for _, c := range utility.Cases {
		score := e.expr(c.Score)
		e.line(fmt.Sprintf("if (%s && (%s > %s))", e.expr(c.Guard), score, scoreName))
		e.line("{")
		e.indent++
		e.line(fmt.Sprintf("%s = %s;", scoreName, score))
		e.line(fmt.Sprintf("%s = %s;", target, e.expr(c.Value)))
		e.indent--
		e.line("}")
	}
}

func (e *emitter) emitWithLet(stmt vdmir.LetStmt, withExpr vdmir.WithExpr) {
	tempName := e.nextTemp()
	e.emitWithCopy(tempName, withExpr)
	e.line(fmt.Sprintf("%s = %s;", typeRef(stmt.Type, stmt.Name), tempName))
}

func (e *emitter) emitWithAssign(target string, withExpr vdmir.WithExpr) {
	tempName := e.nextTemp()
	e.emitWithCopy(tempName, withExpr)
	e.line(fmt.Sprintf("%s = %s;", target, tempName))
}

func (e *emitter) emitWithReturn(withExpr vdmir.WithExpr) {
	tempName := e.nextTemp()
	e.emitWithCopy(tempName, withExpr)
	e.line("return " + tempName + ";")
}

func (e *emitter) emitWithCopy(tempName string, withExpr vdmir.WithExpr) {
	e.line(fmt.Sprintf("%s %s = %s;", typeRef(withExpr.Type(), ""), tempName, e.expr(withExpr.Base)))
	for _, update := range withExpr.Updates {
		e.line(fmt.Sprintf("%s.%s = %s;", tempName, hlslIdentifier(update.Name), e.expr(update.Value)))
	}
}

func (e *emitter) emitMatchLet(stmt vdmir.LetStmt, matchExpr vdmir.MatchExpr) {
	e.line(fmt.Sprintf("%s;", typeRef(stmt.Type, stmt.Name)))
	e.emitMatchAssign(hlslIdentifier(stmt.Name), matchExpr)
}

func (e *emitter) emitMatchAssign(target string, matchExpr vdmir.MatchExpr) {
	subjectName := e.nextTempWithPrefix("match_subject")
	e.line(fmt.Sprintf("%s %s = %s;", typeRef(matchExpr.Subject.Type(), ""), subjectName, e.expr(matchExpr.Subject)))
	for i, arm := range matchExpr.Arms {
		keyword := "if"
		if i > 0 {
			keyword = "else if"
		}
		e.line(fmt.Sprintf("%s (%s.Tag == %s_%s)", keyword, subjectName, arm.EnumName, arm.VariantName))
		e.line("{")
		e.indent++
		if arm.BindingName != "" {
			e.line(fmt.Sprintf("%s %s = %s.%s;", typeRef(arm.BindingType, ""), hlslIdentifier(arm.BindingName), subjectName, hlslIdentifier(arm.VariantName)))
		}
		e.line(fmt.Sprintf("%s = %s;", target, e.expr(arm.Value)))
		e.indent--
		e.line("}")
	}
}

func (e *emitter) emitMatchReturn(matchExpr vdmir.MatchExpr) {
	tempName := e.nextTempWithPrefix("match_result")
	e.line(fmt.Sprintf("%s %s;", typeRef(matchExpr.Type(), ""), tempName))
	e.emitMatchAssign(tempName, matchExpr)
	e.line("return " + tempName + ";")
}

func (e *emitter) emitGuardedReadLet(stmt vdmir.LetStmt, guarded vdmir.GuardedReadExpr) {
	tempName := e.emitGuardedReadValue(guarded)
	e.line(fmt.Sprintf("%s = %s;", typeRef(stmt.Type, stmt.Name), tempName))
}

func (e *emitter) emitGuardedReadAssign(target string, guarded vdmir.GuardedReadExpr) {
	tempName := e.emitGuardedReadValue(guarded)
	// A guarded read is a value expression.  Keep the surrounding assignment
	// outside its conditional load so false guards still write the fallback.
	e.line(fmt.Sprintf("%s = %s;", target, tempName))
}

func (e *emitter) emitGuardedReadValue(guarded vdmir.GuardedReadExpr) string {
	tempName := e.nextTempWithPrefix("guarded_read")
	e.line(fmt.Sprintf("%s %s = %s;", typeRef(guarded.Type(), ""), tempName, e.expr(guarded.Fallback)))
	e.line("if (" + e.expr(guarded.Condition) + ")")
	e.line("{")
	e.indent++
	e.line(fmt.Sprintf("%s = %s;", tempName, e.expr(guarded.Target)))
	e.indent--
	e.line("}")
	return tempName
}

func (e *emitter) emitGuardedReadReturn(guarded vdmir.GuardedReadExpr) {
	tempName := e.emitGuardedReadValue(guarded)
	e.line("return " + tempName + ";")
}

func (e *emitter) emitBoardConstructLet(stmt vdmir.LetStmt, board vdmir.BoardConstructExpr) {
	e.line(fmt.Sprintf("%s;", typeRef(stmt.Type, stmt.Name)))
	e.emitBoardFieldAssignments(hlslIdentifier(stmt.Name), board)
}

func (e *emitter) emitBoardConstructAssign(target string, board vdmir.BoardConstructExpr) {
	e.emitBoardFieldAssignments(target, board)
}

func (e *emitter) emitBoardConstructReturn(board vdmir.BoardConstructExpr) {
	tempName := e.nextTempWithPrefix("board")
	e.line(fmt.Sprintf("%s;", typeRef(board.Type(), tempName)))
	e.emitBoardFieldAssignments(tempName, board)
	e.line("return " + tempName + ";")
}

func (e *emitter) emitBoardFieldAssignments(target string, board vdmir.BoardConstructExpr) {
	for _, field := range board.Fields {
		e.line(fmt.Sprintf("%s.%s = %s;", target, hlslIdentifier(field.Name), e.expr(field.Value)))
	}
}

func (e *emitter) emitDeriveLet(stmt vdmir.LetStmt, derive vdmir.DeriveExpr) {
	e.emitDeriveTemps(derive)
	e.line(fmt.Sprintf("%s;", typeRef(stmt.Type, stmt.Name)))
	e.emitDeriveResultAssignments(hlslIdentifier(stmt.Name), derive)
}

func (e *emitter) emitDeriveAssign(target string, derive vdmir.DeriveExpr) {
	e.emitDeriveTemps(derive)
	e.emitDeriveResultAssignments(target, derive)
}

func (e *emitter) emitDeriveReturn(derive vdmir.DeriveExpr) {
	e.emitDeriveTemps(derive)
	tempName := e.nextTempWithPrefix("derive_result")
	e.line(fmt.Sprintf("%s;", typeRef(derive.Type(), tempName)))
	e.emitDeriveResultAssignments(tempName, derive)
	e.line("return " + tempName + ";")
}

func (e *emitter) emitDeriveTemps(derive vdmir.DeriveExpr) {
	for _, field := range derive.Fields {
		e.line(fmt.Sprintf("%s = %s;", typeRef(field.Value.Type(), field.TempName), e.expr(field.Value)))
	}
}

func (e *emitter) emitDeriveResultAssignments(target string, derive vdmir.DeriveExpr) {
	for _, field := range derive.Fields {
		e.line(fmt.Sprintf("%s.%s = %s;", target, hlslIdentifier(field.Name), hlslIdentifier(field.TempName)))
	}
}

func (e *emitter) expr(expr vdmir.Expr) string {
	switch x := expr.(type) {
	case vdmir.ForeignShaderExpr:
		return "/* inline HLSL expressions require a statement-valued context */"
	case vdmir.LiteralExpr:
		return x.Value
	case vdmir.VarRefExpr:
		return hlslIdentifier(x.Name)
	case vdmir.FieldAccessExpr:
		return e.expr(x.Target) + "." + hlslIdentifier(x.Field)
	case vdmir.IndexExpr:
		if text, ok := e.testInputIndex(x); ok {
			return text
		}
		return e.expr(x.Target) + "[" + e.expr(x.Index) + "]"
	case vdmir.Index2DExpr:
		return e.index2D(x)
	case vdmir.GuardedReadExpr:
		return "/* unsupported guarded read expr position */"
	case vdmir.RegTileZeroExpr:
		return "/* reg_tile_zero */"
	case vdmir.RowMajorViewExpr:
		return "/* matrix view */"
	case vdmir.CallExpr:
		args := make([]string, 0, len(x.Arguments))
		for _, arg := range x.Arguments {
			args = append(args, e.expr(arg))
		}
		return e.expr(x.Callee) + "(" + strings.Join(args, ", ") + ")"
	case vdmir.IntrinsicCallExpr:
		args := make([]string, 0, len(x.Arguments))
		for _, arg := range x.Arguments {
			args = append(args, e.expr(arg))
		}
		return hlslIntrinsic(x.Intrinsic) + "(" + strings.Join(args, ", ") + ")"
	case vdmir.BinaryExpr:
		return "(" + e.expr(x.Left) + " " + x.Operator + " " + e.expr(x.Right) + ")"
	case vdmir.UnaryExpr:
		return x.Operator + e.expr(x.Operand)
	case vdmir.WhenUtilityExpr:
		return e.whenUtility(x)
	case vdmir.WithExpr:
		return "/* unsupported with expr position */"
	case vdmir.ReductionExpr:
		return "/* unsupported reduction expr position */"
	case vdmir.EnumConstructExpr:
		args := make([]string, 0, len(x.Fields))
		for _, field := range x.Fields {
			args = append(args, e.expr(field.Value))
		}
		return enumConstructorName(x.EnumName, x.VariantName) + "(" + strings.Join(args, ", ") + ")"
	case vdmir.BoardConstructExpr:
		return "/* unsupported board construct expr position */"
	case vdmir.DeriveExpr:
		return "/* unsupported derive expr position */"
	case vdmir.MatchExpr:
		return "/* unsupported match expr position */"
	default:
		return "/* unsupported */"
	}
}

func (e *emitter) testInputIndex(expr vdmir.IndexExpr) (string, bool) {
	target, ok := expr.Target.(vdmir.VarRefExpr)
	if !ok || target.Name != vdmir.TestInputResourceName {
		return "", false
	}
	base := e.expr(expr.Target) + "[" + e.expr(expr.Index) + "]"
	switch expr.Type().Kind {
	case vdmir.TypeBool:
		return "(" + base + " != 0u)", true
	case vdmir.TypeI32:
		return "asint(" + base + ")", true
	case vdmir.TypeF32:
		return "asfloat(" + base + ")", true
	default:
		return base, true
	}
}

func (e *emitter) emitForeignSource(path string, line int, raw string) {
	e.line(fmt.Sprintf("// BEGIN INLINE HLSL %s:%d", path, line))
	for _, sourceLine := range strings.Split(raw, "\n") {
		e.line(sourceLine)
	}
	e.line("// END INLINE HLSL")
}

func (e *emitter) emitForeignExprStatement(expr vdmir.ForeignShaderExpr) {
	temp := e.nextTempWithPrefix("inline_hlsl")
	e.line(fmt.Sprintf("%s;", typeRef(expr.Type(), temp)))
	e.emitForeignExpressionAssignment(temp, expr)
}

func (e *emitter) emitForeignExpressionAssignment(target string, expr vdmir.ForeignShaderExpr) {
	// HLSL has no portable immediate lambda expression. Keeping the source as a
	// local block makes it valid for DXC and preserves the declared result boundary.
	body := strings.Replace(expr.RawSource, "return", target+" =", 1)
	e.line("{")
	e.indent++
	e.emitForeignSource(expr.Provenance.Path, expr.SourceLine, body)
	e.indent--
	e.line("}")
}

func reductionIdentityLiteral(expr vdmir.ReductionExpr) string {
	switch expr.Op {
	case vdmir.ReductionProduct:
		return oneLiteral(expr.Type())
	default:
		return zeroLiteral(expr.Type())
	}
}

func reductionCombineOperator(op vdmir.ReductionOp) string {
	switch op {
	case vdmir.ReductionProduct:
		return "*"
	default:
		return "+"
	}
}

func zeroLiteral(ref vdmir.Type) string {
	switch ref.Kind {
	case vdmir.TypeF32:
		return "0.0"
	case vdmir.TypeU32:
		return "0u"
	default:
		return "0"
	}
}

func oneLiteral(ref vdmir.Type) string {
	switch ref.Kind {
	case vdmir.TypeF32:
		return "1.0"
	case vdmir.TypeU32:
		return "1u"
	default:
		return "1"
	}
}

func (e *emitter) whenUtility(expr vdmir.WhenUtilityExpr) string {
	var b strings.Builder
	b.WriteString("([&]() { auto __sdslv_best = ")
	b.WriteString(e.expr(expr.Else))
	b.WriteString("; float __sdslv_score = -3.402823466e+38F; ")
	for _, c := range expr.Cases {
		b.WriteString("if (")
		b.WriteString(e.expr(c.Guard))
		b.WriteString(" && (")
		b.WriteString(e.expr(c.Score))
		b.WriteString(" > __sdslv_score)) { __sdslv_score = ")
		b.WriteString(e.expr(c.Score))
		b.WriteString("; __sdslv_best = ")
		b.WriteString(e.expr(c.Value))
		b.WriteString("; } ")
	}
	b.WriteString("return __sdslv_best; })()")
	return b.String()
}

func (e *emitter) index2D(expr vdmir.Index2DExpr) string {
	target := e.expr(expr.Target)
	stride := expr.Stride
	if stride == nil {
		if ref, ok := expr.Target.(vdmir.VarRefExpr); ok {
			if alias, exists := e.viewAliases[ref.Name]; exists {
				target = e.expr(alias.Buffer)
				stride = alias.Cols
			}
		}
	}
	strideText := "0"
	if stride != nil {
		strideText = e.expr(stride)
	}
	return target + "[((" + e.expr(expr.Row) + ") * (" + strideText + ")) + (" + e.expr(expr.Col) + ")]"
}

func (e *emitter) emitRegTileZeroLet(name string, typ vdmir.Type) {
	e.line(fmt.Sprintf("%s;", typeRef(typ, name)))
	elemType := elementTypeForArrayish(typ)
	for i := 0; i < typ.ArraySize; i++ {
		e.line(fmt.Sprintf("%s[%d] = %s;", name, i, zeroLiteral(elemType)))
	}
}

func elementTypeForArrayish(ref vdmir.Type) vdmir.Type {
	if ref.Element == nil {
		return vdmir.Type{}
	}
	return *ref.Element
}

func (e *emitter) nextTemp() string {
	return e.nextTempWithPrefix("with")
}

func (e *emitter) nextTempWithPrefix(prefix string) string {
	name := fmt.Sprintf("__sdslv_%s_%d", prefix, e.tempCounter)
	e.tempCounter++
	return name
}

func (e *emitter) line(text string) {
	for i := 0; i < e.indent; i++ {
		e.builder.WriteString("    ")
	}
	e.builder.WriteString(text)
	e.builder.WriteByte('\n')
}

func typeRef(ref vdmir.Type, name string) string {
	mapped := ref.Name
	switch ref.Kind {
	case vdmir.TypeF32:
		mapped = "float"
	case vdmir.TypeI32:
		mapped = "int"
	case vdmir.TypeU32:
		mapped = "uint"
	case vdmir.TypeUint2:
		mapped = "uint2"
	case vdmir.TypeUint3:
		mapped = "uint3"
	case vdmir.TypeUint4:
		mapped = "uint4"
	case vdmir.TypeVoid:
		mapped = "void"
	}
	if ref.IsArray() && ref.Element != nil {
		elem := typeRef(*ref.Element, "")
		if name == "" {
			return elem
		}
		if ref.Kind == vdmir.TypeArray {
			return fmt.Sprintf("%s %s[%d]", elem, hlslIdentifier(name), ref.ArraySize)
		}
		return fmt.Sprintf("%s %s[]", elem, hlslIdentifier(name))
	}
	if (ref.Kind == vdmir.TypeTile || ref.Kind == vdmir.TypeRegTile) && ref.Element != nil {
		elem := typeRef(*ref.Element, "")
		if name == "" {
			return elem
		}
		return fmt.Sprintf("%s %s[%d]", elem, hlslIdentifier(name), ref.Rows*ref.Cols)
	}
	if ref.Kind == vdmir.TypeMatrixView {
		if name == "" {
			return "/* matrix_view */"
		}
		return "/* matrix_view */ " + hlslIdentifier(name)
	}
	if ref.Kind == vdmir.TypeBoard {
		mapped = ref.Name
	}
	if name == "" {
		return mapped
	}
	return mapped + " " + hlslIdentifier(name)
}

func hlslIdentifier(name string) string {
	switch name {
	case "linear":
		return name + "_"
	default:
		return name
	}
}

func hlslExprPath(path string) string {
	parts := strings.Split(path, ".")
	for i, part := range parts {
		parts[i] = hlslIdentifier(part)
	}
	return strings.Join(parts, ".")
}

func sanitizeName(name string) string {
	var b strings.Builder
	for _, r := range name {
		if (r >= 'A' && r <= 'Z') || (r >= 'a' && r <= 'z') || (r >= '0' && r <= '9') || r == '_' {
			b.WriteRune(r)
		} else {
			b.WriteRune('_')
		}
	}
	return b.String()
}

func hlslIntrinsic(intrinsic vdmir.Intrinsic) string {
	switch intrinsic {
	case vdmir.IntrinsicWorkgroupBarrier:
		return "GroupMemoryBarrierWithGroupSync"
	case vdmir.IntrinsicWorkgroupMemoryBarrier:
		return "GroupMemoryBarrier"
	default:
		return "GroupMemoryBarrierWithGroupSync"
	}
}

func enumPayloadTypeName(enumName, variantName string) string {
	return enumName + "_" + variantName + "Payload"
}

func enumConstructorName(enumName, variantName string) string {
	return "__sdslv_make_" + sanitizeName(enumName) + "_" + sanitizeName(variantName)
}
