package hlsl

import (
	"fmt"
	"strings"

	"github.com/yuechen-li-dev/oct/internal/sdslv/ast"
)

func Emit(module ast.Module) (string, error) {
	var e emitter
	e.line("// Generated by GoOct SDSL-V M0. Do not edit by hand.")
	if module.Namespace != "" {
		e.line("// namespace " + module.Namespace)
	}
	e.line("")
	for _, decl := range module.Decls {
		switch d := decl.(type) {
		case ast.TypeAliasDecl:
			e.line(fmt.Sprintf("// type %s = %s", d.Name, typeRef(d.Type, "")))
			e.line("")
		case ast.RecordDecl:
			e.emitRecord(d)
		case ast.EnumDecl:
			e.emitEnum(d)
		case ast.FunctionDecl:
			e.emitFunction("", d, nil)
		case ast.ShaderDecl:
			e.emitShader(d)
		case ast.UnsupportedDecl:
			return "", fmt.Errorf("%s is not implemented in GoOct SDSL-V M0", d.Kind)
		}
	}
	return e.builder.String(), nil
}

type emitter struct {
	builder       strings.Builder
	indent        int
	currentShader string
}

func (e *emitter) emitRecord(record ast.RecordDecl) {
	e.line("struct " + record.Name)
	e.line("{")
	e.indent++
	for _, field := range record.Fields {
		e.line(fmt.Sprintf("%s;", typeRef(field.Type, field.Name)))
	}
	e.indent--
	e.line("};")
	e.line("")
}

func (e *emitter) emitEnum(enum ast.EnumDecl) {
	for i, variant := range enum.Variants {
		e.line(fmt.Sprintf("static const int %s_%s = %d;", enum.Name, variant, i))
	}
	e.line("")
}

func (e *emitter) emitShader(shader ast.ShaderDecl) {
	for _, resource := range shader.Resources {
		elem := "float"
		if len(resource.Type.Args) == 1 {
			elem = typeRef(resource.Type.Args[0], "")
		}
		if resource.Access == "readonly" {
			e.line(fmt.Sprintf("Buffer<%s> %s;", elem, resource.Name))
		} else {
			e.line(fmt.Sprintf("RWBuffer<%s> %s;", elem, resource.Name))
		}
	}
	if len(shader.Resources) > 0 {
		e.line("")
	}
	for _, method := range shader.Methods {
		e.emitFunction(shader.Name, method, shader.Resources)
	}
}

func (e *emitter) emitFunction(shaderName string, fn ast.FunctionDecl, resources []ast.ResourceDecl) {
	previousShader := e.currentShader
	e.currentShader = shaderName
	defer func() { e.currentShader = previousShader }()

	name := fn.Name
	if shaderName != "" {
		name = shaderName + "_" + fn.Name
	}
	if fn.Stage == "compute" && fn.NumThreads != nil {
		e.line(fmt.Sprintf("[numthreads(%d, %d, %d)]", fn.NumThreads.X, fn.NumThreads.Y, fn.NumThreads.Z))
	}
	params := e.parameters(fn)
	e.line(fmt.Sprintf("%s %s(%s)", typeRef(fn.ReturnType, ""), name, strings.Join(params, ", ")))
	e.emitBlock(fn.Body)
	e.line("")
}

func (e *emitter) parameters(fn ast.FunctionDecl) []string {
	params := make([]string, 0, len(fn.Parameters)+4)
	for _, param := range fn.Parameters {
		params = append(params, typeRef(param.Type, param.Name))
	}
	if fn.Stage == "compute" {
		params = append(params,
			"uint3 DispatchThreadID : SV_DispatchThreadID",
			"uint3 GroupThreadID : SV_GroupThreadID",
			"uint3 GroupID : SV_GroupID",
			"uint GroupIndex : SV_GroupIndex",
		)
	}
	return params
}

func (e *emitter) emitBlock(block ast.Block) {
	e.line("{")
	e.indent++
	for _, stmt := range block.Statements {
		e.emitStmt(stmt)
	}
	e.indent--
	e.line("}")
}

func (e *emitter) emitStmt(stmt ast.Stmt) {
	switch s := stmt.(type) {
	case ast.LetStmt:
		if s.Value == nil {
			e.line(fmt.Sprintf("%s;", typeRef(s.Type, s.Name)))
			return
		}
		if utility, ok := s.Value.(ast.WhenUtilityExpr); ok {
			e.emitWhenUtilityLet(s, utility)
			return
		}
		e.line(fmt.Sprintf("%s = %s;", typeRef(s.Type, s.Name), e.expr(s.Value)))
	case ast.AssignStmt:
		if utility, ok := s.Value.(ast.WhenUtilityExpr); ok {
			e.emitWhenUtilityAssign(e.expr(s.Target), utility)
			return
		}
		e.line(fmt.Sprintf("%s = %s;", e.expr(s.Target), e.expr(s.Value)))
	case ast.ReturnStmt:
		if s.Value == nil {
			e.line("return;")
		} else {
			e.line("return " + e.expr(s.Value) + ";")
		}
	case ast.ExprStmt:
		e.line(e.expr(s.Value) + ";")
	case ast.IfStmt:
		e.line("if (" + e.expr(s.Condition) + ")")
		e.emitBlock(s.ThenBody)
		if s.ElseBody != nil {
			e.line("else")
			e.emitBlock(*s.ElseBody)
		}
	case ast.ForStmt:
		step := e.expr(s.Step)
		e.line(fmt.Sprintf("for (uint %s = %s; %s < %s; %s += %s)", s.Name, e.expr(s.Start), s.Name, e.expr(s.End), s.Name, step))
		e.emitBlock(s.Body)
	}
}

func (e *emitter) emitWhenUtilityLet(stmt ast.LetStmt, utility ast.WhenUtilityExpr) {
	e.line(fmt.Sprintf("%s = %s;", typeRef(stmt.Type, stmt.Name), e.expr(utility.Else)))
	e.emitWhenUtilityAssign(stmt.Name, utility)
}

func (e *emitter) emitWhenUtilityAssign(target string, utility ast.WhenUtilityExpr) {
	scoreName := "__sdslv_" + sanitizeName(target) + "_score"
	e.line(fmt.Sprintf("float %s = -3.402823466e+38F;", scoreName))
	for _, c := range utility.Cases {
		score := e.expr(c.Score)
		e.line(fmt.Sprintf("if (%s && (%s > %s))", e.expr(c.Condition), score, scoreName))
		e.line("{")
		e.indent++
		e.line(fmt.Sprintf("%s = %s;", scoreName, score))
		e.line(fmt.Sprintf("%s = %s;", target, e.expr(c.Value)))
		e.indent--
		e.line("}")
	}
}

func (e *emitter) expr(expr ast.Expr) string {
	switch x := expr.(type) {
	case ast.IntegerLiteral:
		return x.Value
	case ast.FloatLiteral:
		return x.Value
	case ast.BoolLiteral:
		if x.Value {
			return "true"
		}
		return "false"
	case ast.StringLiteral:
		return fmt.Sprintf("%q", x.Value)
	case ast.IdentifierExpr:
		return x.Name
	case ast.FieldAccessExpr:
		return e.expr(x.Target) + "." + x.Field
	case ast.IndexExpr:
		return e.expr(x.Target) + "[" + e.expr(x.Index) + "]"
	case ast.CallExpr:
		args := make([]string, 0, len(x.Arguments))
		for _, arg := range x.Arguments {
			args = append(args, e.expr(arg))
		}
		return e.callName(x.Callee) + "(" + strings.Join(args, ", ") + ")"
	case ast.BinaryExpr:
		return "(" + e.expr(x.Left) + " " + x.Operator + " " + e.expr(x.Right) + ")"
	case ast.UnaryExpr:
		return x.Operator + e.expr(x.Operand)
	case ast.ParenExpr:
		return "(" + e.expr(x.Inner) + ")"
	case ast.WhenUtilityExpr:
		return e.whenUtility(x)
	default:
		return "/* unsupported */"
	}
}

func (e *emitter) callName(expr ast.Expr) string {
	if id, ok := expr.(ast.IdentifierExpr); ok && e.currentShader != "" && !isHLSLConstructor(id.Name) {
		return e.currentShader + "_" + id.Name
	}
	return e.expr(expr)
}

func (e *emitter) whenUtility(expr ast.WhenUtilityExpr) string {
	// M0 lowers utility selection into a deterministic comma-expression lambda.
	var b strings.Builder
	b.WriteString("([&]() { auto __sdslv_best = ")
	b.WriteString(e.expr(expr.Else))
	b.WriteString("; float __sdslv_score = -3.402823466e+38F; ")
	for _, c := range expr.Cases {
		b.WriteString("if (")
		b.WriteString(e.expr(c.Condition))
		b.WriteString(" && (")
		b.WriteString(e.expr(c.Score))
		b.WriteString(" > __sdslv_score)) { __sdslv_score = ")
		b.WriteString(e.expr(c.Score))
		b.WriteString("; __sdslv_best = ")
		b.WriteString(e.expr(c.Value))
		b.WriteString("; } ")
	}
	b.WriteString("return __sdslv_best; })()")
	return b.String()
}

func (e *emitter) line(text string) {
	for i := 0; i < e.indent; i++ {
		e.builder.WriteString("    ")
	}
	e.builder.WriteString(text)
	e.builder.WriteByte('\n')
}

func typeRef(ref ast.TypeRef, name string) string {
	if ref.Name == "array" && len(ref.Args) == 1 {
		if name == "" {
			return typeRef(ref.Args[0], "")
		}
		if ref.HasArraySize {
			return fmt.Sprintf("%s %s[%d]", typeRef(ref.Args[0], ""), name, ref.ArraySize)
		}
		return fmt.Sprintf("%s %s[]", typeRef(ref.Args[0], ""), name)
	}
	mapped := ref.Name
	switch ref.Name {
	case "f32":
		mapped = "float"
	case "i32":
		mapped = "int"
	case "u32":
		mapped = "uint"
	case "void":
		mapped = "void"
	}
	if name == "" {
		return mapped
	}
	return mapped + " " + name
}

func sanitizeName(name string) string {
	var b strings.Builder
	for _, r := range name {
		if (r >= 'A' && r <= 'Z') || (r >= 'a' && r <= 'z') || (r >= '0' && r <= '9') || r == '_' {
			b.WriteRune(r)
		} else {
			b.WriteRune('_')
		}
	}
	return b.String()
}

func isHLSLConstructor(name string) bool {
	switch name {
	case "float2", "float3", "float4":
		return true
	default:
		return false
	}
}
