package hlsl

import (
	"fmt"
	"sort"
	"strings"

	"github.com/yuechen-li-dev/oct/internal/sdslv/vdmir"
	"github.com/yuechen-li-dev/oct/internal/source"
)

func Emit(module vdmir.Module) (string, error) {
	var e emitter
	e.line("// Generated by canonical GoOct SDSL-V via VD-MIR. Do not edit by hand.")
	if module.Namespace != "" {
		e.line("// namespace " + module.Namespace)
	}
	e.line("")
	if moduleRequiresCooperativeMatrix(module) {
		e.emitCooperativeMatrixPreamble()
	}
	for _, alias := range module.TypeAliases {
		suffix := ""
		if alias.Target.Space != "" {
			suffix = " @space(" + alias.Target.Space + ")"
		}
		e.line(fmt.Sprintf("// type %s = %s%s", alias.Name, typeRef(alias.Target, ""), suffix))
		e.line("")
	}
	for _, record := range module.Records {
		e.emitStruct(record.Name, record.Fields)
	}
	for _, board := range module.Boards {
		e.emitStruct(board.Name, board.Fields)
	}
	for _, stream := range module.Streams {
		if len(stream.Fields) == 0 {
			continue
		}
		e.emitStruct(stream.Name, stream.Fields)
	}
	for _, enum := range module.Enums {
		e.emitEnum(enum)
	}
	resources := append([]vdmir.Resource(nil), module.Resources...)
	if len(module.GraphicsEntryPoints) == 0 {
		// Pre-M41 compute artifacts emitted resource bundles in name order. VD-MIR
		// retains canonical source order, while this backend-only compatibility
		// projection preserves production SPIR-V byte identity.
		for start := 0; start < len(resources); {
			end := start + 1
			for end < len(resources) && resources[end].BundleName == resources[start].BundleName {
				end++
			}
			if resources[start].BundleName != "" {
				bundle := resources[start:end]
				sort.SliceStable(bundle, func(i, j int) bool {
					return bundle[i].Name < bundle[j].Name
				})
			}
			start = end
		}
	}
	for _, resource := range resources {
		e.emitResource(resource)
	}
	for _, material := range module.Materials {
		e.emitMaterial(material)
	}
	for _, workgroup := range module.Workgroups {
		e.emitWorkgroup(workgroup)
	}
	if len(module.Resources) > 0 || len(module.Materials) > 0 || len(module.Workgroups) > 0 {
		e.line("")
	}
	entrySet := map[string]vdmir.ComputeEntryPoint{}
	for _, entry := range module.EntryPoints {
		entrySet[entry.EmittedName] = entry
	}
	e.graphicsEntries = map[string]vdmir.GraphicsEntryPoint{}
	for _, entry := range module.GraphicsEntryPoints {
		e.graphicsEntries[entry.EmittedName] = entry
	}
	for _, fn := range module.Functions {
		e.emitFunction(fn, entrySet[fn.EmittedName])
	}
	if e.err != nil {
		return "", e.err
	}
	return e.builder.String(), nil
}

// EmitBenchmark emits one ordinary SDSL-V function behind a minimal compute
// entry point. Benchmark metadata is compiler-owned; this backend only emits
// the already selected entry and deliberately adds no test result ABI.
func EmitBenchmark(module vdmir.Module, function string, workgroup [3]uint32) (string, error) {
	var e emitter
	e.line("// Generated by GoOct SDSL-V M36a. Do not edit.")
	for _, record := range module.Records {
		e.emitStruct(record.Name, record.Fields)
	}
	for _, enum := range module.Enums {
		e.emitEnum(enum)
	}
	for _, resource := range module.Resources {
		e.emitResource(resource)
	}
	var selected *vdmir.ComputeEntryPoint
	for i := range module.EntryPoints {
		if module.EntryPoints[i].FunctionName == function {
			selected = &module.EntryPoints[i]
			break
		}
	}
	if selected != nil {
		for _, fn := range module.Functions {
			if fn.Name == function {
				copy := fn
				copy.EmittedName = "main"
				e.emitFunction(copy, *selected)
				if e.err != nil {
					return "", e.err
				}
				return e.builder.String(), nil
			}
		}
		return "", fmt.Errorf("benchmark entry %s is missing", function)
	}
	emitted := function
	for _, fn := range module.Functions {
		if fn.Name == function {
			emitted = fn.EmittedName
		}
		e.emitFunction(fn, vdmir.ComputeEntryPoint{})
	}
	if e.err != nil {
		return "", e.err
	}
	e.line(fmt.Sprintf("[numthreads(%d, %d, %d)]", workgroup[0], workgroup[1], workgroup[2]))
	e.line("void main(uint3 DispatchThreadID : SV_DispatchThreadID) {")
	e.indent++
	e.line(emitted + "();")
	e.indent--
	e.line("}")
	return e.builder.String(), nil
}

type emitter struct {
	builder         strings.Builder
	indent          int
	tempCounter     int
	viewAliases     map[string]vdmir.RowMajorViewExpr
	testMode        bool
	testFunctions   map[string]bool
	err             error
	graphicsEntries map[string]vdmir.GraphicsEntryPoint
}

// materializedLValue is the shared-backend address boundary. Address
// components are evaluated once in source order, and Text can then be reused
// for both a load and a store without repeating those expressions.
type materializedLValue struct {
	Base              string
	AddressComponents []string
	LinearOffset      string
	Text              string
	ValueType         vdmir.Type
	SourceSpan        source.Span
}

func (e *emitter) emitStruct(name string, fields []vdmir.Field) {
	e.line("struct " + name)
	e.line("{")
	e.indent++
	for _, field := range fields {
		prefix := ""
		if field.HasLocation {
			prefix = fmt.Sprintf("[[vk::location(%d)]] ", field.Location)
		}
		switch field.Interpolation {
		case "flat":
			prefix += "nointerpolation "
		case "noperspective":
			prefix += "noperspective "
		}
		semantic := ""
		if field.Semantic != "" {
			semantic = " : " + field.Semantic
		}
		e.line(fmt.Sprintf("%s%s%s;", prefix, typeRef(field.Type, field.Name), semantic))
	}
	e.indent--
	e.line("};")
	e.line("")
}

func (e *emitter) emitEnum(enum vdmir.Enum) {
	for i, variant := range enum.Variants {
		e.line(fmt.Sprintf("static const int %s_%s = %d;", enum.Name, variant.Name, i))
	}
	for _, variant := range enum.Variants {
		if !variant.HasPayload {
			continue
		}
		e.emitStruct(enumPayloadTypeName(enum.Name, variant.Name), variant.Payload)
	}
	e.line("struct " + enum.Name)
	e.line("{")
	e.indent++
	e.line("int Tag;")
	for _, variant := range enum.Variants {
		if !variant.HasPayload {
			continue
		}
		e.line(fmt.Sprintf("%s %s;", enumPayloadTypeName(enum.Name, variant.Name), hlslIdentifier(variant.Name)))
	}
	e.indent--
	e.line("};")
	e.line("")
	for _, variant := range enum.Variants {
		e.emitEnumConstructor(enum.Name, variant)
	}
}

func (e *emitter) emitEnumConstructor(enumName string, variant vdmir.EnumVariant) {
	params := make([]string, 0, len(variant.Payload))
	for _, field := range variant.Payload {
		params = append(params, typeRef(field.Type, field.Name))
	}
	e.line(fmt.Sprintf("%s %s(%s)", enumName, enumConstructorName(enumName, variant.Name), strings.Join(params, ", ")))
	e.line("{")
	e.indent++
	e.line(fmt.Sprintf("%s value;", enumName))
	e.line(fmt.Sprintf("value.Tag = %s_%s;", enumName, variant.Name))
	for _, field := range variant.Payload {
		e.line(fmt.Sprintf("value.%s.%s = %s;", hlslIdentifier(variant.Name), hlslIdentifier(field.Name), hlslIdentifier(field.Name)))
	}
	e.line("return value;")
	e.indent--
	e.line("}")
	e.line("")
}

func (e *emitter) emitResource(resource vdmir.Resource) {
	prefix := fmt.Sprintf("[[vk::binding(%d, %d)]] ", resource.Binding.Binding, resource.Binding.Set)
	switch resource.Kind {
	case vdmir.ResourceTexture2D:
		e.line(fmt.Sprintf("%sTexture2D<%s> %s;", prefix, typeRef(resource.ElementType, ""), hlslIdentifier(resource.Name)))
	case vdmir.ResourceSampler:
		e.line(fmt.Sprintf("%sSamplerState %s;", prefix, hlslIdentifier(resource.Name)))
	case vdmir.ResourceUniform:
		e.line(fmt.Sprintf("%sConstantBuffer<%s> %s;", prefix, typeRef(resource.ElementType, ""), hlslIdentifier(resource.Name)))
	default:
		elem := typeRef(resource.ElementType, "")
		if resource.Access == vdmir.ResourceReadOnly {
			e.line(fmt.Sprintf("%sStructuredBuffer<%s> %s;", prefix, elem, hlslIdentifier(resource.Name)))
			return
		}
		e.line(fmt.Sprintf("%sRWStructuredBuffer<%s> %s;", prefix, elem, hlslIdentifier(resource.Name)))
	}
}

func (e *emitter) emitMaterial(material vdmir.Material) {
	e.line(fmt.Sprintf("[[vk::binding(%d, %d)]] ConstantBuffer<%s> Material;", material.Binding.Binding, material.Binding.Set, material.TypeName))
}

func (e *emitter) emitWorkgroup(workgroup vdmir.WorkgroupMemoryDecl) {
	if workgroup.IsTile {
		e.line(fmt.Sprintf("groupshared %s %s[%d * %d];", typeRef(workgroup.ElementType, ""), hlslIdentifier(workgroup.Name), workgroup.Rows, workgroup.Cols))
		return
	}
	e.line(fmt.Sprintf("groupshared %s;", typeRef(workgroup.Type, workgroup.Name)))
}

func (e *emitter) emitFunction(fn vdmir.Function, entry vdmir.ComputeEntryPoint) {
	e.viewAliases = map[string]vdmir.RowMajorViewExpr{}
	if entry.EmittedName != "" {
		e.emitEntryParamGlobals(entry)
	}
	if entry.EmittedName != "" {
		e.line(fmt.Sprintf("[numthreads(%d, %d, %d)]", entry.NumThreadsX, entry.NumThreadsY, entry.NumThreadsZ))
	}
	graphics := e.graphicsEntries[fn.EmittedName]
	params := make([]string, 0, len(fn.Params))
	if entry.EmittedName == "" {
		for _, param := range fn.Params {
			params = append(params, typeRef(param.Type, param.Name))
		}
		if e.testMode && e.testFunctions[fn.Name] {
			// Test bodies are ordinary lowered functions, but the generated test
			// wrapper is their compute entry point. Thread the one builtin that
			// test bodies may observe through that wrapper rather than inventing
			// test-only invocation semantics.
			params = append(params, "uint3 DispatchThreadID")
			params = append(params, "inout SdslvTestFailure failure")
		}
	} else {
		for _, builtin := range entry.Builtins {
			if builtin.Referenced {
				if builtin.SPIRVInputBuiltinID == 0 {
					params = append(params, fmt.Sprintf("%s %s : %s", typeRef(builtin.Type, ""), hlslIdentifier(builtin.Name), builtin.Semantic))
				}
			}
		}
	}
	returnSemantic := ""
	if graphics.Stage == vdmir.StagePixel && fn.ReturnType.Kind != vdmir.TypeStream {
		returnSemantic = " : SV_Target0"
	}
	e.line(fmt.Sprintf("%s %s(%s)%s", typeRef(fn.ReturnType, ""), fn.EmittedName, strings.Join(params, ", "), returnSemantic))
	e.line("{")
	e.indent++
	e.emitEntryThreadLocals(entry)
	for _, stmt := range fn.Body.Statements {
		e.emitStmt(stmt)
	}
	e.indent--
	e.line("}")
	e.line("")
}

func (e *emitter) emitEntryParamGlobals(entry vdmir.ComputeEntryPoint) {
	emittedBuiltin := false
	for _, builtin := range entry.Builtins {
		if !builtin.Referenced || builtin.SPIRVInputBuiltinID == 0 {
			continue
		}
		e.line(fmt.Sprintf("[[vk::ext_builtin_input(/* %s */ %d)]]", builtin.Name, builtin.SPIRVInputBuiltinID))
		e.line(fmt.Sprintf("static const %s %s;", typeRef(builtin.Type, ""), hlslIdentifier(builtin.Name)))
		emittedBuiltin = true
	}
	if emittedBuiltin {
		e.line("")
	}
	for _, param := range entry.Params {
		e.line(fmt.Sprintf("[[vk::push_constant]] ConstantBuffer<%s> %s;", typeRef(param.Type, ""), hlslIdentifier(param.Name)))
	}
	if len(entry.Params) > 0 {
		e.line("")
	}
}

func (e *emitter) emitEntryThreadLocals(entry vdmir.ComputeEntryPoint) {
	for _, thread := range entry.ThreadParams {
		e.line(fmt.Sprintf("%s %s;", thread.TypeName, hlslIdentifier(thread.ParamName)))
		for _, field := range thread.Fields {
			value := field.BuiltinName
			if field.BuiltinField != "" {
				value += "." + field.BuiltinField
			}
			e.line(fmt.Sprintf("%s.%s = %s;", hlslIdentifier(thread.ParamName), hlslIdentifier(field.FieldName), hlslExprPath(value)))
		}
	}
	if len(entry.ThreadParams) > 0 {
		e.line("")
	}
}

func (e *emitter) emitBlock(block vdmir.Block) {
	e.line("{")
	e.indent++
	for _, stmt := range block.Statements {
		e.emitStmt(stmt)
	}
	e.indent--
	e.line("}")
}

func (e *emitter) emitStmt(stmt vdmir.Stmt) {
	switch s := stmt.(type) {
	case vdmir.ForeignShaderStmt:
		e.emitForeignSource(s.Provenance.Path, s.SourceLine, s.RawSource)
	case vdmir.LetStmt:
		if s.Value == nil {
			e.line(fmt.Sprintf("%s;", typeRef(s.Type, s.Name)))
			return
		}
		if literal, ok := s.Value.(vdmir.NDArrayLiteral); ok {
			e.line(fmt.Sprintf("%s;", typeRef(s.Type, s.Name)))
			for i, value := range literal.Elements {
				e.line(fmt.Sprintf("%s[%d] = %s;", hlslIdentifier(s.Name), i, e.materializeExpr(value)))
			}
			return
		}
		if fill, ok := s.Value.(vdmir.FillConstruct); ok {
			e.emitFillConstructLet(s, fill)
			return
		}
		if generate, ok := s.Value.(vdmir.GenerateConstruct); ok {
			e.emitGenerateConstructLet(s, generate)
			return
		}
		if zero, ok := s.Value.(vdmir.RegTileZeroExpr); ok {
			e.emitRegTileZeroLet(s.Name, zero.Type())
			return
		}
		if rowMajor, ok := s.Value.(vdmir.RowMajorViewExpr); ok {
			e.viewAliases[s.Name] = rowMajor
			return
		}
		if reduction, ok := s.Value.(vdmir.ReductionExpr); ok {
			e.emitReductionLet(s, reduction)
			return
		}
		if utility, ok := s.Value.(vdmir.WhenUtilityExpr); ok {
			e.emitWhenUtilityLet(s, utility)
			return
		}
		if withExpr, ok := s.Value.(vdmir.WithExpr); ok {
			e.emitWithLet(s, withExpr)
			return
		}
		if matchExpr, ok := s.Value.(vdmir.MatchExpr); ok {
			e.emitMatchLet(s, matchExpr)
			return
		}
		if board, ok := s.Value.(vdmir.BoardConstructExpr); ok {
			e.emitBoardConstructLet(s, board)
			return
		}
		if derive, ok := s.Value.(vdmir.DeriveExpr); ok {
			e.emitDeriveLet(s, derive)
			return
		}
		value := e.materializeExpr(s.Value)
		e.line(fmt.Sprintf("%s = %s;", typeRef(s.Type, s.Name), value))
	case vdmir.AssignStmt:
		if reduction, ok := s.Value.(vdmir.ReductionExpr); ok {
			e.emitReductionAssign(e.expr(s.Target), reduction)
			return
		}
		if utility, ok := s.Value.(vdmir.WhenUtilityExpr); ok {
			e.emitWhenUtilityAssign(e.expr(s.Target), utility)
			return
		}
		if withExpr, ok := s.Value.(vdmir.WithExpr); ok {
			e.emitWithAssign(e.expr(s.Target), withExpr)
			return
		}
		if matchExpr, ok := s.Value.(vdmir.MatchExpr); ok {
			e.emitMatchAssign(e.expr(s.Target), matchExpr)
			return
		}
		if board, ok := s.Value.(vdmir.BoardConstructExpr); ok {
			e.emitBoardConstructAssign(e.expr(s.Target), board)
			return
		}
		if derive, ok := s.Value.(vdmir.DeriveExpr); ok {
			e.emitDeriveAssign(e.expr(s.Target), derive)
			return
		}
		value := e.materializeExpr(s.Value)
		e.line(fmt.Sprintf("%s = %s;", e.expr(s.Target), value))
	case vdmir.TensorAssign:
		e.emitTensorAssign(s, 0)
	case vdmir.GuardedWriteStmt:
		condition := e.materializeExpr(s.Condition)
		e.line("if (" + condition + ")")
		e.line("{")
		e.indent++
		value := e.materializeExpr(s.Value)
		e.line(fmt.Sprintf("%s = %s;", e.expr(s.Target), value))
		e.indent--
		e.line("}")
	case vdmir.ReturnStmt:
		if s.Value == nil {
			e.line("return;")
			return
		}
		if reduction, ok := s.Value.(vdmir.ReductionExpr); ok {
			e.emitReductionReturn(reduction)
			return
		}
		if withExpr, ok := s.Value.(vdmir.WithExpr); ok {
			e.emitWithReturn(withExpr)
			return
		}
		if matchExpr, ok := s.Value.(vdmir.MatchExpr); ok {
			e.emitMatchReturn(matchExpr)
			return
		}
		if board, ok := s.Value.(vdmir.BoardConstructExpr); ok {
			e.emitBoardConstructReturn(board)
			return
		}
		if derive, ok := s.Value.(vdmir.DeriveExpr); ok {
			e.emitDeriveReturn(derive)
			return
		}
		e.line("return " + e.materializeExpr(s.Value) + ";")
	case vdmir.ExprStmt:
		value := e.materializeExpr(s.Value)
		if value != "" {
			e.line(value + ";")
		}
	case vdmir.AssertStmt:
		e.emitTestAssert(s)
	case vdmir.BlockStmt:
		e.emitBlock(s.Body)
	case vdmir.FlowStmt:
		e.emitFlow(s.Flow)
	case vdmir.IfStmt:
		e.emitIfStmt(s)
	case vdmir.ForRangeStmt:
		switch s.LoopHint {
		case vdmir.LoopHintUnroll:
			e.line("[unroll]")
		case vdmir.LoopHintLoop:
			e.line("[loop]")
		}
		loopType := typeRef(s.Type, "")
		start := e.materializeExpr(s.Start)
		end := e.materializeExpr(s.End)
		step := e.materializeExpr(s.Step)
		e.line(fmt.Sprintf("for (%s %s = %s; %s < %s; %s += %s)", loopType, s.Name, start, s.Name, end, s.Name, step))
		e.emitBlock(s.Body)
	}
}

func (e *emitter) emitTensorAssign(stmt vdmir.TensorAssign, depth int) {
	if depth < len(stmt.FreeIndices) {
		index := stmt.FreeIndices[depth]
		e.flowMarker("tensor free-index loop", "", index.Span, index.Name)
		e.line(fmt.Sprintf("for (uint %s = 0u; %s < %du; %s += 1u)", index.ID, index.ID, index.Extent, index.ID))
		e.line("{")
		e.indent++
		e.emitTensorAssign(stmt, depth+1)
		e.indent--
		e.line("}")
		return
	}
	e.flowMarker("tensor statement", "", stmt.SourceSpan, string(stmt.AssignmentKind))
	destination := e.materializeIndexedLValue(stmt.Destination, stmt.SourceSpan)
	if e.err != nil {
		return
	}
	if stmt.AssignmentKind == vdmir.TensorAssignAdd {
		old := e.nextTempWithPrefix("tensor_old")
		e.line(fmt.Sprintf("%s %s = %s;", typeRef(stmt.ElementType, ""), old, destination.Text))
		rhs := e.nextTempWithPrefix("tensor_rhs")
		e.emitTensorValue(rhs, stmt.ElementType, stmt.Value)
		e.flowMarker("tensor final destination write", "", stmt.SourceSpan, "+=")
		e.line(fmt.Sprintf("%s = %s + %s;", destination.Text, old, rhs))
		return
	}
	rhs := e.nextTempWithPrefix("tensor_rhs")
	e.emitTensorValue(rhs, stmt.ElementType, stmt.Value)
	e.flowMarker("tensor final destination write", "", stmt.SourceSpan, "=")
	e.line(fmt.Sprintf("%s = %s;", destination.Text, rhs))
}

func (e *emitter) emitTensorValue(name string, typ vdmir.Type, value vdmir.Expr) {
	result := e.materializeExpr(value)
	e.line(fmt.Sprintf("%s %s = %s;", typeRef(typ, ""), name, result))
}

func (e *emitter) emitTensorReduction(target string, reduction vdmir.TensorReductionExpr, depth int) {
	if depth < len(reduction.Indices) {
		index := reduction.Indices[depth]
		e.flowMarker("tensor reduction loop", "", index.Span, index.Name)
		e.line(fmt.Sprintf("for (uint %s = 0u; %s < %du; %s += 1u)", index.ID, index.ID, index.Extent, index.ID))
		e.line("{")
		e.indent++
		e.emitTensorReduction(target, reduction, depth+1)
		e.indent--
		e.line("}")
		return
	}
	e.flowMarker("tensor reduction body", "", reduction.Span, reduction.Kind)
	body := e.materializeExpr(reduction.Body)
	e.line(fmt.Sprintf("%s = %s + (%s);", target, target, body))
}

func (e *emitter) emitIfStmt(stmt vdmir.IfStmt) {
	condition := e.materializeExpr(stmt.Condition)
	e.line("if (" + condition + ")")
	e.emitBlock(stmt.ThenBody)
	if stmt.ElseBody == nil {
		return
	}
	if len(stmt.ElseBody.Statements) == 1 {
		if nested, ok := stmt.ElseBody.Statements[0].(vdmir.IfStmt); ok {
			nestedCondition := e.materializeExpr(nested.Condition)
			e.line("else " + "if (" + nestedCondition + ")")
			e.emitBlock(nested.ThenBody)
			if nested.ElseBody != nil {
				e.emitElseTail(*nested.ElseBody)
			}
			return
		}
	}
	e.line("else")
	e.emitBlock(*stmt.ElseBody)
}

func (e *emitter) emitElseTail(block vdmir.Block) {
	if len(block.Statements) == 1 {
		if nested, ok := block.Statements[0].(vdmir.IfStmt); ok {
			nestedCondition := e.materializeExpr(nested.Condition)
			e.line("else " + "if (" + nestedCondition + ")")
			e.emitBlock(nested.ThenBody)
			if nested.ElseBody != nil {
				e.emitElseTail(*nested.ElseBody)
			}
			return
		}
	}
	e.line("else")
	e.emitBlock(block)
}

// emitFlow is the shared backend execution model for M31b flows.  State IDs
// are declaration-order IDs from validated VD-MIR; 0xffffffff is FlowComplete.
func (e *emitter) emitFlow(flow vdmir.Flow) {
	if err := validateFlow(flow); err != nil {
		e.err = err
		return
	}
	name := "__flow_" + sanitizeName(flow.Name) + "_" + fmt.Sprintf("%d", e.tempCounter)
	e.tempCounter++
	state, complete := name+"_state", "4294967295u"
	dispatcherSpan := flow.SourceSpan
	if !dispatcherSpan.Known() && len(flow.States) != 0 {
		dispatcherSpan = flow.States[flow.Entry].NameSpan
	}
	e.flowMarker("flow dispatcher", flow.Provenance.Path, dispatcherSpan, flow.Name)
	e.line(fmt.Sprintf("uint %s = %du;", state, flow.Entry))
	top, stack := name+"_stack_top", name+"_return_stack"
	if flow.HasPushPop {
		e.flowMarker("flow stack", flow.Provenance.Path, dispatcherSpan, fmt.Sprintf("MaxStackDepth=%d", flow.MaxStackDepth))
		e.line(fmt.Sprintf("uint %s = 0u;", top))
		e.line(fmt.Sprintf("uint %s[%d];", stack, flow.MaxStackDepth))
	}
	e.line(fmt.Sprintf("while (%s != %s)", state, complete))
	e.line("{")
	e.indent++
	e.line(fmt.Sprintf("switch (%s)", state))
	e.line("{")
	e.indent++
	for _, s := range flow.States {
		e.flowMarker("flow state", flow.Provenance.Path, s.NameSpan, s.Name)
		e.line(fmt.Sprintf("case %du:", s.ID))
		e.line("{")
		e.indent++
		for _, stmt := range s.Body.Statements {
			e.emitStmt(stmt)
		}
		e.emitFlowTerminator(s.Terminator, state, top, stack, complete)
		e.line("break;")
		e.indent--
		e.line("}")
	}
	e.line("default:")
	e.line("{")
	e.indent++
	e.line(state + " = " + complete + ";")
	e.line("break;")
	e.indent--
	e.line("}")
	e.indent--
	e.line("}")
	e.indent--
	e.line("}")
}

func (e *emitter) emitFlowTerminator(t vdmir.FlowTerminator, state, top, stack, complete string) {
	value := func(id int) string {
		if id == vdmir.FlowCompleteStateID {
			return complete
		}
		return fmt.Sprintf("%du", id)
	}
	switch t.Kind {
	case vdmir.FlowTerminatorFallthrough, vdmir.FlowTerminatorGoto:
		e.flowMarker("flow terminator", "", t.Span, string(t.Kind))
		e.line(state + " = " + value(t.Target) + ";")
	case vdmir.FlowTerminatorFinish:
		e.flowMarker("flow terminator", "", t.Span, string(t.Kind))
		e.line(state + " = " + complete + ";")
	case vdmir.FlowTerminatorPush:
		e.flowMarker("flow terminator", "", t.Span, fmt.Sprintf("%s target=%s return=%s", t.Kind, value(t.Target), value(t.ReturnTo)))
		e.flowMarker("flow stack push", "", t.Span, "")
		e.line(fmt.Sprintf("%s[%s] = %s;", stack, top, value(t.ReturnTo)))
		e.line(top + " += 1u;")
		e.line(state + " = " + value(t.Target) + ";")
	case vdmir.FlowTerminatorPop:
		e.flowMarker("flow terminator", "", t.Span, string(t.Kind))
		e.flowMarker("flow stack pop", "", t.Span, "")
		e.line(top + " -= 1u;")
		e.line(state + " = " + stack + "[" + top + "];")
	}
}

func (e *emitter) flowMarker(kind, path string, span source.Span, detail string) {
	if !span.Known() {
		if detail != "" {
			e.line("// " + kind + ": " + detail)
			return
		}
		e.line("// " + kind)
		return
	}
	location := fmt.Sprintf("%d:%d", span.Start.Line, span.Start.Column)
	if path != "" {
		location = path + ":" + location
	}
	if detail != "" {
		e.line(fmt.Sprintf("// %s %s %s", kind, location, detail))
		return
	}
	e.line(fmt.Sprintf("// %s %s", kind, location))
}

func validateFlow(flow vdmir.Flow) error {
	if flow.Entry < 0 || flow.Entry >= len(flow.States) {
		return fmt.Errorf("malformed FlowProgram %s: invalid entry state ID %d", flow.Name, flow.Entry)
	}
	if flow.HasPushPop && flow.MaxStackDepth == 0 {
		return fmt.Errorf("malformed FlowProgram %s: push/pop requires positive MaxStackDepth", flow.Name)
	}
	seen := map[int]bool{}
	for _, s := range flow.States {
		if s.ID < 0 || seen[s.ID] {
			return fmt.Errorf("malformed FlowProgram %s: duplicate or invalid state ID %d", flow.Name, s.ID)
		}
		seen[s.ID] = true
	}
	valid := func(id int) bool { return id == vdmir.FlowCompleteStateID || seen[id] }
	for _, s := range flow.States {
		switch t := s.Terminator; t.Kind {
		case vdmir.FlowTerminatorFallthrough, vdmir.FlowTerminatorGoto:
			if !valid(t.Target) {
				return fmt.Errorf("malformed FlowProgram %s: invalid target state ID %d", flow.Name, t.Target)
			}
		case vdmir.FlowTerminatorPush:
			if !flow.HasPushPop || !valid(t.Target) || !valid(t.ReturnTo) {
				return fmt.Errorf("malformed FlowProgram %s: invalid push terminator", flow.Name)
			}
		case vdmir.FlowTerminatorPop:
			if !flow.HasPushPop {
				return fmt.Errorf("malformed FlowProgram %s: pop without return-stack contract", flow.Name)
			}
		case vdmir.FlowTerminatorFinish:
		default:
			return fmt.Errorf("malformed FlowProgram %s: unsupported terminator %q", flow.Name, t.Kind)
		}
	}
	return nil
}

func (e *emitter) emitWhenUtilityLet(stmt vdmir.LetStmt, utility vdmir.WhenUtilityExpr) {
	otherwise := e.materializeExpr(utility.Else)
	e.line(fmt.Sprintf("%s = %s;", typeRef(stmt.Type, stmt.Name), otherwise))
	e.emitWhenUtilityAssign(hlslIdentifier(stmt.Name), utility)
}

func (e *emitter) emitReductionLet(stmt vdmir.LetStmt, reduction vdmir.ReductionExpr) {
	e.line(fmt.Sprintf("%s = %s;", typeRef(stmt.Type, stmt.Name), reductionIdentityLiteral(reduction)))
	e.emitReductionLoop(hlslIdentifier(stmt.Name), reduction)
}

func (e *emitter) emitReductionAssign(target string, reduction vdmir.ReductionExpr) {
	tempName := e.nextTempWithPrefix("reduce")
	e.line(fmt.Sprintf("%s = %s;", typeRef(reduction.Type(), tempName), reductionIdentityLiteral(reduction)))
	e.emitReductionLoop(tempName, reduction)
	e.line(fmt.Sprintf("%s = %s;", target, tempName))
}

func (e *emitter) emitReductionReturn(reduction vdmir.ReductionExpr) {
	tempName := e.nextTempWithPrefix("reduce")
	e.line(fmt.Sprintf("%s = %s;", typeRef(reduction.Type(), tempName), reductionIdentityLiteral(reduction)))
	e.emitReductionLoop(tempName, reduction)
	e.line("return " + tempName + ";")
}

func (e *emitter) emitReductionLoop(target string, reduction vdmir.ReductionExpr) {
	e.emitReductionLoopMaterialized(target, reduction)
}

func (e *emitter) emitWhenUtilityAssign(target string, utility vdmir.WhenUtilityExpr) {
	scoreName := "__sdslv_" + sanitizeName(target) + "_score"
	e.line(fmt.Sprintf("float %s = -3.402823466e+38F;", scoreName))
	for _, c := range utility.Cases {
		guard := e.materializeExpr(c.Guard)
		score := e.materializeExpr(c.Score)
		e.line(fmt.Sprintf("if (%s && (%s > %s))", guard, score, scoreName))
		e.line("{")
		e.indent++
		e.line(fmt.Sprintf("%s = %s;", scoreName, score))
		value := e.materializeExpr(c.Value)
		e.line(fmt.Sprintf("%s = %s;", target, value))
		e.indent--
		e.line("}")
	}
}

func (e *emitter) emitWithLet(stmt vdmir.LetStmt, withExpr vdmir.WithExpr) {
	tempName := e.nextTemp()
	e.emitWithCopy(tempName, withExpr)
	e.line(fmt.Sprintf("%s = %s;", typeRef(stmt.Type, stmt.Name), tempName))
}

func (e *emitter) emitWithAssign(target string, withExpr vdmir.WithExpr) {
	tempName := e.nextTemp()
	e.emitWithCopy(tempName, withExpr)
	e.line(fmt.Sprintf("%s = %s;", target, tempName))
}

func (e *emitter) emitWithReturn(withExpr vdmir.WithExpr) {
	tempName := e.nextTemp()
	e.emitWithCopy(tempName, withExpr)
	e.line("return " + tempName + ";")
}

func (e *emitter) emitWithCopy(tempName string, withExpr vdmir.WithExpr) {
	base := e.materializeExpr(withExpr.Base)
	e.line(fmt.Sprintf("%s %s = %s;", typeRef(withExpr.Type(), ""), tempName, base))
	for _, update := range withExpr.Updates {
		value := e.materializeExpr(update.Value)
		e.line(fmt.Sprintf("%s.%s = %s;", tempName, hlslIdentifier(update.Name), value))
	}
}

func (e *emitter) emitMatchLet(stmt vdmir.LetStmt, matchExpr vdmir.MatchExpr) {
	e.line(fmt.Sprintf("%s;", typeRef(stmt.Type, stmt.Name)))
	e.emitMatchAssign(hlslIdentifier(stmt.Name), matchExpr)
}

func (e *emitter) emitMatchAssign(target string, matchExpr vdmir.MatchExpr) {
	subjectName := e.nextTempWithPrefix("match_subject")
	subject := e.materializeExpr(matchExpr.Subject)
	e.line(fmt.Sprintf("%s %s = %s;", typeRef(matchExpr.Subject.Type(), ""), subjectName, subject))
	for i, arm := range matchExpr.Arms {
		keyword := "if"
		if i > 0 {
			keyword = "else if"
		}
		e.line(fmt.Sprintf("%s (%s.Tag == %s_%s)", keyword, subjectName, arm.EnumName, arm.VariantName))
		e.line("{")
		e.indent++
		if arm.BindingName != "" {
			e.line(fmt.Sprintf("%s %s = %s.%s;", typeRef(arm.BindingType, ""), hlslIdentifier(arm.BindingName), subjectName, hlslIdentifier(arm.VariantName)))
		}
		value := e.materializeExpr(arm.Value)
		e.line(fmt.Sprintf("%s = %s;", target, value))
		e.indent--
		e.line("}")
	}
}

func (e *emitter) emitMatchReturn(matchExpr vdmir.MatchExpr) {
	tempName := e.nextTempWithPrefix("match_result")
	e.line(fmt.Sprintf("%s %s;", typeRef(matchExpr.Type(), ""), tempName))
	e.emitMatchAssign(tempName, matchExpr)
	e.line("return " + tempName + ";")
}

func (e *emitter) emitGuardedReadLet(stmt vdmir.LetStmt, guarded vdmir.GuardedReadExpr) {
	tempName := e.emitGuardedReadValue(guarded)
	e.line(fmt.Sprintf("%s = %s;", typeRef(stmt.Type, stmt.Name), tempName))
}

func (e *emitter) emitGuardedReadAssign(target string, guarded vdmir.GuardedReadExpr) {
	tempName := e.emitGuardedReadValue(guarded)
	// A guarded read is a value expression.  Keep the surrounding assignment
	// outside its conditional load so false guards still write the fallback.
	e.line(fmt.Sprintf("%s = %s;", target, tempName))
}

func (e *emitter) emitGuardedReadValue(guarded vdmir.GuardedReadExpr) string {
	tempName := e.nextTempWithPrefix("guarded_read")
	e.line(fmt.Sprintf("%s %s = %s;", typeRef(guarded.Type(), ""), tempName, e.expr(guarded.Fallback)))
	e.line("if (" + e.expr(guarded.Condition) + ")")
	e.line("{")
	e.indent++
	e.line(fmt.Sprintf("%s = %s;", tempName, e.expr(guarded.Target)))
	e.indent--
	e.line("}")
	return tempName
}

func (e *emitter) emitGuardedReadReturn(guarded vdmir.GuardedReadExpr) {
	tempName := e.emitGuardedReadValue(guarded)
	e.line("return " + tempName + ";")
}

func (e *emitter) emitBoardConstructLet(stmt vdmir.LetStmt, board vdmir.BoardConstructExpr) {
	e.line(fmt.Sprintf("%s;", typeRef(stmt.Type, stmt.Name)))
	e.emitBoardFieldAssignments(hlslIdentifier(stmt.Name), board)
}

func (e *emitter) emitBoardConstructAssign(target string, board vdmir.BoardConstructExpr) {
	e.emitBoardFieldAssignments(target, board)
}

func (e *emitter) emitBoardConstructReturn(board vdmir.BoardConstructExpr) {
	tempName := e.nextTempWithPrefix("board")
	e.line(fmt.Sprintf("%s;", typeRef(board.Type(), tempName)))
	e.emitBoardFieldAssignments(tempName, board)
	e.line("return " + tempName + ";")
}

func (e *emitter) emitBoardFieldAssignments(target string, board vdmir.BoardConstructExpr) {
	for _, field := range board.Fields {
		value := e.materializeExpr(field.Value)
		e.line(fmt.Sprintf("%s.%s = %s;", target, hlslIdentifier(field.Name), value))
	}
}

func (e *emitter) emitDeriveLet(stmt vdmir.LetStmt, derive vdmir.DeriveExpr) {
	e.emitDeriveTemps(derive)
	e.line(fmt.Sprintf("%s;", typeRef(stmt.Type, stmt.Name)))
	e.emitDeriveResultAssignments(hlslIdentifier(stmt.Name), derive)
}

func (e *emitter) emitDeriveAssign(target string, derive vdmir.DeriveExpr) {
	e.emitDeriveTemps(derive)
	e.emitDeriveResultAssignments(target, derive)
}

func (e *emitter) emitDeriveReturn(derive vdmir.DeriveExpr) {
	e.emitDeriveTemps(derive)
	tempName := e.nextTempWithPrefix("derive_result")
	e.line(fmt.Sprintf("%s;", typeRef(derive.Type(), tempName)))
	e.emitDeriveResultAssignments(tempName, derive)
	e.line("return " + tempName + ";")
}

func (e *emitter) emitDeriveTemps(derive vdmir.DeriveExpr) {
	for _, field := range derive.Fields {
		value := e.materializeExpr(field.Value)
		e.line(fmt.Sprintf("%s = %s;", typeRef(field.Value.Type(), field.TempName), value))
	}
}

func (e *emitter) emitDeriveResultAssignments(target string, derive vdmir.DeriveExpr) {
	for _, field := range derive.Fields {
		e.line(fmt.Sprintf("%s.%s = %s;", target, hlslIdentifier(field.Name), hlslIdentifier(field.TempName)))
	}
}

// materializeExpr emits any required prelude and returns a stable HLSL value.
// Recursive operands are visited in source order. Structured expressions that
// cannot be represented safely as an inline HLSL expression always receive a
// deterministic compiler-owned temporary.
func (e *emitter) materializeExpr(expr vdmir.Expr) string {
	if expr == nil {
		e.err = fmt.Errorf("cannot materialize nil VD-MIR expression")
		return "0"
	}
	switch x := expr.(type) {
	case vdmir.ForeignShaderExpr:
		name := e.nextTempWithPrefix("inline_hlsl")
		e.line(fmt.Sprintf("%s;", typeRef(x.Type(), name)))
		e.emitForeignExpressionAssignment(name, x)
		return name
	case vdmir.GuardedReadExpr:
		name := e.nextTempWithPrefix("guarded_read")
		fallback := e.materializeExpr(x.Fallback)
		e.line(fmt.Sprintf("%s %s = %s;", typeRef(x.Type(), ""), name, fallback))
		condition := e.materializeExpr(x.Condition)
		e.line("if (" + condition + ")")
		e.line("{")
		e.indent++
		target := e.materializeExpr(x.Target)
		e.line(fmt.Sprintf("%s = %s;", name, target))
		e.indent--
		e.line("}")
		return name
	case vdmir.TensorReductionExpr:
		name := e.nextTempWithPrefix("tensor_accumulator")
		e.flowMarker("tensor accumulator initialization", x.Provenance.Path, x.Span, x.Kind)
		identity := e.materializeExpr(x.Identity)
		e.line(fmt.Sprintf("%s %s = %s;", typeRef(x.Type(), ""), name, identity))
		e.emitTensorReduction(name, x, 0)
		return name
	case vdmir.ReductionExpr:
		name := e.nextTempWithPrefix("reduce")
		e.line(fmt.Sprintf("%s %s = %s;", typeRef(x.Type(), ""), name, reductionIdentityLiteral(x)))
		e.emitReductionLoopMaterialized(name, x)
		return name
	case vdmir.IndexExpr, vdmir.Index2DExpr, vdmir.IndexNExpr:
		if !exprNeedsPrelude(expr) {
			return e.expr(expr)
		}
		lvalue := e.materializeIndexedLValue(x, source.Span{})
		name := e.nextTempWithPrefix("indexed_value")
		e.line(fmt.Sprintf("%s %s = %s;", typeRef(expr.Type(), ""), name, lvalue.Text))
		return name
	case vdmir.BinaryExpr:
		left := e.materializeOperand(x.Left)
		right := e.materializeOperand(x.Right)
		return "(" + left + " " + x.Operator + " " + right + ")"
	case vdmir.UnaryExpr:
		operand := e.materializeOperand(x.Operand)
		return x.Operator + operand
	case vdmir.CallExpr:
		callee := e.materializeExpr(x.Callee)
		args := make([]string, 0, len(x.Arguments))
		for _, arg := range x.Arguments {
			args = append(args, e.materializeOperand(arg))
		}
		call := callee + "(" + strings.Join(args, ", ") + ")"
		if x.Type().Kind == vdmir.TypeVoid {
			e.line(call + ";")
			return ""
		}
		return call
	case vdmir.IntrinsicCallExpr:
		if x.Intrinsic == vdmir.IntrinsicCooperativeMatMulF16F32M16N16K16Subgroup {
			args := make([]string, 0, len(x.Arguments))
			for _, arg := range x.Arguments {
				args = append(args, e.materializeExpr(arg))
			}
			e.emitCooperativeMatMul(args)
			return ""
		}
		if x.Intrinsic == vdmir.IntrinsicPackF16x2 {
			a := e.materializeOperand(x.Arguments[0])
			return "(f32tof16(" + a + ").x | (f32tof16(" + a + ").y << 16u))"
		}
		args := make([]string, 0, len(x.Arguments))
		for _, arg := range x.Arguments {
			args = append(args, e.materializeExpr(arg))
		}
		return e.m35Intrinsic(x, args)
	case vdmir.VectorExtractExpr:
		return e.materializeExpr(x.Target) + "." + x.Component
	case vdmir.FieldAccessExpr:
		target := e.materializeExpr(x.Target)
		return target + "." + hlslIdentifier(x.Field)
	case vdmir.WhenUtilityExpr:
		name := e.nextTempWithPrefix("utility")
		otherwise := e.materializeExpr(x.Else)
		e.line(fmt.Sprintf("%s %s = %s;", typeRef(x.Type(), ""), name, otherwise))
		e.emitWhenUtilityAssign(name, x)
		return name
	case vdmir.WithExpr:
		name := e.nextTempWithPrefix("with")
		e.emitWithCopy(name, x)
		return name
	case vdmir.MatchExpr:
		name := e.nextTempWithPrefix("match_result")
		e.line(fmt.Sprintf("%s %s;", typeRef(x.Type(), ""), name))
		e.emitMatchAssign(name, x)
		return name
	case vdmir.BoardConstructExpr:
		name := e.nextTempWithPrefix("board")
		e.line(fmt.Sprintf("%s %s;", typeRef(x.Type(), ""), name))
		e.emitBoardFieldAssignments(name, x)
		return name
	case vdmir.DeriveExpr:
		e.emitDeriveTemps(x)
		name := e.nextTempWithPrefix("derive_result")
		e.line(fmt.Sprintf("%s %s;", typeRef(x.Type(), ""), name))
		e.emitDeriveResultAssignments(name, x)
		return name
	case vdmir.EnumConstructExpr:
		args := make([]string, 0, len(x.Fields))
		for _, field := range x.Fields {
			args = append(args, e.materializeOperand(field.Value))
		}
		return enumConstructorName(x.EnumName, x.VariantName) + "(" + strings.Join(args, ", ") + ")"
	default:
		return e.expr(expr)
	}
}

func (e *emitter) materializeOperand(expr vdmir.Expr) string {
	value := e.materializeExpr(expr)
	switch expr.(type) {
	case vdmir.CallExpr:
		if expr.Type().Kind == vdmir.TypeVoid {
			return value
		}
		name := e.nextTempWithPrefix("operand")
		e.line(fmt.Sprintf("%s %s = %s;", typeRef(expr.Type(), ""), name, value))
		return name
	default:
		return value
	}
}

func exprNeedsPrelude(expr vdmir.Expr) bool {
	switch x := expr.(type) {
	case vdmir.ForeignShaderExpr, vdmir.GuardedReadExpr, vdmir.TensorReductionExpr, vdmir.ReductionExpr:
		return true
	case vdmir.IndexExpr:
		return exprNeedsPrelude(x.Index) || exprNeedsPrelude(x.Target)
	case vdmir.Index2DExpr:
		return exprNeedsPrelude(x.Row) || exprNeedsPrelude(x.Col) || (x.Stride != nil && exprNeedsPrelude(x.Stride)) || exprNeedsPrelude(x.Target)
	case vdmir.IndexNExpr:
		if exprNeedsPrelude(x.Target) {
			return true
		}
		for _, index := range x.Indices {
			if exprNeedsPrelude(index) {
				return true
			}
		}
	case vdmir.CallExpr:
		return true
	case vdmir.IntrinsicCallExpr:
		if x.Intrinsic == vdmir.IntrinsicCooperativeMatMulF16F32M16N16K16Subgroup {
			return true
		}
		if x.Intrinsic == vdmir.IntrinsicPackF16x2 {
			return true
		}
		for _, arg := range x.Arguments {
			if exprNeedsPrelude(arg) {
				return true
			}
		}
		return false
	case vdmir.FieldAccessExpr:
		return exprNeedsPrelude(x.Target)
	case vdmir.WhenUtilityExpr, vdmir.WithExpr, vdmir.MatchExpr, vdmir.BoardConstructExpr, vdmir.DeriveExpr:
		return true
	case vdmir.BinaryExpr:
		return exprNeedsPrelude(x.Left) || exprNeedsPrelude(x.Right)
	case vdmir.UnaryExpr:
		return exprNeedsPrelude(x.Operand)
	}
	return false
}

func (e *emitter) emitReductionLoopMaterialized(target string, reduction vdmir.ReductionExpr) {
	switch reduction.LoopHint {
	case vdmir.LoopHintUnroll:
		e.line("[unroll]")
	case vdmir.LoopHintLoop:
		e.line("[loop]")
	}
	start := e.materializeExpr(reduction.Start)
	end := e.materializeExpr(reduction.End)
	step := e.materializeExpr(reduction.Step)
	loopName := hlslIdentifier(reduction.Name)
	e.line(fmt.Sprintf("for (%s %s = %s; %s < %s; %s += %s)", typeRef(reduction.IndexType, ""), loopName, start, loopName, end, loopName, step))
	e.line("{")
	e.indent++
	body := e.materializeExpr(reduction.Body)
	e.line(fmt.Sprintf("%s = %s %s (%s);", target, target, reductionCombineOperator(reduction.Op), body))
	e.indent--
	e.line("}")
}

func (e *emitter) materializeIndexedLValue(expr vdmir.Expr, span source.Span) materializedLValue {
	result := materializedLValue{ValueType: expr.Type(), SourceSpan: span}
	component := func(value vdmir.Expr) string {
		text := e.materializeExpr(value)
		name := e.nextTempWithPrefix("tensor_index")
		e.line(fmt.Sprintf("uint %s = %s;", name, text))
		result.AddressComponents = append(result.AddressComponents, name)
		return name
	}
	switch x := expr.(type) {
	case vdmir.IndexNExpr:
		if x.Layout != vdmir.IndexLayoutRowMajorLinear || len(x.Indices) == 0 || len(x.Indices) != len(x.Extents) {
			e.err = fmt.Errorf("invalid rank-general fixed-array linearization metadata")
			return result
		}
		result.Base = e.expr(x.Target)
		parts := make([]string, 0, len(x.Indices))
		for _, index := range x.Indices {
			parts = append(parts, component(index))
		}
		offset := parts[0]
		for axis := 1; axis < len(parts); axis++ {
			if x.Extents[axis] == 0 {
				e.err = fmt.Errorf("invalid zero extent in rank-general fixed-array linearization")
				return result
			}
			offset = fmt.Sprintf("((%s * %du) + %s)", offset, x.Extents[axis], parts[axis])
		}
		result.LinearOffset = e.nextTempWithPrefix("tensor_offset")
		e.line(fmt.Sprintf("uint %s = %s;", result.LinearOffset, offset))
		result.Text = result.Base + "[" + result.LinearOffset + "]"
	case vdmir.Index2DExpr:
		result.Base = e.expr(x.Target)
		row := component(x.Row)
		col := component(x.Col)
		strideExpr := x.Stride
		if strideExpr == nil {
			if ref, ok := x.Target.(vdmir.VarRefExpr); ok {
				if alias, exists := e.viewAliases[ref.Name]; exists {
					result.Base = e.expr(alias.Buffer)
					strideExpr = alias.Cols
				}
			}
		}
		if strideExpr == nil {
			e.err = fmt.Errorf("missing stride for materialized 2D lvalue")
			return result
		}
		stride := component(strideExpr)
		result.LinearOffset = e.nextTempWithPrefix("tensor_offset")
		e.line(fmt.Sprintf("uint %s = ((%s * %s) + %s);", result.LinearOffset, row, stride, col))
		result.Text = result.Base + "[" + result.LinearOffset + "]"
	case vdmir.IndexExpr:
		result.Base = e.expr(x.Target)
		index := component(x.Index)
		result.LinearOffset = index
		result.Text = result.Base + "[" + index + "]"
		if target, ok := x.Target.(vdmir.VarRefExpr); ok && target.Name == vdmir.TestInputResourceName {
			switch x.Type().Kind {
			case vdmir.TypeBool:
				result.Text = "(" + result.Text + " != 0u)"
			case vdmir.TypeI32:
				result.Text = "asint(" + result.Text + ")"
			case vdmir.TypeF32:
				result.Text = "asfloat(" + result.Text + ")"
			}
		}
	default:
		e.err = fmt.Errorf("tensor destination is not an indexed lvalue: %T", expr)
	}
	return result
}

func (e *emitter) expr(expr vdmir.Expr) string {
	switch x := expr.(type) {
	case vdmir.ForeignShaderExpr:
		e.err = fmt.Errorf("inline HLSL expression bypassed shared materialization")
		return "0"
	case vdmir.LiteralExpr:
		return x.Value
	case vdmir.VarRefExpr:
		return hlslIdentifier(x.Name)
	case vdmir.FieldAccessExpr:
		return e.expr(x.Target) + "." + hlslIdentifier(x.Field)
	case vdmir.VectorExtractExpr:
		return e.expr(x.Target) + "." + x.Component
	case vdmir.IndexExpr:
		if text, ok := e.testInputIndex(x); ok {
			return text
		}
		return e.expr(x.Target) + "[" + e.expr(x.Index) + "]"
	case vdmir.Index2DExpr:
		return e.index2D(x)
	case vdmir.IndexNExpr:
		return e.indexN(x)
	case vdmir.TensorReductionExpr:
		e.err = fmt.Errorf("tensor reduction bypassed shared materialization")
		return "0"
	case vdmir.GuardedReadExpr:
		e.err = fmt.Errorf("guarded read bypassed shared materialization")
		return "0"
	case vdmir.RegTileZeroExpr:
		return "/* reg_tile_zero */"
	case vdmir.RowMajorViewExpr:
		return "/* matrix view */"
	case vdmir.CallExpr:
		args := make([]string, 0, len(x.Arguments))
		for _, arg := range x.Arguments {
			args = append(args, e.expr(arg))
		}
		return e.expr(x.Callee) + "(" + strings.Join(args, ", ") + ")"
	case vdmir.IntrinsicCallExpr:
		if x.Intrinsic == vdmir.IntrinsicCooperativeMatMulF16F32M16N16K16Subgroup {
			e.err = fmt.Errorf("cooperative matrix intrinsic bypassed statement materialization")
			return ""
		}
		if x.Intrinsic == vdmir.IntrinsicPackF16x2 {
			a := e.materializeOperand(x.Arguments[0])
			return "(f32tof16(" + a + ").x | (f32tof16(" + a + ").y << 16u))"
		}
		args := make([]string, 0, len(x.Arguments))
		for _, arg := range x.Arguments {
			args = append(args, e.expr(arg))
		}
		return e.m35Intrinsic(x, args)
	case vdmir.BinaryExpr:
		return "(" + e.expr(x.Left) + " " + x.Operator + " " + e.expr(x.Right) + ")"
	case vdmir.UnaryExpr:
		return x.Operator + e.expr(x.Operand)
	case vdmir.WhenUtilityExpr:
		return e.whenUtility(x)
	case vdmir.WithExpr:
		e.err = fmt.Errorf("with expression bypassed shared materialization")
		return "0"
	case vdmir.ReductionExpr:
		e.err = fmt.Errorf("reduction expression bypassed shared materialization")
		return "0"
	case vdmir.EnumConstructExpr:
		args := make([]string, 0, len(x.Fields))
		for _, field := range x.Fields {
			args = append(args, e.expr(field.Value))
		}
		return enumConstructorName(x.EnumName, x.VariantName) + "(" + strings.Join(args, ", ") + ")"
	case vdmir.BoardConstructExpr:
		e.err = fmt.Errorf("board construction bypassed shared materialization")
		return "0"
	case vdmir.DeriveExpr:
		e.err = fmt.Errorf("derive expression bypassed shared materialization")
		return "0"
	case vdmir.MatchExpr:
		e.err = fmt.Errorf("match expression bypassed shared materialization")
		return "0"
	default:
		return "/* unsupported */"
	}
}

func (e *emitter) testInputIndex(expr vdmir.IndexExpr) (string, bool) {
	target, ok := expr.Target.(vdmir.VarRefExpr)
	if !ok || target.Name != vdmir.TestInputResourceName {
		return "", false
	}
	base := e.expr(expr.Target) + "[" + e.expr(expr.Index) + "]"
	switch expr.Type().Kind {
	case vdmir.TypeBool:
		return "(" + base + " != 0u)", true
	case vdmir.TypeI32:
		return "asint(" + base + ")", true
	case vdmir.TypeF32:
		return "asfloat(" + base + ")", true
	default:
		return base, true
	}
}

func (e *emitter) emitForeignSource(path string, line int, raw string) {
	e.line(fmt.Sprintf("// BEGIN INLINE HLSL %s:%d", path, line))
	for _, sourceLine := range strings.Split(raw, "\n") {
		e.line(sourceLine)
	}
	e.line("// END INLINE HLSL")
}

func (e *emitter) emitForeignExprStatement(expr vdmir.ForeignShaderExpr) {
	temp := e.nextTempWithPrefix("inline_hlsl")
	e.line(fmt.Sprintf("%s;", typeRef(expr.Type(), temp)))
	e.emitForeignExpressionAssignment(temp, expr)
}

func (e *emitter) emitForeignExpressionAssignment(target string, expr vdmir.ForeignShaderExpr) {
	// HLSL has no portable immediate lambda expression. Keeping the source as a
	// local block makes it valid for DXC and preserves the declared result boundary.
	body := strings.Replace(expr.RawSource, "return", target+" =", 1)
	e.line("{")
	e.indent++
	e.emitForeignSource(expr.Provenance.Path, expr.SourceLine, body)
	e.indent--
	e.line("}")
}

func reductionIdentityLiteral(expr vdmir.ReductionExpr) string {
	switch expr.Op {
	case vdmir.ReductionProduct:
		return oneLiteral(expr.Type())
	default:
		return zeroLiteral(expr.Type())
	}
}

func reductionCombineOperator(op vdmir.ReductionOp) string {
	switch op {
	case vdmir.ReductionProduct:
		return "*"
	default:
		return "+"
	}
}

func zeroLiteral(ref vdmir.Type) string {
	switch ref.Kind {
	case vdmir.TypeF32:
		return "0.0"
	case vdmir.TypeU32:
		return "0u"
	default:
		return "0"
	}
}

func oneLiteral(ref vdmir.Type) string {
	switch ref.Kind {
	case vdmir.TypeF32:
		return "1.0"
	case vdmir.TypeU32:
		return "1u"
	default:
		return "1"
	}
}

func (e *emitter) whenUtility(expr vdmir.WhenUtilityExpr) string {
	var b strings.Builder
	b.WriteString("([&]() { auto __sdslv_best = ")
	b.WriteString(e.expr(expr.Else))
	b.WriteString("; float __sdslv_score = -3.402823466e+38F; ")
	for _, c := range expr.Cases {
		b.WriteString("if (")
		b.WriteString(e.expr(c.Guard))
		b.WriteString(" && (")
		b.WriteString(e.expr(c.Score))
		b.WriteString(" > __sdslv_score)) { __sdslv_score = ")
		b.WriteString(e.expr(c.Score))
		b.WriteString("; __sdslv_best = ")
		b.WriteString(e.expr(c.Value))
		b.WriteString("; } ")
	}
	b.WriteString("return __sdslv_best; })()")
	return b.String()
}

func (e *emitter) index2D(expr vdmir.Index2DExpr) string {
	target := e.expr(expr.Target)
	stride := expr.Stride
	if stride == nil {
		if ref, ok := expr.Target.(vdmir.VarRefExpr); ok {
			if alias, exists := e.viewAliases[ref.Name]; exists {
				target = e.expr(alias.Buffer)
				stride = alias.Cols
			}
		}
	}
	strideText := "0"
	if stride != nil {
		strideText = e.expr(stride)
	}
	return target + "[((" + e.expr(expr.Row) + ") * (" + strideText + ")) + (" + e.expr(expr.Col) + ")]"
}

func (e *emitter) indexN(expr vdmir.IndexNExpr) string {
	if expr.Layout != vdmir.IndexLayoutRowMajorLinear || len(expr.Indices) == 0 || len(expr.Indices) != len(expr.Extents) {
		e.err = fmt.Errorf("invalid rank-general fixed-array linearization metadata")
		return "0"
	}
	offset := e.expr(expr.Indices[0])
	for axis := 1; axis < len(expr.Indices); axis++ {
		offset = fmt.Sprintf("((%s * %du) + %s)", offset, expr.Extents[axis], e.expr(expr.Indices[axis]))
	}
	return e.expr(expr.Target) + "[" + offset + "]"
}

func (e *emitter) emitRegTileZeroLet(name string, typ vdmir.Type) {
	e.line(fmt.Sprintf("%s;", typeRef(typ, name)))
	elemType := elementTypeForArrayish(typ)
	for i := 0; i < typ.ArraySize; i++ {
		e.line(fmt.Sprintf("%s[%d] = %s;", name, i, zeroLiteral(elemType)))
	}
}

func validFixedShape(ref vdmir.Type) bool {
	_, _, ok := fixedShapeMetadata(ref)
	return ok
}

// emitFillConstructLet evaluates Value once, then reuses the materialized
// scalar for all compiler-owned flat row-major stores.
func (e *emitter) emitFillConstructLet(stmt vdmir.LetStmt, fill vdmir.FillConstruct) {
	elemType, shape, ok := fixedShapeMetadata(stmt.Type)
	_, _, fillOK := fixedShapeMetadata(fill.Type())
	if !ok || !fillOK {
		e.err = fmt.Errorf("malformed fixed-shape Fill metadata")
		return
	}
	e.line(fmt.Sprintf("%s;", typeRef(stmt.Type, stmt.Name)))
	temp := e.nextTempWithPrefix("fill")
	e.line(fmt.Sprintf("%s = %s;", typeRef(elemType, temp), e.materializeExpr(fill.Value)))
	count := 1
	for _, extent := range shape {
		count *= int(extent)
	}
	for i := 0; i < count; i++ {
		e.line(fmt.Sprintf("%s[%d] = %s;", hlslIdentifier(stmt.Name), i, temp))
	}
}

// emitGenerateConstructLet uses source binder order as loop nesting order;
// indexN owns the one row-major linearization formula used by ndarray access.
func (e *emitter) emitGenerateConstructLet(stmt vdmir.LetStmt, generate vdmir.GenerateConstruct) {
	_, shape, ok := fixedShapeMetadata(stmt.Type)
	_, _, generateOK := fixedShapeMetadata(generate.Type())
	if !ok || !generateOK || len(generate.Binders) != len(shape) {
		e.err = fmt.Errorf("malformed fixed-shape Generate metadata")
		return
	}
	e.line(fmt.Sprintf("%s;", typeRef(stmt.Type, stmt.Name)))
	indices := make([]vdmir.Expr, len(generate.Binders))
	for i, binder := range generate.Binders {
		indices[i] = vdmir.VarRefExpr{ExprType: vdmir.Type{Kind: vdmir.TypeU32, Name: "u32"}, Name: binder, Kind: vdmir.VarLocal}
	}
	var emitAxis func(int)
	emitAxis = func(axis int) {
		if axis == len(indices) {
			destination := e.materializeIndexedLValue(vdmir.IndexNExpr{
				Target:  vdmir.VarRefExpr{ExprType: stmt.Type, Name: stmt.Name, Kind: vdmir.VarLocal},
				Indices: indices,
				Extents: shape,
				Layout:  vdmir.IndexLayoutRowMajorLinear,
			}, source.Span{})
			if e.err != nil {
				return
			}
			value := e.materializeExpr(generate.Body)
			e.line(fmt.Sprintf("%s = %s;", destination.Text, value))
			return
		}
		name := hlslIdentifier(generate.Binders[axis])
		e.line(fmt.Sprintf("for (uint %s = 0u; %s < %du; ++%s)", name, name, shape[axis], name))
		e.line("{")
		e.indent++
		emitAxis(axis + 1)
		e.indent--
		e.line("}")
	}
	emitAxis(0)
}

func fixedShapeMetadata(ref vdmir.Type) (vdmir.Type, []uint32, bool) {
	switch ref.Kind {
	case vdmir.TypeNDArray:
		if ref.Element == nil || len(ref.Shape) == 0 {
			return vdmir.Type{}, nil, false
		}
		return *ref.Element, append([]uint32(nil), ref.Shape...), true
	case vdmir.TypeArray:
		if len(ref.Shape) == 0 {
			return vdmir.Type{}, nil, false
		}
		elem, _ := fixedArrayStorage(ref)
		return elem, append([]uint32(nil), ref.Shape...), true
	default:
		return vdmir.Type{}, nil, false
	}
}

func elementTypeForArrayish(ref vdmir.Type) vdmir.Type {
	if ref.Element == nil {
		return vdmir.Type{}
	}
	return *ref.Element
}

func (e *emitter) nextTemp() string {
	return e.nextTempWithPrefix("with")
}

func (e *emitter) nextTempWithPrefix(prefix string) string {
	name := fmt.Sprintf("__sdslv_%s_%d", prefix, e.tempCounter)
	e.tempCounter++
	return name
}

func (e *emitter) line(text string) {
	for i := 0; i < e.indent; i++ {
		e.builder.WriteString("    ")
	}
	e.builder.WriteString(text)
	e.builder.WriteByte('\n')
}

func typeRef(ref vdmir.Type, name string) string {
	mapped := ref.Name
	switch ref.Kind {
	case vdmir.TypeF32:
		mapped = "float"
	case vdmir.TypeI32:
		mapped = "int"
	case vdmir.TypeU32:
		mapped = "uint"
	case vdmir.TypeUint2:
		mapped = "uint2"
	case vdmir.TypeUint3:
		mapped = "uint3"
	case vdmir.TypeUint4:
		mapped = "uint4"
	case vdmir.TypeVoid:
		mapped = "void"
	}
	if ref.IsArray() && ref.Element != nil {
		elemType := *ref.Element
		count := ref.ArraySize
		if ref.Kind == vdmir.TypeArray {
			elemType, count = fixedArrayStorage(ref)
		}
		elem := typeRef(elemType, "")
		if name == "" {
			return elem
		}
		if ref.Kind == vdmir.TypeArray || ref.Kind == vdmir.TypeNDArray {
			return fmt.Sprintf("%s %s[%d]", elem, hlslIdentifier(name), count)
		}
		return fmt.Sprintf("%s %s[]", elem, hlslIdentifier(name))
	}
	if (ref.Kind == vdmir.TypeTile || ref.Kind == vdmir.TypeRegTile) && ref.Element != nil {
		elem := typeRef(*ref.Element, "")
		if name == "" {
			return elem
		}
		return fmt.Sprintf("%s %s[%d]", elem, hlslIdentifier(name), ref.Rows*ref.Cols)
	}
	if ref.Kind == vdmir.TypeMatrixView {
		if name == "" {
			return "/* matrix_view */"
		}
		return "/* matrix_view */ " + hlslIdentifier(name)
	}
	if ref.Kind == vdmir.TypeBoard {
		mapped = ref.Name
	}
	if name == "" {
		return mapped
	}
	return mapped + " " + hlslIdentifier(name)
}

// fixedArrayStorage maps nested fixed arrays to their compiler-owned linear
// HLSL storage. Tiles, register tiles, matrix views, and runtime arrays retain
// their existing category-specific representations.
func fixedArrayStorage(ref vdmir.Type) (vdmir.Type, int) {
	count := 1
	current := ref
	for current.Kind == vdmir.TypeArray && current.Element != nil {
		count *= current.ArraySize
		current = *current.Element
	}
	return current, count
}

func hlslIdentifier(name string) string {
	switch name {
	case "linear":
		return name + "_"
	default:
		return name
	}
}

func hlslExprPath(path string) string {
	parts := strings.Split(path, ".")
	for i, part := range parts {
		parts[i] = hlslIdentifier(part)
	}
	return strings.Join(parts, ".")
}

func sanitizeName(name string) string {
	var b strings.Builder
	for _, r := range name {
		if (r >= 'A' && r <= 'Z') || (r >= 'a' && r <= 'z') || (r >= '0' && r <= '9') || r == '_' {
			b.WriteRune(r)
		} else {
			b.WriteRune('_')
		}
	}
	return b.String()
}

func hlslIntrinsic(intrinsic vdmir.Intrinsic) string {
	switch intrinsic {
	case vdmir.IntrinsicWorkgroupBarrier:
		return "GroupMemoryBarrierWithGroupSync"
	case vdmir.IntrinsicWorkgroupMemoryBarrier:
		return "GroupMemoryBarrier"
	case vdmir.IntrinsicDot:
		return "dot"
	case vdmir.IntrinsicCross:
		return "cross"
	case vdmir.IntrinsicNormalize:
		return "normalize"
	case vdmir.IntrinsicSaturate:
		return "saturate"
	case vdmir.IntrinsicLerp:
		return "lerp"
	case vdmir.IntrinsicReflect:
		return "reflect"
	case vdmir.IntrinsicUnpackF16x2:
		return "f16tof32"
	case vdmir.IntrinsicBitcast:
		return "asuint" // overridden below by result-aware emission where needed
	case vdmir.IntrinsicConvert:
		return "float"
	default:
		return "GroupMemoryBarrierWithGroupSync"
	}
}

func (e *emitter) m35Intrinsic(x vdmir.IntrinsicCallExpr, args []string) string {
	if len(args) == 0 {
		return hlslIntrinsic(x.Intrinsic) + "()"
	}
	switch x.Intrinsic {
	case vdmir.IntrinsicSampleTexture2D:
		if len(args) != 3 {
			e.err = fmt.Errorf("Sample intrinsic requires 3 lowered arguments")
			return "/* invalid Sample */"
		}
		return args[0] + ".Sample(" + args[1] + ", " + args[2] + ")"
	case vdmir.IntrinsicUnpackF16x2:
		return "f16tof32(uint2((" + args[0] + " & 65535u), (" + args[0] + " >> 16u)))"
	case vdmir.IntrinsicBitcast:
		switch x.Type().Kind {
		case vdmir.TypeF32:
			return "asfloat(" + args[0] + ")"
		case vdmir.TypeI32:
			return "asint(" + args[0] + ")"
		default:
			return "asuint(" + args[0] + ")"
		}
	case vdmir.IntrinsicConvert:
		return typeRef(x.Type(), "") + "(" + args[0] + ")"
	default:
		return hlslIntrinsic(x.Intrinsic) + "(" + strings.Join(args, ", ") + ")"
	}
}

func moduleRequiresCooperativeMatrix(module vdmir.Module) bool {
	for _, requirement := range module.Requirements {
		if requirement.Kind == vdmir.CapabilityCooperativeMatrixF16F32M16N16K16Subgroup {
			return true
		}
	}
	return false
}

func (e *emitter) emitCooperativeMatrixPreamble() {
	for _, line := range strings.Split(cooperativeMatrixPreamble, "\n") {
		e.line(line)
	}
	e.line("")
}

func (e *emitter) emitCooperativeMatMul(args []string) {
	if len(args) != 8 {
		e.err = fmt.Errorf("cooperative matrix intrinsic requires 8 lowered arguments, got %d", len(args))
		return
	}
	a, b, c := args[0], args[1], args[2]
	groupID, lane, m, n, k := args[3], args[4], args[5], args[6], args[7]
	_ = m // The aligned proof validates M on the host; row addressing uses group ID.
	e.line("{")
	e.indent++
	e.line("uint __sdslv_row = (" + groupID + ").x * 16u;")
	e.line("uint __sdslv_column = (" + groupID + ").y * 16u;")
	e.line("__sdslv_cooperative::MatrixC __sdslv_accumulator;")
	e.line("__sdslv_accumulator.value = __sdslv_cooperative::Splat<__sdslv_cooperative::MatrixCType>(0.0f);")
	e.line("[loop]")
	e.line("for (uint __sdslv_inner = 0u; __sdslv_inner < " + k + "; __sdslv_inner += 16u)")
	e.line("{")
	e.indent++
	e.line("[unroll]")
	e.line("for (uint __sdslv_element = " + lane + "; __sdslv_element < 256u; __sdslv_element += 32u)")
	e.line("{")
	e.indent++
	e.line("uint __sdslv_tile_row = __sdslv_element / 16u;")
	e.line("uint __sdslv_tile_column = __sdslv_element % 16u;")
	e.line("uint __sdslv_a_element = (__sdslv_row + __sdslv_tile_row) * " + k + " + __sdslv_inner + __sdslv_tile_column;")
	e.line("uint __sdslv_b_element = (__sdslv_inner + __sdslv_tile_row) * " + n + " + __sdslv_column + __sdslv_tile_column;")
	e.line("uint __sdslv_a_packed = " + a + "[__sdslv_a_element / 2u];")
	e.line("uint __sdslv_b_packed = " + b + "[__sdslv_b_element / 2u];")
	e.line("__sdslv_cooperative_tile_a[__sdslv_element] = (float16_t)f16tof32((__sdslv_a_element % 2u) == 0u ? (__sdslv_a_packed & 65535u) : (__sdslv_a_packed >> 16u));")
	e.line("__sdslv_cooperative_tile_b[__sdslv_element] = (float16_t)f16tof32((__sdslv_b_element % 2u) == 0u ? (__sdslv_b_packed & 65535u) : (__sdslv_b_packed >> 16u));")
	e.indent--
	e.line("}")
	e.line("GroupMemoryBarrierWithGroupSync();")
	e.line("__sdslv_cooperative::MatrixA __sdslv_tile_a;")
	e.line("__sdslv_tile_a.value = __sdslv_cooperative::Load<__sdslv_cooperative::MatrixAType>(__sdslv_cooperative::GetGroupSharedAddress(__sdslv_cooperative_tile_a[0]), __sdslv_cooperative::RowMajor, 16u, 48, __sdslv_cooperative::ScopeWorkgroup);")
	e.line("__sdslv_cooperative::MatrixB __sdslv_tile_b;")
	e.line("__sdslv_tile_b.value = __sdslv_cooperative::Load<__sdslv_cooperative::MatrixBType>(__sdslv_cooperative::GetGroupSharedAddress(__sdslv_cooperative_tile_b[0]), __sdslv_cooperative::RowMajor, 16u, 48, __sdslv_cooperative::ScopeWorkgroup);")
	e.line("__sdslv_accumulator.value = __sdslv_cooperative::MultiplyAdd<__sdslv_cooperative::MatrixCType>(__sdslv_tile_a.value, __sdslv_tile_b.value, __sdslv_accumulator.value, 0);")
	e.line("GroupMemoryBarrierWithGroupSync();")
	e.indent--
	e.line("}")
	e.line("__sdslv_cooperative::Store(" + c + "[__sdslv_row * " + n + " + __sdslv_column], __sdslv_accumulator.value, __sdslv_cooperative::RowMajor, " + n + ", 0);")
	e.indent--
	e.line("}")
}

const cooperativeMatrixPreamble = `namespace __sdslv_cooperative {
enum Scope { ScopeWorkgroup = 2, ScopeSubgroup = 3 };
enum Layout { RowMajor = 0, ColumnMajor = 1 };

using MatrixAType = vk::SpirvOpaqueType<
    4456, float16_t, vk::integral_constant<uint, ScopeSubgroup>,
    vk::integral_constant<uint, 16>, vk::integral_constant<uint, 16>,
    vk::integral_constant<uint, 0> >;
using MatrixBType = vk::SpirvOpaqueType<
    4456, float16_t, vk::integral_constant<uint, ScopeSubgroup>,
    vk::integral_constant<uint, 16>, vk::integral_constant<uint, 16>,
    vk::integral_constant<uint, 1> >;
using MatrixCType = vk::SpirvOpaqueType<
    4456, float, vk::integral_constant<uint, ScopeSubgroup>,
    vk::integral_constant<uint, 16>, vk::integral_constant<uint, 16>,
    vk::integral_constant<uint, 2> >;

struct MatrixA {
  [[vk::ext_extension("SPV_KHR_cooperative_matrix")]]
  [[vk::ext_capability(6022)]]
  [[vk::ext_capability(5345)]]
  MatrixAType value;
};
struct MatrixB { MatrixBType value; };
struct MatrixC { MatrixCType value; };

template <typename PointeeType>
using WorkgroupPointer = const vk::SpirvOpaqueType<
    32, vk::Literal<vk::integral_constant<uint, ScopeWorkgroup> >, PointeeType>;

template <typename T>
[[vk::ext_instruction(83)]] WorkgroupPointer<T>
GetGroupSharedAddress([[vk::ext_reference]] T value);

template <typename ResultType, typename ComponentType>
[[vk::ext_instruction(80)]] ResultType Splat(ComponentType value);

template <typename ResultType, typename PointerType>
[[vk::ext_instruction(4457)]] ResultType Load(
    WorkgroupPointer<PointerType> pointer, Layout layout, uint stride,
    [[vk::ext_literal]] uint memoryOperands, Scope scope);

template <typename ResultType, typename MatrixTypeA, typename MatrixTypeB,
          typename MatrixTypeC>
[[vk::ext_instruction(4459)]] ResultType MultiplyAdd(
    MatrixTypeA a, MatrixTypeB b, MatrixTypeC c,
    [[vk::ext_literal]] uint operands);

template <typename ObjectType, typename PointerType>
[[vk::ext_instruction(4458)]] void Store(
    [[vk::ext_reference]] PointerType pointer, ObjectType object, Layout layout,
    uint stride, [[vk::ext_literal]] uint memoryOperands);
}

groupshared float16_t __sdslv_cooperative_tile_a[256];
groupshared float16_t __sdslv_cooperative_tile_b[256];`

func enumPayloadTypeName(enumName, variantName string) string {
	return enumName + "_" + variantName + "Payload"
}

func enumConstructorName(enumName, variantName string) string {
	return "__sdslv_make_" + sanitizeName(enumName) + "_" + sanitizeName(variantName)
}
