package hlsl

import (
	"fmt"
	"github.com/yuechen-li-dev/oct/internal/sdslv/vdmir"
	"strings"
)

// EmitTestGroup emits a backend-neutral VD-MIR test compilation group. The
// normal emitter owns every ordinary statement and expression in test bodies.
func EmitTestGroup(program vdmir.TestProgram, group vdmir.TestCompilationGroup) (string, error) {
	var e emitter
	e.testMode = true
	e.testFunctions = map[string]bool{}
	e.line("// Generated by GoOct SDSL-V M29b via VD-MIR. Do not edit.")
	e.line("struct SdslvTestInvocationResult { uint abi_version; uint failed; uint assertion_id; uint source_line; uint source_column; uint invocation_x; uint invocation_y; uint invocation_z; uint value_kind; uint component_count; uint expected_bits[4]; uint actual_bits[4]; uint tolerance_bits[4]; };")
	e.line("struct SdslvTestFailure { bool failed; uint assertion_id; uint source_line; uint source_column; uint value_kind; uint expected_bits[4]; uint actual_bits[4]; uint tolerance_bits[4]; };")
	e.line("struct SdslvTestPush { uint test_case_id; uint theory_row_id; uint invocation_width; uint invocation_height; };")
	e.line("RWStructuredBuffer<SdslvTestInvocationResult> __sdslv_test_results : register(u0, space0);")
	e.line("[[vk::binding(1, 0)]] StructuredBuffer<uint> __sdslv_test_input;")
	e.line("[[vk::push_constant]] SdslvTestPush __sdslv_push;")
	allTestFunctions := map[string]bool{}
	for _, candidateGroup := range program.Groups {
		for _, entry := range candidateGroup.Entries {
			allTestFunctions[entry.FunctionName] = true
		}
	}
	for _, x := range group.Entries {
		e.testFunctions[x.FunctionName] = true
	}
	for _, record := range program.Module.Records {
		e.emitStruct(record.Name, record.Fields)
	}
	for _, board := range program.Module.Boards {
		e.emitStruct(board.Name, board.Fields)
	}
	for _, enum := range program.Module.Enums {
		e.emitEnum(enum)
	}
	for _, fn := range program.Module.Functions {
		if allTestFunctions[fn.Name] && !e.testFunctions[fn.Name] {
			continue
		}
		e.emitFunction(fn, vdmir.ComputeEntryPoint{})
	}
	e.line(fmt.Sprintf("[numthreads(%d, %d, %d)]", group.WorkgroupSize[0], group.WorkgroupSize[1], group.WorkgroupSize[2]))
	e.line("void main(uint3 dispatch_id : SV_DispatchThreadID) {")
	e.indent++
	e.line("SdslvTestFailure failure; failure.failed=false; failure.assertion_id=0u; failure.source_line=0u; failure.source_column=0u; failure.value_kind=0u; [unroll] for(uint i=0u;i<4u;i++){failure.expected_bits[i]=0u;failure.actual_bits[i]=0u;failure.tolerance_bits[i]=0u;}")
	e.line("switch (__sdslv_push.test_case_id) {")
	e.indent++
	for _, x := range group.Entries {
		args := []string{}
		if x.TheoryRow != nil {
			for _, v := range x.TheoryRow.Values {
				args = append(args, v.Value)
			}
		}
		args = append(args, "dispatch_id", "failure")
		e.line(fmt.Sprintf("case %du: { %s(%s); break; }", x.Selector, x.FunctionName, strings.Join(args, ", ")))
	}
	e.line("default: { failure.failed=true; failure.assertion_id=0xffffffffu; break; }")
	e.indent--
	e.line("}")
	e.line("uint index = dispatch_id.x + dispatch_id.y * __sdslv_push.invocation_width + dispatch_id.z * __sdslv_push.invocation_width * __sdslv_push.invocation_height;")
	e.line(fmt.Sprintf("SdslvTestInvocationResult r; r.abi_version=%du; r.failed=failure.failed?1u:0u; r.assertion_id=failure.assertion_id;r.source_line=failure.source_line;r.source_column=failure.source_column;r.invocation_x=dispatch_id.x;r.invocation_y=dispatch_id.y;r.invocation_z=dispatch_id.z;r.value_kind=failure.value_kind;r.component_count=1u;[unroll]for(uint i=0u;i<4u;i++){r.expected_bits[i]=failure.expected_bits[i];r.actual_bits[i]=failure.actual_bits[i];r.tolerance_bits[i]=failure.tolerance_bits[i];}__sdslv_test_results[index]=r;", program.ABI.ABIVersion))
	e.indent--
	e.line("}")
	return e.builder.String(), nil
}

func (e *emitter) emitTestAssert(a vdmir.AssertStmt) {
	vals := []vdmir.Expr{}
	if a.Expected != nil {
		vals = append(vals, a.Expected)
	}
	if a.Actual != nil {
		vals = append(vals, a.Actual)
	}
	if a.Tolerance != nil {
		vals = append(vals, a.Tolerance)
	}
	n := make([]string, len(vals))
	for i, v := range vals {
		n[i] = e.nextTempWithPrefix("sdslv_once")
		e.emitTestAssertOperand(n[i], v)
	}
	cond, ex, ac, tol := "false", "0u", "0u", "0u"
	switch a.Kind {
	case vdmir.AssertTrue:
		cond = "!" + n[0]
		ex = "1u"
	case vdmir.AssertFalse:
		cond = n[0]
	case vdmir.AssertEqual:
		cond = n[0] + " != " + n[1]
		ex = testBits(n[0], a.Expected.Type())
		ac = testBits(n[1], a.Actual.Type())
	case vdmir.AssertNotEqual:
		cond = n[0] + " == " + n[1]
		ex = testBits(n[0], a.Expected.Type())
		ac = testBits(n[1], a.Actual.Type())
	case vdmir.AssertNear:
		cond = n[2] + " < 0.0 || isnan(" + n[0] + ") || isnan(" + n[1] + ") || isnan(" + n[2] + ") || ((isinf(" + n[0] + ") || isinf(" + n[1] + ")) ? (" + n[0] + " != " + n[1] + ") : (abs(" + n[0] + " - " + n[1] + ") > " + n[2] + "))"
		ex = testBits(n[0], a.Expected.Type())
		ac = testBits(n[1], a.Actual.Type())
		tol = testBits(n[2], a.Tolerance.Type())
	}
	e.line(fmt.Sprintf("if(!failure.failed && (%s)){failure.failed=true;failure.assertion_id=%du;failure.source_line=%du;failure.source_column=%du;failure.value_kind=%du;failure.expected_bits[0]=%s;failure.actual_bits[0]=%s;failure.tolerance_bits[0]=%s;}", cond, a.LexicalIndex, a.CallSpan.Start.Line, a.CallSpan.Start.Column, a.ValueKind, ex, ac, tol))
}

func (e *emitter) emitTestAssertOperand(name string, expr vdmir.Expr) {
	value := e.materializeExpr(expr)
	e.line(fmt.Sprintf("%s %s = %s;", typeRef(expr.Type(), ""), name, value))
}

func testBits(x string, t vdmir.Type) string {
	if t.Kind == vdmir.TypeF32 || t.Kind == vdmir.TypeI32 {
		return "asuint(" + x + ")"
	}
	if t.Kind == vdmir.TypeBool {
		return "(" + x + "?1u:0u)"
	}
	return x
}
