// Code generated by Veril-Oct. DO NOT EDIT.
// Oct Int hardware policy: signed 64-bit two's-complement; SI dimensions are compile-time only.
// Packed aggregates use declaration order, first field/tag in the least-significant bits.

module CalibrationSum(
    output logic signed [63:0] Result
);

function automatic logic signed [63:0] oct_fn_Hardware__CalibrationSum();
    logic signed [63:0] __oct_internal_tmp_0;
    logic signed [63:0] __oct_internal_tmp_1;
    logic signed [63:0] __oct_internal_tmp_2;
    logic signed [63:0] __oct_internal_tmp_3;
    logic signed [63:0] sum;
    logic signed [63:0] index;
    logic __oct_active_entry;
    logic __oct_active_b1;
    logic __oct_active_b2;
    logic __oct_active_b3;
    logic __oct_active_b4;
    logic __oct_active_b5;
    logic __oct_active_b6;
    oct_fn_Hardware__CalibrationSum = '0;
    __oct_internal_tmp_0 = '0;
    __oct_internal_tmp_1 = '0;
    __oct_internal_tmp_2 = '0;
    __oct_internal_tmp_3 = '0;
    sum = '0;
    index = '0;
    __oct_active_entry = 1'b0;
    __oct_active_b1 = 1'b0;
    __oct_active_b2 = 1'b0;
    __oct_active_b3 = 1'b0;
    __oct_active_b4 = 1'b0;
    __oct_active_b5 = 1'b0;
    __oct_active_b6 = 1'b0;
    __oct_active_entry = 1'b1;
    if (__oct_active_entry) begin : oct_block_entry
        sum = 64'sd0;
        __oct_internal_tmp_0 = 64'sd0;
        __oct_internal_tmp_1 = 64'sd8;
        __oct_internal_tmp_2 = 64'sd1;
        __oct_active_b1 = 1'b1;
    end
    if (__oct_active_b1) begin : oct_block_b1
        index = __oct_internal_tmp_0;
        if ((__oct_internal_tmp_0 <= __oct_internal_tmp_1)) __oct_active_b2 = 1'b1;
        else __oct_active_b6 = 1'b1;
    end
    if (__oct_active_b2) begin : oct_block_b2
        for (index = 64'sd0; index < 64'sd8; index = index + 64'sd1) begin : oct_static_loop_b2
            __oct_internal_tmp_3 = (sum + index);
            sum = __oct_internal_tmp_3;
        end
        __oct_active_b5 = 1'b1;
    end
    if (__oct_active_b5) begin : oct_block_b5
        oct_fn_Hardware__CalibrationSum = sum;
    end
    if (__oct_active_b6) begin : oct_block_b6
    end
endfunction

logic signed [63:0] __oct_internal_tmp_0;

always_comb begin
    logic __oct_active_entry;
    Result = '0;
    __oct_internal_tmp_0 = '0;
    __oct_active_entry = 1'b0;
    __oct_active_entry = 1'b1;
    if (__oct_active_entry) begin : oct_block_entry
        __oct_internal_tmp_0 = oct_fn_Hardware__CalibrationSum();
        Result = __oct_internal_tmp_0;
    end
end

endmodule

module MotorCommand(
    input  logic [127:0] sensor,
    input  logic [65:0] command,
    output logic [128:0] Result
);

function automatic logic signed [63:0] oct_fn_Hardware__RequestedPosition(input logic [127:0] sensor, input logic [65:0] command);
    logic __oct_internal_tmp_0;
    logic signed [63:0] __oct_internal_tmp_1;
    logic signed [63:0] __oct_internal_tmp_2;
    logic __oct_internal_tmp_3;
    logic signed [63:0] __oct_internal_tmp_4;
    logic signed [63:0] __oct_internal_tmp_5;
    logic __oct_internal_tmp_6;
    logic signed [63:0] __oct_internal_tmp_7;
    logic signed [63:0] __oct_internal_tmp_8;
    logic signed [63:0] delta;
    logic signed [63:0] factor;
    logic __oct_active_entry;
    logic __oct_active_b1;
    logic __oct_active_b2;
    logic __oct_active_b3;
    logic __oct_active_b4;
    logic __oct_active_b5;
    logic __oct_active_b6;
    logic __oct_active_b7;
    oct_fn_Hardware__RequestedPosition = '0;
    __oct_internal_tmp_0 = '0;
    __oct_internal_tmp_1 = '0;
    __oct_internal_tmp_2 = '0;
    __oct_internal_tmp_3 = '0;
    __oct_internal_tmp_4 = '0;
    __oct_internal_tmp_5 = '0;
    __oct_internal_tmp_6 = '0;
    __oct_internal_tmp_7 = '0;
    __oct_internal_tmp_8 = '0;
    delta = '0;
    factor = '0;
    __oct_active_entry = 1'b0;
    __oct_active_b1 = 1'b0;
    __oct_active_b2 = 1'b0;
    __oct_active_b3 = 1'b0;
    __oct_active_b4 = 1'b0;
    __oct_active_b5 = 1'b0;
    __oct_active_b6 = 1'b0;
    __oct_active_b7 = 1'b0;
    __oct_active_entry = 1'b1;
    if (__oct_active_entry) begin : oct_block_entry
        __oct_internal_tmp_0 = (command[1:0] == 2'd0);
        if (__oct_internal_tmp_0) __oct_active_b2 = 1'b1;
        else __oct_active_b3 = 1'b1;
    end
    if (__oct_active_b2) begin : oct_block_b2
        __oct_internal_tmp_1 = sensor[63:0];
        __oct_internal_tmp_2 = __oct_internal_tmp_1;
        __oct_active_b1 = 1'b1;
    end
    if (__oct_active_b3) begin : oct_block_b3
        __oct_internal_tmp_3 = (command[1:0] == 2'd1);
        if (__oct_internal_tmp_3) __oct_active_b4 = 1'b1;
        else __oct_active_b5 = 1'b1;
    end
    if (__oct_active_b4) begin : oct_block_b4
        delta = command[65:2];
        __oct_internal_tmp_4 = sensor[63:0];
        __oct_internal_tmp_5 = (__oct_internal_tmp_4 + delta);
        __oct_internal_tmp_2 = __oct_internal_tmp_5;
        __oct_active_b1 = 1'b1;
    end
    if (__oct_active_b5) begin : oct_block_b5
        __oct_internal_tmp_6 = (command[1:0] == 2'd2);
        if (__oct_internal_tmp_6) __oct_active_b6 = 1'b1;
        else __oct_active_b7 = 1'b1;
    end
    if (__oct_active_b6) begin : oct_block_b6
        factor = command[65:2];
        __oct_internal_tmp_7 = sensor[63:0];
        __oct_internal_tmp_8 = (__oct_internal_tmp_7 * factor);
        __oct_internal_tmp_2 = __oct_internal_tmp_8;
        __oct_active_b1 = 1'b1;
    end
    if (__oct_active_b1) begin : oct_block_b1
        oct_fn_Hardware__RequestedPosition = __oct_internal_tmp_2;
    end
    if (__oct_active_b7) begin : oct_block_b7
    end
endfunction

function automatic logic signed [63:0] oct_fn_Hardware__ClampDistance(input logic signed [63:0] value, input logic signed [63:0] limit);
    logic __oct_internal_tmp_0;
    logic signed [63:0] __oct_internal_tmp_1;
    logic __oct_internal_tmp_2;
    logic signed [63:0] __oct_internal_tmp_3;
    logic __oct_active_entry;
    logic __oct_active_b1;
    logic __oct_active_b2;
    logic __oct_active_b3;
    logic __oct_active_b4;
    logic __oct_active_b5;
    logic __oct_active_b6;
    oct_fn_Hardware__ClampDistance = '0;
    __oct_internal_tmp_0 = '0;
    __oct_internal_tmp_1 = '0;
    __oct_internal_tmp_2 = '0;
    __oct_internal_tmp_3 = '0;
    __oct_active_entry = 1'b0;
    __oct_active_b1 = 1'b0;
    __oct_active_b2 = 1'b0;
    __oct_active_b3 = 1'b0;
    __oct_active_b4 = 1'b0;
    __oct_active_b5 = 1'b0;
    __oct_active_b6 = 1'b0;
    __oct_active_entry = 1'b1;
    if (__oct_active_entry) begin : oct_block_entry
        __oct_internal_tmp_0 = (value > limit);
        if (__oct_internal_tmp_0) __oct_active_b1 = 1'b1;
        else __oct_active_b2 = 1'b1;
    end
    if (__oct_active_b1) begin : oct_block_b1
        oct_fn_Hardware__ClampDistance = limit;
    end
    if (__oct_active_b2) begin : oct_block_b2
        __oct_active_b3 = 1'b1;
    end
    if (__oct_active_b3) begin : oct_block_b3
        __oct_internal_tmp_1 = (-limit);
        __oct_internal_tmp_2 = (value < __oct_internal_tmp_1);
        if (__oct_internal_tmp_2) __oct_active_b4 = 1'b1;
        else __oct_active_b5 = 1'b1;
    end
    if (__oct_active_b4) begin : oct_block_b4
        __oct_internal_tmp_3 = (-limit);
        oct_fn_Hardware__ClampDistance = __oct_internal_tmp_3;
    end
    if (__oct_active_b5) begin : oct_block_b5
        __oct_active_b6 = 1'b1;
    end
    if (__oct_active_b6) begin : oct_block_b6
        oct_fn_Hardware__ClampDistance = value;
    end
endfunction

function automatic logic [128:0] oct_fn_Hardware__Evaluate(input logic [127:0] sensor, input logic [65:0] command);
    logic signed [63:0] __oct_internal_tmp_0;
    logic [128:0] __oct_internal_tmp_1;
    logic [128:0] __oct_internal_tmp_10;
    logic signed [63:0] __oct_internal_tmp_2;
    logic __oct_internal_tmp_3;
    logic __oct_internal_tmp_4;
    logic signed [63:0] __oct_internal_tmp_5;
    logic signed [63:0] __oct_internal_tmp_6;
    logic __oct_internal_tmp_7;
    logic signed [63:0] __oct_internal_tmp_8;
    logic signed [63:0] __oct_internal_tmp_9;
    logic signed [63:0] requested;
    logic [128:0] oct_initial;
    logic __oct_active_entry;
    logic __oct_active_b1;
    logic __oct_active_b2;
    logic __oct_active_b3;
    logic __oct_active_b4;
    logic __oct_active_b5;
    oct_fn_Hardware__Evaluate = '0;
    __oct_internal_tmp_0 = '0;
    __oct_internal_tmp_1 = '0;
    __oct_internal_tmp_10 = '0;
    __oct_internal_tmp_2 = '0;
    __oct_internal_tmp_3 = '0;
    __oct_internal_tmp_4 = '0;
    __oct_internal_tmp_5 = '0;
    __oct_internal_tmp_6 = '0;
    __oct_internal_tmp_7 = '0;
    __oct_internal_tmp_8 = '0;
    __oct_internal_tmp_9 = '0;
    requested = '0;
    oct_initial = '0;
    __oct_active_entry = 1'b0;
    __oct_active_b1 = 1'b0;
    __oct_active_b2 = 1'b0;
    __oct_active_b3 = 1'b0;
    __oct_active_b4 = 1'b0;
    __oct_active_b5 = 1'b0;
    __oct_active_entry = 1'b1;
    if (__oct_active_entry) begin : oct_block_entry
        __oct_internal_tmp_0 = oct_fn_Hardware__RequestedPosition(sensor, command);
        requested = __oct_internal_tmp_0;
        __oct_internal_tmp_1 = {1'b0, requested, requested};
        oct_initial = __oct_internal_tmp_1;
        __oct_internal_tmp_2 = sensor[127:64];
        __oct_internal_tmp_3 = (requested > __oct_internal_tmp_2);
        __oct_internal_tmp_4 = 1'b1;
        if (__oct_internal_tmp_3) __oct_active_b2 = 1'b1;
        else __oct_active_b1 = 1'b1;
    end
    if (__oct_active_b1) begin : oct_block_b1
        __oct_internal_tmp_5 = sensor[127:64];
        __oct_internal_tmp_6 = (-__oct_internal_tmp_5);
        __oct_internal_tmp_7 = (requested < __oct_internal_tmp_6);
        __oct_internal_tmp_4 = __oct_internal_tmp_7;
        __oct_active_b2 = 1'b1;
    end
    if (__oct_active_b2) begin : oct_block_b2
        if (__oct_internal_tmp_4) __oct_active_b3 = 1'b1;
        else __oct_active_b4 = 1'b1;
    end
    if (__oct_active_b3) begin : oct_block_b3
        __oct_internal_tmp_8 = sensor[127:64];
        __oct_internal_tmp_9 = oct_fn_Hardware__ClampDistance(requested, __oct_internal_tmp_8);
        __oct_internal_tmp_10 = {1'b1, __oct_internal_tmp_9, oct_initial[63:0]};
        oct_fn_Hardware__Evaluate = __oct_internal_tmp_10;
    end
    if (__oct_active_b4) begin : oct_block_b4
        __oct_active_b5 = 1'b1;
    end
    if (__oct_active_b5) begin : oct_block_b5
        oct_fn_Hardware__Evaluate = oct_initial;
    end
endfunction

logic [128:0] __oct_internal_tmp_0;

always_comb begin
    logic __oct_active_entry;
    Result = '0;
    __oct_internal_tmp_0 = '0;
    __oct_active_entry = 1'b0;
    __oct_active_entry = 1'b1;
    if (__oct_active_entry) begin : oct_block_entry
        __oct_internal_tmp_0 = oct_fn_Hardware__Evaluate(sensor, command);
        Result = __oct_internal_tmp_0;
    end
end

endmodule
