// Generated by canonical GoOct SDSL-V via VD-MIR. Do not edit by hand.
// namespace Prometheus.Experimental.Attention

struct AttentionScaleParams
{
    uint Rows;
    uint Columns;
    uint RowStride;
    uint TotalElements;
    float Scale;
    uint Reserved0;
    uint Reserved1;
    uint Reserved2;
};

[[vk::binding(0, 0)]] StructuredBuffer<float> Input;
[[vk::binding(3, 0)]] RWStructuredBuffer<float> Output;

[[vk::push_constant]] ConstantBuffer<AttentionScaleParams> params;

[numthreads(256, 1, 1)]
void AttentionScaleScoresF32_CS(uint3 DispatchThreadID : SV_DispatchThreadID)
{
    uint element = DispatchThreadID.x;
    if ((element >= params.TotalElements))
    {
        return;
    }
    uint row = (element / params.Columns);
    uint column = (element - (row * params.Columns));
    uint storageIndex = ((row * params.RowStride) + column);
    Output[storageIndex] = (Input[storageIndex] * params.Scale);
    return;
}

