// Generated by canonical GoOct SDSL-V via VD-MIR. Do not edit by hand.
// namespace Prometheus.Experimental.Attention

struct AttentionTransposeParams
{
    uint InputRows;
    uint InputColumns;
    uint InputRowStride;
    uint OutputRowStride;
    uint OutputElementCount;
    uint Reserved0;
    uint Reserved1;
    uint Reserved2;
};

[[vk::binding(0, 0)]] StructuredBuffer<float> Input;
[[vk::binding(3, 0)]] RWStructuredBuffer<float> Output;

[[vk::push_constant]] ConstantBuffer<AttentionTransposeParams> params;

[numthreads(256, 1, 1)]
void AttentionTransposeF32_CS(uint3 DispatchThreadID : SV_DispatchThreadID)
{
    uint outputIndex = DispatchThreadID.x;
    if ((outputIndex >= params.OutputElementCount))
    {
        return;
    }
    uint outputRow = (outputIndex / params.OutputRowStride);
    uint outputColumn = (outputIndex - (outputRow * params.OutputRowStride));
    if (((outputRow >= params.InputColumns) || (outputColumn >= params.InputRows)))
    {
        return;
    }
    Output[outputIndex] = Input[((outputColumn * params.InputRowStride) + outputRow)];
    return;
}

