// Generated by canonical GoOct SDSL-V via VD-MIR. Do not edit by hand.
// namespace Prometheus.Experimental.Attention

struct AttentionPackParams
{
    uint LogicalRows;
    uint LogicalColumns;
    uint InputRowStride;
    uint OutputRows;
    uint OutputColumns;
    uint Transpose;
    uint PackedWordCount;
    uint Reserved;
};

[[vk::binding(0, 0)]] StructuredBuffer<float> Input;
[[vk::binding(3, 0)]] RWStructuredBuffer<uint> Output;

[[vk::push_constant]] ConstantBuffer<AttentionPackParams> params;

[numthreads(256, 1, 1)]
void AttentionPackF32ToF16_CS(uint3 DispatchThreadID : SV_DispatchThreadID)
{
    uint word = DispatchThreadID.x;
    if ((word >= params.PackedWordCount))
    {
        return;
    }
    float low = 0.0;
    float high = 0.0;
    uint lowIndex = (word * 2u);
    uint highIndex = (lowIndex + 1u);
    uint lowRow = (lowIndex / params.OutputColumns);
    uint lowColumn = (lowIndex - (lowRow * params.OutputColumns));
    if ((lowRow < params.OutputRows))
    {
        if ((params.Transpose == 0u))
        {
            if (((lowRow < params.LogicalRows) && (lowColumn < params.LogicalColumns)))
            {
                low = Input[((lowRow * params.InputRowStride) + lowColumn)];
            }
        }
        else if (((lowRow < params.LogicalColumns) && (lowColumn < params.LogicalRows)))
        {
            low = Input[((lowColumn * params.InputRowStride) + lowRow)];
        }
    }
    uint highRow = (highIndex / params.OutputColumns);
    uint highColumn = (highIndex - (highRow * params.OutputColumns));
    if ((highRow < params.OutputRows))
    {
        if ((params.Transpose == 0u))
        {
            if (((highRow < params.LogicalRows) && (highColumn < params.LogicalColumns)))
            {
                high = Input[((highRow * params.InputRowStride) + highColumn)];
            }
        }
        else if (((highRow < params.LogicalColumns) && (highColumn < params.LogicalRows)))
        {
            high = Input[((highColumn * params.InputRowStride) + highRow)];
        }
    }
    float2 __sdslv_operand_0 = float2(low, high);
    Output[word] = (f32tof16(__sdslv_operand_0).x | (f32tof16(__sdslv_operand_0).y << 16u));
    return;
}

