// Generated by canonical GoOct SDSL-V via VD-MIR. Do not edit by hand.
// namespace Prometheus.Experimental.Attention

struct AttentionDirectProjectionParams
{
    uint Tokens;
    uint HeadDim;
    uint ModelWidth;
    uint HeadRowStride;
    uint PaddedModelWidth;
    uint TotalOutputElements;
    uint Reserved0;
    uint Reserved1;
};

struct DirectProjectionLane
{
    uint Element;
    uint Token;
    uint OutputColumn;
    float Accumulator;
};

static const int HeadSample_Invalid = 0;
static const int HeadSample_Value = 1;
struct HeadSample_ValuePayload
{
    float X;
    uint WeightRow;
};

struct HeadSample
{
    int Tag;
    HeadSample_ValuePayload Value;
};

HeadSample __sdslv_make_HeadSample_Invalid()
{
    HeadSample value;
    value.Tag = HeadSample_Invalid;
    return value;
}

HeadSample __sdslv_make_HeadSample_Value(float X, uint WeightRow)
{
    HeadSample value;
    value.Tag = HeadSample_Value;
    value.Value.X = X;
    value.Value.WeightRow = WeightRow;
    return value;
}

[[vk::binding(0, 0)]] StructuredBuffer<float> Head0;
[[vk::binding(1, 0)]] StructuredBuffer<float> Head1;
[[vk::binding(2, 0)]] StructuredBuffer<float> Head2;
[[vk::binding(3, 0)]] StructuredBuffer<float> Head3;
[[vk::binding(4, 0)]] StructuredBuffer<float> Head4;
[[vk::binding(5, 0)]] StructuredBuffer<float> Head5;
[[vk::binding(6, 0)]] StructuredBuffer<float> Head6;
[[vk::binding(7, 0)]] StructuredBuffer<float> Head7;
[[vk::binding(9, 0)]] RWStructuredBuffer<float> Output;
[[vk::binding(8, 0)]] StructuredBuffer<uint> WoPacked;

HeadSample AttentionDirectSegmentedProjection_SelectHeadSample(uint head, uint sourceIndex, uint column, uint headDim)
{
    if ((head == 0u))
    {
        return __sdslv_make_HeadSample_Value(Head0[sourceIndex], column);
    }
    if ((head == 1u))
    {
        return __sdslv_make_HeadSample_Value(Head1[sourceIndex], (headDim + column));
    }
    if ((head == 2u))
    {
        return __sdslv_make_HeadSample_Value(Head2[sourceIndex], ((headDim * 2u) + column));
    }
    if ((head == 3u))
    {
        return __sdslv_make_HeadSample_Value(Head3[sourceIndex], ((headDim * 3u) + column));
    }
    if ((head == 4u))
    {
        return __sdslv_make_HeadSample_Value(Head4[sourceIndex], ((headDim * 4u) + column));
    }
    if ((head == 5u))
    {
        return __sdslv_make_HeadSample_Value(Head5[sourceIndex], ((headDim * 5u) + column));
    }
    if ((head == 6u))
    {
        return __sdslv_make_HeadSample_Value(Head6[sourceIndex], ((headDim * 6u) + column));
    }
    if ((head == 7u))
    {
        return __sdslv_make_HeadSample_Value(Head7[sourceIndex], ((headDim * 7u) + column));
    }
    return __sdslv_make_HeadSample_Invalid();
}

float AttentionDirectSegmentedProjection_RoundHeadValue(float value)
{
    float2 __sdslv_operand_0 = float2(value, 0.0);
    float2 pair = f16tof32(uint2(((f32tof16(__sdslv_operand_0).x | (f32tof16(__sdslv_operand_0).y << 16u)) & 65535u), ((f32tof16(__sdslv_operand_0).x | (f32tof16(__sdslv_operand_0).y << 16u)) >> 16u)));
    return pair.x;
}

float AttentionDirectSegmentedProjection_LoadWeight(uint weightIndex)
{
    float2 pair = f16tof32(uint2((WoPacked[(weightIndex / 2u)] & 65535u), (WoPacked[(weightIndex / 2u)] >> 16u)));
    if (((weightIndex % 2u) != 0u))
    {
        return pair.y;
    }
    return pair.x;
}

float AttentionDirectSegmentedProjection_ResolveContribution(HeadSample sample, uint outputColumn, uint paddedModelWidth)
{
    float __sdslv_match_result_1;
    HeadSample __sdslv_match_subject_2 = sample;
    if (__sdslv_match_subject_2.Tag == HeadSample_Invalid)
    {
        __sdslv_match_result_1 = 0.0;
    }
    else if (__sdslv_match_subject_2.Tag == HeadSample_Value)
    {
        HeadSample_ValuePayload payload = __sdslv_match_subject_2.Value;
        float __sdslv_operand_3 = AttentionDirectSegmentedProjection_RoundHeadValue(payload.X);
        float __sdslv_operand_4 = AttentionDirectSegmentedProjection_LoadWeight(((payload.WeightRow * paddedModelWidth) + outputColumn));
        __sdslv_match_result_1 = (__sdslv_operand_3 * __sdslv_operand_4);
    }
    return __sdslv_match_result_1;
}

[[vk::push_constant]] ConstantBuffer<AttentionDirectProjectionParams> params;

[numthreads(256, 1, 1)]
void AttentionDirectSegmentedProjection_CS(uint3 DispatchThreadID : SV_DispatchThreadID)
{
    uint element = DispatchThreadID.x;
    if ((element >= params.TotalOutputElements))
    {
        return;
    }
    {
        DirectProjectionLane Lane;
        Lane.Element = element;
        Lane.Token = 0u;
        Lane.OutputColumn = 0u;
        Lane.Accumulator = 0.0;
        Lane.Token = (Lane.Element / params.ModelWidth);
        Lane.OutputColumn = (Lane.Element - (Lane.Token * params.ModelWidth));
        for (uint column = 0u; column < params.HeadDim; column += 1)
        {
            uint sourceIndex__ct0 = ((Lane.Token * params.HeadRowStride) + column);
            HeadSample sample__ct0 = AttentionDirectSegmentedProjection_SelectHeadSample(0u, sourceIndex__ct0, column, params.HeadDim);
            float __sdslv_operand_5 = AttentionDirectSegmentedProjection_ResolveContribution(sample__ct0, Lane.OutputColumn, params.PaddedModelWidth);
            Lane.Accumulator = (Lane.Accumulator + __sdslv_operand_5);
        }
        for (uint column = 0u; column < params.HeadDim; column += 1)
        {
            uint sourceIndex__ct1 = ((Lane.Token * params.HeadRowStride) + column);
            HeadSample sample__ct1 = AttentionDirectSegmentedProjection_SelectHeadSample(1u, sourceIndex__ct1, column, params.HeadDim);
            float __sdslv_operand_6 = AttentionDirectSegmentedProjection_ResolveContribution(sample__ct1, Lane.OutputColumn, params.PaddedModelWidth);
            Lane.Accumulator = (Lane.Accumulator + __sdslv_operand_6);
        }
        for (uint column = 0u; column < params.HeadDim; column += 1)
        {
            uint sourceIndex__ct2 = ((Lane.Token * params.HeadRowStride) + column);
            HeadSample sample__ct2 = AttentionDirectSegmentedProjection_SelectHeadSample(2u, sourceIndex__ct2, column, params.HeadDim);
            float __sdslv_operand_7 = AttentionDirectSegmentedProjection_ResolveContribution(sample__ct2, Lane.OutputColumn, params.PaddedModelWidth);
            Lane.Accumulator = (Lane.Accumulator + __sdslv_operand_7);
        }
        for (uint column = 0u; column < params.HeadDim; column += 1)
        {
            uint sourceIndex__ct3 = ((Lane.Token * params.HeadRowStride) + column);
            HeadSample sample__ct3 = AttentionDirectSegmentedProjection_SelectHeadSample(3u, sourceIndex__ct3, column, params.HeadDim);
            float __sdslv_operand_8 = AttentionDirectSegmentedProjection_ResolveContribution(sample__ct3, Lane.OutputColumn, params.PaddedModelWidth);
            Lane.Accumulator = (Lane.Accumulator + __sdslv_operand_8);
        }
        for (uint column = 0u; column < params.HeadDim; column += 1)
        {
            uint sourceIndex__ct4 = ((Lane.Token * params.HeadRowStride) + column);
            HeadSample sample__ct4 = AttentionDirectSegmentedProjection_SelectHeadSample(4u, sourceIndex__ct4, column, params.HeadDim);
            float __sdslv_operand_9 = AttentionDirectSegmentedProjection_ResolveContribution(sample__ct4, Lane.OutputColumn, params.PaddedModelWidth);
            Lane.Accumulator = (Lane.Accumulator + __sdslv_operand_9);
        }
        for (uint column = 0u; column < params.HeadDim; column += 1)
        {
            uint sourceIndex__ct5 = ((Lane.Token * params.HeadRowStride) + column);
            HeadSample sample__ct5 = AttentionDirectSegmentedProjection_SelectHeadSample(5u, sourceIndex__ct5, column, params.HeadDim);
            float __sdslv_operand_10 = AttentionDirectSegmentedProjection_ResolveContribution(sample__ct5, Lane.OutputColumn, params.PaddedModelWidth);
            Lane.Accumulator = (Lane.Accumulator + __sdslv_operand_10);
        }
        for (uint column = 0u; column < params.HeadDim; column += 1)
        {
            uint sourceIndex__ct6 = ((Lane.Token * params.HeadRowStride) + column);
            HeadSample sample__ct6 = AttentionDirectSegmentedProjection_SelectHeadSample(6u, sourceIndex__ct6, column, params.HeadDim);
            float __sdslv_operand_11 = AttentionDirectSegmentedProjection_ResolveContribution(sample__ct6, Lane.OutputColumn, params.PaddedModelWidth);
            Lane.Accumulator = (Lane.Accumulator + __sdslv_operand_11);
        }
        for (uint column = 0u; column < params.HeadDim; column += 1)
        {
            uint sourceIndex__ct7 = ((Lane.Token * params.HeadRowStride) + column);
            HeadSample sample__ct7 = AttentionDirectSegmentedProjection_SelectHeadSample(7u, sourceIndex__ct7, column, params.HeadDim);
            float __sdslv_operand_12 = AttentionDirectSegmentedProjection_ResolveContribution(sample__ct7, Lane.OutputColumn, params.PaddedModelWidth);
            Lane.Accumulator = (Lane.Accumulator + __sdslv_operand_12);
        }
        Output[Lane.Element] = Lane.Accumulator;
    }
    return;
}

