// Generated by canonical GoOct SDSL-V via VD-MIR. Do not edit by hand.
// namespace Prometheus.Experimental.Attention

struct AttentionInterleaveParams
{
    uint Tokens;
    uint HeadDim;
    uint HeadRowStride;
    uint OutputRows;
    uint OutputColumns;
    uint PackedOutput;
    uint WorkItemCount;
    uint Reserved;
};

[[vk::binding(0, 0)]] StructuredBuffer<float> Head0;
[[vk::binding(1, 0)]] StructuredBuffer<float> Head1;
[[vk::binding(2, 0)]] StructuredBuffer<float> Head2;
[[vk::binding(3, 0)]] StructuredBuffer<float> Head3;
[[vk::binding(4, 0)]] StructuredBuffer<float> Head4;
[[vk::binding(5, 0)]] StructuredBuffer<float> Head5;
[[vk::binding(6, 0)]] StructuredBuffer<float> Head6;
[[vk::binding(7, 0)]] StructuredBuffer<float> Head7;
[[vk::binding(8, 0)]] RWStructuredBuffer<float> OutputF32;
[[vk::binding(9, 0)]] RWStructuredBuffer<uint> OutputPacked;

[[vk::push_constant]] ConstantBuffer<AttentionInterleaveParams> params;

[numthreads(256, 1, 1)]
void AttentionInterleaveHeads_CS(uint3 DispatchThreadID : SV_DispatchThreadID)
{
    uint word = DispatchThreadID.x;
    if ((word >= params.WorkItemCount))
    {
        return;
    }
    uint lowIndex = (word * 2u);
    uint highIndex = (lowIndex + 1u);
    uint lowRow = (lowIndex / params.OutputColumns);
    uint lowColumn = (lowIndex - (lowRow * params.OutputColumns));
    uint highRow = (highIndex / params.OutputColumns);
    uint highColumn = (highIndex - (highRow * params.OutputColumns));
    uint concatenatedColumns = (params.HeadDim * 8u);
    float low = 0.0;
    float high = 0.0;
    if (((lowRow < params.Tokens) && (lowColumn < concatenatedColumns)))
    {
        uint head = (lowColumn / params.HeadDim);
        uint column = (lowColumn - (head * params.HeadDim));
        uint source = ((lowRow * params.HeadRowStride) + column);
        if ((head == 0u))
        {
            low = Head0[source];
        }
        if ((head == 1u))
        {
            low = Head1[source];
        }
        if ((head == 2u))
        {
            low = Head2[source];
        }
        if ((head == 3u))
        {
            low = Head3[source];
        }
        if ((head == 4u))
        {
            low = Head4[source];
        }
        if ((head == 5u))
        {
            low = Head5[source];
        }
        if ((head == 6u))
        {
            low = Head6[source];
        }
        if ((head == 7u))
        {
            low = Head7[source];
        }
    }
    if (((highRow < params.Tokens) && (highColumn < concatenatedColumns)))
    {
        uint head = (highColumn / params.HeadDim);
        uint column = (highColumn - (head * params.HeadDim));
        uint source = ((highRow * params.HeadRowStride) + column);
        if ((head == 0u))
        {
            high = Head0[source];
        }
        if ((head == 1u))
        {
            high = Head1[source];
        }
        if ((head == 2u))
        {
            high = Head2[source];
        }
        if ((head == 3u))
        {
            high = Head3[source];
        }
        if ((head == 4u))
        {
            high = Head4[source];
        }
        if ((head == 5u))
        {
            high = Head5[source];
        }
        if ((head == 6u))
        {
            high = Head6[source];
        }
        if ((head == 7u))
        {
            high = Head7[source];
        }
    }
    if ((params.PackedOutput != 0u))
    {
        float2 __sdslv_operand_0 = float2(low, high);
        OutputPacked[word] = (f32tof16(__sdslv_operand_0).x | (f32tof16(__sdslv_operand_0).y << 16u));
    }
    else
    {
        OutputF32[lowIndex] = low;
        if ((highIndex < (params.OutputRows * params.OutputColumns)))
        {
            OutputF32[highIndex] = high;
        }
    }
    return;
}

